### ISSUE TITLE
.NET 6 single file deployment improvements

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1007]
- [ ] Experiment with `EnableSingleFileAnalysis=true` to verify if any warnings show up. The goal is to make sure the SDK works properly with single file deployment.
- [ ] Turn one of the samples in single file deployment (I.e: Console.Customized)

Requires preview 4 or newer

**Comment by mattjohnsonpint** [comment]
Related to https://github.com/getsentry/sentry-dotnet/issues/2362
