### ISSUE TITLE
Usage of `DebugDiagnosticLogger` in the shipped SDK will be no-op

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1040]
`DebugDiagnosticLogger` works when developing the SDK as we compile in debug mode.
Once we ship the SDK, we're building in Release. The `Debug` class won't be compiled so basically `DebugDiagnosticLogger` is no-op.

We need to revert #1012 and rethink the approach with shipping a logger that makes sense when `Console` isn't available.

**Comment by Tyrrrz** [comment]
I can't believe we never considered this lol 🤦🏻
