### ISSUE TITLE
Exceptions not captured since updating to 3.4.0 or above

### ISSUE THREAD

**Issue by Camble** [getsentry/sentry-dotnet#1050]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
Sentry.AspNetCore 3.4.0 & 3.5.0

### Steps to Reproduce

Installed & configured Sentry SDK 3.5.0 on a new ASP.NET Core 3.1 Web API. 
Using webBuilder.UseSentry() in Program.cs
Configuration in appsettings.json, but also tried hardcoding values.

### Expected Result

Test exception to be captured

### Actual Result

No exceptions captured.
Rolled back to known working version (3.3.4) and this resolved the issue.

**Comment by Tyrrrz** [comment]
Hi! Where was the exception thrown? Inside an endpoint or somewhere else?

**Comment by bruno-garcia** [comment]
@Camble Running the sample in the repo works fine:
![image](https://user-images.githubusercontent.com/1633368/121392391-57d8e980-c91d-11eb-94c0-aa5d1ce4e834.png)


Could you please share a repro so we can investigate? If you set the SDK in Debug mode, anything shows on the log to indicate the problem?

**Comment by Camble** [comment]
@Tyrrrz Inside an endpoint, but I tried capturing a test message from various places using the SentrySdk static class.

@bruno-garcia I'm unable to share the exact repo, but I can try to reproduce in a new project. I'll investigate further. Thanks.

**Comment by bruno-garcia** [comment]
Thanks @Camble . With a repro in hand we can debug it to find out what's going on. But the tests we did with our samples, we couldn't reproduce it.

**Comment by jouni-kantola** [comment]
Same problem here; here's a repro:
[SentryUnhandledExceptionsNotCapturedRepro.zip](https://github.com/getsentry/sentry-dotnet/files/6657457/SentryUnhandledExceptionsNotCapturedRepro.zip)

The unhandled exception is not captured when the following project config is used:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sentry.AspNetCore" Version="3.5.0" />
  </ItemGroup>
</Project>
```

The unhandled exception is captured with either of these combos:
- `Sentry.AspNetCore@3.3.4` works with `netcoreapp3.1`
- `Sentry.AspNetCore@3.5.0` works with `net5.0`

**Comment by Tyrrrz** [comment]
Thanks for the repro!

I debugged the issue and it looks like Sentry is crashing in `DoSendEvent(...)` here:

https://github.com/getsentry/sentry-dotnet/blob/f84c23b9683c8d90880d613701fd9359528061bb/src/Sentry/SentryClient.cs#L220-L223

With this exception:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Diagnostics.Internal.PortablePdbReader..ctor()
   at System.Diagnostics.EnhancedStackTrace.GetFrames(StackTrace stackTrace) in /_/modules/Ben.Demystifier/src/Ben.Demystifier/EnhancedStackTrace.Frames.cs:line 74
   at Sentry.Extensibility.SentryStackTraceFactory.CreateFrames(StackTrace stackTrace, Boolean isCurrentStackTrace)+MoveNext() in /_/src/Sentry/Extensibility/SentryStackTraceFactory.cs:line 84
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1.MoveNext()
   at Sentry.Extensibility.SentryStackTraceFactory.Create(StackTrace stackTrace, Boolean isCurrentStackTrace) in /_/src/Sentry/Extensibility/SentryStackTraceFactory.cs:line 67
   at Sentry.Extensibility.SentryStackTraceFactory.Create(Exception exception) in /_/src/Sentry/Extensibility/SentryStackTraceFactory.cs:line 40
   at Sentry.Internal.MainExceptionProcessor.CreateSentryException(Exception exception)+MoveNext() in /_/src/Sentry/Internal/MainExceptionProcessor.cs:line 122
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sentry.Internal.MainExceptionProcessor.Process(Exception exception, SentryEvent sentryEvent) in /_/src/Sentry/Internal/MainExceptionProcessor.cs:line 29
   at Sentry.SentryClient.DoSendEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 209
   at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 77
```

Judging by the stacktrace, it looks like `Ben.Demystifier` is using `System.Reflection.Metadata, Version=5.0.0.0` which is not declared as a reference in our package. Because it's present on .NET5, it works there.

**Comment by Tyrrrz** [comment]
Relevant StackOverflow question: https://stackoverflow.com/questions/68019132/sentry-exception-logging-net-core

**Comment by bruno-garcia** [comment]
We haven't changed the submodule since the first version, 5 months ago: https://github.com/getsentry/sentry-dotnet/tree/main/modules
I wonder how does it compile if the type is not present on .NET Core 3.x? Seems odd.

Here's the diff between 3.3.4 and 3.5.0:
https://github.com/getsentry/sentry-dotnet/compare/3.3.4...3.5.0

### Workaround

Add a dependency: `<PackageReference Include="System.Reflection.Metadata" Version="5.0.0" />` to your app directly

**Comment by bruno-garcia** [comment]
@Tyrrrz Isn't the problem is the version though? The one in the runtime will be 3.x.x and we're depending on 5.0.0.

**Comment by bruno-garcia** [comment]
We've added it as a dependency explicitly to work around this issue. It's available on our latest preview: https://github.com/getsentry/sentry-dotnet/releases/tag/3.6.0-alpha.2

Again, workaround for you without the need to upgrade the Sentry SDK:

Add a dependency: <PackageReference Include="System.Reflection.Metadata" Version="5.0.0" /> to your app directly

**Comment by bruno-garcia** [comment]
Version 3.6.0 was already released with this fix: https://www.nuget.org/packages/Sentry/3.6.0

**Comment by SirSalamandra** [comment]
Hey guys, I was checking the new version of Sentry (3.30.0) and the dependecy for .NET Core 3.x was removed from the package again and the error is back.

https://www.nuget.org/packages/Sentry/3.30.0#dependencies-body-tab

**Comment by SirSalamandra** [comment]
Hey guys, I was looking the new version of Sentry.AspNetCore and looks like the dependency for System.Reflection.Metadata  is not present on .NET Core 3.x again.

I tried the workaround and it worked, so maybe it was unintended removed? 

Link for the new version: https://www.nuget.org/packages/Sentry/3.30.0#dependencies-body-tab

**Comment by mattjohnsonpint** [comment]
@SirSalamandra - Thanks. I'll take a look asap.

**Comment by mattjohnsonpint** [comment]
Restored in #2302.  Adding the dependency manually to your project should be fine in the meantime.  Thanks.
