### ISSUE TITLE
Add a Session context to event

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1056]
If a session exists, use its id on any outgoing event so we can easily group all events that are related to a session.
This will allow us to see all events that happened during a session.

The session info should be part of a new Context. The server can infer tags from its ids.

Related: getsentry/sentry-java#1416

**Comment by Tyrrrz** [comment]
@bruno-garcia this is currently high up on priority list. Is this still the case, after the requirements changed from putting the session ID on tag to creating a custom session context?

**Comment by bruno-garcia** [comment]
I need to write something down. Sorry the delay

**Comment by bruno-garcia** [comment]
We decided not to do this due to the high cardinality value and low impact
