### ISSUE TITLE
Bitbucket integration issue

### ISSUE THREAD

**Issue by petrovicboban** [getsentry/sentry-dotnet#106]
Hi,
why can't I add repository to project? I've added bitbucket account, but I can't add repo, `add repository button` is disabled:

![image](https://user-images.githubusercontent.com/13204754/46249073-2b0d6e00-c423-11e8-9765-75381228b719.png)

**Comment by bruno-garcia** [comment]
Hi @petrovicboban,

The integrations with sentry itself are not developed on this repository.
Please reach out via [support](https://sentry.io/contact/support/) or the [forum](https://forum.sentry.io/) instead.
