### ISSUE TITLE
InformationalVersion for referenced assemblies

### ISSUE THREAD

**Issue by GeertvanHorrik** [getsentry/sentry-dotnet#1072]
We really like the assemblies part where we can see what assembly versions are being used. However, it does not support pre-release versions (e.g. 2.0.0-alpha0027). They all show up as 2.0.0.0.

For the main app and sentry, it respects the `InformationalVersion` attribute.

Could this part be changed to prefer that instead of the version first?

https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Internal/MainSentryEventProcessor.cs#L109

**Comment by bruno-garcia** [comment]
@GeertvanHorrik that's definitely a fair request. One way we could go about this is to add an option to toggle the behavior and have the `InformationalVersionAttribute` approach be an opt-in. What do you think?

If that would solve it for you, would you be willing to make a PR adding the feature?

**Comment by GeertvanHorrik** [comment]
I am more than happy to PR it. Since informational version is the default for all others, I would recommend setting InformationVersion as default here as well.

But I am happy either way, it's just a 1-time change for us.

**Comment by bruno-garcia** [comment]
Thanks for that, happy to review and merge the change.
We could change the default on a next major but for now it's best to keep the same behavior.

**Comment by GeertvanHorrik** [comment]
Currently working on this feature. While marking the old option obsolete, I was wondering whether you every considered using [ObsoleteEx](https://github.com/fody/obsolete) (not needed for now, just wanted you to be aware of this since it will help you not forget about removing the obsolete members).
