### ISSUE TITLE
Sentry loses its scope inside the ASP.NET pipeline because it uses AsyncLocal for storage

### ISSUE THREAD

**Issue by Zero3** [getsentry/sentry-dotnet#1106]
[The official Sentry SDK docs for ASP.NET](https://docs.sentry.io/platforms/dotnet/guides/aspnet/) instructs one to start and finish tracing transactions like this in `Global.asax.cs`:

```csharp
protected void Application_BeginRequest()
{
    Context.StartSentryTransaction();
}

protected void Application_EndRequest()
{
    Context.FinishSentryTransaction();
}
```

This approach is buggy, as it will sometimes cause the Sentry scope to be lost inside the (non-Core) ASP.NET pipeline. The underlying problem is that the Sentry SDK stores its scopes in an `AsyncLocal` field in `SentryScopeManager.cs`. This is *not* a safe way to store such state in (non-Core) ASP.NET. The only safe method is likely to use `HttpContext.Items`. For more information, see:

* https://stackoverflow.com/questions/43391498/asynclocal-value-is-null-after-being-set-from-within-application-beginrequest
* https://devblogs.microsoft.com/dotnet/net-framework-4-7-1-asp-net-and-configuration-features/#asp-net-execution-step-feature
* http://piers7.blogspot.com/2005/11/threadstatic-callcontext-and_02.html

In my use case, I only care about the transaction reference, so I applied the following workaround to `Global.asax.cs`, based on the above mentioned blog post my Microsoft and how they themselves work around the issue in [Application Insights]( https://github.com/microsoft/ApplicationInsights-dotnet/blob/7c6589e2c5799edae5ffc30991b54364b2756835/WEB/Src/Web/Web/ApplicationInsightsHttpModule.cs#L150):

```csharp
public override void Init()
{
    base.Init();
    
    OnExecuteRequestStep((httpContextBase, step) =>
    {
        if (httpContextBase.CurrentNotification == RequestNotification.ExecuteRequestHandler && !httpContextBase.IsPostNotification)
        {
            SentrySdk.ConfigureScope(scope =>
            {
                if (scope.Transaction == null)
                {
                    scope.Transaction = (ITransaction) httpContextBase.Items["__SentryTransaction"];
                }
            });
        }

        step();
    });
}
```

**Comment by Tyrrrz** [comment]
Hi @Zero3.

Do I understand correctly that the high-level user-facing impact of this is that sometimes added scoped data (such as tags) is not being reflected in the transaction?

**Comment by Zero3** [comment]
@Tyrrrz that is mostly correct, as far as I know.

It might also cause `NullReferenceException` to be thrown unexpectedly from user-added instrumentation code, potentially crashing important stuff. This can happen if the code expects to always be running inside a Sentry transaction, and thus does not check if the parent span is `null` before doing stuff on it, like adding a child span. That is how I discovered the bug in the first place.

**Comment by Tyrrrz** [comment]
I see. I guess we should add your workaround to the docs.

cc @bruno-garcia

**Comment by Zero3** [comment]
@Tyrrrz keep in mind that my workaround is just for the transaction field. The rest of the scope should still be lost.

**Comment by Tyrrrz** [comment]
Note for the future: It looks like it's somewhat related to the Global Hub idea, with the exception that this adds another concept of Hub to the mix -- the `HttpContext`-synchronized Hub.

So the right way to solve it would be, instead of relying on `AsyncLocal<T>` for tracking scopes everywhere, we would use:

- `AsyncLocal<T>` for ASP.NET Core, console apps, and by default (i.e. no integration package is installed)
- Global/singleton Hub for desktop/mobile/Unity apps (i.e. there is only one scope stack)
- `HttpContext`-backed Hub that uses `HttpContext.Items[...]` to store the scope stack

**Comment by bruno-garcia** [comment]
Relates to #505

**Comment by bruno-garcia** [comment]
We solved on version **3.8.1** which uses the HttpContext to propagate the scope on ASP.NET

**Comment by Tyrrrz** [comment]
@Zero3 can you please try out the new version and see if it works without your workarounds? Thanks!

**Comment by Zero3** [comment]
Thanks for the fix! I am off for summer holidays, but I might be able to test this in August.

**Comment by Zero3** [comment]
@Tyrrrz `SentrySdk.GetSpan()` now throws a `NullReferenceException` from deep within Sentry when executed outside a HTTP request. It used to return `null`. Is this intentional?

The problem is that `.Current` can return `null` in the getter here, which is unhandled:

https://github.com/getsentry/sentry-dotnet/blob/28ec35d278b2fa15d356af41079ab81a956fe364/src/Sentry.AspNet/Internal/HttpContextScopeStackContainer.cs#L11-L15

Also see this related issue: https://github.com/getsentry/sentry-dotnet/issues/1157

**Comment by Tyrrrz** [comment]
cc @bruno-garcia
