### ISSUE TITLE
Error Serialization and deserialization of 'System.Type' instances are not supported and should be avoided

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1108]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
.NET Core latest 

### Steps to Reproduce

You can try the following project: https://github.com/lucas-zimerman/sample-ef-core-in-asp-net-core
Run and try the first endpoint (or any of them), you'll then notice that on the ide Debug window, there's a Json error related to System.Type

This line is adding the problematic data https://github.com/getsentry/sentry-dotnet/blob/6b60f9cffe1ceb507cbc0d0075afb9ada870603b/src/Sentry/DefaultSentryScopeStateProcessor.cs#L50
where state is Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor and one of the inner parameters is of type System.Type.
![image](https://user-images.githubusercontent.com/8229322/124770155-7a582580-df10-11eb-91f6-9045bed8f534.png)
![image](https://user-images.githubusercontent.com/8229322/124770173-7d531600-df10-11eb-99e7-0b1c24091d25.png)
![image](https://user-images.githubusercontent.com/8229322/124770178-7f1cd980-df10-11eb-80a6-5b321cf48b6e.png)

### Expected Result

No errors and transactions being registered.

### Actual Result

No transactions were registered due to errors.

**Comment by bruno-garcia** [comment]
Dup of #962
