### ISSUE TITLE
HTTP Request Breadcrumbs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1109]
> With #1178 we add auto performance instrumentation for HTTP requests. Having this in place it should be rather "easy" to add breadcrumbs for HTTP requests as this is an [expected](https://develop.sentry.dev/sdk/features/#http-client-integrations) feature for SDKs.

See: https://github.com/getsentry/sentry-cocoa/issues/1197#issuecomment-875631210

**Comment by lucas-zimerman** [comment]
@bruno-garcia  why have you moved it to To Do?

**Comment by bruno-garcia** [comment]
not sure

**Comment by bruno-garcia** [comment]
ouch, again. this is done
