### ISSUE TITLE
Any way to tell why CaptureEvent would return an empty SentryId?

### ISSUE THREAD

**Issue by nicholashead** [getsentry/sentry-dotnet#1115]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
.NET Framework 4.7.2
Sentry 3.6.1

### Steps to Reproduce

1. When logging some events via CaptureEvent, sometimes the returned SentryId == SentryId.Empty. 99% of our other events work fine.

### Expected Result

That we wouldn't have a small portion of our events come back with no SentryId (which means not logged, I believe).

### Actual Result

We receive back an empty SentryId and the event is never logged into Sentry.io

----

Is there any way to get more context about why a request failed when we have an Empty SentryId? It seems like traffic to our API endpoint is what is causing this - so I don't know if it's a UserAgent filter or something else - but I have no data to go off of to try and track it down. Is there a way I can get access to the rejection/HTTP response error?

Thanks!

**Comment by bruno-garcia** [comment]
The SDK will return an empty sentry id if it fails to enqueue the event.

For example if the queue is full:

https://github.com/getsentry/sentry-dotnet/blob/1b7e3c8740d3096391a9f8c1b7ee94d68a88ba2b/src/Sentry/Internal/BackgroundWorker.cs#L62

The client does print out to the diagnostic logger though:

https://github.com/getsentry/sentry-dotnet/blob/1b7e3c8740d3096391a9f8c1b7ee94d68a88ba2b/src/Sentry/SentryClient.cs#L263-L268

You can enable debug mode and even change where the SDK logs too.
Some docs: https://docs.sentry.io/platforms/dotnet/configuration/diagnostic-logger/
https://docs.sentry.io/platforms/dotnet/configuration/options/#debug

**Comment by bruno-garcia** [comment]
Let us know if things are still not clear.
