### ISSUE TITLE
Contexts.CopyTo is missing Trace.Clone

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dotnet#1116]
The clone method of Context doesn't call clone on Trace.
See https://github.com/getsentry/sentry-dotnet/blob/7d008a9fc437d86d6eeff33300f2ba0160c74a9c/src/Sentry/Protocol/Contexts.cs#L74-L91

**Comment by bruno-garcia** [comment]
I believe this was by design. As you clone the scope we didn't want that same trace to propagate through
