### ISSUE TITLE
Opt-in to replace `Task.Run` with dedicated thread

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#112]
If configured, it should be possible to avoid a potential thread-pool starvation affect events being sent to Sentry, replace the `BackgroundWorker`'s `Task.Run` with:

```csharp
Task.Factory.StartNew(..., TaskCreationOptions.LongRunning);
```

The trade-off is: With Task.Run, there will be no dedicated thread allocated which reduces the footprint of the SDK into an app. On the other hand, if a thread-pool starvation happens and the app locks down, no events queued would be sent to Sentry.

This will also allow a potential health check that will monitor and send an event to sentry if thread-pool starvation happens.

**Comment by roryprimrose** [comment]
I looked into long running background threads recently. Came across an interesting blog post about it - http://blog.i3arnon.com/2015/07/02/task-run-long-running/

**Comment by bruno-garcia** [comment]
@roryprimrose Thanks for sharing, I also got to that write-up today when writing down this ticket.
I've been thinking about this for a while tbh. It's trade-off here and I don't think having a dedicated background thread by default is the right thing here. 

The worker is non blocking and doesn't really do anything [calling the transport](https://github.com/getsentry/sentry-dotnet/blob/006e185e8da0e94620154ffe2b6d26429dc5cc65/src/Sentry/Internal/BackgroundWorker.cs#L128) which serializes the event and starts the async I/O work.
