### ISSUE TITLE
Captured exceptions are not showing up in Sentry - After deployment on IIS 8

### ISSUE THREAD

**Issue by senad004** [getsentry/sentry-dotnet#114]
Hi All,

Hello All, I am using .NET framework 4.5.2. Using SharpRaven nuget to capture the exceptions on Sentry . But it is not working after deployment on IIS 8 . Working fine in debug mode and on IIS 7 on windows 2008 server. Not sure what is missing on IIS 8 ? Can someone help me on this?

**Comment by senad004** [comment]
My code -
 catch (Exception ex)
        {
    SharpRaven.RavenClient client = new SharpRaven.RavenClient(new SharpRaven.Dsn("SENTRY_DSN KEY"));
            var ev = new SentryEvent("TEST INFO EVENT3");
            ev.Level = ErrorLevel.Error;
            client.CaptureEvent( new SentryEvent(ex));
}

**Comment by bruno-garcia** [comment]
Raven is our legacy SDK but since you are using .NET Framework 4.5.2, which doesn't implement .NET Standard 2.0, Raven is your best call.

A few things to make sure:

1. Is the DSN available also on your release build?
2. Can your server access the Internet?
3. Does it require a proxy to reach out to the Internet?
4. If it does, is the proxy listed in your web.config?

Can you write a small console application which sends an event, run from your PC to make sure it work then pack it up and move it to the server and run it again. 
If you don't get an event then, the logs are printed out to the console so you should see the error. It will likely be your server can't reach out to Sentry.

**Comment by senad004** [comment]
To answer your questions, 
Is the DSN available also on your release build? - Yes.
Can your server access the Internet? - Yes
Does it require a proxy to reach out to the Internet? - No
If it does, is the proxy listed in your web.config? - NA

I have two servers Windows 2008 and 2012. It is working on 2008(IIS 7) server and not on 2012. So I think problem is on 2012 server(IIS 8) only

**Comment by bruno-garcia** [comment]
".NET 4.6 and above. You don’t need to do any additional work to support TLS 1.2, it’s supported by default.
.NET 4.5. TLS 1.2 is supported, but it’s not a default protocol. You need to opt-in to use it. The following code will make TLS 1.2 default, make sure to execute it before making a connection to secured resource:"
```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
```

On top of that, I advise you update your app/server to run on a more current version of the .NET Framework. Specifically, the latest, .NET 4.7.2.

**Comment by senad004** [comment]
Wow. It is working fine.

**Comment by bruno-garcia** [comment]
Glad I could help!

**Comment by senad004** [comment]
Hi @bruno-garcia I successfully implemented SENTRY in my applications. I recently saw some different behavior and thought to get help from you. Please see below
I am using .NET framework 4.5 and added below line to transfer logs to SENTRY
 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

It's working perfectly. But on the server side, I am seeing 2 versions are enabled (TLS 1.2 and SSL ). No other TLS versions are disabled. SENTRY is logging all errors. 

My questions is ,
      What does SENTRY expect exactly? 
               Does it check whether all TLS lower versions are disabled on the server and enabled only TLS 
              1.2 ? 
              (OR) 
              Does it check whether TLS 1.2 is enabled or not on the server ? 

Also is it compatible for Windows 2008 servers? 

It would be great if you clarify my doubt.
