### ISSUE TITLE
Improvements for `Sentry.Tunnel`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1141]
- [ ] Split AddSentryTunnel and UseSentryTunnel into different files and use already imported namespace (like `Microsoft.AspNetCore.Builder`. See Sentry.AspNetCore)
- [ ] Documentation must mention the need for registering HttpClientFactory (`[18:18:21 ERR] Connection id "0HMAFN6VRLADL", Request id "0HMAFN6VRLADL:00000006": An unhandled exception was thrown by the application.
System.InvalidOperationException: No service for type 'System.Net.Http.IHttpClientFactory' has been registered.`
- [ ] Document to include it either before/after the tracing middleware.
- [ ] Add the middleware docs to the actually Sentry docs: [docs.sentry.io/platforms/javascript/guides/wasm/troubleshooting](https://docs.sentry.io/platforms/javascript/guides/wasm/troubleshooting/)
- [ ] Add the tunnel to the ASP.NET Core sample and use it from the error page which has User Feedback (that has JS SDK)

**Comment by bruno-garcia** [comment]
Example where it's used: https://github.com/dotnet/nuget-trends/blob/62a481bc7a7629a8fe805f77f4b47f93bad3de21/src/NuGetTrends.Web/Startup.cs#L34

**Comment by bruno-garcia** [comment]
Docs for tunnel: https://docs.sentry.io/platforms/javascript/guides/wasm/troubleshooting/

**Comment by SimonCropp** [comment]
@bruno-garcia what sample?

> Add the tunnel to the ASP.NET Core sample and use it from the error page which has User Feedback (that has JS SDK)
