### ISSUE TITLE
Api name not being catpured.

### ISSUE THREAD

**Issue by michaelakin** [getsentry/sentry-dotnet#1155]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
.net core 3.8.3

### Steps to Reproduce

1. Did a post command to our wepapi.

### Expected Result
should have captured the api name as well as the path

https://ourservername.com/UserAPI/v1/Authentication/AuthenticateUser

### Actual Result

it only has references to the server and path, but not the api

   it only shows this:  v1/Authentication/AuthenticateUser

What actually happened. Maybe a screenshot/recording? Maybe some logs?

![image](https://user-images.githubusercontent.com/7062652/128734222-76af6512-d0ed-4e0e-9751-2b6552caca4a.png)

**Comment by lucas-zimerman** [comment]
Hi @michaelakin , could you please share how are you defining the route? And, do you recall if the same behavior happened on a previous version of the SDK?

**Comment by michaelakin** [comment]
Sure, we have this on the controller

```
    [Route("v1/[controller]")]
    [ApiController]
```
And this on the method

```
        [HttpPost]
        [Route("AuthenticateUser")]
        public async Task<IActionResult> AuthenticateUser([FromBody] AuthUser user)
```

This is our first version to use of the sdk, so not sure if it ever worked.

We have multiple projects on the same web server and this does not seem to capture the name of the project.

Thanks!

**Comment by lucas-zimerman** [comment]
Oh, just to be sure.
You expected the UI to show the below path?
```
POST /UserAPI/v1/Authentication/AuthenticateUser
```
Where UserAPI is your path base?

**Comment by michaelakin** [comment]
That would be nice and easier to go to the right project in our system.
