### ISSUE TITLE
Cant initialise Sentry if using "AddAspNet" during Init() and HttpContext is null

### ISSUE THREAD

**Issue by steve-tapley** [getsentry/sentry-dotnet#1157]
### Environment

using Sentry 3.8.3, with ASP.Net classic, .Net 472

We upgraded from 3.5.0 to 3.8.3

### Steps to Reproduce

I created a new project from scratch to repro the error. Our code to initialise looks like this:
`SentrySdk.Init(o =>`
`            {`
`                o.Dsn = "https://mockkey@mock.sentry/12345";`
`                o.Release = "1";`
`                o.Environment = "test";`
`                o.AddAspNet();`
`            });`

This now fails with an exception message: "Object reference not set to an instance of an object.". 
The stacktrace given is:
"   at Sentry.AspNet.Internal.HttpContextScopeStackContainer.get_Stack() in /_/src/Sentry.AspNet/Internal/HttpContextScopeStackContainer.cs:line 13\r\n   at Sentry.Internal.SentryScopeManager.get_ScopeAndClientStack() in /_/src/Sentry/Internal/SentryScopeManager.cs:line 18\r\n   at Sentry.Internal.SentryScopeManager.PushScope[TState](TState state) in /_/src/Sentry/Internal/SentryScopeManager.cs:line 97\r\n   at Sentry.Internal.SentryScopeManager.PushScope() in /_/src/Sentry/Internal/SentryScopeManager.cs:line 56\r\n   at Sentry.Internal.Hub..ctor(SentryOptions options, ISentryClient client, ISessionManager sessionManager, ISystemClock clock, IInternalScopeManager scopeManager) in /_/src/Sentry/Internal/Hub.cs:line 56\r\n   at Sentry.SentrySdk.InitHub(SentryOptions options) in /_/src/Sentry/SentrySdk.cs:line 54\r\n   at Sentry.SentrySdk.Init(Action`1 configureOptions) in /_/src/Sentry/SentrySdk.cs:line 84\r\n   at WebApplication1.Class1.init() "

If I create a HttpContext manually like this prior to the Init() call:
`HttpContext.Current = new HttpContext(`
`                new HttpRequest(string.Empty, "http://mock.server", string.Empty),`
`                new HttpResponse(new StringWriter()))`
`            {`
`                User = new GenericPrincipal(new GenericIdentity("test@test.com"), Array.Empty<string>()),`
`            };`

then the Init() does work for our unit testing.  However, that doesn't work for our production environment obviously.

### Expected Result

I think Sentry should initialise no matter if HttpContext is null or not - this would match the prior behaviour.

### Actual Result

Exception :(

This looks like it was introduced by https://github.com/getsentry/sentry-dotnet/pull/1124

**Comment by Zero3** [comment]
I also ran into a similar problem with the new scope storage, as seen in the issue I just linked above.

`SentrySdk.Init()` actually works if you run it from `Application_Start()`, but only because of a weirdness in classic ASP.NET as `HttpContext.Current` actually is set to a "dummy" context when `Application_Start()` is called.

A few thoughs from me:

1) Sentry should probably not try to access `HttpContext.Current` during initialization. Maybe there is a good reason to do so, but I have a feeling that there probably is not.

2) You should probably not run `AddAspNet()` from your unit testing code if they execute outside ASP.NET, which it sounds like they do. That method is for integrating with ASP.NET, so what would you expect it to do if you run it without using ASP.NET?

**Comment by lucas-zimerman** [comment]
Hi @steve-tapley, are you experiencing this problem only during unit testing? And would you mind sharing a sample repro?

**Comment by bruno-garcia** [comment]
The issue makes sense. Sounds like we don't have an HttpContext when IIS starts (no requests there yet) so we should handle that. Just deal with `this` being null if this is an extension method

**Comment by steve-tapley** [comment]
Hi @lucas-zimerman & @bruno-garcia 
The problem occurs on real code as well as unit testing code.  Our Sentry.Init() call is made from a static class, so its initialised quite early. As @Zero3 mentioned, we could actually call it during Application_Start() but that just a fluke that it works and I dont think that's a 'real' solution.
It sounds like if that extension method dealt with the possibility of HttpContext being null, then it would work for us (as long as that Init() code is not relying on HttpContext being set for any other reason).
