### ISSUE TITLE
Failed to find BootTime (.NET Console + Sentry)

### ISSUE THREAD

**Issue by thiagoloureiro** [getsentry/sentry-dotnet#1160]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
self-hosted - on prem

Which SDK and version?
.NET 4.6
Sentry SDK -> 3.8.3

### Steps to Reproduce
just installed sentry normally on Program.cs

### Expected Result
.
What you thought would happen.

### Actual Result
 Error: Failed to find BootTime: Now 8/23/2021 1:19:09 PM +00:00, GetTimestamp 1716554697458, Frequency 2441438, TicksPerSecond: 10000000
System.DivideByZeroException: Attempted to divide by zero.
   at Sentry.Internal.ProcessInfo..ctor(SentryOptions options, Func`1 findPreciseStartupTime) in /_/src/Sentry/Internal/ProcessInfo.cs:line 26Console mode

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by thiagoloureiro** [comment]
https://github.com/getsentry/sentry-dotnet/issues/954
Found related issue, put the 

o.DetectStartupTime = StartupTimeDetectionMode.None;

and fixed. thanks

**Comment by bruno-garcia** [comment]
Just to confirm: This only affected the log output, right? The SDK handled the error and printed out what happened but things worked normally?

**Comment by thiagoloureiro** [comment]
not 100% sure Bruno, because I'm still during the implementation and this specific service is quite complex under proxy and other stuff.

**Comment by bruno-garcia** [comment]
Feel free to raise an issue if the default value isn't working. Setting to `None` is a good fallback to avoid issues but it's nice to see when the process started when the issue can be related to long (or short) running process'
