### ISSUE TITLE
Add `Sentry` to global usings

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1163]
If `ImplicitUsings` is set to true, add `Sentry` as a global using via msbuild:

See: https://github.com/spectreconsole/spectre.console/pull/516/files

**Comment by bruno-garcia** [comment]
Might need to rename some types like `Span`. Should be called `SentrySpan` instead.

**Comment by SimonCropp** [comment]
> Might need to rename some types like Span. Should be called SentrySpan instead.

i would prefer not to Add Sentry to global usings fs it means needing to add a `Sentry` prefix to types.
