### ISSUE TITLE
Invalid data (invalid character '{') in path

### ISSUE THREAD

**Issue by Cyral** [getsentry/sentry-dotnet#1177]
### Environment

How do you use Sentry?
Sentry SaaS 

Which SDK and version?
.NET 5.0.8, Sentry.AspNetCore 3.8.3

### Steps to Reproduce

Installed Sentry.AspNetCore according to guide:

In Program.cs CreateDefaultBuilder:

```
.ConfigureWebHostDefaults(webBuilder => {
    webBuilder.UseSentry(o => {
        o.Dsn = "https://xxx.ingest.sentry.io/xxx";
        // o.Debug = true;
        o.SendDefaultPii = true;
        o.TracesSampleRate = 0.1;
        o.AddExceptionFilterForType<ApiException>();
});
```

In Startup.cs Configure method:
```
app.UseRouting();
app.UseSentryTracing();
```

### Expected Result

Correct path should show in issue

### Actual Result

![image](https://user-images.githubusercontent.com/4945029/131160647-d038fe31-c3ed-4e5b-863a-9ad955c41a01.png)

**Comment by lucas-zimerman** [comment]
It comes from 
Scope.cs Apply TState
![image](https://user-images.githubusercontent.com/8229322/131349047-44932d90-16f5-43e0-af8c-dd7d5851e8e7.png)
one of the object keys is called {OriginalFormat}

https://github.com/getsentry/sentry-dotnet/blob/5a305f8acd725d1536a08f8eb304a29cff17056e/src/Sentry/Scope.cs#L409

Perhaps adding  a filter to remove the brackets from the keys inside of SentryScopeStateProcessor os simply filtering that {OriginalFormat} key
