### ISSUE TITLE
[Feature Request] Sentry.Serilog: Setting breadcrum/event category through context value

### ISSUE THREAD

**Issue by Cyberunner23** [getsentry/sentry-dotnet#1181]
We are using Sentry with the Serilog integration and we would like to be able to set the category of a breadcrum and event. As far as we can tell there is no way to do this. The way we see as to how this may be done is by setting the category through Serilog's LogContext.

**Comment by bruno-garcia** [comment]
Currently you can only set the category through `SentrySdk.AddBreadcrumb` or `SentrySdk.ConfigureScope(s => s.AddBreadcrumb()`.

The latter has more extension methods with more variations but in either case you can do `new Breadcrumb(...` and access all fields of it.

You could also try to change the crumb through `BeforeBreadcrumb` callback but other than that, I don't believe there's a way to define what the crumb will look like from a Serilog API point of view

**Comment by Cyberunner23** [comment]
Would it not be possible to set it through a property in the Serilog's LogContext?

**Comment by bruno-garcia** [comment]
It would if we changed the `SentrySink` to read up on those at the time it creates a breadcrumb. 

For example a context like: `Sentry:Category:xyz` and we check for contexts starting with `Sentry:` which is rather cheap and from those we go to the well known bits like `Category` or `Type` or whatever. If this makes sense and you'd like to contribute, feel free to open a draft PR without any tests or anything just to discuss the design and we could guide you through the review process.

**Comment by Cyberunner23** [comment]
After further investigation I found that setting the property named `SourceContext` sets the Category of the breadcrum. This is the behavior I was looking for. Thanks for the help!
