### ISSUE TITLE
Avoid adding generated assemblies to the event module's list

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1192]
The code already skips dynamic assemblies:
https://github.com/getsentry/sentry-dotnet/blob/8a305405325a7b805c13ea99f0ac50906db4d3ad/src/Sentry/Internal/MainSentryEventProcessor.cs#L104-L108

But somehow MVC apps end up with such modules:

![image](https://user-images.githubusercontent.com/1633368/132892103-7d9d70c5-34da-487e-bef3-fc5d07c3b5b2.png)

**Comment by SimonCropp** [comment]
@bruno-garcia do u have a repro for this? i tried with both mvc sample apps and could not see this behavior

**Comment by bruno-garcia** [comment]
I don't have a repro, sadly. We can close it then until a repro shows up. Thanks for digging into it.
