### ISSUE TITLE
Unable to suppress "Ignoring request with Size null and configuration RequestSize Always" message 

### ISSUE THREAD

**Issue by shones34** [getsentry/sentry-dotnet#1220]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ X ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [ X ] .NET Core

* Version:

Please mark the NuGet packages used:

- [ X ] Sentry
- [ X ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ X ] Sentry.AspNetCore

* Version: 3.8.3

Hello, I have enabled the "MaxRequestBodySize": "Always" property and am constantly getting warnings for requests which are null. 

Sentry config:
```
"Sentry": {
    "Dsn": XXX,
    "MaxRequestBodySize": "Always",
    "SendDefaultPii": true,
    "MinimumBreadcrumbLevel": "Debug",
    "MinimumEventLevel": "Warning", 
    "AttachStackTrace": true,
    "Debug": false,
    "DiagnosticsLevel": "Error"
  }
```
Is there a way to suppress the warning so that I do not see this noise on every call with a null request? 

![image](https://user-images.githubusercontent.com/16258204/135174591-f0a42a8c-2a41-472e-9aaa-4527e04ab4c3.png)

**Comment by bruno-garcia** [comment]
We could skip this log entry altogether in case it's `null`. It's only null with requests that don't have body so no big deal. Is this something you could contribute with a PR?
