### ISSUE TITLE
Using SentrySdk.WithScope with SentrySdk.CaptureException causes Rider to not be able to evaulate IEnumerable statements

### ISSUE THREAD

**Issue by jasekiw** [getsentry/sentry-dotnet#1232]
### Environment
Windows 10 x64
dotnet core 3.1

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
dotnet core 3.1
.NET Sentry 3.9.4

### Steps to Reproduce

Sample Project: https://github.com/jasekiw/example-rider-evaluation-issue

1. Put a breakpoint on the first line of the Main method and debug the program until it hits that line.
2. Evaluate the following in the Evaluation window in the Jetbrains Rider IDE
```
(new List<string>{"", ""}).Where(e => e != null).ToList()
```
3. Hit Enter

### Expected Result

Get a a list result

### Actual Result

Null Reference Exception

### Extra information

I created a ticket with Rider as well that has more information and screenshots about this issue: https://youtrack.jetbrains.com/issue/RIDER-68524

I created this issue here in order to open communications since this is a cross company issue.

I have not ever experienced this with any other lines of code/software.

Note: The code doesn't have to execute, it just has to exist.

**Comment by lucas-zimerman** [comment]
Just to be sure
```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                Console.WriteLine("Hello World!");
            }
            catch (Exception e)
            {
                SentrySdk.WithScope(scope =>
                {
                    SentrySdk.CaptureException(e);
                });
            }
        }
    }
```
Is this the correct sample?

**Comment by jasekiw** [comment]
Yes that is correct.

**Comment by SimonCropp** [comment]
it seems to me that `(new List<string>{"", ""}).Where(e => e != null).ToList()` is not valid. since the evaluation runs in the context of the current debug statement. so the variable `e` will conflict. change it to `(new List<string>{"", ""}).Where(b => b != null).ToList()` seems to make it work
