### ISSUE TITLE
OS Build not getting triggered.

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1266]
It seems like if a PR doesn't do any change to a code file, the os builds will never start (tested here: https://github.com/getsentry/sentry-dotnet/pull/1265)

With that said, you'll be blocked to merge changes that don't have any relation with the project code.

Ideally, the os build should be triggered even if the only field you altered was the changelog.

**Comment by lucas-zimerman** [comment]
I can't merge since windows/mac/linux builds are required before merging 😅

**Comment by SimonCropp** [comment]
closing this, since a build was triggered here https://github.com/getsentry/sentry-dotnet/pull/1581
