### ISSUE TITLE
Regression in changing the case of environment

### ISSUE THREAD

**Issue by manuel-zulian** [getsentry/sentry-dotnet#1267]
### Environment

How do you use Sentry? Sentry.AspNetCore

Which SDK and version?
3.9.4

### Steps to Reproduce
There seems to be a regression for this issue: https://github.com/getsentry/sentry-dotnet/issues/999
In particular, I noticed this morning that I get the environment lower-cased even if I set the option "AdjustStandardEnvironmentNameCasing" to false.

~~It might be due to the changes in this file: https://github.com/ajbeaven/sentry-dotnet/blob/53323f0ea6b788a06aeb2cecf693fdf23e1b71a1/src/Sentry.AspNetCore/SentryAspNetCoreOptionsSetup.cs which seems to be different from the version that actually fixed the issue: https://github.com/getsentry/sentry-dotnet/pull/1057/files~~

EDIT My bad, there doesn't seem to be any change in the files above. 

### Expected Result

Environment not lowercased

### Actual Result

Environment lowercased (from Staging to staging)

**Comment by bruno-garcia** [comment]
A simpler solution would be for Sentry not to care about environment casing: https://github.com/getsentry/sentry/issues/6568

**Comment by bruno-garcia** [comment]
What if we make this property to `internal`? Does ASP.NET Core configuration binding still work?
https://github.com/getsentry/sentry-dotnet/blob/263961124a49c5fa8290c8721294e7fd472e7027/src/Sentry.AspNetCore/SentryAspNetCoreOptions.cs#L46-L54

This way we remove the pitfall.

**Comment by bruno-garcia** [comment]
We can try the making it `internal` approach while documenting to use the framework configuration strategies (even a callback is possible through `IOptions`). Or any other breaking change.

**Comment by SimonCropp** [comment]
we could add a static `SentryAspNetCoreOptions.DefaultEnvironmentNameCasing`. then use that to derive true/false for `AdjustStandardEnvironmentNameCasing` on `SentryAspNetCoreOptions` construction

**Comment by SimonCropp** [comment]
on second thoughts. given the root fix is https://github.com/getsentry/sentry/issues/6568. lets obsolete `AdjustStandardEnvironmentNameCasing` with a message to use app config. then we can burn it in the next major

**Comment by mattjohnsonpint** [comment]
I'm not a fan of obsoleting that.  Not everyone uses app config files, and the problem is indicative of a larger issue.

The root cause appears to be that `SentryAspNetCoreOptionsSetup` is too early to be setting options based on other options.  The environment name setup should be moved later, so that anything the user sets is still applied - whether it came from configuration or code.
