### ISSUE TITLE
ASP.NET Core: Configure scope during `UseSentry`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#129]
In order to facilitate setting some values that will be used on all events, expose a `ConfigureScope` on `SentryOptions`:

```csharp
.UseSentry(o =>
{
  o.ConfigureScope(s => s.SetExtra("extra", "sent with all events");
{
```

**Comment by facundofarias** [comment]
Indeed. Any news on this?

**Comment by bruno-garcia** [comment]
@facundofarias Got something together on #160
Didn't tests much yet/write any tests yet, still accepting PRs :)
