### ISSUE TITLE
native

### ISSUE THREAD

**Issue by kxmark** [getsentry/sentry-dotnet#1291]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:

**Comment by lucas-zimerman** [comment]
Hi, perhaps you forgot to edit the Question?

**Comment by SimonCropp** [comment]
closing this one. @kxmark happy to reopen if you can give use some more details of the question/bug
