### ISSUE TITLE
Update Entity Framework Migration Guide for PR #1107

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1295]
PR https://github.com/getsentry/sentry-dotnet/pull/1107/files/34486a8e7f2b8a42bdea88fdd3f7f9287dad6a36#diff-9d3d6393e8e474fba51da05f84be5ddc7a0b7a30a5294d51ac1ddf2f5a3c463e
will bump the version for Entity Framework.

#1107

**Comment by bruno-garcia** [comment]
PR was merged, should we prioritize this?

**Comment by SimonCropp** [comment]
tracking here https://github.com/getsentry/sentry-docs/compare/master...SimonCropp:patch-2
