### ISSUE TITLE
Opt-in Source Context when source bundled in app

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1297]
Source link and embed source exist as features in .net. if either of these exists we should leverage the sentry [source context feature ](https://docs.sentry.io/platforms/native/data-management/debug-files/source-context/) to expose this information.

See: https://github.com/getsentry/sentry-dotnet/commit/518ab6464418cb1912ae4adad08262c440f4da42

**Comment by SimonCropp** [comment]
can you elaborate on this one?

**Comment by mattjohnsonpint** [comment]
@bruno-garcia  - if you could please add more context about this, that would be great. 👍

**Comment by bruno-garcia** [comment]
Sorry about the lost messages. I've given up on notifications:
![image](https://user-images.githubusercontent.com/1633368/165397001-f3a17f28-0898-430e-a08c-12f00d5e8e89.png)

Additionally from sourcelink and embed source, Sentry has a solution for Source Context used in Native called Source Bundle. Which is basically creating a zip with all the source code at build time. The server pulls that bundle while processing the event to add the source context.

**Comment by bruno-garcia** [comment]
Closing in favor of: https://github.com/getsentry/sentry-dotnet/issues/646
