### ISSUE TITLE
[UWP][.NET Native] Discarded invalid value for parameter 'exception'

### ISSUE THREAD

**Issue by XuJinNet** [getsentry/sentry-dotnet#130]
When use `SentrySdk.CaptureException(ex)` to send exception from my UWP app (Release Package), then get a error: Discarded invalid value for parameter 'exception', and the issue\`s title is `<unlabeled event>`, **OS** is `Unknown OS`, **Version** is `undefined`.

![image](https://user-images.githubusercontent.com/442382/48247835-c553cf00-e42f-11e8-8080-8f53d40ddf18.png)

**Comment by bruno-garcia** [comment]
I'm glad to know it actually works beside this issue :)
We haven't focused on supporting UWP yet. Since that's a native target, 

From the issue it seems that the code reading the `Exception` data doesn't work in UWP. We'll need to investigate what kind of data we have available at that point in order to build the event.

**Comment by Lyra2108** [comment]
That the operating system was not reconised might be related to UWP, but the unlabeled event is fault to some problems with the parsing of the stacktrace. I had the same problem with Xamarin.Android and could not fix it so far.

The send stactrace to sentry is 

`
"stacktrace":{"frames":[{"instruction_offset":-1,"in_app":true},{"instruction_offset":-1,"in_app":true}]}
`

**Comment by bruno-garcia** [comment]
I've just tested the latest version of the [Sentry .NET SDK, 2.0.0-beta2](https://www.nuget.org/packages/Sentry/2.0.0-beta2) and in **Release** mode, with PDBs locally it included the stack traces:

![image](https://user-images.githubusercontent.com/1633368/59354282-21b00180-8d25-11e9-8224-f09917f0d283.png)

I've used the latest target: _Windows 10 1803 (build 17134) _ but it should work with _10.0.16299_ and higher.

I just hooked the SDK into the UWP error handler:

> Note that `FlushAsync().Wait` is going to block the calling thread. Replace that with proper dispose of the SDK on Application Exit (xaml OnExit?).

```csharp
UnhandledException += (sender, args) =>
{
    using (SentrySdk.PushScope())
    {
        SentrySdk.ConfigureScope(s => s.SetTag("UnhandledException", "true"));
        SentrySdk.CaptureException(args.Exception);
        if (!args.Handled) // Not handled yet
        {
            // App might crash so make sure we flush this event.
            SentrySdk.FlushAsync(TimeSpan.FromSeconds(2)).Wait();
        }
    }
};
``` 

Could y'all give it a try and give some feedback? Unfortunately I don't have any UWP live app for dogfooding.

**Comment by bruno-garcia** [comment]
There's a sample here now:
https://github.com/camper-vienna/UwpCsharp

**Comment by bruno-garcia** [comment]
In this [comment ](https://github.com/getsentry/sentry-dotnet/issues/130#issuecomment-501268787) I share a test I did which seems things work fine with UWP as it is.
Haven't gotten any feedback yet from other users though.
Would you be able to try it out and give us some feedback?

**Comment by bruno-garcia** [comment]
I'm closing this because it works fine with UWP. 
We're adding more UWP specific context in 3.0.0 (by we I mean @lucas-zimerman)
