### ISSUE TITLE
Add support to UWP

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#131]
Add support to UWP applications.

See #130

**Comment by Paradoxon101** [comment]
Now that SharpRaven has been declared deprecated, when can we use this library for UWP?

**Comment by bruno-garcia** [comment]
SharpRaven didn't support UWP in any way that this library doesn't.

We still haven't planned any work here but it should already support most cases.
Please see:

https://github.com/getsentry/sentry-dotnet/issues/130#issuecomment-501268787

I'll close this issue as a dupe of #130
