### ISSUE TITLE
Sentry doesn't capture Error log with Microsoft.Extension.Logging

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#132]
Raised in a comment by @alesdvorakcz in #103

I am not using anything more than `.UseSentry()` extension method and buildin logger. No extra configuration is provided

Repro: https://github.com/alesdvorakcz/sentry-test

**Comment by bruno-garcia** [comment]
@alesdvorakcz Raised a new issue as it was not within topic of the last one.

The reason your sample doesn't capture `LogError` is [documented here](https://docs.sentry.io/platforms/dotnet/microsoft-extensions-logging/):

> NOTE: Messages logged from assemblies with the name starting with Sentry will not generate events.

Your sample project is namespaced Sentry: To avoid the possibility of an internal error within Sentry's package to end up on a recursive capture, we simply don't capture error coming from `Sentry` namespace.

**Comment by alesdvorakcz** [comment]
Oh thanks, I was confused by fact that unhandled exception is logged but captured and sended by LogError is not. I tried in different project and it works correctly
