### ISSUE TITLE
ApiApprovalTests doesn't update the PR if run on Github Actions 

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1334]
The breaking change check doesn't update the PR code if tested exclusively on Github when the developer/user didn't test it locally.
 
I believe that the changed files are being generated inside of the GH Machine. But, the altered files are not automatically pushed to the main PR.

Expected: PRs with breaking changes where the user didn't test locally should have the ApiApprovalTests updated once tested on Github Actions.

It may require an additional step on CI for committing the changes once the tests are done.

**Comment by SimonCropp** [comment]
>  But, the altered files are not automatically pushed to the main PR.

I dont think they should be. the act of accepting the new api should be a deliberate decision of the developer. it should not happen as an automated step on a PR.

**Comment by SimonCropp** [comment]
i think this is a better approach https://github.com/getsentry/sentry-dotnet/pull/1341.
