### ISSUE TITLE
Release sentry on nuget with net461 target

### ISSUE THREAD

**Issue by maheskett** [getsentry/sentry-dotnet#135]
We are trying to add sentry to one of our Sitefinity 10.1.6520.0 projects but we are getting Severity	Code Description Project File Line Suppression State Error Unable to find a version of 'Autofac' that is compatible with 'Progress.Sitefinity.Authentication 11.1.6800 constraint: Autofac (= 3.5.2)'.

Is there anyway to get around this error message?

Using .net 4.6.1 and installing Sentry from nuget

**Comment by justinweske** [comment]
Hello Megan, 
Here is another error we are receiving with a different project. 
I'm using nuget to install sentry package
"install-package sentry"

One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Flurl 2.3.0 constraint: System.Globalization (>= 4.0.11)', 'Flurl 2.3.0 constraint: System.Linq (>= 4.1.0)', 'Flurl 2.3.0 constraint: System.Reflection.TypeExtensions (>= 4.1.0)'
install-package : Unable to find a version of 'Microsoft.AspNet.WebApi.Core' that is compatible with 'Microsoft.AspNet.WebApi.Cors 5.2.6 constraint: Microsoft.AspNet.WebApi.Core (>= 5.2.6 && < 5.3.0)', 'Microsoft.AspNet.WebApi.Owin 5.2.6 constraint: 
Microsoft.AspNet.WebApi.Core (>= 5.2.6 && < 5.3.0)', 'Microsoft.AspNet.WebApi.Tracing 5.2.6 constraint: Microsoft.AspNet.WebApi.Core (>= 5.2.6 && < 5.3.0)'.

**Comment by maheskett** [comment]
cc @bruno-garcia

**Comment by bruno-garcia** [comment]
We'll be targeting .NET Framework 4.6.1 to try addressing this issue.

Microsoft has now released a [guideline for library authors](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting) that advises creating such target to work around different issues related to 4.6.1 depending on .NET Standard 2.0 libraries.

> Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

Considering I don't have a repro of the issue, I'm not sure if this will fix it.

I understand that for some people upgrading to .NET Framework 4.7.2 isn't an option but it's not really me saying you should, [it's the PM of .NET](https://twitter.com/terrajobst/status/1031999730320986112):

![image](https://user-images.githubusercontent.com/1633368/48473639-29dca880-e7f9-11e8-8260-14387dfe2e9d.png)

**Comment by justinweske** [comment]
I tried to install beta2 and i'm still getting the following error

One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Flurl 2.3.0 constraint: System.Globalization (>= 4.0.11)', 'Flurl 2.3.0 constraint: System.Linq (>= 4.1.0)', 'Flurl 2.3.0 constraint: System.Reflection.TypeExtensions (>= 4.1.0)'
Install-Package : Unable to find a version of 'Microsoft.AspNet.WebApi.Core' that is compatible with 'Microsoft.AspNet.WebApi.Cors 5.2.6 constraint: Microsoft.AspNet.WebApi.Core (>= 5.2.6 && < 5.3.0)', 'Microsoft.AspNet.WebApi.Owin 5.2.6 constraint: 
Microsoft.AspNet.WebApi.Core (>= 5.2.6 && < 5.3.0)', 'Microsoft.AspNet.WebApi.Tracing 5.2.6 constraint: Microsoft.AspNet.WebApi.Core (>= 5.2.6 && < 5.3.0)'.

**Comment by bruno-garcia** [comment]
@justinweske could you please share a small reproducible app? A link to a github or an attached zip would do.

None of the assemblies listed in the error message are brought in by `Sentry` or depends on Sentry in anyway. Adding Sentry to a project should not affect the dependency tree to those packages so unless we are able to have a repro to work on the root cause, it would be hard to find a solution.
