### ISSUE TITLE
Default to 60 seconds if `Retry-After` is missing

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1376]
If abuse filter is triggered, load balancers can return 429 without any `Retry-After` header.
In this case the SDK should [default to 60 seconds:](https://github.com/getsentry/develop/pull/479)

Currently it's not doing that: https://github.com/getsentry/sentry-dotnet/blob/83f2de36a8cb7823b0ae2f0dd33158a570575aa0/src/Sentry/Internal/Http/RetryAfterHandler.cs#L66-L91

**Comment by SimonCropp** [comment]
dup of #1443
