### ISSUE TITLE
Adjust ASP.NET Core installation steps for .NET 6

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1381]
[Migration docs from .NET 5 to 6 state](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio):

> When using the minimal hosting model, the endpoint routing middleware wraps the entire middleware pipeline, therefore there's no need to have explicit calls to UseRouting or UseEndpoints to register routes. UseRouting can still be used to specify where route matching happens, but UseRouting doesn't need to be explicitly called if routes should be matched at the beginning of the middleware pipeline.

Our current docs point out users must add our `UseSentryTracing` middleware after `UseRouting`. This can be confusing to users when they are no longer there.

Install steps must account for framework version: https://github.com/getsentry/sentry-docs/blob/master/src/wizard/dotnet/aspnetcore.md

**Comment by bruno-garcia** [comment]
Relates to: https://github.com/getsentry/sentry-dotnet/issues/1453

**Comment by bruno-garcia** [comment]
builder.WebHost.UseSentry();

var app = builder.Build();

app.UseSentryTracing();

**Comment by SimonCropp** [comment]
current plan is to update https://github.com/getsentry/sentry-docs/blob/master/src/wizard/dotnet/aspnetcore.md to target the current stable. ie net6

**Comment by bitsandfoxes** [comment]
Parts of this have been addressed in https://github.com/getsentry/sentry-dotnet/pull/2726 and our [documentation](https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/tracing/#middleware) regarding a limitation when calling `UseRouting` explicitly has been updated.
