### ISSUE TITLE
Move solution filter files to 'exclude' approach

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1405]
Once this is implemented: https://developercommunity.visualstudio.com/t/solution-filter-should-allow-for-includeexclude-ba/1090914

Resolves: https://github.com/getsentry/sentry-dotnet/pull/1396#discussion_r770160968

**Comment by SimonCropp** [comment]
@bruno-garcia i dont think the current approach to sln filters has caused enough friction to justify investing in this. @mattjohnsonpint thoughts?
