### ISSUE TITLE
Guide to get sentry-dotnet to work with onpremise

### ISSUE THREAD

**Issue by brunis** [getsentry/sentry-dotnet#1416]
We upgraded a bunch of NuGet packages in our solution, most importantly, we moved from Raven to Sentry-Dotnet and everything seemed fine. Took us several weeks to realize we weren't getting any Sentry events from .NET. Would be really nice to have some docs on minimum version requirements on OnPremise sentry, if that is the issue, or as other issues on the forum suggest, some sort of ErrorOnCapture, so we can log other places that Sentry isn't working.

**Comment by brunis** [comment]
We had 3.10 and tried upgrading to 3.12.2, doesn't work with Sentry OnPremise, but v1.1.2 does, nothing in the readme about breaking changes that makes newer versions of sentry-dotnet incompatible with Sentry OnPremise v9.1.2

**Comment by lucas-zimerman** [comment]
Hi Brunis, Since version 3, you'll need a newer version of OnPremise (Same for the other SDKs).

More information can be found here: https://docs.sentry.io/platforms/dotnet/migration/#self-hosted-support
