### ISSUE TITLE
.Net 6 asp net app - how to enable user integration

### ISSUE THREAD

**Issue by januszj** [getsentry/sentry-dotnet#1417]
I love the app, it looks really nice and have good UX, easy to see what's the problem.

### Environment

Sentry SaaS (sentry.io) 
Using Sentry.AspNetCore Version="3.12.3"

### Steps to Reproduce
Trying to see user linked to Issues.
My setup, in Program.cs
```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder
                .UseStartup<Startup>()
                .UseSentry(o =>
                {
                    o.Dsn = "https://__key__@abc.ingest.sentry.io/123";
                    o.Debug = true;
                    o.TracesSampleRate = 1.0;
                });
            });
```
In Startup.cs - ConfigureServices:
```C#
services.AddSentry();
```
In Startup.cs - Configure:
```C#
...
app.UseRouting();
app.UseSentryTracing();
...
```
I also tried to use, in my Base Controller class where I'm getting current user from Identity User.Identity.Name:
```C# 
SentrySdk.ConfigureScope(scope =>
            {
                scope.User = new User
                {
                    Email = userId
                };
            });
```

### Expected Result

See user linked to the Issue.

### Actual Result
No Users linked to the issues.

**Comment by SimonCropp** [comment]
have you tried this approach to configuring the current user https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/#capturing-the-affected-user  ?

**Comment by januszj** [comment]
Thanks ! that helped
