### ISSUE TITLE
Add 'hint' to the API

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1433]
The unified API has introduced hint back at v1 in 2018 ([see blog](https://blog.sentry.io/2018/09/19/new-sdks-unified-python-javascript-dotnet-rust#powerful-hints-and-hooks)) but we never got around adding this in the .NET SDK.

This will allow passing custom data (if hint becomes a dictionary of sorts) and resolve issues such as this request from the Unity SDK: https://github.com/getsentry/sentry-unity/issues/492

**Comment by mattjohnsonpint** [comment]
Per internal discussion, "hints" are an implementation detail for achieving the goal in #1469.  We'll track this there instead.
