### ISSUE TITLE
Set Global Config Later From Database Config (Startup.cs)

### ISSUE THREAD

**Issue by bradlis7** [getsentry/sentry-dotnet#1434]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
.NET 5.0

### Steps to Reproduce
Trying to set global options in Startup after I use `webBuilder.UseSentry();` in Program.cs, but it doesn't seem to work. I'm using Sentry.AspNetCore.

I tried using `SentrySdk.Init` and `SentrySdk.ConfigureScope`, but the changes don't stick. I need to load up database config, and it's not available in Program.cs.

### Expected Result
If I use `SentrySdk.ConfigureScope` or `SentrySdk.Init`, the things I set should be applied once I log an error. It's unclear how I should set a global configuration after it's initialized with `UseStartup()`.

### Actual Result
The config changes I made were not sent to Sentry.

**Comment by lucas-zimerman** [comment]
SentrySdk.ConfigureScope will only apply the changes on the current request, not affecting the other transactions.

One way to apply those changes to all events/transactions is to configure your tags/context/... inside of the UseSentry callback:

```csharp
.UseSentry(options =>
{
    // Configures the root scope
    options.ConfigureScope(s => s.SetTag("Always sent", "this tag"));
    // Or
    options.DefaultTags.Add("Always sent2", "this tag");
}
```

**Comment by bradlis7** [comment]
@lucas-zimerman yes, but in Program.cs, I don't have access to my database config which I need to configure some information. Perhaps I need to work on restructuring the app in some way, or perhaps relying on a database value shouldn't be a requirement for setting up my error logging, but it just seems like there needs to be a way to set some global config at a later point in the application.

**Comment by bruno-garcia** [comment]
Within web requests the SDK already pushes a new scope so data about the request can go in events to Sentry without mixing with other request. So there you won't be able to add a global tag.

If you resolved the SDK via DI elsewhere (i.e: HostedService or something), or just called `SentrySdk.ConfigureScope` it should set that globally

**Comment by bradlis7** [comment]
@bruno-garcia `Startup.ConfigureServices` and `Startup.Configure` should happen before it any request begins, correct? The changes made using `SentrySdk.ConfigureScope` in these methods were not being saved.

Does calling `WithScope` cancel out info configured in a previous `ConfigureScope`? We have a centralized place where we log the exception:

```
SentrySdk.WithScope(scope => {
  scope.User = ...;
  scope.Level = ...;
  SentrySdk.CaptureException(ex);
});
```

**Comment by bruno-garcia** [comment]
> @bruno-garcia `Startup.ConfigureServices` and `Startup.Configure` should happen before it any request begins, correct? 

That's right.

> The changes made using `SentrySdk.ConfigureScope` in these methods were not being saved.

Scopes rely on AsyncLocal so it's possible there was an async start and somehow the asynclocal during Configure or ConfigureServices didn't flow the same way as when the host started and requests were served. So I guess no work around that I can think of right now. We're discussing a new API in the SDKs that would expose the "root" scope so you could access it from anywhere but that's likely a few months away

> Does calling `WithScope` cancel out info configured in a previous `ConfigureScope`? We have a centralized place where we log the exception:
> 
> ```
> SentrySdk.WithScope(scope => {
>   scope.User = ...;
>   scope.Level = ...;
>   SentrySdk.CaptureException(ex);
> });
> ```

**Comment by bruno-garcia** [comment]
A way to do this is to add a `ISentryEventProcessor` to the container. This will be resolved by the SDK and events captured will go through this. Meaning you can read your settings on the first run (be aware of concurrency), cache the data in the instance (i.e: register a singleton) and subsequent events captured will just read the cached value.

You will not be setting data to scope, you'll be applying to the event directly before the SDK serializes it to send to Sentry

**Comment by lucas-zimerman** [comment]
Feel free to reach out in this issue or another one if you have more questions.
