### ISSUE TITLE
`Sentry.AspNetCore` ignores configured `RouteOptions`

### ISSUE THREAD

**Issue by jacobmstein** [getsentry/sentry-dotnet#1435]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`Sentry.AspNetCore` v3.13.0 (latest)

### Steps to Reproduce

1. Configure ASP.NET Core to lowercase URLs

```cs
services.Configure<RouteOptions>(options =>
{
    options.LowercaseQueryStrings = true;
    options.LowercaseUrls = true;
});
```

2. Configure Sentry as shown [here](https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/)

```cs
// In ConfigureWebHostDefaults:
webBuilder.UseSentry();

// Right before app.UseRouting():
app.UseSentryTracing();
```

3. Create a controller with a `Route` attribute using token replacement, eg.
```cs
[ApiController]
[Route("[controller]")]
public class SubscriptionsController : ControllerBase
{
    [Authorize(Roles = Role.Customer)]
    [HttpPost("checkout")]
    public async Task<IActionResult> GetCheckoutUri([FromQuery] [Required] int orgId)
    {
    
    // ...
```

### Expected Result

Transaction will appear lowercased (`/subscriptions/checkout`) in the Sentry dashboard, similar to Swagger and other tools.

### Actual Result

Transaction appears as if no `RouteOptions` were provided. This is especially obnoxious because I manually name some multi-word controllers to use kebab case rather than token replacement (`[controller]`), eg.
```cs
[Route("password-resets")]
```

![image](https://user-images.githubusercontent.com/31670124/149071596-6511eccf-b35e-4eeb-be38-785cb74b171e.png)

**Comment by jacobmstein** [comment]
> Sounds like a bug. Thanks for raising this and letting us know

Sure thing. I also found another issue with routing which is related, so I will put it here. Let me know if you want me to open a new issue.

I am using an application base path (`app.UsePathBase("/api");`), which is accounted for, as well as the new [ASP.NET Core health checks](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0) (`endpoints.MapHealthChecks("/healthz");`). It shows up in the dashboard as `GET api//healthz`. Duplicate slashes should also probably be removed. If you're okay with that behavior I could submit a PR.

**Comment by mattjohnsonpint** [comment]
Sorry this appears to have fallen off our radar.  We'll take another look ASAP and reassess priority.

And yes, PRs are always welcome. 😃 

Thanks.

**Comment by SeanFeldman** [comment]
I've tried the latest version of `Sentry.AspNetCore`, 3.29.1, and it appears to behave as expected. The transaction name generated for the use case you've provided `GET subscriptions/checkout`.

The controller name will be lowercase for a multi-word controller use case, but no kebab case will be applied. And that's the default ASP.NET Core behaviour. You can work around that by registering a custom route transformer.  For example, for a `SubscriptionsManagement` controller name to show up in the transaction name as `GET subscriptions-management/checkout`. Below is the code to achieve that with the workaround that lowers the case and delimiters words - credits to the StackOverflow answer [here](https://stackoverflow.com/a/53838976/59563).

The Startup code I've used to confirm the default behaviour:

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<RouteOptions>(options =>
{
    options.LowercaseUrls = true;
    options.LowercaseQueryStrings = true;
});

// Workaround to fix Route Options shortcomings related to Controllers name
builder.Services.AddControllers(options =>
{
    options.Conventions.Add(new RouteTokenTransformerConvention(new SlugifyParameterTransformer()));
});

builder.WebHost.UseSentry();

var app = builder.Build();

app.UseSentryTracing();

app.MapHealthChecks("/healthz");

app.UsePathBase(new PathString("/api"));
app.UseRouting();

app.MapControllers();

app.Run();
```

And the controller

```
[ApiController]
[Route("[controller]")]
public class SubscriptionsManagementController : ControllerBase
{
    [HttpGet("checkout")]
    public Task<string> GetCurrentStatus([FromQuery] [Required] int orgId)
    {
        throw new Exception("Oy vay");
    }
}
```
![image](https://user-images.githubusercontent.com/1309622/227815806-7723eb4e-e9ae-403f-93b8-3cc12de3c4e1.png)

You could apply the same to your actions and derive a slugified name from the action/method name itself. The workaround would need a slight modification to remove the HTTP verbs as suffixes, but I'll let you decide if you want that. That way, you'd not have to hardcode the route name. For example: 

```
[HttpGet]
[Route("[action]")]
public Task<string> GetCurrentStatus()
{
    throw new Exception("thrown when using the defaults");
}
```

It would produce a transaction name `GET subscriptions-management/get-current-status`. 

As for the health endpoint with `/healthz`, that's a bug. The generated transaction name `GET api//healthz` is wrong.
Here's a link to the dedicated issue I'll work on. https://github.com/getsentry/sentry-dotnet/issues/2256
