### ISSUE TITLE
x64 Sentry Binary in NuGet

### ISSUE THREAD

**Issue by jasonlor** [getsentry/sentry-dotnet#1436]
I'm trying to compile Sentry into a x64 only project and I've been encountering this issue: https://forum.sentry.io/t/net-c-does-not-report-to-the-backend/14468/4. 

Upon closer inspection of the NuGet package, it appears that only x86 binary is available: <img width="2129" alt="image" src="https://user-images.githubusercontent.com/197345/149370901-987ed62c-700d-4678-9e0b-57448ea57ef7.png">

Is it possible for x64 only DLL be made available?

**Comment by bruno-garcia** [comment]
The package includes only IL code. There's no native code at all

**Comment by bruno-garcia** [comment]
Btw if by any chance you're running [`sentry-native` on Windows](https://github.com/getsentry/sentry-native), that'd be named Sentry.DLL too. Is it possible that's the case?

**Comment by jasonlor** [comment]
As far as I'm aware, I've tried installing this package:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/197345/150298919-28bb77a0-0eb6-4cb9-b4fa-c30704594ad6.png">

I'm definitely seeing the issues described in that thread but the `AutoGenerateBindingRedirects` doesn't appear to do the trick.

**Comment by lucas-zimerman** [comment]
Could you set `Debug` as true on your Sentry Options and share the output from your application?

**Comment by bruno-garcia** [comment]
I'm not sure what issue you're describing. The NuGet package installed on a project will being a DLL that's not specific to any CPU as I described above. Could you please describe what you are trying to do?

Is that a `dotnet new console` `dotnet run` that fails?

**Comment by bruno-garcia** [comment]
Closing this as there's nothing much we can do here. Feel free to reopen if that's not the case.
