### ISSUE TITLE
Use latest release for new issues

### ISSUE THREAD

**Issue by robbaman** [getsentry/sentry-dotnet#1439]
I've browsed through the docs but haven't been able to find it, but is there a way to use the latest Release for new issues? In our situation we push new release versions to Sentry as part of our CI-tooling, but the various services that push issues to Sentry don't all have access to this release version number.

It seems that when you don't set a Release version in the options, it just uses 1.0.0 which means we can't use the Releases functionality which would be a major letdown :(

Thanks in advance.

**Comment by lucas-zimerman** [comment]
Hi,
To better help you, could you provide which platform are you using? (.NET Core, ASP.NET, console, Xamarin,...)

**Comment by robbaman** [comment]
Apologies, we're using dotnet 6 using the Sentry.AspNetCore package and add Sentry in the startup file using:

```
.ConfigureWebHostDefaults(webBuilder => {
	webBuilder.UseStartup<Startup>();
	webBuilder.UseSentry();
});
```

However, we ended up just creating a project in Sentry for each external service and tracking separate release numbers, so I suppose the urgency is somewhat gone. It does surprise me though, we used Sentry up to about a year ago and I'm certain we never provided a Release number before and all issues used to be added to the latest release anyway.

**Comment by lucas-zimerman** [comment]
The SDK sets the release version from the Package Version or from the environment variable  "SENTRY_RELEASE".

You can also manually specify the release version on `appsettings.json` or on UseSentry
```csharp
webBuilder.UseSentry(options => options.Release = "1.0.1");
```

**Comment by robbaman** [comment]
Thanks, that's what we ended up doing. We now set the Release property in the appsettings.json and use a different project for every application that has a CI-pipeline. This is good enough for us for now.
