### ISSUE TITLE
Sentry.EntityFramework spamming diagnostic logs

### ISSUE THREAD

**Issue by CADbloke** [getsentry/sentry-dotnet#1440]
### Win 10 VS 2019 

How do you use Sentry?
WPF App with Serilog.Sentry  .NET 4.8

Which SDK and version?
```` xml
  <package id="EntityFramework" version="6.4.4" targetFramework="net48" />
  ...
  <package id="Sentry" version="3.12.3" targetFramework="net48" />
  <package id="Sentry.EntityFramework" version="3.12.3" targetFramework="net48" />
  <package id="Sentry.Serilog" version="3.12.3" targetFramework="net48" />
  <package id="Serilog" version="2.10.0" targetFramework="net48" />
  <package id="Serilog.Enrichers.Demystifier" version="1.0.1" targetFramework="net48" />
  <package id="Serilog.Exceptions" version="8.0.0" targetFramework="net48" />
  <package id="Serilog.Sinks.Async" version="1.5.0" targetFramework="net48" />
  <package id="Serilog.Sinks.File" version="5.0.0" targetFramework="net48" />
  <package id="SQLite.CodeFirst" version="1.7.0.34" targetFramework="net48" />
  <package id="Stub.System.Data.SQLite.Core.NetFramework" version="1.0.115.5" targetFramework="net48" />
...
  <package id="System.Data.SQLite" version="1.0.115.5" targetFramework="net48" />
  <package id="System.Data.SQLite.Core" version="1.0.115.5" targetFramework="net48" />
  <package id="System.Data.SQLite.EF6" version="1.0.115.5" targetFramework="net48" />
  <package id="System.Data.SQLite.Linq" version="1.0.115.5" targetFramework="net48" />
````

Same results with v 3.13 of Sentry packages.

### Steps to Reproduce

1. installed Sentry.EntityFramework
2. WPF App crashed today with no notice, was not logged even by even by the unhandled exception catcher. May not be related
3. looked at Sentry diagnostic  logs - a text logger : `SelfLog.Enable(msg => File.AppendAllText(_serilogSelfLogFilePath, msg + Environment.NewLine));` - which had tens of thousands of lines like `[v1.1.3521.22017] 2022-01-17 11:50:03.339 [Information] "Span with key db.query was not found on interceptionContext."  {  }`
4. I uninstalled the Sentry.EntityFramework package & removed `s.AddEntityFramework();`
5. see https://github.com/getsentry/sentry-dotnet/commit/15064c57e469b85c497c39a2fd4e16da8592f609#diff-3c0d927d9ad1e225d2b5fc7aefe1c1bad5a8e6fd28f3ab96f5b9d75b6babf92dR73 for where this is logged.

### Expected Result

less noise in the diagnostic file.

### Actual Result

62k entries in 13 daily log files mostly like 
````
[v1.1.3521.22017] 2022-01-17 11:50:03.334 [Information] "Span with key db.query was not found on interceptionContext."  {  }
[v1.1.3521.22017] 2022-01-17 11:50:03.334 [Information] "Span with key db.query was not found on interceptionContext."  {  }
[v1.1.3521.22017] 2022-01-17 11:50:03.335 [Information] "Span with key db.query was not found on interceptionContext."  {  }
[v1.1.3521.22017] 2022-01-17 11:50:03.335 [Information] "Span with key db.query was not found on interceptionContext."  {  }
[v1.1.3521.22017] 2022-01-17 11:50:03.336 [Information] "Span with key db.query was not found on interceptionContext."  {  }
[v1.1.3521.22017] 2022-01-17 11:50:03.336 [Information] "Span with key db.query was not found on interceptionContext."  {  }
[v1.1.3521.22017] 2022-01-17 11:50:03.336 [Information] "Span with key db.query was not found on interceptionContext."  {  }
````

Please let me know if this is expected behaviour and something is broken in the EF part on my app. Apologies in advance if it's my mess. If I can help in any way, please let me know.

Cheers
Ewen

**Comment by lucas-zimerman** [comment]
Hi and thanks for opening this issue.

I suppose that you're not using transactions right?
The problem might be happening because 
https://github.com/getsentry/sentry-dotnet/commit/15064c57e469b85c497c39a2fd4e16da8592f609#diff-3c0d927d9ad1e225d2b5fc7aefe1c1bad5a8e6fd28f3ab96f5b9d75b6babf92dR45
expects to have an active transaction inside of the Hub.

For the moment, you can disable this integration with the following code:
```csharp
s.AddEntityFramework();
s.DisableDbInterceptionIntegration();
```
Or you could register a new Transaction into the Hub
```
var transaction = SentrySdk.StartTransaction("My transaction", "operation");
SentrySdk.ConfigureScope(scope => scope.Transaction = transaction);
// Your code to be measured.
transaction.Finish(SpanStatus.Ok);
```

**Comment by bruno-garcia** [comment]
If this warning happens even if users don't have performance monitoring, the warning is the issue

**Comment by CADbloke** [comment]
> I suppose that you're not using transactions right?

Correct. I added it simply to see what it adds to the breadcrumb trail without adding anything else to my code.  didn't add performance monitoring or anything else, just the Nuget package and the 1 extra line in the config.
