### ISSUE TITLE
use IHttpClientFactory to avoid HttpClient issues

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1442]
HttpClient has issues with sockets exhaustion and DNS changes
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net

>Another issue that developers run into is when using a shared instance of HttpClient in long-running processes. In a situation where the HttpClient is instantiated as a singleton or a static object, it fails to handle the DNS changes as described in this issue of the dotnet/runtime GitHub repository.
> However, the issue isn't really with HttpClient per se, but with the default constructor for HttpClient, because it creates a new concrete instance of HttpMessageHandler, which is the one that has sockets exhaustion and DNS changes issues mentioned above.
> To address the issues mentioned above and to make HttpClient instances manageable, .NET Core 2.1 introduced the IHttpClientFactory interface which can be used to configure and create HttpClient instances in an app through Dependency Injection (DI). It also provides extensions for Polly-based middleware to take advantage of delegating handlers in HttpClient.

Proposal: Add the ability to use IHttpClientFactory

**Comment by bruno-garcia** [comment]
`SocketsHttpHandler` is already the default when using HttpClient on .NET Core 2.1 or later:

[SocketsHttpHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-6.0)
> Provides the default message handler used by HttpClient in .NET Core 2.1 and later.
