### ISSUE TITLE
Introduce a default Retry-After value if one is not present

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1443]
The SDK doesn't have a default value in case the response headers don't include a value for Retry-After:

https://github.com/getsentry/sentry-dotnet/blob/a9304a0a4b4702d0e62e2703d55c66483d27a0e5/src/Sentry/Internal/Http/RetryAfterHandler.cs#L80-L87

See: https://github.com/getsentry/develop/pull/492

**Comment by bruno-garcia** [comment]
Update notion once this is done:

https://www.notion.so/sentry/Add-rate-limit-default-to-NET-fe4aa210986e475c952b2924640c4204

**Comment by mattjohnsonpint** [comment]
Done.

**Comment by bruno-garcia** [comment]
Nice! Thank you Matt!
