### ISSUE TITLE
Add `handled:true` when an exception has been handled

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1480]
The SDK captures unhandled exceptions by flagging those to `handled: false`. The opposite isn't the case. Simply no option is sent.
The issue is when customers are trying to create alerts. Or query by "Handled: true". To help with this, the SDK should always include the Handled property, and default it to 'true'

**Comment by bruno-garcia** [comment]
Further clarification: By default events are "handled:true" that's why the value hasn't been added explicitly before.

**Comment by mattjohnsonpint** [comment]
I rediscovered this while working in other areas.  Investigation results:

### `exception.mechanism.handled:true`
- Tags the event with:
  <img width="113" alt="image" src="https://user-images.githubusercontent.com/1396388/230159499-2b0ae2df-ebc6-4af9-8993-29dfaccfc8ec.png">
- Flags the exception with:
  <img width="123" alt="image" src="https://user-images.githubusercontent.com/1396388/230156656-38d1ab27-2903-46d9-9b62-6324f9da9cc3.png">
- Appears in search results with filters `error.handled:true` or `error.unhandled:false`
- Does not appear in search results with filters `error.handled:false` or `error.unhandled:true`
- Triggers alert with filters `error.handled == true` or `error.unhandled == false`
- Does not trigger alert with filters `error.handled == false` or `error.unhandled == true`
- Does not trigger alert with filters `error.handled is unset` or `error.unhandled is unset`

### `exception.mechanism.handled:false`
- Marks the event title with:
  <img width="97" alt="image" src="https://user-images.githubusercontent.com/1396388/230157887-9672a79e-1afc-4619-8265-717add9788cf.png">
- Tags the event with:
  <img width="104" alt="image" src="https://user-images.githubusercontent.com/1396388/230159260-a9926b3e-2cbd-4a81-b41e-163eef0a25b2.png">
- Flags the exception with:
  <img width="130" alt="image" src="https://user-images.githubusercontent.com/1396388/230157385-72c62206-77cd-4a7f-8b70-7a3781b4b3e5.png">
- Appears in search results with filters `error.handled:false` or `error.unhandled:true`
- Does not appear in search results with filters `error.handled:true` or `error.unhandled:false`
- Triggers alert with filters `error.handled == false` or `error.unhandled == true`
- Does not trigger alert with filters `error.handled == true` or `error.unhandled == false`
- Does not trigger alert with filters `error.handled is unset` or `error.unhandled is unset`

### `exception.mechanism.handled:null` (default)
- Doesn't add any tags or flags to the event or exception in any way.
- Appears in search results with filters `error.handled:true` or `error.unhandled:false`
- Does not appear in search results with filters `error.handled:false` or `error.unhandled:true`
- Triggers alert with filters with filters `error.handled is unset` or `error.unhandled is unset`
- ***Does not trigger alert with filters `error.handled == false` or `error.unhandled == false`***
- ***Does not trigger alert with filters `error.handled == true` or `error.unhandled == true`***

### Conclusion

Presently, we set `exception.mechanism.handled:false` in all unhandled exception handlers, so everything is fine there.  However, we never set `exception.mechanism.handled:true`, so event are never tagged with `handled:yes`, and exceptions are never marked with `handled:true`.  Search filters work fine, but alert filters would only fire on handled exceptions if specifically setting up the filter with "is unset".

I believe we should do the following:

- Keep sending `exception.mechanism.handled:false` for unhandled exceptions such as:

  ```csharp
  throw new Exception();
  ```

- Keep sending `exception.mechanism.handled:null` if the exception is captured directly, such as:

  ```csharp
  SentrySdk.CaptureException(new Exception());
  ```

- Start sending `exception.mechanism.handled:true` if the exception was caught and then captured, such as:

  ```csharp
  try
  {
      throw new Exception();
  }
  catch (Exception ex)
  {
      SentrySdk.CaptureException(ex);
  }
  ```

I tested this approach and it does not affecting issue grouping.  It only affects the UI and alert filters.

**Comment by mattjohnsonpint** [comment]
I should elaborate on a key point.  The reason to continue using `exception.mechanism.handled:null` on an exception that is never thrown, is because it is ultimately just the same as capturing a message.  It just has some additional details included.  It was never thrown, so it's neither handled nor unhandled - it's just information.
