### ISSUE TITLE
Revert adding Sentry to global usings

### ISSUE THREAD

**Issue by jhartmann123** [getsentry/sentry-dotnet#1487]
The latest Release 3.14.0 comes with the following feature:

> Add Sentry to global usings when ImplicitUsings is enabled (<ImplicitUsings>true</ImplicitUsings>) (https://github.com/getsentry/sentry-dotnet/pull/1398)

We do have implicit usings enabled, with the intention was that only the often used "standard"-namespaces are added there.
Sentry on the other hand is a namespace which we use exactly once in our ASP.NET Core API projects: when configuring Sentry on startup.

For me as an "end user" of this library it does make absolutely no sense to have Sentry in the global usings.

**Main issue:**  
The main conflict here is `Sentry.User`. I guess a `User` is not a really uncommon name for a class. Now, with the latest update we have a lot of ambiguous references between Sentry.User and our Domain-User. As a workaround I'd have to explicitly reference our Domain-User in a ton of classes over multiple projects. Which I really don't want to do.

So I vote for removing Sentry from global usings again.

**Comment by bruno-garcia** [comment]
`User` is definitely high chance of conflict. I suggest we take a pragmatic approach:

1. asap: release a patch release with a opt-out for ImplicitUsings (e.g: `<SentryImplicitUsings>false`)
2. Name Sentry.User to `SentryUser` on the next major change. Do such renames on other types that are high risk of conflict

**Comment by davidroth** [comment]
IMO adding Sentry to global usings was a mistake. This library is used only in the composition root in 99% of the cases. The potential for real naming clashes (`User`) and similar types (i.e. `Sentry.Span` vs `System.Span<T>`) is real and not worth it IMO.

**Comment by bruno-garcia** [comment]
We discussed and agreed to revert this feature, until we release 4.0 that will include renaming some types prone to conflict.
Lets spin off a new issue to track the class renames and adding this feature back in.
