### ISSUE TITLE
consider adding  the windows marketing version (eg 21H2) to the reported metadata

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1517]
![image](https://user-images.githubusercontent.com/122666/157742639-798a2ec7-ee1a-487a-9b2e-79e6bdcaf091.png)

**Comment by SimonCropp** [comment]
TODO: raise with relay team

**Comment by mattjohnsonpint** [comment]
If this *can* be captured directly from environment variables (etc.), without having a translation from the version number, then we should probably do so in the SDK, IMHO.

**Comment by SimonCropp** [comment]
upstream fixed: https://github.com/getsentry/relay/issues/1201

so closing this
