### ISSUE TITLE
Add option to skip modules registration

### ISSUE THREAD

**Issue by voltcode** [getsentry/sentry-dotnet#152]
I'm trying to disable registering all modules (packages) on each event - they are of no use, just take up bandwidth.

MainSentryEventProcessor.Process always loops through assemblies to register the modules.

Could the options be extended to include whether to include the modules at all? Or maybe there is already another option for that, apart from providing a BeforeSend option that would erase already collected modules?

**Comment by bruno-garcia** [comment]
That makes sense.
Would make sense to have a configuration property called: `ReportAssemblies` on SentryOptions with a default value of `true` so it won't be a breaking change.

And surround this code:

https://github.com/getsentry/sentry-dotnet/blob/e7d71e7fe4a221ae9deb76c49214a8fb964f8bfe/src/Sentry/Internal/MainSentryEventProcessor.cs#L114-L123

With a `if` that checks this configuration option. `MainSentryEventProcessor` already depends on `SentryOptions` so it it's just a matter of adding the `if`.

**Comment by bruno-garcia** [comment]
Done through: #202
Will be available on 1.1.3-beta5
