### ISSUE TITLE
Issue with SentrySqlListenerTests.OnNext_KnownKey_GetSpanInvoked test

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1524]
`dotnet test` pops a failed debug assert on Windows for the .NET Framework 4.6.1 target.  Does not occur on any other targets, nor for this target on macOS with Mono.  Doesn't hit our CI because our build scripts are running tests in `Release` configuration.

Command to run just the one test:
```
dotnet test test/Sentry.DiagnosticSource.Tests -f net461 --filter Sentry.DiagnosticSource.Tests.SentrySqlListenerTests.OnNext_KnownKey_GetSpanInvoked
```

On Windows (Win 11 21H2, .NET Framework 4.8 runtime) gives a debug popup:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1396388/158240678-f0c60117-ab9c-4c9d-b54b-c10162987e1d.png">

Debugging goes to here:

https://github.com/getsentry/sentry-dotnet/blob/bf6d12d7cbf248e9dcadcfbc6309c2172545b086/src/Sentry.DiagnosticSource/Internals/DiagnosticSource/SentrySqlListener.cs#L62

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1396388/158241343-226a381c-b5cf-46cd-9842-b3fe2b338e9e.png">

Despite the failed assertion, the test will pass if you ignore and continue.  Is an empty `operationId` valid?

**Comment by lucas-zimerman** [comment]
issue seems related to this line
https://github.com/getsentry/sentry-dotnet/blob/bf6d12d7cbf248e9dcadcfbc6309c2172545b086/test/Sentry.DiagnosticSource.Tests/SentrySqlListenerTests.cs#L167
where we are not passing a valid guid to the operation id and the connection id .
we could fix the issue by setting a new guid to both operation and connection id.

**Comment by mattjohnsonpint** [comment]
Also, it seems that the operation id is empty on all platforms, it's just that how `Debug.Assert` is handled by the `dotnet test` runner varies between versions.
