### ISSUE TITLE
Make breadcrumbs from console events.

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1526]
It seems like some libraries use Console for outputting some warning/debug/error messages, for example

https://github.com/xamarin/Essentials/search?q=Console.WriteLine

https://github.com/Redth/ZXing.Net.Mobile/search?q=Console.WriteLine

An example of what could be done is the following snippet:

```csharp
Console.SetOut(new ConsoleTraceListener());
...
        private class ConsoleTraceListener : TextWriter
        {
            public override Encoding Encoding => Encoding.Default;

            private string _previousString { get; set; }

            public override void Write(char[] buffer)
            {
                var str = new string(buffer);
                if (ShouldLog(str))
                {
                    _previousString = str;
                    SentrySdk.AddBreadcrumb(str, "Console.Write");
                    base.Write(buffer);
                }
            }

            public override void WriteLine(char[] buffer)
            {
                base.WriteLine(buffer);
                var str = new string(buffer);
                if (ShouldLog(str))
                {
                    _previousString = str;
                    SentrySdk.AddBreadcrumb(str, "Console.WriteLine");
                    base.WriteLine(buffer);
                }
            }
            private bool ShouldLog(string buffer)
                => _previousString != buffer && !buffer.StartsWith("  Debug") && !string.IsNullOrWhiteSpace(buffer);
        }
    }
```

**Comment by bruno-garcia** [comment]
Sounds like this could be a .NET SDK integration. Perhaps turned on by default, except in some integrations we can remove it.

**Comment by mattjohnsonpint** [comment]
I think there are too many ways this could be fragile.  For example, imagine an app has both console logging and sentry logging enabled, and we picked up the console logging as breadcrumbs - we could end up in an endless loop.

Also, @SimonCropp point out that there are usually better ways to hook these sorts of events.  Both of the scenarios linked to are generally anti-patterns - one should either write to an error handler, or at least use `Console.Error.WriteLine`, etc. or use a logging abstraction like Serilog.  So we probably shouldn't reinforce using that approach.

That said, if someone really needs to do this, they can certainly pick up the code from this issue to add their own breadcrumbs.  I just wouldn't want to build it in.
