### ISSUE TITLE
Allow to use custom sampling context provider

### ISSUE THREAD

**Issue by TailyFair** [getsentry/sentry-dotnet#1533]
It would be great to be able to integrate my own custom sampling context provider. So trace sampling could be more flexible.
Then it would be possible to use IP address or some header to decide if transaction should be sampled.

Suggested API:
```csharp
public interface ISentryCustomSamplingContextProvider
{
    Dictionary<string, object?> GetSamplingContext(HttpContext context);
}
```

Usage:
```csharp

public class CustomContextProvider : ISentryCustomSamplingContextProvider
{
    public Dictionary<string, object?> GetSamplingContext(HttpContext context)
    {
        return new Dictionary<string, object?>(1, StringComparer.Ordinal)
        {
             ["CustomProperty"] = context.Requests.Headers.GetValueOrDefault("ShouldSample");
        }
    }
}

// In Startup.cs
app.UseSentryTracing(options => 
{
    options.SamplingContextProvider = new CustomContextProvider()
});
```

**Comment by mattjohnsonpint** [comment]
We do already have this API:

https://github.com/getsentry/sentry-dotnet/blob/6f35bc4f58a598a07252e4b38d641c1acebc7cf1/src/Sentry/IHub.cs#L25-L30

Which you can see used here:

https://github.com/getsentry/sentry-dotnet/blob/e615aa9e482c30012db1712d3d8b1b8622ef4d57/src/Sentry.AspNetCore/SentryTracingMiddleware.cs#L74-L81

However, we agree that this doesn't quite cut it.  It would be better if the delegate had the entire `HttpContext` passed in.

There's also this option:

https://github.com/getsentry/sentry-dotnet/blob/107cb5838b2e22144572dee0db271da3846aabe5/src/Sentry/SentryOptions.cs#L480-L490

Which is documented here:

https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/configuration/options/#traces-sampler

But I think we can do better both on the implementation and docs.

Thanks!

**Comment by bruno-garcia** [comment]
Customers are asking about accessing the HttpContext in the `TracesSampler` callback (through the data bag in there):
https://sentry.zendesk.com/agent/tickets/64563

**Comment by mattjohnsonpint** [comment]
This came up again on Discord chat recently.  The customer needed access to HTTP headers within the `TracesSampler`.  I'm going to raise the priority on this.
