### ISSUE TITLE
Windows tests dev dependencies

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#1551]
I'm trying to execute tests `./build.ps` on the repo on Windows and am getting the following issues. There seem to be a dependency that's not mentioned in `CONTRIBUTING.md`:

```
[xUnit.net 00:00:02.79]     SqlListenerTests.RecordsEf [FAIL]
  Failed SqlListenerTests.RecordsSql [1 ms]
  Error Message:
   System.TypeInitializationException : The type initializer for 'SqlListenerTests' threw an exception.
---- System.Exception : Failed to setup a LocalDB instance.
name: SqlListenerTestsDotNet6_0
 ```

**Comment by vaind** [comment]
Installing LocalDB have helped, see this guide: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15 - so maybe the docs need an update.

**Comment by SimonCropp** [comment]
@vaind you are correct. i will fix that now

**Comment by SimonCropp** [comment]
@vaind how does this look https://github.com/getsentry/sentry-dotnet/pull/1552  ?
