### ISSUE TITLE
Cant target net6.0-maccatalyst

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1565]
since `net6.0-maccatalyst` [current assumes c#10](https://github.com/dotnet/runtime/issues/67497) and `sentry.csproj` targets c#9 for compat with unity, we cant have a target `net6.0-maccatalyst`.

**Comment by SimonCropp** [comment]
@bruno-garcia did we ever confirm there are real problems with c#10 and unity? i seem to remember we did this as a precaution

**Comment by mattjohnsonpint** [comment]
From the linked issue:

> This was fixed by [xamarin/xamarin-macios#14475](https://github.com/xamarin/xamarin-macios/pull/14475), it should be in the rc1 release of maui/xamarin.

That is expected this month.  I think we can just wait.

**Comment by mattjohnsonpint** [comment]
I verified it builds with the MAUI RC1 release.  That said, I don't think we'll actually want a `net6.0-maccatalyst` target for `Sentry.csproj` itself.

**Comment by bruno-garcia** [comment]
I think we can multi target to native sdks straight on the Sentry.csproj 
This allows any framework integration built on top of it to have native crash reporting and release health. Similar to the Android draft pr open
