### ISSUE TITLE
remove server_os in favor of only client_os

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1575]
### Problem Statement

`contexts.os` is still "the OS the SDK ran on" while `contexts.client_os` is practically "the OS as parsed from UA if there is no other OS set".

- Advantages: Event schema is simple, no SDK changes necessary, user search remains useful

### Solution Brainstorm

https://www.notion.so/sentry/Conflicting-OS-contexts-6b4b157034c54c02a97ea8523bee265d#6aa1e8cc97f4444bb33d180ecf7c3adf

Relates to: https://github.com/getsentry/sentry-dotnet/issues/1484

See also: https://github.com/getsentry/develop/pull/557

**Comment by SimonCropp** [comment]
@mattjohnsonpint @bruno-garcia can i get access to notion?

**Comment by mattjohnsonpint** [comment]
Notion is internal only - sorry.  You're not missing much though, that page is just the raw notes from the original discussion.  The result was captured into the public develop docs here:  https://develop.sentry.dev/sdk/event-payloads/contexts/#os-context

That trumps anything that is on Notion anyway.  Thanks.

**Comment by mattjohnsonpint** [comment]
After reviewing [the dev docs](https://develop.sentry.dev/sdk/event-payloads/contexts/#os-context), I can better summarize the required change

- In Sentry core, we are only sending `"os"`, and we should continue to do so.
- In Sentry.AspNet and Sentry.AspNetCore, we have code that moves `"os"` to `"server-os"`, and `"runtime"` to `"server-runtime"`.  We should simply stop doing that.

We never populate any other os or runtime contexts, and Sentry on the back-end will still create a separate `client_os` context derived from the user agent data we're sending.

I've made these changes in #1893.
