### ISSUE TITLE
check vulnerable nuget packages is broken

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1596]
requires a build first. I will submit a PR

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/122666/165282501-7cf314d2-88c4-4f83-85bd-c986c7646b15.png">

https://github.com/getsentry/sentry-dotnet/runs/6173260174?check_suite_focus=true

```
No assets file was found for `/home/runner/work/sentry-dotnet/sentry-dotnet/src/Sentry/Sentry.csproj`.
Please run restore before running this command.

No assets file was found for `/home/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Tests/Sentry.Tests.csproj`.
Please run restore before running this command.
```

**Comment by SimonCropp** [comment]
i wonder if we bother fixing this? it has been broken forever, so we clearly dont use it. and it adds ~50s to a build. Should we just remove it?

**Comment by bruno-garcia** [comment]
This probably broken when changing to .NET 6 as the dotnet format broke?

Lets fix this, we can get it to build first in that workflow to avoid delaying the main build/test/pack?

**Comment by SimonCropp** [comment]
but to avoid two restore+build, cant we just do this in the build workflow?

**Comment by mattjohnsonpint** [comment]
We really should try only to restore once, due to https://github.com/getsentry/sentry-dotnet/issues/1568#issuecomment-1110000305.  I'd even be in favor of a separate restore stage running `dotnet restore` and using `--no-restore` on the build stage.
