### ISSUE TITLE
`IncludeRequestPayload` - JSON

### ISSUE THREAD

**Issue by btecu** [getsentry/sentry-dotnet#164]
`IncludeRequestPayload` should also include a `json` body, as opposed to just a body form.

**Comment by bruno-garcia** [comment]
@btecu could you please elaborate?
The current implementation also supports JSON body. One of the samples actually returns JSON.

**Comment by btecu** [comment]
It didn't include the `JSON` body when I tested it. Seems to have included everything else.
I looked and it seemed it was checking only forms: https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry.AspNetCore/FormRequestPayloadExtractor.cs#L9

My use case is in a `MvcCore` - api only application. Not sure if this makes a difference or if there's something else that regular `Mvc` brings in.
Do you have a template for tests? I could try creating one.

**Comment by bruno-garcia** [comment]
The [`DefaultPayloadExtractor`](https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry.AspNetCore/DefaultRequestPayloadExtractor.cs) will take care of JSON.
It works with any type of ASP.NET Core application. It doesn't require MVC as it depends only on `Microsoft.AspNetCore.Http`.

Tests for it are [here](https://github.com/getsentry/sentry-dotnet/blob/4035e25116d188eeac073a4042d130bb7ef2b613/test/Sentry.AspNetCore.Tests/ServiceCollectionExtensionsTests.cs). No specific tests for JSON. Would be great to get them! Thanks.

**Comment by btecu** [comment]
Looks like it throws internally:
![image](https://user-images.githubusercontent.com/7517745/53135875-e9ed3600-354a-11e9-962f-8f4fb99dc995.png)

What more information can I provide?

**Comment by bruno-garcia** [comment]
It seems the request stream was disposed. This was raised here: https://github.com/getsentry/sentry-dotnet/issues/159

Something is disposing you request stream before we have a chance to read from it.

**Comment by btecu** [comment]
That was the issue, the JSON deserializer was using the stream (`Request.Body`) without marking it with `leaveOpen: true`.

Perhaps this should be documented somewhere, since a lot of people are going to run into it?
