### ISSUE TITLE
Dependency caching restore super slow on Windows

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1647]
https://github.com/getsentry/sentry-dotnet/runs/6327391846?check_suite_focus=true

Time to restore dependencies from cache:

| Ubuntu | macOS | Windows |
|-|-|-|
| 18s | 29s | 4m 5s |

With timings visible, it's clearly the `tar` operation that is the culprit:

![image](https://user-images.githubusercontent.com/1396388/167201605-79897d3a-8607-4c17-8368-d37fee88591c.png)

Others appear to be having the same issue.  Reported on the thread here: https://github.com/actions/cache/issues/752#issuecomment-1119931553

**Comment by mattjohnsonpint** [comment]
Going to disable it on Windows for now.  Leaving this issue open though, so we can remember to turn it back on when GitHub fixes the underlying issue.

**Comment by bitsandfoxes** [comment]
Closing this as it got cleaned up along the way somewhere.
