### ISSUE TITLE
Add missing parameter `sent_at` to the envelope header 

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1687]
### Problem Statement

see: https://github.com/getsentry/sentry/issues/35312 and https://develop.sentry.dev/sdk/envelopes/#data-model

this is a recommended parameter to be sent in order to properly set the clock drift correction for transactions/events.

**Comment by SimonCropp** [comment]
we send a `timestamp`  with what seems like the same data. should that be named `sent_at`?

**Comment by SimonCropp** [comment]
seems we should have both

> If the actual question you're asking is why we don't fill sent_at with event.timestamp: This is based on the assumption that we cannot trust the event timestamp, since the SDKs have arbitrary delays between recording and sending an event. See native, where the events are buffered on disk and sent on restart.

https://github.com/getsentry/relay/issues/534#issuecomment-601674314

**Comment by SimonCropp** [comment]
current status: @bruno-garcia is going to follow up on the exact requirement for `sent_at`

**Comment by mattjohnsonpint** [comment]
I don't understand why we need this.  We already have `sentry_timestamp` set in the `X-Sentry-Auth` header per https://develop.sentry.dev/sdk/overview/#authentication

Since that's the last point out the door before sending the http request to sentry, it's going to be more accurate than anything captured on the event.

**Comment by SimonCropp** [comment]
@mattjohnsonpint sorry, ignore [my comment](https://github.com/getsentry/sentry-dotnet/pull/1690#issuecomment-1153091247). Yes my sent_at PR would add no more value than using the `sentry_timestamp` header

**Comment by SimonCropp** [comment]
@mattjohnsonpint @bruno-garcia what was the outcome of this?
