### ISSUE TITLE
Extension for AggregateException

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#1696]
### Problem Statement

Came up through Unity: https://github.com/getsentry/sentry-unity/pull/683/files#r886622626

The linked PR in the Unity repo copy&pastes the creation of `EnumerateChainedExceptions` from the MainExceptionProcessor. 

### Solution Brainstorm

It would be great if that functionality were to be refactored so it's usable outside of the MainExceptionProcessor.

**Comment by SimonCropp** [comment]
@bitsandfoxes  should unit respect [KeepAggregateException](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/SentryOptions.cs#L607)

**Comment by SimonCropp** [comment]
fixed by https://github.com/getsentry/sentry-dotnet/pull/1733
