### ISSUE TITLE
asp.net core file upload - Sentry rejected the event. Status code: RequestEntityTooLarge. 

### ISSUE THREAD

**Issue by alesdvorakcz** [getsentry/sentry-dotnet#170]
I use asp.net core with .UseSentry() integration. it works very well.
But now my app crashed during file upload and sentry rejected the event with Status code: RequestEntityTooLarge. I find out that it sends entire POST body of the request. But it can be large file.

Is there any way how to detect if request body is too large to send and log the event without it?

**Comment by bruno-garcia** [comment]
@alesdvorakcz Currently the only solution is for you to add a `BeforeSend` callback and truncate or reject the payload. 

**Something like this**:

```csharp
SentrySdk.Init(o => o.BeforeSend = e => 
{
    if (e.Request.Data != null)
    {
         if (e.Request.Data is string strData && strData.Length > 1000) {
            e.Request.Data = e.Request.Data.Substring(0, 1000);
            // Or simply delete all the data:
            e.Request.Data = null; 
         }
         else if (e.Request.Data is YouObject o)
            e.Request.Data = // make sure your object when serialized won't be too large
    }
    return e;
}
```

We'll be adding support[ as per the _Unified SDK_, so you can choose the size etc.](https://docs.sentry.io/error-reporting/configuration/?platform=csharp#request-bodies)

**Comment by alesdvorakcz** [comment]
Ok thank you for this workaround

**Comment by bruno-garcia** [comment]
We'll be merging soon: https://github.com/getsentry/sentry-dotnet/pull/174/files

**Comment by bruno-garcia** [comment]
We've released a fix for this.
Could you please give it a shot and some feedback?

https://github.com/getsentry/sentry-dotnet/releases/tag/1.1.3-beta2
Feel free to reopen
