### ISSUE TITLE
DiagnosticSource can easily be added twice

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1707]
### Package

Sentry.DiagnosticSource

### .NET Flavor

.NET

### .NET Version

all

### OS

Other

### SDK Version

all

### Steps to Reproduce

Install Sentry.AspNet

Call AddAspNet and AddDiagnosticSourceIntegration

### Expected Result

Only add it once. 

### Actual Result

The integration is added twice.

https://github.com/getsentry/sentry-dotnet/blob/89cad6dd25fd9cb0df4051c7414fba8263b4f1ac/src/Sentry.DiagnosticSource/SentryOptionsDiagnosticExtensions.cs#L18

**Comment by SimonCropp** [comment]
should we throw or ignore?

**Comment by bruno-garcia** [comment]
Let's just ignore the second add.

**Comment by bruno-garcia** [comment]
For the record, we discuss whether we should disallow dupe integration altogether or just special case for this:

> Don't know of a use case where one would like to add the same integration twice. But in theory there could be. An integration that takes something as a parameter LogFileWatcherIntegration("path..") could take two instances of it. With different paths.
