### ISSUE TITLE
Android workload dependency broke Unity build

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#1759]
### Package

Sentry

### .NET Flavor

.NET Framework

### .NET Version

6.0.301

### OS

Any (not platform specific)

### SDK Version

3.19.0

### Steps to Reproduce

See the errors in Unity CI

https://github.com/getsentry/sentry-unity/runs/7105003576?check_suite_focus=true

```
/usr/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: android [/sentry-unity/src/sentry-dotnet/src/Sentry/Sentry.csproj]
/usr/share/dotnet/sdk/6.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [/sentry-unity/src/sentry-dotnet/src/Sentry/Sentry.csproj]
    0 Warning(s)
    1 Error(s)
```

### Expected Result

I'd expect builds to not break, this being a minor version increase.

### Actual Result

.

**Comment by bruno-garcia** [comment]
@vaind can we just add the workload to CI? It takes just a few seconds to install. 
The other route is to have a property that defines we're building or unity and try to reset the targets but I'd avoid that if we can

**Comment by vaind** [comment]
As long as we're sure this only breaks if building as a submodule, i.e. not for other consumers, then sure we can do that.

**Comment by bruno-garcia** [comment]
Yeah this only breaks building the Sentry project. The nuget package has targets available and are used as needed by the final app

**Comment by vaind** [comment]
these changes were needed in sentry-unity: https://github.com/getsentry/sentry-unity/pull/860/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f

feel free to close this issue if you're fine with that

**Comment by mattjohnsonpint** [comment]
Just FYI, the android target was added in the previous release 3.18.0.  Not sure why you didn't encounter it then.  The changes look fine to me though.

That said, it still might be worth considering changing the build to reduce to the targets Unity needs, to speed up build time.

**Comment by SimonCropp** [comment]
plan is to attempt to check if "is unity" in msbuild and  not include the android bits.
