### ISSUE TITLE
Exception is only caught when debugger is attached

### ISSUE THREAD

**Issue by belidzs** [getsentry/sentry-dotnet#176]
I'm currently migrating an app from `RavenSharp` to `sentry-dotnet`, but I'm having some difficulties.

It seems that whenever I run the app in the IDE with the debugger attached, Sentry is working well, it's catching exceptions and reports them as it should.

However, when the debugger is not attached (e.g. the app is started with `CTRL+F5` or outside the IDE) the exception is not handled anymore and it is thrown. It doesn't matter if the build config is set to Release or Debug.

This only happens if the exception happens on a `Form`. If the exception happens before `Application.Run()`, it works as it should.

I have attached a sample project to demonstrate this problem: [WindowsFormsApp1.zip](https://github.com/getsentry/sentry-dotnet/files/2997098/WindowsFormsApp1.zip)

To reproduce:
1. Open the project
1. Restore Nuget packages
1. Set DSN (optional)
1. Run with `F5` using the debugger attached -> works
1. Run with `CTRL+F5` -> the exception is uncaught

**Comment by belidzs** [comment]
Okay so it seems that a .NET application will only route unhandled exceptions to `AppDomain.CurrentDomain.UnhandledException` when it's not thrown from a UI thread which explains why exceptions from `Program.cs` were caught while others didn't. 

Exceptions coming from the UI will end up in `Application.ThreadException` which is not automatically handled by `sentry-dotnet`. Since I really think it should I'm leaving this ticket open.

As a workaround, it is possible to reroute all exceptions to `AppDomain.CurrentDomain.UnhandledException` so it is handled by Sentry without the debugger attached to it by issuing the following command before the first UI element is created:

```csharp
Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);
```

### Sources
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.setunhandledexceptionmode?redirectedfrom=MSDN&view=netframework-4.7.2#overloads

https://stackoverflow.com/questions/2014562/whats-the-difference-between-application-threadexception-and-appdomain-currentd

**Comment by bruno-garcia** [comment]
I wouldn't say this is a bug since the SDK is not tied up to a specific framework like Windows Forms.
We could `#ifdef` .NET Framework target since now we multi target `net461` and `netstandard2` and add this as an integration. 
Other integrations we consider are `UnobservedTaskException` for example.

**Comment by belidzs** [comment]
Right, either sentry-dotnet should offer integration with all three unhandled exception event types or the documentation should warn that WinForms apps need some additional configuration.

It was really just pure luck that I ran the application without the debugger attached but with an exception  intentionally thrown so I could realize that something was wrong. Otherwise I would've thought that everything was all right since the exceptions were caught and they were showing up on the website.

Maybe it's just me but I think an average developer normally tests a new Sentry integration only inside the IDE which automatically redirects `Application.ThreadException` to `AppDomain.CurrentDomain.UnhandledException`, so this behavior stays hidden until the application is deployed.

**Comment by fl4p** [comment]
I ran into the same situation and discovered it by luck.

Its dotnet to blame for this, the default behavior should be to throw exceptions in the main thread instead of popping up a runtime error message box. The `UnhandledExceptionMode` being `Automatic` as default is a design mistake.

You're right, the should be a big warning about this in the integration docs.

**Comment by bruno-garcia** [comment]
@fl4p @belidzs So basically the feature request is to subscribe to `Application.ThreadException` as we do from `AppDomain.UnhandledException`, capture it and rethrow?

**Comment by belidzs** [comment]
@bruno-garcia not really as it seems a bit messy and I agree with @fl4p that this is more of a dotnet issue.

Probably a better way to go is to just update the documentation and the usage section of [README.md](https://github.com/getsentry/sentry-dotnet/blob/master/README.md) so other users will know that the following line is needed for WinForms app if they want all exceptions to be handled by Sentry:

```csharp
Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);
```

**Comment by bruno-garcia** [comment]
This has been documented here: https://docs.sentry.io/platforms/dotnet/winforms/

We could register a hook there and once capturing the exception, forward to the original handler (which shows the dialog). PR's welcomed if someone would like to help

**Comment by absid89** [comment]
this not work on .net framework 4.8? i set "Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException) " before create any window, but after getting unhandled exception app is closing and not sended report to sentry

this works fine on only in IDE, in debug mode

**Comment by bruno-garcia** [comment]
> this not work on .net framework 4.8? i set "Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException) " before create any window, but after getting unhandled exception app is closing and not sended report to sentry
> 
> 
> 
> this works fine on only in IDE, in debug mode

It should work. Could you please raise an issue and fill out the issue template? It'll ask for the version of Sentry SDK etc. A repro would help us debug.

**Comment by absid89** [comment]
> > this not work on .net framework 4.8? i set "Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException) " before create any window, but after getting unhandled exception app is closing and not sended report to sentry
> > this works fine on only in IDE, in debug mode
> 
> It should work. Could you please raise an issue and fill out the issue template? It'll ask for the version of Sentry SDK etc. A repro would help us debug.

with this code, working only in IDE

```
            Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException)

            Dim options = New SentryOptions()
            With options

                .Dsn = New Dsn("key")

                .RequestBodyCompressionBuffered = true
                .RequestBodyCompressionLevel = CompressionLevel.Fastest

                .SendDefaultPii = True
                .AttachStacktrace = True
                .ReportAssemblies = True
                .Release = $"{Application.ProductName}@{Application.ProductVersion}"
                .Environment = "Production"

            End With

            SentrySdk.Init(options)
```

**Comment by bruno-garcia** [comment]
From reading that code nothing I can't spot a reason why it wouldn't work outside of the IDE.

> It should work. Could you please raise an issue and fill out the issue template? It'll ask for the version of Sentry SDK etc. A repro would help us debug.

**Comment by absid89** [comment]
[WindowsApp4.zip](https://github.com/getsentry/sentry-dotnet/files/6121090/WindowsApp4.zip)


> From reading that code nothing I can't spot a reason why it wouldn't work outside of the IDE.

**Comment by bruno-garcia** [comment]
> > From reading that code nothing I can't spot a reason why it wouldn't work outside of the IDE.
> 
> [WindowsApp4.zip](https://github.com/getsentry/sentry-dotnet/files/6129793/WindowsApp4.zip)

I've added my DSN, build the `sln`, ran the app and got events in Sentry.

**Comment by bruno-garcia** [comment]
Since this is documented behavior: https://docs.sentry.io/platforms/dotnet/guides/winforms/

We'll consider adding something out of the box with #512
