### ISSUE TITLE
Implement a subscribable event which runs after the event has been sent to the server

### ISSUE THREAD

**Issue by belidzs** [getsentry/sentry-dotnet#177]
It would be nice if there was an event which would run after the event was successfully sent to the server.

Currently I'm trying to manually subscribe to unhandled application exceptions and kill the app after they were sent due to #176. Killing the app can't happen right after `CaptureException()` due to its asynchronous nature.

**Comment by bruno-garcia** [comment]
@belidzs The Sentry .NET SDK doesn't suppress any exception. If an exception goes unhandled by the application code and the `AppDomain.UnhandledException` event fires the SDK does capture it but it rethrows it after. So the app would terminate anyway in this case.
The SDK does flush it's queue before rethrowing the event, so the event is properly sent to Sentry.

https://github.com/getsentry/sentry-dotnet/blob/582d088f10fb1b38d67d3489dcc90799f3741a22/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L36-L39

**Comment by belidzs** [comment]
Thanks for the explanation @bruno-garcia! 

What I was originally trying to achieve didn't make use of `AppDomainUnhandledExceptionIntegration` since I wasn't aware that uncaught exceptions from GUI threads are not collected by sentry by default.

My *(quite ugly)* attempt to work around this was to subscribe to `Application.ThreadException` with a method which posts the exception to sentry using `SentrySdk.CaptureException()` and then kills the app. Because of the way .NET works instead of killing the failing app, JIT is invoked on unhandled `ThreadException` events and it pops up a window which gives the user an opportunity to continue. This is what I wanted to avoid by killing the app instead.

Anyway, obviously I don't need sentry to support this use case anymore since I can just ask .NET to redirect all exceptions to `AppDomain.CurrentDomain.UnhandledException` as described in #176 but this event still would be useful for example to reassure the user after an unhandled exception that the problem has been successfully reported. Currently, I can only do this *before* sending out a report and there's no guarantee it actually will be sent.

**Comment by bruno-garcia** [comment]
Since then there has been more docs on it and we plan to ship a package for WinForms #512 

Please refer to the WinForms docs: https://docs.sentry.io/platforms/dotnet/guides/winforms/
