### ISSUE TITLE
Replace "Unknown Route" with the raw URL and a transaction annotation

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1786]
### Problem Statement

The spec now allows to send raw URLs when they are annotated so the server can take that into account:

https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations

### Solution Brainstorm

We can rely on that and replace the current "Unknown Route" sent by the ASP.NET Core integration which isn't very helpful.

This is a change worthy of landing on the next major. Since a lot of new transactions will show up in Sentry. Today they'd be grouped under one things and going forward they'd rely on Sentry's ability to group them well (even though it'll be based on heuristics)

**Comment by mattjohnsonpint** [comment]
So, we should send only `route` when we have it, but otherwise send `url` and don't send "unknown route" ever.

**Comment by mattjohnsonpint** [comment]
I think we can do this without waiting for 4.x, but we should note the behavior change in the changelog.

**Comment by mattjohnsonpint** [comment]
Note, this change will be visible to almost everyone that uses `.UseSentryTracing()` in ASP.Net Core  for performance monitoring, as it will stop grouping 404s together.

**Comment by SimonCropp** [comment]
@bruno-garcia any thoughts on the comment from @mattjohnsonpint ?
