### ISSUE TITLE
Ability to set SampleRate to 0 

### ISSUE THREAD

**Issue by crayne02** [getsentry/sentry-dotnet#1789]
### Problem Statement

We have a use case where we want to turn off SampleRate in order to not receive error events from some of our lower environments as this is causing noise etc. 

The Docs states to "configures the sample rate for error events, in the range of 0.0 to 1.0 " however we are unable to set as 0.0 as SampleRate expects "values between 0.01 (inclusive) and 1.0 (exclusive)" and sates "use null to disable"

https://github.com/getsentry/sentry-dotnet/blob/e62781ca688b9ebadf41434f90b3382262d14c91/src/Sentry/SentryOptions.cs#L144-L171 

The application is .NET running SDK version 3.19.0

We have set the Sentry options as below 

`{
  "Sentry": {
    "Dsn": "https://xxxxxxx",
    "MaxRequestBodySize": "Always",
    "SendDefaultPii": false,
    "MinimumBreadcrumbLevel": "Debug",
    "MinimumEventLevel": "Error",
    "AttachStackTrace": true,
    "DiagnosticsLevel": "Error",
    "Debug": true,
    "TracesSampleRate": 0,
    "SampleRate": null
  },`

With the above configuration we are still getting errors reported to Sentry.  Is this the correct implementation? The expectation was that this wouldn't send error events.

**Comment by mattjohnsonpint** [comment]
The docs could be a bit clearer here but `null` disables *sampling*, not the sending of events.  

If you don't want to send data to sentry for a particular environment, then avoid initializing the SDK in that environment.

**Comment by mattjohnsonpint** [comment]
If you're using asp.net core, you can use [per-environment config](https://docs.microsoft.com/aspnet/core/fundamentals/environments).

In the config, if you don't have a Sentry DSN specified, then `UseSentry` will do nothing.

Another approach would be to let sentry run in all environments, and just filter it within the Sentry UI.   Sentry can actually be really helpful in dev/test, as you can often better control what you want to break.
