### ISSUE TITLE
Document `MaxRequestBodySize`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#179]
1.1.3-beta2 added support to `MaxRequestBodySize` on ASP.NET Classic and ASP.NET Core.
Once 1.1.3 is out, add docs to `docs.sentry.io`

**Comment by lucas-zimerman** [comment]
https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/configuration/options/#max-request-body-size

https://docs.sentry.io/platforms/dotnet/guides/aspnet/configuration/options/#max-request-body-size

Already implemented on both ASP.NET + Core docs.
