### ISSUE TITLE
Add support for F#, update docs with F# references

### ISSUE THREAD

**Issue by delneg** [getsentry/sentry-dotnet#180]
Dotnet isn't just C#, it's functional too.
Please add examples and/or docs for F# usage

**Comment by bruno-garcia** [comment]
@delneg Agreed it would be great to have F# samples!
The only reason we don't yet, is that we haven't had the time to prioritize this work yet.

Please mind [Sentry is open source](https://sentry.io/_/open-source/) which include [our docs](https://github.com/getsentry/sentry-docs). 

With regards to samples in F# it would be great to have them in the the [samples repo](https://github.com/getsentry/sentry-dotnet-samples).

We'd love some help with this.

**Comment by Tyrrrz** [comment]
Hi @delneg!
We'll be adding F# samples and onboarding docs soon. This will include the base integration.
Is there anything specific you may want to see there as well? What frameworks are you using Sentry with in F#?

**Comment by delneg** [comment]
Hello!
Thanks for your response.
I'd love to see Giraffe and/or Saturn examples as well as (depending on your current status of Xamarin support) Fabulous Xamarin Forms.
Would be great to maybe have some Fable samples for the Javascript client-side Sentry usage as well if it's possible
I've been using Sentry for a while now and would love to start using it for F# projects as well

**Comment by Tyrrrz** [comment]
Some F# samples:

Console: https://github.com/sentry-demos/fsharp

Giraffe: https://github.com/sentry-demos/giraffe
