### ISSUE TITLE
Unable to send events since 3.20.0 - Invalid envelope header, duplicate field `sent_at`

### ISSUE THREAD

**Issue by JadeBanks** [getsentry/sentry-dotnet#1817]
### Package

Sentry

### .NET Flavor

Xamarin

### .NET Version

Xamarin.Android SDK 12.3.3.3

### OS

Android

### SDK Version

3.20.0

### Steps to Reproduce

This works with 3.19.0 but no longer in 3.20.0.

Problem occurs on both Android and iOS. I haven't tested on any other platforms.

Init and send events as described in the Sentry docs.

### Expected Result

Expect to see events on the Sentry website

### Actual Result

```
  Error: Sentry rejected the envelope . Status code: BadRequest. Error detail: invalid event envelope. Error causes: invalid envelope header, duplicate field `sent_at` at line 1 column 110.
  Debug: Failed envelope '' has payload: {"sdk":{"name":"sentry.dotnet","version":"3.20.0"},"sent_at":"2022-07-26T16:19:43.929796\u002B00:00","sent_at":"2022-07-26T16:19:59.401494+00:00"} {"type":"client_report","length":308} {"timestamp":"2022-07-26T16:19:43.925254+00:00","discarded_events":[{"reason":"before_send","category":"error","quantity":1},{"reason":"network_error","category":"default","quantity":13},{"reason":"network_error","category":"error","quantity":1},{"reason":"network_error","category":"session","quantity":9}]
```

This #1690 PR seems to be the likely cause.

**Comment by mattjohnsonpint** [comment]
Thanks.  I was just debugging another issue and found the same thing.  Fix coming asap, with a 3.20.1 release.

**Comment by mattjohnsonpint** [comment]
FYI - it only occurs if you have set a cache directory path in the options, or are using an SDK integration that sets one by default.

**Comment by mattjohnsonpint** [comment]
Version 3.20.1 has been released with a fix for this bug.  Please update.

Thanks.

**Comment by JadeBanks** [comment]
Hi Matt, thanks for such a quick response. 3.20.1 is working for me 😄
