### ISSUE TITLE
Does Sentry .NET supports offline mode?

### ISSUE THREAD

**Issue by yoobato** [getsentry/sentry-dotnet#182]
Hello, I'm using Sentry in my .NET application.

I added SentrySdk.CaptureMessage() when the application's internet connection is lost.
What I expected was Sentry to report errors when the internet connection is regained.

However, it seems like to not sending the errors when the application goes offline and back to online. Even though, I think Sentry does not record or save event occurred in offline. I think Sentry SDK tries to send error to Sentry server (it may get a connection lost error), but when it fails then do nothing.

I know that `Sentry for Android` supports offline mode. Does Sentry for .NET does not support offline mode?

**Comment by HazAT** [comment]
So we do not yet support offline caching but this is something we will implement at one point see https://github.com/getsentry/sentry-dotnet/issues/80

In regards tooffline `capture` calls, if it's really the case that new `captureX` calls only work after restarting that app instead of also working after regaining an internet connection, this is a bug we will fix.

Can you please double check if I got this right?!

**Comment by yoobato** [comment]
@HazAT 

When my application's internet connection got lost,

1) Restart the application immediately
- Successfully sending the report

2) Restart the application after long time ago
- Does not send the report

So I think that if I call captureException, then it'll try to send the report to Sentry server, right?
However, if timeout occurs(maybe due to network issue), then it doesn't caching for resend.
If, I turned off before timeout (so the API request will be cancelled), and restart the application, then it successfully reports.

---

BTW, is there any callback if Sentry reports succeed or failed? If there exists, then I can do my own queueing for Sentry reports when the application is offline.

**Comment by HazAT** [comment]
So we do not provide a way to await sending events since we consider it a fire and forget thing, we will investigate what's going on here.

**Comment by bruno-garcia** [comment]
@yoobato We need to add support to offline mode (caching the event when no Internet connection to send it once the app is back online).

Closing as a dupe #80
