### ISSUE TITLE
Dynamic Sampling support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1840]
### Problem Statement

Similar to the Java issue: https://github.com/getsentry/sentry-java/issues/2205

https://develop.sentry.dev/sdk/performance/dynamic-sampling-context/

### Solution Brainstorm

* Add support for baggage propagation for HTTP libraries (HttpMessageHandler).
* Read incoming baggage from requests in ASP.NET and ASP.NET Core
* Make sure envelopes sent to Sentry include the trace context info needed for DS.

**Comment by bruno-garcia** [comment]
A few notes:

* There's no need to implement any of the `freeze` specs that came up earlier. That was trying to solve problems in JS where the transaction name changes in the middle of the transaction and result in transactions downstream containing different transactions name.
* Need to add `tracePropagationTargets` to control what endpoints we should send the trace context

The spec should be up-to-date with all changes

**Comment by mattjohnsonpint** [comment]
Just FYI for anyone who may have been following Sentry's product announcements about dynamic sampling - yes, we are working on adding it to the .NET SDK.  It should be available in the next release.  You can watch this issue for updates.  Thanks for your patience! 😃

**Comment by mattjohnsonpint** [comment]
This will be included in the 3.22.0 release (coming soon).
