### ISSUE TITLE
.NET MAUI Support (GA)

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1850]
This is a subset of the issue tracking the complete MAUI support (#1174)  and builds upon the work completed for Preview 1 (#1651), Preview 2 (#1729), and Preview 3 (#1769)

Here is the next set of work planned before we remove the "preview" tag from the `Sentry.Maui` package.

- <s>[ ] Finish connecting `BeforeSend` and `OnCrashedLastRun` to the Cocoa SDK</s>.
  - Deferred. Tracking as a future enhancement in #2102
- [x] Upload native symbols for Android and iOS (on Release builds) via Sentry CLI during build
  - Completed in #2107
- [x] Device tests using simulators/emulators
- [x] Fix any reported bugs related to MAUI or the iOS/Android targets of the main Sentry SDK

At this time, a "Preview 4" is not planned, but we reserve the right to change our minds depending on how things go.

**Comment by bruno-garcia** [comment]
For running sentry-cli we need 3 values. It's possible to load automatically through the wizard endpoint: https://github.com/getsentry/team-mobile/issues/26

**Comment by mattjohnsonpint** [comment]
> For running sentry-cli we need 3 values. It's possible to load automatically through the wizard endpoint: [getsentry/team-mobile#26](https://github.com/getsentry/team-mobile/issues/26)

Tracking that separately in #2116.

For now, the user can either configure via environment variables or config file (per [docs](https://docs.sentry.io/product/cli/configuration/)), or they can set properties in their csproj (`SentryOrg`, `SentryProject`, etc. - see [here](https://github.com/getsentry/sentry-dotnet/blob/6b17e2cd3ef6143d7e74d25211657bc879b69c83/src/Sentry/buildTransitive/Sentry.props#L49-L53)).
