### ISSUE TITLE
Does Sentry .NET supports .NET obfuscators ? 

### ISSUE THREAD

**Issue by Green7** [getsentry/sentry-dotnet#186]
Our net code is obfuscated. It is possible to upload obfuscator map file to sentry and deobfuscate  stack traces ?

**Comment by bruno-garcia** [comment]
@Green7 At the moment Sentry doesn't support any .NET obfuscator but that's something we could possibly add to [symbolic](https://github.com/getsentry/symbolic).

Could you describe more the scenario? What obfuscator do you use and what mapping format does it output?
What use-cases are there? These are desktop apps only? WPF or WinForms or would this work with UWP? Does it work with Portable PDB or Windows PDBs?

**Comment by Green7** [comment]
We using Crypto Obfuscator For .Net (https://www.ssware.com) 
This obfuscator supports many types of project but I'm not sure if it supports  UWP and NetCore (probably not). We using it only dlls and WinForms applications.
Obfuscator creates its own .map file, it is a simple XML file with different entries like this:

`<Entry OldName="TestApp.Forms.MainForm.Field" NewName="NameAfterRename">`  
`<File OldName="MainForm.cs" NewName="NewFileName" />

I think that the analysis of these two types of entries should be enough to get the file name and line number of the exception.

Here is example. Part of original stack trace:
> at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
>at at System.Int32.Parse(String s)
>at ObfuscatorTest.MainForm.buttonException_Click(Object sender, EventArgs e) in P:\Tmp\_CSharp_\ObfuscatorTest\MainForm.cs:line 22

This same part after obfuscation:
>at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
>at System.Int32.Parse(String s)
>at A.c0c14cff4ff8c95467fb4b40c83b22b7e.c84694f6f423b163152387802e9d63e34(String c8f88c860d974470b592f5fb4f68ab38b)
> at A.c2af3bbb17a25555feec7059af010e514.c78d291e7ac31c9cba308c21da1934c01(Object cec11e26ddd9c8d7680dcaab78eb85f30, EventArgs c33a006dd1a2b0fb0addfab059628f528) in File0:line 22

and fragments of .map file:

`<Entry OldName="Proxy_System.Int32.Parse(String )" NewName="A.c0c14cff4ff8c95467fb4b40c83b22b7e.c84694f6f423b163152387802e9d63e34(String c8f88c860d974470b592f5fb4f68ab38b)" />`

`<Entry OldName="ObfuscatorTest.MainForm.buttonException_Click(Object sender, EventArgs e)" NewName="A.c2af3bbb17a25555feec7059af010e514.c78d291e7ac31c9cba308c21da1934c01(Object cec11e26ddd9c8d7680dcaab78eb85f30, EventArgs c33a006dd1a2b0fb0addfab059628f528)" />`

`<File OldName="P:\Tmp\_CSharp_\ObfuscatorTest\MainForm.cs" NewName="File0" />`

If you like, I can send a full sample project.

**Comment by SimonCropp** [comment]
@Green7 no sentry does no support de-obfuscation. The complexity in implementing this is that each obfuscator has their own custom de-obfuscator, with their own stack of dependencies. it would be extremely difficult for sentry to add support for these.

The current recommendation is to rout exceptions through your own webserivce proxy. in that proxy you can de-obfuscate and upload to sentry. this approach is suggested here https://forum.sentry.io/t/custom-deobfuscation/3160

Another option is to disable method name obfuscation. Many obfuscation tool support this. It means the code inside methods is obfuscated, by the method names are not. The resulting stack trace is then more readable
