### ISSUE TITLE
Blazor Wasm global scope

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1871]
### Problem Statement

Global scope: https://github.com/getsentry/sentry-dotnet/blob/66ddcd819b823af88c66e62690a1fd9ee8bc2c83/src/Sentry/SentryOptions.cs#L59

by default relies on AsyncLocal. This is optimal for web servers, where we `PushScope` at the start of web requests to have isolation for Logs, HTTP data, etc.

This is an issue on Client apps such as Mobile and Desktop. It turns out on Blazor WASM it's the same issue. Users set scope such as User when retriving a user from the backend, and expect any subsequent event will include that data.

### Solution Brainstorm

Possibly enable global mode for Blazor WASM out of the box.

Come [from Zendesk](https://sentry.zendesk.com/agent/tickets/69979)

**Comment by mattjohnsonpint** [comment]
Looks like we should just detect running in a browser at runtime and set global mode true for that.
