### ISSUE TITLE
Null Exception on AddAspNet

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#1875]
### Package

Sentry.AspNet

### .NET Flavor

.NET

### .NET Version

4.7

### OS

Windows

### SDK Version

3.20.1

### Steps to Reproduce

I was trying to figure out how to support Transactions for a OWIN application but it seems like when adding the `AddAspNet` to the code it throws a nullexception error.
The only plausible cause is the HttpContext being null here: https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.AspNet/Internal/SystemWebVersionLocator.cs#L20

### Expected Result

AddAspNet to not throw a null Exception

### Actual Result

![image](https://user-images.githubusercontent.com/8229322/186931524-414aa4e8-0436-4c16-bbe9-dd9bd3140315.png)
There are no line numbers :\
```
   at Sentry.AspNet.Internal.SystemWebVersionLocator.Resolve(HttpContext context)
   at Sentry.AspNet.SentryAspNetOptionsExtensions.AddAspNet(SentryOptions options, RequestSize maxRequestBodySize)
```

**Comment by SimonCropp** [comment]
can u share a repro?

**Comment by SimonCropp** [comment]
@lucas-zimerman or can you re-run with break on all exception enabled to see what line it occurred on

**Comment by SimonCropp** [comment]
looking at the code in question

```
    internal static string? Resolve(HttpContext context)
    {
        if (context.ApplicationInstance?.GetType() is { } type)
        {
            // Usually the type is ASP.global_asax and the BaseType is the Web Application.
            while (type is { Namespace: "ASP" })
            {
                type = type.BaseType;
            }

            if (type?.Assembly is { } assembly)
            {
                return ApplicationVersionLocator.GetCurrent(assembly);
            }
        }

        return null;
    }
```

the only way i can see a null ref is if HttpContext is null. googling around there seems to be many scenario where HttpContext.Current can be null. given `SystemWebVersionLocator.Resolve` seems to be "best effort" at finding version. do we add a null check and return null?

**Comment by mattjohnsonpint** [comment]
@lucas-zimerman - Once this gets released (or if you want to do a custom build now), please let us know if Simon's change in #1881 solved the issue.  I'll leave this open until you can check.  Thanks.

**Comment by lucas-zimerman** [comment]
Sure I'll validate it.

**Comment by lucas-zimerman** [comment]
Closing as fixed, thanks for the fix :D
