### ISSUE TITLE
Improve network status listeners

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1882]
## Problem Statement

We already have the [`INetworkStatusListener`](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Extensibility/INetworkStatusListener.cs) interface, and [`SentryOptions.NetworkStatusListener`](https://github.com/getsentry/sentry-dotnet/blob/6cdca908b20e4021fe61b9e93eea1bf11ace572a/src/Sentry/SentryOptions.cs#L662-L672) which is used in the caching transport to avoid trying to send events when we know we're offline.

https://github.com/getsentry/sentry-dotnet/blob/56477c7250a3e8f2e1ca9ec25891dc8628d40ecc/src/Sentry/Internal/Http/CachingTransport.cs#L278-L283

Initially, the only implementation was [`MauiNetworkStatusListener`](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry.Maui/Internal/MauiNetworkStatusListener.cs).

We now also have a `PollingNetworkStatusListener` that we can use in non-MAUI applications. See:
    -  https://github.com/getsentry/sentry-dotnet/pull/3438)

Without caching enabled however, we discard the event completely.  Ideally we could do something a bit better, even when caching was disabled.

## Solution Brainstorm

- The network connectivity check could be done earlier (perhaps in `HttpTransportBase`, or perhaps in `BackgroundWorker`, or both) and events could queue until network status is restored, rather than being sent and lost (when not caching).

## References

These are less relevant now that we have a couple of different implementations of `INetworkStatusListener`, but for posterity:

### Windows APIs

Some discussion here (for Windows):
- https://stackoverflow.com/a/60585095/634824
- https://stackoverflow.com/questions/2031824/what-is-the-best-way-to-check-for-internet-connectivity-using-net
- https://stackoverflow.com/questions/5405895/how-to-check-the-internet-connection-with-net-c-and-wpf

Ideally we could avoid a Windows specific solution though and use a reliable generic approach.

### Network change events

There are also some basic network connectivity events built-in to .NET:
https://docs.microsoft.com/en-us/dotnet/fundamentals/networking/network-info#network-change-events

When using the `PollingNetworkStatusListener`, these could potentially provide an additional trigger to check the network, so we can more quickly detect when the network becomes available again. 

This might be valuable if the queue was being filled in under 32 seconds (as we'd end up dropping less events).

**Comment by jamescrosswell** [comment]
Given the reduced scope of this now #3438 has been merged, @bitsandfoxes and I discussed and decided to close this issue.

If people want reliable transmission on unreliable networks, the obvious solution is to use our caching transport. The alternative is essentially some form of MemoryCache and Disk is cheaper than Memory.
