### ISSUE TITLE
Focus Event stops working when Sentry.Maui is installed

### ISSUE THREAD

**Issue by Higor13** [getsentry/sentry-dotnet#1886]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

6.0.400

### OS

Windows

### SDK Version

3.20.1

### Steps to Reproduce

1. Create a Maui project;
2. Add Sentry.Maui package;
3. Add at least two entries and one button;
4. Give the entries x:Names like entry1 and entry2;
5. On the button clicked method try this: entry2.Focus();
6. Unistall Sentry.Maui package and try again and will work;

### Expected Result

The focus should goes to entry2.

`    {
        entry2.Text = "something";
        entry2.Focus(); 
    }`

### Actual Result

Nothing happens, no erros on output. The entry2.Focus(); it's just ignored. Nothing happens. If you add another event like entry2.Text = "something"; it works but the Focus is ignored.

**Comment by mattjohnsonpint** [comment]
Thanks for reporting.  I'll investigate this right away.

**Comment by mattjohnsonpint** [comment]
I have found and fixed the problem.  See the PR for details.  

It will be in the next release.  Thanks again!
