### ISSUE TITLE
Add extensions for IHostBuilder

### ISSUE THREAD

**Issue by LordMike** [getsentry/sentry-dotnet#190]
The current implementation for MS's DI is for `IWebHostBuilder`, but given the new Generic Hosts, I think more and more will use the `IHostBuilder` builder.

Please add a `.UseSentry()` for `IHostBuilder`. :)

**Comment by bruno-garcia** [comment]
True this is pending. Would be great to get some help on this.

**Comment by xt0rted** [comment]
I'm migrating a console app over to the new generic host and in order to use `appsettings.json` for my config with the `ILoggingBuilder.AddSentry()` method I needed to adjust my setup like so:

```diff
 var builder = Host.CreateDefaultBuilder()
     .ConfigureLogging((ctx, loggingBuilder) =>
     {
+        loggingBuilder.Services.Configure<SentryLoggingOptions>(ctx.Configuration.GetSection("Sentry"));
         loggingBuilder.AddSentry();
     })
```

To make this more reusable I've added a helper function:

```csharp
public static class SentryHostBuilderExtensions
{
    public static IHostBuilder UseSentry(this IHostBuilder builder) =>
        builder.ConfigureLogging((ctx, logging) =>
        {
            logging.Services.Configure<SentryLoggingOptions>(ctx.Configuration.GetSection("Sentry"));

            logging.AddSentry();
        });
}
```

And then I use it just like the asp.net core integration:

```csharp
var builder = Host.CreateDefaultBuilder()
    .UseSentry()
    .ConfigureServices((ctx, services) => { ... });
```

**Comment by bruno-garcia** [comment]
This looks straightforward @xt0rted thanks.
Isn't there any other hooks we can add via `IHostBuilder`? With `IWebHostBuilder` we have the middleware pipeline so that's an obvious place we add code to. But I'm unaware of `IHostBuilder`.

Is there a way to capture exceptions of `BackgroundService`s or whatever else is usually setup?

**Comment by xt0rted** [comment]
@bruno-garcia I'm not seeing any graceful exception handling for these (here's the [Host](https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/Internal/Host.cs) code). In the `StopAsync()` method it does throw an aggregate exception if anything was thrown inside of the `IHostedService`s, but that  just throws, it doesn't even call `logger.LogError(ex)` 😞 

Here's a question about this and the feature has been moved to the backlog https://github.com/aspnet/Extensions/issues/813.

**Comment by bruno-garcia** [comment]
I just tried the template for ASP.NET Core 3.0 on preview 9 which is supposed to be the last one (3.0 will be released in a week) and it looks like this:

```

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

So until we support Generic host, please just add:
```
weBuilder.UseSentry();
```
and it should all work fine.

**Comment by Kampfmoehre** [comment]
Is there a way to configure Sentry release for the .NET core worker template? I generated a new project with .NET core 3.1 with `dotnet new worker` and this is how CreateHostBuilder looks like:
```csharp
    public static IHostBuilder CreateHostBuilder(string[] args) =>
      Host.CreateDefaultBuilder(args)
        .ConfigureServices((hostContext, services) =>
        {
          services.AddHostedService<Worker>();
        });
```

With the solution from @xt0rted I can add Sentry in general but I am unable to configure it. I would like to set the Release property for example.

**Comment by bruno-garcia** [comment]
@Kampfmoehre do you tag your assemblies? Like `AssemblyInformationalVersion` or `AssemblyVersion`? The SDK picks those up automatically.

**Comment by Kampfmoehre** [comment]
I don't want to go too much off topic here, but here is alittle background:
We use Semantic Release (NodeJS) with a self written plugin (that just uses the Semantic Release CLI) that creates releases. During Semantic Release the Version property in Directory.build.props is set to the version Semantic Release offers. During deploy we use the Sentry CLI to notify Sentry about the deployment.
When I set all those up I stumbled upon a few problems and ended up, using a project-key in combination with the version number to distinguish more between versions. Maybe this is not necessary but at least the examples in the [docs](https://docs.sentry.io/workflow/releases/?platform=csharp) use that too.
Would that name be picked up from the Assembly name?

**Comment by bruno-garcia** [comment]
The snippet you added to the comment you edited is not needed because the SDK (code I pasted) does exactly the same.

It looks for `SENTRY_RELEASE` env var, it not set it read values from `AssemblyInformationalVersionAttribute` which can have a string (useful for adding a git commit hash which btw is automatically [patched by sourcelink](https://github.com/dotnet/sourcelink) ) and if that was also not defined, uses the standard `AssemblyInfo` which is the format `0.0.0.0`.

You can control these via `Directory.Build.props` so sounds like it's what you are doing.

**Comment by Kampfmoehre** [comment]
Thank you @bruno-garcia for the info. So would I need to set AssemblyInformationalVersionAttribute to my-application@1.0.0 for the release to be app@version, or is the my-application part taken from somewhere else?

**Comment by bruno-garcia** [comment]
Correct. It'll take what's in either of those assemblies and set as Release. In the order I mentioned.

**Comment by ltechera** [comment]
> I just tried the template for ASP.NET Core 3.0 on preview 9 which is supposed to be the last one (3.0 will be released in a week) and it looks like this:
> 
> ```
> public static IHostBuilder CreateHostBuilder(string[] args) =>
>     Host.CreateDefaultBuilder(args)
>         .ConfigureWebHostDefaults(webBuilder =>
>         {
>             webBuilder.UseStartup<Startup>();
>         });
> ```
> 
> So until we support Generic host, please just add:
> 
> ```
> weBuilder.UseSentry();
> ```
> 
> and it should all work fine.

Didn't work for me.. Using this I get an error saying I need to have a Startup class in my console app project.
@xt0rted 's post did the trick!

**Comment by bruno-garcia** [comment]
@ltechera Thanks for sharing that. This is something we could improve, adding to our backlog

**Comment by rh78** [comment]
Supporting this! It is missing.

**Comment by Bowenf3** [comment]
Bump - running into issues with this.

**Comment by a-legotin** [comment]
any updates here?

**Comment by mattjohnsonpint** [comment]
Yes.  I picked this up again a couple of weeks ago, starting with reviving #1015.  There's a lot of work still to do, and I'm not sure exactly when it will be completed, but I will update this issue when it's ready.

In the meantime, you can use the current release as follows:

When using ASP.NET Core with the Web Host:

```csharp
WebHost.CreateDefaultBuilder()
    .UseSentry(...);
```

When using ASP.NET Core with the Generic Host:

```csharp
Host.CreateDefaultBuilder()
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.UseSentry(...);
    });
```

When using the Generic Host _without_ ASP.NET Core:

```csharp
Host.CreateDefaultBuilder()
    .ConfigureServices(services =>
    {
        services.AddHostedService<YourHostedService>();
    }
    .ConfigureLogging(loggingBuilder =>
    {
        loggingBuilder.AddSentry(...);
    });
```

**Comment by ryanelian** [comment]
I just hit this issue when trying to configure Sentry and Serilog inside an extension method for `IHostBuilder` which is used in separate ASP.NET Core Web API project and Generic Host (Worker service) project.

It would be nice if I can `UseSentry` from the `IHostBuilder` to configure both ASP.NET Core and Worker service with one method...

**Comment by mattjohnsonpint** [comment]
Thanks.  We haven't forgotten about this, there's just been a few other things prioritized higher.  For now, use the workaround above.  Thanks.

**Comment by PMExtra** [comment]
A real equivalent of `IWebHostBuilder.UseSentry()`:

```csharp
            var builder = WebAppliccation.CreateBuilder(args);
            builder.Host
                .ConfigureLogging((context, logging) =>
                {
                    var section = context.Configuration.GetSection("Sentry");
                    logging.Services
                        .Configure<SentryAspNetCoreOptions>(section)
                        .AddSingleton<IConfigureOptions<SentryAspNetCoreOptions>, SentryAspNetCoreOptionsSetup>()
                        .AddSingleton<ILoggerProvider, SentryAspNetCoreLoggerProvider>();
                    logging.AddFilter<SentryAspNetCoreLoggerProvider>(
                        "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware",
                        LogLevel.None
                    );
                    logging.Services.AddSentry().AddSentryOptions(options =>
                    {
                        var hostingEnvironment = context.HostingEnvironment;
                        var settingLocator = options.GetType()
                            .GetProperty("SettingLocator", BindingFlags.Instance | BindingFlags.NonPublic)!;
                        Check.NotNull(settingLocator, nameof(settingLocator));
                        var getEnvironment = settingLocator.PropertyType
                            .GetMethod("GetEnvironment", BindingFlags.Instance)!;
                        var environment = getEnvironment
                            .Invoke(settingLocator.GetValue(options), new object[] { false });
                        if (environment is not null) return;
                        if (options.AdjustStandardEnvironmentNameCasing)
                        {
                            options.Environment =
                                hostingEnvironment.IsProduction() ? "production" :
                                hostingEnvironment.IsStaging() ? "staging" :
                                hostingEnvironment.IsDevelopment() ? "development" :
                                hostingEnvironment.EnvironmentName;
                        }
                        else
                        {
                            options.Environment = hostingEnvironment.EnvironmentName;
                        }
                    });
                })
                .ConfigureServices(services =>
                {
                    services.AddTransient<IStartupFilter, SentryStartupFilter>();
                    var sentryMiddleware =
                        typeof(SentryStartupFilter).Assembly.GetType("Sentry.AspNetCore.SentryMiddleware")!;
                    Check.NotNull(sentryMiddleware, nameof(sentryMiddleware));
                    services.AddTransient(sentryMiddleware);
                });
```

**Comment by PMExtra** [comment]
@mattjohnsonpint 

I'm using `IHostBuilder` rather than `IWebHostBuilder` with ASP.NET Core. 

I have some other integrations such as `UseAutofac()` that have to depends on `IHostBuilder` rather than `IWebHostBuilder`.

When I called `.ConfigureWebHostDefaults` it throws an exception.

**Comment by mattjohnsonpint** [comment]
Can you give an example of the exception?

Can you try `ConfigureWebHost` (without "Defaults")?

Thanks.

**Comment by mattjohnsonpint** [comment]
Also, I'm not sure why it matters that you've got other integrations.  You certainly can use both `Host` and `WebHost` properties of a `WebApplicationBuilder`. For example:

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseAutofac();
builder.WebHost.UseSentry();
var app = builder.Build();
```

Also, I haven't used Autofac in ages, but the docs tell me its actually `builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());` - Unless you're using something like ABP Framework.

**Comment by PMExtra** [comment]
@mattjohnsonpint 
Thanks! It's solved.
I'm confused why there be both `builder.Host` and `builder.WebHost`, and even they can work together at the same project.
I was wrong to think there is only `builder.Host` I can use.
And a more confusing thing is that  there are  actually `IHostBuilder.ConfigureWebHost()` and `IHostBuilder.ConfigureWebHostDefaults()` methods. And they will through exceptions.

**Comment by mattjohnsonpint** [comment]
Glad that worked for you. 🙂

Yeah, it's even more confusing if you take into account all the naming changes that have happened over the years between versions.  It certainly is challenging for us to support them all, but we do our best to keep up!

**Comment by Kampfmoehre** [comment]
Since this cost me some time to find, I want to add, when using `Host.CreateApplicationBuilder(args);` (.NET 7+) for non Web projects Sentry can be added like this
```cs
HostApplicationBuilder builder = Host.CreateApplicationBuilder(args);

builder.Logging.AddSentry(o =>
{
  o.Dsn = "...";
});
```
