### ISSUE TITLE
Sentry fails with latest version of System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by andher1802** [getsentry/sentry-dotnet#1901]
### Package

Sentry

### .NET Flavor

.NET Framework

### .NET Version

.NET Framework 4.8

### OS

Windows

### SDK Version

3.20.1 & 3.21.0

### Steps to Reproduce

1. WPF application
2. Install the System.Runtime.CompilerServices.Unsafe to version = 5.0.0
3. Try to capture an error or message. 

### Expected Result

Send the error to my Sentry.io project with the latest version of System.Runtime.CompilerServices.Unsafe (version 6.0.0.)

### Actual Result

Only sends the actual captured error/message when the System.Runtime.CompilerServices.Unsafe set to version = 5.0.0. It fails when the version is set to 6.0.0 with the following error.  

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1
[SentyTestWPF.zip](https://github.com/getsentry/sentry-dotnet/files/9500232/SentyTestWPF.zip)

**Comment by mattjohnsonpint** [comment]
The usual method for dealing with this issue in .NET Framework is [assembly binding redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions).

**Comment by mattjohnsonpint** [comment]
Testing with the app you provided in the zip file, everything works as expected.  I see the required binding redirect in your `App.config` file:

``
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

The only way I can get the error you reported is by removing the binding redirect and also setting `AutoGenerateBindingRedirects` to `false` in the csproj.
