### ISSUE TITLE
Support for Stack Trace Linking

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1902]
Sentry doesn't yet support [stack trace linking](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking) for .NET projects.

**Comment by mattjohnsonpint** [comment]
Not sure if Source Context (#646) will need to be completed first or if they are independent features.

**Comment by realkosty** [comment]
Source context is working now + I see that stack trace linking works for GitHub but apparently not AzureDevOps

**Comment by realkosty** [comment]
Turns out AzureDevOps is supported as well!
Resolving 

![azuredevops-stack-trace-linking](https://github.com/getsentry/sentry-dotnet/assets/490201/98d227e6-eb98-43d3-92c7-7e4c8a729fa9)
