### ISSUE TITLE
Stray/broken tests

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1904]
There are some tests here:

https://github.com/getsentry/sentry-dotnet/tree/main/test/Sentry.Extensions.Logging.EfCore.Tests

But this project is not in the solution, and thus it hasn't been run.  I tried adding it, but it fails.

@lucas-zimerman - Looks like it was added by you with #1112.  Can you please update it and add it to the solution?  If it's failing because something is actually broken, that would be good to know as well.

Thanks.

**Comment by mattjohnsonpint** [comment]
Actually, they look like they're just older versions of these:
https://github.com/getsentry/sentry-dotnet/blob/main/test/Sentry.DiagnosticSource.Tests/Integration/SQLite/SentryDiagnosticListenerTests.cs

I think we can just delete them.  Please confirm.  Thanks.

**Comment by lucas-zimerman** [comment]
> Actually, they look like they're just older versions of these: https://github.com/getsentry/sentry-dotnet/blob/main/test/Sentry.DiagnosticSource.Tests/Integration/SQLite/SentryDiagnosticListenerTests.cs
> 
> I think we can just delete them. Please confirm. Thanks.

Correct, they are the same tests.
