### ISSUE TITLE
Example for Custom StackTrace Factory

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#196]
Would it be possible to get an example of how to use the Custom StackTrace factory?  With the latest beta, I still see `Void MoveNext()` in many of my stacktraces.

**Comment by bruno-garcia** [comment]
@lunim the latest release only exposed hooks that can be used to modify the stack trace conversion. 
[If you move to .NET Core 2.1 or later there should be improvements without any modification](https://www.ageofascent.com/2018/01/26/stack-trace-for-exceptions-in-dotnet-core-2.1/).

@pengweiqhca [is planning to publish a package](https://github.com/getsentry/sentry-dotnet/issues/101) which will depend on [Ben.Demystifier](https://github.com/benaadams/Ben.Demystifier) which will improve the stack traces for .NET Framework and Mono.

**Comment by pengweiqhca** [comment]
I will publish a beta package soon

**Comment by bruno-garcia** [comment]
The samples you're looking for are here:
https://github.com/getsentry/sentry-dotnet/pull/201/files

For support, please each out to the fork that owns the package:
https://github.com/pengweiqhca/sentry-dotnet

**Comment by lunim** [comment]
@bruno-garcia Thanks for the details.  I'm using .Net core 2.1, but still see many references to `Void MoveNext()`.  Using the new stacktrace factory and NuGet package in the sample, I get the actual function names.

**Comment by bruno-garcia** [comment]
@lunim right. We should not send the _Context Line_ in that case. 

On the top of the line where you see `MoveNext` you see the actual method name, right? Next to namespace, and assembly name etc?

**Comment by lunim** [comment]
@bruno-garcia Yes, I see the method name in the top line, the context line just gives details on the function, instead of a reference to `MoveNext`

**Comment by bruno-garcia** [comment]
Great. Yes, we need to avoid reporting it when it's just MoveNext
