### ISSUE TITLE
feat: Don't report context line when it's state machine

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#198]
NOTE: This will change grouping with the legacy grouping code.

In .NET Core 2.1 the stack traces are cleaned up but context line is not:

![image](https://user-images.githubusercontent.com/1633368/57704431-29b34d80-7662-11e9-981c-eb0fe612ff22.png)

Method is reported as `ExecuteAsync`. Reporting the context line `MoveNext` is just noise.

Goal: Don't report context line when it equals to: `Void MoveNext()` and `lambda`:

![image](https://user-images.githubusercontent.com/1633368/57707473-fd023480-7667-11e9-9782-7d3df271c9ec.png) by skipping this frame altogether.

https://github.com/getsentry/sentry-dotnet/blob/967c0e08d7ae03692c605807664bd086796b1455/src/Sentry/Extensibility/SentryStackTraceFactory.cs#L108

**Comment by kanadaj** [comment]
Have you considered just simply using https://github.com/benaadams/Ben.Demystifier?

**Comment by bruno-garcia** [comment]
@kanadaj yes. It was decided not to add the dependency nor publish another package.
THere's a community option thought. See: #201 to get `Ben.Demystifier`.

.NET Core already has improved stack traces. The `context line` is just wrong but the method name is correct.

**Comment by bruno-garcia** [comment]
Resolved by #223
