### ISSUE TITLE
SentryTunnelMiddleware's default configuration discards all tunnelled events

### ISSUE THREAD

**Issue by Brads3290** [getsentry/sentry-dotnet#2017]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

6.0.0

### OS

macOS

### SDK Version

3.22.0

### Steps to Reproduce

1. Set up Sentry in AspNetCore like so:
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseSentry(o => {
    o.Dsn = "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxxx.ingest.sentry.io/xxxxxxxxxxxxxxxx";
    o.TracesSampleRate = 1.0;
    o.Debug = true;
});

builder.Services.AddSentryTunneling();

// ...

var app = builder.Build();

app.UseRouting();

app.UseSentryTunneling("/sentry");

// ...

```

2. Set up Javascript front-end like so:
```javascript
Sentry.init({
  dsn: "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxxx.ingest.sentry.io/xxxxxxxxxxxxxxxx",
  tunnel: "/sentry"
});
```

3. Trigger an error on the client side (via the script, not via the console).
<img width="551" alt="image" src="https://user-images.githubusercontent.com/8080871/198162287-cca3fb2a-1403-49d0-8a1c-942c7fbd8f59.png">

4. The browser console, and AspNetCore logging both confirm that the event was received by the tunnel endpoint:
```text
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:7121/sentry text/plain;charset=UTF-8 2806
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST https://localhost:7121/sentry text/plain;charset=UTF-8 2806 - 200 0 - 76.4213ms
```

Placing a breakpoint in `SentryTunnelMiddleware` and stepping through, shows what is happening:
1. The client sends the `dsn` value along with the request (`https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxxx.ingest.sentry.io/xxxxxxxxxxxxxxxx`)
2. The middleware extracts the `dsn` value and parses it as a `System.Uri`.
3. The `Host` property of the DSN URI is then compared to the list of allowed hostnames, which by default **only contains sentry.io**, but the `dsn.Host` property is actually `xxxxxxxxxxxxxxxxx.ingest.sentry.io`
4. Because the DSN host is not in the default list of allowed hosts, the event is discarded.
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/8080871/198162895-102602c8-3e79-4d13-9c6e-34425029613b.png">

### Expected Result

The event should be forwarded to sentry.io.

### Actual Result

The event is discarded.

**Comment by Brads3290** [comment]
Forgot to mention for anyone else coming across this - the temporary fix is to add your sentry host to the `AddSentryTunnelling` call:

```csharp
builder.Services.AddSentryTunneling("xxxxxxxxxxxxxxxx.ingest.sentry.io");
```

**Comment by mattjohnsonpint** [comment]
Hi @Brads3290 - Thanks for reporting this, and for the workaround!  I'll investigate ASAP.
