### ISSUE TITLE
Why db.connection is always connected to root transaction and not visible under proper ChildSpan?

### ISSUE THREAD

**Issue by CrazyBaran** [getsentry/sentry-dotnet#2023]
### Problem Statement

I looking into your implementation for sentry-dotnet and I had big issue with this particular line.
https://github.com/getsentry/sentry-dotnet/blob/e85b2e9ed17e870f956a9fb7f649e5b9e72c18d2/src/Sentry.DiagnosticSource/Internal/DiagnosticSource/SentryEFCoreListener.cs#L65
Is there any reason why you use always Transaction as root for db.connection rather to connect to Child which was created before and finished after connection? Did it is connected with that, that connection could be opened and in meantime we could finish one span and open another one and then close conection?

**Comment by mattjohnsonpint** [comment]
Hi.  Thanks for bringing this up!  I believe @Belphemur had the same concern.  Please see
https://github.com/getsentry/sentry-dotnet/pull/1671#issuecomment-1139623052

**Comment by CrazyBaran** [comment]
@mattjohnsonpint Thx for answer, I think in terms of Instrumentation we don't need to worry so strongly about db.connection in dotnet. Dotnet team do excellent job, maybe only additional tag or something to track this. Today I made new .StartChild(...) and found out this poor bastard and nobody in sentry would convince me, that is better information for me than proper tree. It simple db.connection is on top of everything, but understanding of code flow didn't goes this way. Move it this somewhere else please. 
PS. NullDataBrickService was ran in my full awareness under DataBricksRunAppService.CreateAsync. but this one line of code which I mention ruined all graph. Ok this is end of my grilling about it, I move to mention Issue.
PS2. @mattjohnsonpint It would be useful, if in docs would at least one line that in this case db.connection is always going to transaction. I lost 3 hours to dig down to this line of code, always doubting in my skills xD and then I look into source code...
<img width="439" alt="Zrzut ekranu 2022-10-27 o 23 51 11" src="https://user-images.githubusercontent.com/10425123/198405239-b1e4fd07-528f-4b12-8bc0-f2589728b78a.png">
