### ISSUE TITLE
Captured exceptions using .NET framework and SENTRY with TLS 1.2

### ISSUE THREAD

**Issue by senad004** [getsentry/sentry-dotnet#203]
Hi @bruno-garcia I successfully implemented SENTRY in my applications. I recently saw some different behavior and thought to get help from you. Please see below
I am using .NET framework 4.5 and added below line to transfer logs to SENTRY
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

It's working perfectly. But on the server side, I am seeing 2 versions are enabled (TLS 1.2 and SSL ). No other TLS versions are disabled. SENTRY is logging all errors.

My questions is ,
What does SENTRY expect exactly?
Does it check whether all TLS lower versions are disabled on the server and enabled only TLS
1.2 ?
(OR)
Does it check whether TLS 1.2 is enabled or not on the server ?

Also is it compatible for Windows 2008 servers?

It would be great if you clarify my doubt.

Refer https://github.com/getsentry/sentry-dotnet/issues/114#

**Comment by bruno-garcia** [comment]
`Sentry` NuGet package requires .NET Framework 4.6.1 or higher. Could you confirm what SDK you are using? Keep in mind we don't support SharpRaven anymore.
