### ISSUE TITLE
Set TracesSampleRate to 1.0 by default

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2036]
Per internal TSC discussion, on next major change of all Sentry SDKs (4.0.0 for .NET), the `TracesSampleRate` option should change to `1.0` by default.  The intent is to prefer [dynamic sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/) instead.

Docs should also be updated at that time to remove code snippets describing setting this option.

The option itself should continue to function as it does today. (It controls client-side sampling before the server can make a dynamic sampling decision.)

# Depends on
- https://github.com/getsentry/sentry-dotnet/issues/2410

**Comment by mattjohnsonpint** [comment]
Figure out with #2158 and align with other sdks

**Comment by mattjohnsonpint** [comment]
I believe it should be:

- For `3.x`, `TracesSampleRate` will be `0.0` by default - except that `enableTracing` will set it to `1.0`
- For `4.x`, `TracesSampleRate` will be `1.0` by default

**Comment by bruno-garcia** [comment]
Depends on/relates to:

* #2468 
#2946

**Comment by jamescrosswell** [comment]
> The intent is to prefer [dynamic sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/) instead.

@bitsandfoxes given Matt's original comment that this is part of a move to dynamic sampling, is this blocked by https://github.com/getsentry/sentry-dotnet/issues/2410?
