### ISSUE TITLE
OpenTelemetry Support

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-dotnet#2066]
### Problem Statement

OpenTelemetry has growing popularity in the observability space as one of the top CNCF open standard for APM.

It's data model differs from Sentry so it cannot be natively ingested. But many OpenTelemetry users would like to send their OTEL data to Sentry.

### Details
- [SDK Docs: OpenTelemetry Support | Sentry](https://develop.sentry.dev/sdk/performance/opentelemetry/) 
- span processor - transforming OTEL spans into Sentry spans within Sentry transactions
  - span name, description and [span status](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#optional-add-status)
    - span status needs [special logic](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#exporting-activity-status) for DiagnosticSource versions < 6.0.0
  - parent child relationships
- trace/context propagator - including DSC and trace context 
  - https://opentelemetry.io/docs/reference/specification/context/api-propagators/

## dogfooding

The cartservice on our OTel Demo is .NET 

https://github.com/getsentry/opentelemetry-demo/tree/main/src/cartservice

## Reference
Demo project from OTEL, we created a fork to instrument with Sentry SDKs, to test and demo the implementation. Projects are in the Sentry SDKs org

- https://github.com/getsentry/opentelemetry-demo

For more context, these PRs are not exhaustive list of the work done on other SDKs

- Ruby: https://github.com/getsentry/sentry-ruby/issues/1907
- Python: https://github.com/getsentry/sentry-python/issues/1687
- Node: https://github.com/getsentry/sentry-javascript/issues/6000 & https://github.com/getsentry/sentry-javascript/issues/6127
- Java: https://github.com/getsentry/sentry-java/issues/2327
  - https://github.com/getsentry/sentry-java/pull/2357
  - https://github.com/getsentry/sentry-java/pull/2361

- Relay: https://github.com/getsentry/relay/issues/1636
  - efforts to consolidate the logic so the SDKs do not have to as much

**Comment by mattjohnsonpint** [comment]
Related: #334

**Comment by bruno-garcia** [comment]
`cartservice` in the demo can be instrumented for testing: https://github.com/getsentry/opentelemetry-demo/tree/main/src/cartservice

**Comment by source-studio** [comment]
@mattjohnsonpint - could I ask if there is an ETA for this feature? The .NET OpenTelemetry implementation is reasonably mature now, so it shouldn't present too many roadblocks. Given the popularity of .NET, I'm surprised Sentry deprioritised this implementation, relative to the other supported languages.

**Comment by jamescrosswell** [comment]
@source-studio sorry no one got back to you sooner. I'll see if I can pick this one up... I haven't yet gathered enough context to be able to estimate how long this might take but you should see some updates/activity shortly.
