### ISSUE TITLE
Cookies property is not populated

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2070]
### Package

Sentry.AspNet
Sentry.AspNetCore

### SDK Version

3.24.0

### Steps to Reproduce

In an ASP.NET Core app (such as `Sentry.Samples.AspNetCore.Basic`):

Create a processor to log cookies to the console for both events and transactions:
```csharp
public class MyProcessor : ISentryEventProcessor, ISentryTransactionProcessor
{
    private readonly SentryOptions _options;

    public MyProcessor(SentryOptions options)
    {
        _options = options;
    }

    public SentryEvent Process(SentryEvent @event)
    {
        _options.DiagnosticLogger?.LogInfo("Cookies: {0}", @event.Request.Cookies);
        return @event;
    }

    public Transaction Process(Transaction transaction)
    {
        _options.DiagnosticLogger?.LogInfo("Cookies: {0}", transaction.Request.Cookies);
        return transaction;
    }
}
```

Set options:

```csharp
.UseSentry(options =>
{
    options.Debug = true;
    options.EnableTracing = true;
    options.SendDefaultPii = true;

    var processor = new MyProcessor(options);
    options.AddEventProcessor(processor);
    options.AddTransactionProcessor(processor);
})
```

Set a cookie in some endpoint:
```csharp
endpoints.MapGet("/", (HttpContext context) =>
{
    context.Response.Cookies.Append("foo", "bar");
    return Results.Ok("Hello World!");
});
```

Run the app and load the page once to set the cookie, and then reload the page again so the browser sends the cookie in the request.

### Actual Result

The console output shows:

```
Cookies: (null)
```

### Expected Result

Cookies should be populated and set on the request (as long as `SendDefaultPii == true`)

https://develop.sentry.dev/sdk/event-payloads/request/

Applies to both ASP.Net Framework and ASP.Net Core

```
Cookies: foo=bar;
```

**Comment by kanadaj** [comment]
This is mainly an issue because the default filter for the Identity cookie does not work if the cookie got renamed, and filtering cookies in an unparsed header is far too involved.
