### ISSUE TITLE
sentry-cli uploading PDBs fails when symbols embedded

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2073]
In the Portable PDB PR: https://github.com/getsentry/sentry-dotnet/pull/2050

An error happens on the `Sentry.dll` because of missing `pdb.` Even though it's possible some DLLs won't have PDBs, it doesn't mean debug info isn't available.

In the case of `Sentry.dll`, the debug information is embedded in the DLL itself:

https://github.com/getsentry/sentry-dotnet/blob/de3cf7288aec646842f32d59ef88eec9d859fbf1/src/Directory.Build.props#L32

We need to be able to read the debug info from the DLL and upload that to Sentry to support line numbers/paths.

**Comment by vaind** [comment]
While I'm on board with supporting this in CLI, maybe we should also consider switching to portable PDB at some point. Here's what it does to the android sample app:

### WIth embedded debug info in build.props
<img width="541" alt="image" src="https://user-images.githubusercontent.com/6349682/205930774-0d770bd4-4a6d-472e-ae6b-88688a6cb7b2.png">


### With portable PDB in build.props
<img width="554" alt="image" src="https://user-images.githubusercontent.com/6349682/205930372-3dfa73a7-f3e1-4660-a477-550061c1215e.png">

**Comment by mattjohnsonpint** [comment]
It's not just Sentry.dll, but customers will see this too when symbols are embedded.  Though they might still get stack trace info in such cases - unless it's later trimmed out.

It would be good to get this fixed in sentry-cli itself.

**Comment by mattjohnsonpint** [comment]
But yes, also I think we can stop embedding symbols in our own dlls.  Instead, we should make sure we [publish symbols packages](https://learn.microsoft.com/nuget/create-packages/symbol-packages-snupkg) (.snupkg) with our nugets so customers will still get sources with [Source Link](https://github.com/dotnet/sourcelink/blob/main/README.md).

**Comment by vaind** [comment]
Embedded symbols should be supported with the next release of CLI (assuming it gets the latest symbolic included). I'm keeping track of that so I'll assign this issue to myself too.

**Comment by mattjohnsonpint** [comment]
Is there any benefit though?  If the symbols are embedded, won't we always get line numbers in the actual stack trace - thus making symbolication a no-op?

Note to self - If that's not the case, then when we bump the CLI we should also remove ` And '$(DebugType)' != 'embedded'` from this line:
https://github.com/getsentry/sentry-dotnet/blob/6b17e2cd3ef6143d7e74d25211657bc879b69c83/src/Sentry/buildTransitive/Sentry.props#L38

**Comment by mattjohnsonpint** [comment]
Also, is there an issue tracking this in sentry-cli?  I couldn't find one.  Thanks.

**Comment by mattjohnsonpint** [comment]
Nevermind, found it in Symbolic https://github.com/getsentry/symbolic/pull/734.  Thanks

**Comment by mattjohnsonpint** [comment]
Latest Sentry CLI (2.12.0) doesn't address this.  We do get embedded sources when they are part of the pdb file, but we do not get embedded sources or symbols when they are embedded in the dll.  See https://github.com/getsentry/symbolic/issues/750

**Comment by mattjohnsonpint** [comment]
> Is there any benefit though? If the symbols are embedded...

Just to answer myself here, the benefit is largely to have embedded *sources*, but also I have seen at least one case where even though the symbols were originally embedded, .NET did not include filenames/line-numbers in the stack trace.  This was on an Android app, so I suspect the embedded symbols in the library were stripped out when the app was built.

**Comment by mattjohnsonpint** [comment]
Note, with #2166 this issue no longer affects the Sentry .NET SDKs.  However, it could still affect a user if they are embedding symbols in their own project, so we should keep this issue open until we have an updated Symbolic + Sentry CLI that handles it.

**Comment by vaind** [comment]
closed via https://github.com/getsentry/sentry-cli/pull/1463 and will be available in the next CLI release
