### ISSUE TITLE
SentryLoggingOptions.ConfigureScope callback is never called

### ISSUE THREAD

**Issue by dbraillon** [getsentry/sentry-dotnet#208]
I've made a bit of digging and it seems that callbacks added with SentryLoggingOptions.ConfigureScope is never used when configured from ILoggingBuilder.AddSentry.

I'm using Sentry.Logging.Extensions to configure Sentry:
```c#
loggingBuilder.AddSentry(opt =>
{
    sentrySection.Bind(opt);

    opt.ConfigureScope(s =>
    {
        // First try, no csutomer tag is added in my events
        s.SetTag("customer", "customer1");

        // Second try, no customer tag is added in my events
        s.AddEventProcessor(e =>
        {
            e.SetTag("customer", "jambon");
            return e;
        });
    });
});
```

I've tracked down the configuration and here what I've found:
- [AddSentry method](https://github.com/getsentry/sentry-dotnet/blob/bfc23f0eecc009a80284c1561856c4ecc9dcafd7/src/Sentry.Extensions.Logging/LoggingBuilderExtensions.cs) which configure SentryLoggingOptions in ServiceCollection
- [SentryLoggerProvider](https://github.com/getsentry/sentry-dotnet/blob/bfc23f0eecc009a80284c1561856c4ecc9dcafd7/src/Sentry.Extensions.Logging/SentryLoggerProvider.cs) which create the SentryLogger and I guess the callback should be called here
- [SentryLogger](https://github.com/getsentry/sentry-dotnet/blob/1aaa3e609162b660148d51ec58973ff8e13eb791/src/Sentry.Extensions.Logging/SentryLogger.cs) is using the options but never call the callbacks

I don't think I need to dig more as it seems that other implementation call the callbacks as soon as possible (sample here with [ILoggerFactory](https://github.com/getsentry/sentry-dotnet/blob/bfc23f0eecc009a80284c1561856c4ecc9dcafd7/src/Sentry.Extensions.Logging/SentryLoggerFactoryExtensions.cs))

I can start a PR if you guys can confirm the problem.

**Comment by bruno-garcia** [comment]
@dbraillon thanks for raising this.
Currently there are two entry points to the MEL integration. One via extending `ILoggerFactory` which as you linked does call the registered callbacks and the other extending `ILoggerBuilder` which registerers things with the DI container. Might be this is missing then invoking the callbacks when the instance is created (first instance is resolved via DI.)
Would be great to get some help fixing this, Thanks!

**Comment by dbraillon** [comment]
Here we go, got something for you #210.

**Comment by bruno-garcia** [comment]
@dbraillon I saw that but I believe deleting the other code is a problem. There are two entrypoints IIRC. One for usages of MEL straight with the Factory and one with the LoggingProvider. I'd need to take a look and test it out before approving/merging.
