### ISSUE TITLE
Update Samples / Examples

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2081]
We have samples in two different places:

https://github.com/getsentry/sentry-dotnet/tree/main/samples

https://github.com/getsentry/examples/tree/master/dotnet

The latter is quite outdated and needs a refresh.  Also there are some samples scenarios in there we don't have in the main repo (such as ASP.NET framework).

We should come up with a plan to keep them organized and regularly refreshed.

**Comment by mattjohnsonpint** [comment]
There's also this one:
https://github.com/sentry-demos/AspNetCore-MVC

**Comment by mattjohnsonpint** [comment]
I believe the sales demo (https://github.com/sentry-demos/AspNetCore-MVC) is going to get a refresh soon. 🤞

**Comment by mattjohnsonpint** [comment]
One problem with all of the samples is that we have them hardcoded to use the DSN for the `sentry-sdks/sentry-dotnet` project.  If might work better for an end-user to see the events actually come through to their own Sentry account.  Thus, using the environment variable would be a better approach.  Perhaps the samples should all be like this:

```csharp
using var _ = SentrySdk.Init(o =>
{
    // The DSN is required, but for these samples we recommend using the SENTRY_DSN environment variable
    // If you prefer, you can paste your DSN here in the code instead (uncomment the below line).
    // o.Dsn = "";

    // When debug is enabled, the Sentry client will emit detailed debugging information to the console.
    o.Debug = true;
});
```

**Comment by mattjohnsonpint** [comment]
For now, let's only focus on the samples in this repo: https://github.com/getsentry/sentry-dotnet/tree/main/samples

**Comment by mattjohnsonpint** [comment]
Let's start with the Console samples, followed by the ASP.NET Core samples.  There's enough variation between the two of those to let use work out most of the nuances.

**Comment by SeanFeldman** [comment]
The basic Console sample has been split into two (`Sentry.Samples.Console.Basic.net48` and `Sentry.Samples.Console.Basic.net60`) to see if that's how we want to approach it.

**Comment by mattjohnsonpint** [comment]
I updated the console sample in #2317.  We can use that as an exemplar for the others one-by-one.

Let's keep this issue open until they are all done.  Thanks.

**Comment by bitsandfoxes** [comment]
The `/examples` went the way of the dodo. The rest of the samples get updated on a need-to basis (i.e. https://github.com/getsentry/sentry-dotnet/issues/2275)
