### ISSUE TITLE
Sentry 3.22 Not Sending Exceptions in ASP.Net 4.8 Web Forms

### ISSUE THREAD

**Issue by dancingfire** [getsentry/sentry-dotnet#2088]
### Package

Sentry.AspNet

### .NET Flavor

.NET

### .NET Version

4.8

### OS

Windows

### SDK Version

3.22

### Steps to Reproduce

I'm updating from 2.22 (or thereabouts) and that version worked perfectly - local and in production. When I upgraded (via Nuget), it all stops working,

I init in the application start - which definitely is initializing. 

```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
SentryOptions o = new SentryOptions();
o.Debug = true;
o.Dsn = ConfigurationManager.AppSettings["SentryDNS"];
o.Environment = ConfigurationManager.AppSettings["Environment"];
o.DiagnosticLogger = new ConsoleDiagnosticLogger(SentryLevel.Debug); // Tried it with and without this line.

if (!String.IsNullOrEmpty(ConfigurationManager.AppSettings["SentryDNS"])) {
    _sentry = SentrySdk.Init(o);
};
```

Error is handled here:

```csharp
protected void Application_Error(Object sender, EventArgs e) {
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
    var exception = Server.GetLastError();
    Debug.WriteLine("Capturing an error");
    Sentry.SentryId ID = SentrySdk.CaptureException(exception);
}
```

And here's the debug trace:

An exception of type 'System.NullReferenceException' occurred in ChalkSystems.dll but was not handled in user code
Object reference not set to an instance of an object.

Capturing an error
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 7 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
Event 10 was called with 5 argument(s) , but it is defined with 6 paramenter(s).
The thread 0x315c has exited with code 0 (0x0).

### Expected Result

I would expect an event to show up on Sentry. 

### Actual Result

Nothing shows up in Sentry. There are no additional local debug logs.

**Comment by mattjohnsonpint** [comment]
Hi.  Please see the sample in the ASP.NET guide for how to initialize Sentry in ASP.NET for .NET Framework.

https://docs.sentry.io/platforms/dotnet/guides/aspnet/

In particular, you should call `o.AddAspNet()` when setting the options.  Please let us know if that solves the issue. 

Also I notice your config value is named `SentryDNS` instead of `SentryDSN`.  Please double-check that it is spelled the same as the actual configuration key.

Thanks.

**Comment by mattjohnsonpint** [comment]
Also, I recommend always using the current version which presently is 3.24.0.

**Comment by dancingfire** [comment]
Thanks Matt.  First off apologies - I am using 3.24 in the application. 

This is a webforms application. I don't have the o.AddAspNet() option.  This is also not an oWin application so there's no pipeline to hook...

**Comment by dancingfire** [comment]
Also just confirmed this - I downgrade to version 2.1.1 and update the init as below and the error is captured and sent to sentry.io - so its not the config, but something in the newer versions. I will try this on version 3.0 now...

  ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            SentryOptions o = new SentryOptions();
            o.Debug = true;
            o.Dsn = new Sentry.Dsn(ConfigurationManager.AppSettings["SentryDSN"]);
            o.Environment = ConfigurationManager.AppSettings["Environment"];
            
            if (!String.IsNullOrEmpty(ConfigurationManager.AppSettings["SentryDSN"])) {
                _sentry = SentrySdk.Init(o);
            };

**Comment by dancingfire** [comment]
Reading through all the release notes, I had to include Sentry.AspNet in the project. This gives me the AddAspNet option. So now I have the following (which is still not working) :( Any other ideas? Worst case, I drop back to 2.1.1 and ignore the upgrade message as that was working - I do like having our code base up to date though...

 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            SentryOptions o = new SentryOptions();
            o.Debug = true;
            o.Dsn = ConfigurationManager.AppSettings["SentryDSN"];
            o.Environment = ConfigurationManager.AppSettings["Environment"];
            o.TracesSampleRate = 1.0;
            o.AddAspNet();
            
            if (!String.IsNullOrEmpty(ConfigurationManager.AppSettings["SentryDSN"])) {
                _sentry = SentrySdk.Init(o);
            };

**Comment by dancingfire** [comment]
OK - found the issue - once all this setup was done, the debug threw an error on a version mismatch on System.Runtime.CompilerServices.Unsafe - it was looking for 4.0 and 6.0 was installed. Added an assembly redirect and all was well. Thanks for your help in pointing out what was NOT the issue and showing me I needed the AddAspNet.

**Comment by mattjohnsonpint** [comment]
Glad you were able to find a solution.  Thanks for the feedback!
