### ISSUE TITLE
Stack trace contains file without path to project root (or any path)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2105]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

7.0.1

### OS

Linux

### SDK Version

3.24.1

### Steps to Reproduce

Throw an exception from Program.cs, example:

https://sentry.io/organizations/nugettrends/issues/3821092585/?project=1266317&query=is%3Aunresolved&referrer=issue-stream#context-Current%20Culture

And:

https://sentry.io/organizations/nugettrends/issues/3854515030/?project=1266316&query=is%3Aunresolved&referrer=issue-stream

### Expected Result

`src/NuGetTrends.Web/Program.cs` Or at least `NuGetTrends.Web/Program.cs`

On GitHub:  https://github.com/dotnet/nuget-trends/blob/main/src/NuGetTrends.Web/Program.cs

I want some path in there so I can configure code mappings. And get suspect commits to work.

![image](https://user-images.githubusercontent.com/1633368/210680821-bedce242-0c08-40f1-8777-9b2d78d0821f.png)

### Actual Result

Only the file name is there without any path.

![image](https://user-images.githubusercontent.com/1633368/210680548-d1bba7e5-ea06-4925-9135-92d5a3c986e0.png)

**Comment by mattjohnsonpint** [comment]
What's happening here is that the filename is being stripped of the project path (correctly), but the absolute path is not being sent.  Sending `abs_path` when we truncate the project path will resolve this.
