### ISSUE TITLE
Serilog verbose logs appearing as errors

### ISSUE THREAD

**Issue by mariusz-schimke-iteo** [getsentry/sentry-dotnet#213]
Logs generated with the Verbose(...) method of Serilog appear as errors on Sentry. Sentry seems not to support the verbose log level, but mapping these to errors seems to be incorrect. How about mapping them to debug logs by default?

**Comment by bruno-garcia** [comment]
Right! `Verbose` should map to `Debug`. This sounds like a bug.

**Comment by kanadaj** [comment]
Verbose isn't logged at all, need to check why it turns into an error. Will pick up this one @bruno-garcia , will do a PR in a bit

**Comment by kanadaj** [comment]
Ah yes, missing mapping combined with
```cs
if (@event.Level == null)
{
    @event.Level = SentryLevel.Error;
}```
