### ISSUE TITLE
Android: Upload proguard mapping files on build

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2131]
### Problem Statement

Building [Symbol Collector](https://github.com/getsentry/symbol-collector) in release mode, results in an apk with `30497900` bytes (30.49 MB).

If I [enable R8](https://github.com/xamarin/xamarin-android/blob/1e4503369d0128679e9b7116c62bd1d71eea3710/Documentation/guides/D8andR8.md): 

```
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
  <AndroidLinkTool Condition=" '$(AndroidLinkTool)' == '' ">r8</AndroidLinkTool>
</PropertyGroup>
```

The final, signed **apk** goes **down to `28081202` bytes** (28.08 MB).
That's `2416698` bytes (2.4 MB) shaved off: **8.6%**

Combined with native symbols, managed PDBs and proguard/r8 mapping files, we can offer maximum apk size shrinking capabilities to our users. I suggest we add a page on our docs about shrinking the final app size, and point users to turn this on, since .NET has this off by default. A call out [to risks](https://developer.android.com/studio/build/shrink-code#troubleshoot) should be added. 

### Solution Brainstorm

I see Sentry Android's Proguard rules in `src/SymbolCollector.Android/obj/Release/net7.0-android/proguard/proguard_project_primary.cfg`, such as:

```
-keep class io.sentry.IEnvelopeReader { *; }
-keep class io.sentry.IEnvelopeSender { *; }
...
```

Another file exists in that folder: `src/SymbolCollector.Android/obj/Release/net7.0-android/proguard/proguard_xamarin.cfg`

Running `sentry-cli` on those directories might do. In case globs worked we could go with something like this:

```
sentry-cli upload-proguard obj/Release/**/proguard/*.cfg
```

This is what our Gradle Plugin does: https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadProguardMappingsTask.kt#L113

**Comment by mattjohnsonpint** [comment]
CLI all the things! 🎉

**Comment by mattjohnsonpint** [comment]
Brainstorm:

- If r8 is run, then there should be an msbuild target to attach to, so we can kick of sentry-cli automatically
- Document how-to use Progard with Sentry for .NET Android developers - Blog post perhaps

**Comment by mattjohnsonpint** [comment]
Looks like if you enable r8, then the Proguard `mappings.txt` file is emitted to the `bin` directory by default.  So we just need to make a call to `sentry-cli upload-proguard`, similar to how we are already uploading symbols and source bundles.  We might want to see if the filename can be read from an MSBuild property instead of hardcoding it.

**Comment by bruno-garcia** [comment]
mapping file is generated under `bin/BuildTarget/TFM/mapping.txt`.
Example: `bin/Release/net7.0-android/mapping.txt`

That can be seen as a rule `--printmapping` in the `obj/BuildTarget/TFM/proguard/proguard_xamarin.cfg`
