### ISSUE TITLE
Integrate with Outsystems

### ISSUE THREAD

**Issue by codek** [getsentry/sentry-dotnet#2135]
### Problem Statement

I would love to be able to integrate sentry to outsystems

So would someone else it appears!

https://forum.sentry.io/t/support-outsystems/15893

The two systems seem to be well married together. Outsystems is c# and is very vocal in its error messages, sentry does a good job of managing all that.

Alternatively is there any way to pump the messages via aws - since i see that outsystems can pump to cloudtrail for example?

**Comment by bruno-garcia** [comment]
Thanks for raising this @codek !

1. Are there hooks to get new npm/NuGet packages installed?
2. Can you modify the startup code to add Sentry, as we document how to install
3. I wonder what would take for OutSystems to consider adding this OOTB. So users can just add the DSN

**Comment by mattjohnsonpint** [comment]
I wonder what value showing a stack trace on an exception would be in a low-code / no-code platform?  Aren't the actual important details to resolve an issue, more particular to the abstractions provided by that platform?

**Comment by codek** [comment]
@mattjohnsonpint that is a good point! however the stack traces are valuable to our devs. But for me the most important thing is the alerting and the tracking that the bug fired.  I like that sentry handles all that side of thing without you getting spammed etc.  And the history of resolving issues and so on.

**Comment by mattjohnsonpint** [comment]
> i dont think pumping from the log to sentry is the way to go because you lose a lot of the context etc

Agreed.  Sentry is primarily integrated through SDKs that are purpose-built for each language or platform.  The SDKs are primarily delivered via package managers.  If Outsystems doesn't expose a place where an end-user can add a package and write some code to use it when their app starts, then there's little we can do on our side.  They certainly could integrate Sentry internally, but that would help them make Outsystems better - not offer Sentry to apps hosted on Outsystems.

Outside of SDKs, you can [send events to Sentry via the CLI](https://docs.sentry.io/product/cli/send-event/).  But as you said, you'd lose most of the context.  Usually that's used only for sending events from scripts, not for pumping log messages from elsewhere. 

Also note that when we integrate our SDKs with logging providers (as we do in .NET with Serilog, NLog, Log4Net, and Microsoft.Extensions.Logging), we do that at runtime directly against that provider's own SDK.  That allows us to gather additional context that may have been available but not captured by the logger.  For example, we might capture available memory at the time an error was logged, even though it's not part of the log message.

See also: https://sentry.io/vs/logging/

Going to close this, as there's not much further we can offer here.  Thanks.

**Comment by JesseRok** [comment]
Hi, 

don't know if this is still interesting for you but I made a mobile plugin (using sentry-cordova SDK) for OutSystems to integrate with Sentry.io.
