### ISSUE TITLE
DB Connection spans presented poorly

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2144]
### SDK Version

3.26.2

### Steps to Reproduce

Using code from NugetTrends [here](https://github.com/dotnet/nuget-trends/blob/fc196aee7904b9747a58605b0bf37f115444d1e7/src/NuGetTrends.Scheduler/DailyDownloadWorker.cs#L232-L299), or from scratch, use EF Core to send multiple update queries to the database within one db context.

### Expected Result

The recorded spans should be easy to interpret, and should correctly reflect connection time vs query time.

### Actual Result

We capture a new connection span for each query, though there is likely only one real connection.  We never close the connection span, so it appears that they are running forever (in reality, they close automatically with the transaction)

![image](https://user-images.githubusercontent.com/1396388/215621720-9c54fd0d-f20b-4124-b7a9-c66076067f0b.png)

**Comment by mattjohnsonpint** [comment]
There clearly is a bug here, in that we should be closing the connection span.  But even then, it will still be confusing because there's actually not a separate connection per query.  Rather, EF Core and SQL Client are pooling the connections in the background.

More importantly the only thing we really are interested in seeing with regard to connection is any slowness caused when actually connecting to the database.  Thus, I propose changing how we show the connection span.  Rather than it being the parent of the query, it should be a sibling that comes first.  But also, it shouldn't be the time from connection connected to closed, but rather the time from _connecting_ to _connected_.

**Comment by J-Swift** [comment]
Just came across this when trying to figure out how to interpret `db.connection` vs `db.query`. Would really appreciate this being more straightforward to interpret.

**Comment by jamescrosswell** [comment]
I'm not able to reproduce this. This is what I'm seeing using the same DB context to issue multiple SQL Queries in a single controller method (each with it's own span):
![image](https://github.com/getsentry/sentry-dotnet/assets/728212/b9711244-3835-4dbb-8769-ce045ac4b793)

**Comment by pinkpawkitty** [comment]
@jamescrosswell Those traces seem to be missing the ef core traces.
Yours are called "db query", I assume written by you? The ef core traces are called "db.query" and contain the exeuted SQL as a description

**Comment by jamescrosswell** [comment]
Hm... I had three kinds of queries being run in the transaction above:

1. `_context.Database.SqlQuery`
2. `_context.Database.ExecuteSqlAsync`
3. An `IQueriable` constructed by appending some conditions (like Take(10)) to one of the EF models

If anyone is able to reproduce this, could I get a more detailed description of the code you're using?

Here's the code I'm using to try to reproduce (running against an EF model generated from the [dvdrentals Postgres sample database](https://www.postgresqltutorial.com/postgresql-getting-started/postgresql-sample-database/)) that is being injected as `_context` via the constructor on the ASP.NET Core MVC Controller class for this action. 

```
    public async Task<IActionResult> Index([FromServices] IHub sentry)
    {
        IEnumerable<Customer> customers;
        HttpStatusCode statusCode;

        ITransaction? transaction = null;
        try
        {
            transaction =  sentry.StartTransaction("home", "get-index");
            
            // Get some sample customers
            ISpan? sampleSpan = transaction.StartChild("db query", "getting random sample of customers");
            
            var limit = 10;
            var sampleQuery = FormattableStringFactory.Create(
                $"""
                    SELECT customer.customer_id FROM customer
                    inner join
                    (
                        select customer_id, 1 + trunc(random() * 5100000)::int AS random_id
                        FROM customer 
                        order by random_id
                        limit {limit}
                    ) AS random_pick using (customer_id)
                 """
                );
            var sampleCustomers = await _context.Database.SqlQuery<int>(sampleQuery).ToListAsync();
            
            sampleSpan.Finish();
            
            // Loop through the customers updating them 
            foreach (var customerId in sampleCustomers)
            {
                ISpan? updateSpan = transaction.StartChild("db query", $"updating customer {customerId}");
                await _context.Database.ExecuteSqlAsync($"UPDATE customer SET last_update = timezone('utc', now()) WHERE customer_id = {customerId}");
                updateSpan.Finish();
            }

            // Return the customer details in the model
            ISpan detailsSpan = transaction.StartChild("db query", "getting customer details");
            var query = _context.Customers
                .Where(c => sampleCustomers.Select(c => c).Contains(c.CustomerId))
                .OrderBy(c => c.LastName).ThenBy(c => c.FirstName)
                .Take(10);
            // var query = _context.Customers.OrderBy(c => c.LastName).ThenBy(c => c.FirstName).Take(10);
            customers = await query.ToListAsync();

            detailsSpan.Finish();

            // MAke a random HTTP request
            ISpan? httpSpan = null;

            httpSpan = transaction.StartChild("http", "GET https://www.google.com");
                
            var httpClient = _httpClientFactory.CreateClient();
            var request = new HttpRequestMessage(HttpMethod.Get, "https://www.google.com");
            var response = await httpClient.SendAsync(request);
            statusCode = response.StatusCode;
            
            httpSpan.Finish();
        }
        finally
        {
            transaction?.Finish();
        }

        var model = new HomeViewModel
        {
            Customers = customers,
            StatusCode = statusCode
        };
        return View(model);
    }
```

**Comment by pinkpawkitty** [comment]
@jamescrosswell
The first thing I noticed is that we have these after `StartTransaction()`.
``` c#
sentry.ConfigureScope(scope => scope.Transaction = transaction);
using var sentryScope = sentry.PushScope();
```

We also have `System.Diagnostics.DiagnosticSource` and `System.Diagnostics.TraceSource` packages implicitly installed, I'm not sure if that's relevant.

**Comment by jamescrosswell** [comment]
All good. I have now finally reproduced the problem!

I'm not too sure how we want to handle this though. 

We could potentially give people the option to disable connection logging... which would yield something that looked like this:

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/e281f82e-308c-4619-b771-8468d11b839d)

It's certainly less noisy - but it is missing any information about the connections (which leaves quite a few gaps in the waterfall, that are potentially useful for tracking down performance issues... e.g. when the connection pool isn't big enough and waiting for a connection from the pool has become a bottleneck).

I don't think we can make any assumptions about whether these are different db connections or the same connection. When it comes to it, people probably don't care whether they're the same connection or different connections (which is why they're typically kept in a pool - they're fungible). 

The things that are really important are:
1. How long it takes to establish connections 
2. Potentially, how long connections are being kept open (if connections are neither being closed nor released back to the pool)

One possible solution would be to hide db.connection events that look less than some (configurable) threshold from the UI?

That might work... but we'd have to fix https://github.com/getsentry/sentry-dotnet/issues/2372 first!

**Comment by mattjohnsonpint** [comment]
Just for the record - we didn't go with my thought about "from connecting to connected" - because that would also be disingenuous.  Instead, @jamescrosswell came up with an excellent approach that presents only one connection span per actual connection.  If the connection is re-used through pooling, it doesn't appear a second time.  Then furthermore, we've unparented the connection from the query, so that they are both tied to the same original parent span.  See comments and screenshots in #2409.

Thanks for the great work @jamescrosswell !
