### ISSUE TITLE
Set release to `-dev` after publishing

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2160]
With `sentry-cli`, we don't want to accidentally associate release info for work-in-progress with the last shipped release.  Currently, that would happen because we keep the `<Version>` in `Directory.Build.props` untouched until publishing each release.

Add a small post-release script to add a `-dev` tag.

**Comment by ericsampson** [comment]
The recent (.NET 8) default addition of the commit hash as part of AssemblyInformationalVersion might help address this, maybe the sentry SDK could recreate this format for older .NET SDKs/Framework

**Comment by bitsandfoxes** [comment]
@jamescrosswell with https://github.com/getsentry/sentry-dotnet/pull/3462 merged, we're going to run into this issue, right?

**Comment by jamescrosswell** [comment]
> [@jamescrosswell](https://github.com/jamescrosswell) with [#3462](https://github.com/getsentry/sentry-dotnet/pull/3462) merged, we're going to run into this issue, right?

Very likely yes. At least now with SetCommits we should get specific commits associated with each release as well but it would still be misleading to associate all our dev work on release N + 1 with release N... so I think Matt's suggestion of adding some suffix like `-dev` or `-next.wip` or something makes sense.
