### ISSUE TITLE
Create a Sentry event for failed HTTP requests

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2217]
### Problem Statement

Failed HTTP requests don't result in Sentry events

### Solution Brainstorm

* Spec: https://develop.sentry.dev/sdk/features/#http-client-errors

Main issue with description
* https://github.com/getsentry/team-mobile/issues/38

**Comment by mattjohnsonpint** [comment]
Applies to `HttpClient` - we already have `SentryHttpMessageHandler`, so this should be fairly trivial to add there.

We should think about what stacktrace (if any) belongs with the error.

**Comment by mattjohnsonpint** [comment]
This would be part of our [`SentryHttpMessageHandler`](
https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/SentryHttpMessageHandler.cs)

**Comment by jamescrosswell** [comment]
I'm looking into this now and in particular the [docs regarding FailedRequestTargets](https://develop.sentry.dev/sdk/features/#http-client-errors).

We already have the [TracePropagationTarget class](https://github.com/getsentry/sentry-dotnet/blob/efb5dc8acea1450de9fe1dd8561ad31c4ef069e4/src/Sentry/TracePropagationTarget.cs), which appears to do exactly what we want. About the only thing wrong with it is the name. If it wasn't public I'd suggest we simply rename it to `PropagationTarget` and reuse it for `SentryOptions.FailedRequestTargets` as well. 

Two alternatives I can think of then (and there may be more):
1. Refactor key functionality to a new `PropagationTarget` class that `TracePropagationTarget` inherits from... 
2. Refactor into a Utils/Helper class, similar to the [PropogationTargetsUtils class](https://github.com/getsentry/sentry-java/blob/b79a165be139ac8f7dc2b56c598831b9d3d8601c/sentry/src/main/java/io/sentry/util/PropagationTargetsUtils.java) in the Java SDK. 
3. Something else entirely. 

Are there any strong opinions about which approach to take? I was leaning towards option 1 personally... but it may have drawbacks I haven't considered.

**Comment by mattjohnsonpint** [comment]
Agreed, the name is too specific.  Even `PropogationTarget` is too specific, IMHO.  What do you think of `SubstringOrRegexPattern`?

**Comment by jamescrosswell** [comment]
`SubstringOrRegexPattern` works... quite literal ;-)

**Comment by jamescrosswell** [comment]
So I think I'm in the home stretch on this. All I have to do now is actually send the event data!

I think I'll be able to take a lot of inspiration from [SentryOkHttpInterceptor.captureEvent](https://github.com/getsentry/sentry-java/blob/c9d0787e5af1756f10b872907843ce0d29dfdc20/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt#L151) in the Java SDK. 

I think I have a few questions though. 

The Java SDK contains a `SentryHttpClientException` and an `ExceptionMechanismException` decorator, which is what gets passed to the SentryEvent constructor. 

I see the .NET SDK includes a `SentryException` class (which is not derived from `System.Exception`) that has a [Mechanism property](https://github.com/getsentry/sentry-dotnet/blob/529a0a9168494e00c0d41de5e338987b768af0c5/src/Sentry/Protocol/SentryException.cs#L44) on it. And the `SentryEvent` class in the .NET SDK has a SentryExceptions property as well as an Exception property. 

I'm trying to work out, in .NET, how we should be recording all the appropriate information. My best guess is:
1. Create a new `SentryHttpClientException`
2. Leverage `SentryExceptionExtensions.SetSentryMechanism` to record details of the mechanism in that exception
3. Create a new `SentryEvent`, passing our newly created Exception in via the constructor

I suspect (but haven't gone all the way down the rabbit hole to verify) that the `SentryEvent.SentryExceptions` property would then get set when Sentry processes the event (in the [MainExceptionProcessor](https://github.com/getsentry/sentry-dotnet/blob/529a0a9168494e00c0d41de5e338987b768af0c5/src/Sentry/Internal/MainExceptionProcessor.cs#L7)). So I don't have to manually populate the `SentryEvent.SentryExceptions` right?

Is that the general flow? Maybe there's a good example of how synthetic exception events are generated somewhere else in the .NET SDK code that would be good to refer to?

**Comment by mattjohnsonpint** [comment]
> I see the .NET SDK includes a SentryException class (which is not derived from System.Exception)  ...

Correct.  `SentryException` is the model class for passing exceptions to Sentry, within a `SentryEvent`.  It's not an actual .NET Exception.

> 1. Create a new `SentryHttpClientException` ...

We don't need to create any custom exception here, because .NET already has `HttpRequestException` designed for this.  We can also just let .NET throw the exception for us, so we don't have to create a custom message.  We should still set the mechanism though.

```csharp
try
{
    response.EnsureSuccessStatusCode();
}
catch (HttpRequestException exception)
{
    exception.SetSentryMechanism(MechanismType);
    _hub.CaptureException(exception);
}
```

> I suspect ... that the `SentryEvent.SentryExceptions` property would then get set when Sentry processes the event. ... So I don't have to manually populate the `SentryEvent.SentryExceptions` right?

Correct.  We don't need to do anything special here.  Just capture the exception and let the existing SDK components do the rest.

**Comment by mattjohnsonpint** [comment]
I'll add some comments inline the draft PR also.  Thanks. 😃
