### ISSUE TITLE
System.Environment.Exit(0); causes a WatchdogTermination issue

### ISSUE THREAD

**Issue by mdima** [getsentry/sentry-dotnet#2226]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

6.0.14

### OS

iOS

### SDK Version

3.29.0

### Steps to Reproduce

- Set up a MAUI application
- Run System.Environment.Exit(0);
- The application will be closed and a WatchdogTermination issue will be reported

### Expected Result

The application just get closed. 

### Actual Result

The application get closed, and an new issue is reported.

**Comment by mattjohnsonpint** [comment]
Thanks for reporting.  I'll investigate.

**Comment by mdima** [comment]
Thanks! 
In the while I just ignore the issue.

**Comment by mattjohnsonpint** [comment]
Hey, just FYI - I haven't been able to reproduce the issue.  Can I ask, does this happen while just running in an iOS simulator? Or does it only happen on a real device?  What version of iOS are you testing on?  Are you developing on Windows or a Mac? Does it happen every time, or just intermittently?


Can you reproduce it from scratch on a new MAUI project? Or just within your own app?  If the latter, is it possible that the watchdog error is correct?  Perhaps you have other stuff going on in your app on other threads when you exit?  See https://docs.sentry.io/platforms/apple/guides/ios/configuration/watchdog-terminations/ to understand more about this detection.

If you want to turn watchdog termination detection off completely, you can do so in your config:

```csharp
.UseSentry(options =>
{
    // ... your existing options ...

#if __IOS__
    options.iOS.EnableWatchdogTerminationTracking = false;
#endif
})
```

**Comment by mattjohnsonpint** [comment]
Also, while it should work, it does feel strange to me to call `System.Environment.Exit` in a mobile app at all.  Most mobile apps I've ever used don't have any sort of exit or close button in the app itself.  Is there a particular reason you need to do so in your app?  Just curious.  Thanks.

**Comment by mdima** [comment]
Hi @mattjohnsonpint ,
  about your questions: 

- Can I ask, does this happen while just running in an iOS simulator? Or does it only happen on a real device? Real iOS device;
- What version of iOS are you testing on? 16.3.1
- Are you developing on Windows or a Mac? I am developing on Windows, linked to a Mac (macos 13.2.1, XCode 14.2);
- Does it happen every time, or just intermittently? Every time, very punctual.

Probably "System.Environment.Exit(0)" it is a bit too much "rude" and triggers the watchdog, it totally makes sense. Before that I was calling the "App.Current.Quit();" instruction, but it did not work on iOS, the app was still running after that command. 
About other tasks,  

About the question "why"? Eh, you're right, closing an app is not so usual... it is just a request from the customer. Probably we will try to agree with him to remove the "close button", since it doesn't make so much sense on a mobile app. 

About the termination detection, is there any way to disable it after the initialization? In this way I would just disable the watchdog, then close the app. 
That would conserve the watchdog termination (which is useful), but avoid false positives before closing the app. 

About a test project, I created for you the attached project. Also in this case if I click on "quit" a new WatchdogTermination issue is created (the issue ID 4001590831 on my panel). 

Thanks,
Michele

[Test.Matt.Sentry.zip](https://github.com/getsentry/sentry-dotnet/files/10959277/Test.Matt.Sentry.zip)

**Comment by mattjohnsonpint** [comment]
Thanks for the sample app.  I can indeed reproduce this now, in release mode on a real device only.

Regarding your suggestion about disabling Sentry's Watchdog Termination detection just before exiting - Unfortunately there isn't a clean way to do that.  Sentry's integrations are loaded during initialization, and we don't currently have APIs for unregistering them.

Digging in a bit more, it appears that MAUI has a standard way to exit an application programmatically, which is `Application.Current.Quit()`.  However, it is not implemented for iOS.  Instead, it raises a warning, as seen [in the code](https://github.com/dotnet/maui/blob/12aa0eea435c2811319d67f4846395443cb2fad4/src/Core/src/Handlers/Application/ApplicationHandler.iOS.cs#L18):

```csharp
handler.Logger?.LogWarning("iOS does not support programmatically terminating the app.");
```

This is backed up by several comments about Apple disallowing apps deployed through the App Store to have such a feature, though it's unclear as if that is still a hard rule or not.  See https://github.com/dotnet/maui/issues/2814#issuecomment-934641621 and Apple threads linked from there.

That said, if you doing an enterprise deployment (not through the Apple App Store), there are a variety of other ways to terminate an iOS app that you could try.  I found [a great blog post about this](https://www.redbitdev.com/post/exiting-an-ios-app-with-xamarin), written for Xamarin C# - which should apply to .NET MAUI as well.

I tried them out, and the only one that didn't record a Watchdog Termination error in Sentry was `terminateWithSuccess`.  You can use it like so:

```csharp
#if IOS
    var selector = new ObjCRuntime.Selector("terminateWithSuccess");
    var application = UIKit.UIApplication.SharedApplication;
    application.PerformSelector(selector, application, 0);
#else
    Application.Current.Quit();
#endif
```

Use at your own risk.  I have no idea what other side effects it may have.  Thanks.

**Comment by mattjohnsonpint** [comment]
Just to be super clear, if you use `terminateWithSuccess` in an application you intend to publish to the Apple App Store, it likely _will_ be rejected.  See (for example) https://stackoverflow.com/a/1997665/634824

There is no _supported_ way to terminate an iOS application programatically.

**Comment by mdima** [comment]
Thank you Matt for your work and your suggestions!
