### ISSUE TITLE
Meta issue about Symbolication and Source Context

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2233]
This issue hopes to summary and collect all things related to: 
1. Symbolication (line numbers and paths done server side)
2. Source Context (through source bundle, embedded source or source link)

In December version 3.25.0 the SDK started sending `debug_meta`:
* https://github.com/getsentry/sentry-dotnet/pull/2050

With this and related changes in the backend, we got support for server side symbolication. Where clients without the `pdb` sitting next to the `exe`/`dll` get line numbers and file paths for Portable PDB format.

That also adds support for `nuget.org` and `Microsoft` symbol server. Which is now added by default to all new Sentry projects. With this, we get line numbers and paths for framework libraries. The .NET Runtime itself sends data to the `Microsoft` symbol server. Sentry SDK itself sends to `nuget.org`:
* https://github.com/getsentry/sentry/pull/44417
* https://github.com/getsentry/sentry-dotnet/pull/2166

We considered not sending `debug_meta`:
* https://github.com/getsentry/sentry-dotnet/issues/2227

On 3.29.1 through the following PR we can get source context for .NET Framework on Windows PDB (but no line numbers/path server side, see above).
* https://github.com/getsentry/sentry-dotnet/pull/2222

### Known issues

In the process we found out we don't support Windows PDBs for .NET (we do for native Windows apps):
* https://github.com/getsentry/team-stacktrace/issues/41

.NET MAUI Android specifically has a source context issues:
* ~https://github.com/getsentry/sentry-dotnet/issues/2177~ (fixed)

### AOT support

iOS runs on AOT and that's not supported at the moment (aka: MonoAOT)
* https://github.com/getsentry/sentry-dotnet/issues/2180

.NET Native AOT (new .NET AOT, not UWP ".NET Native"): Support is not required/planned yet. Shouldn't be error'ing out with processing errors, though.

* https://github.com/getsentry/sentry-dotnet/issues/2247

### SourceLink: Stack Trace Linking and Source Context

Work to rely on sourcelink to fetch sources and add as source context was done but the feature isn't completed yet. Related work:
* https://github.com/getsentry/symbolic/issues/735
* https://github.com/getsentry/symbolicator/pull/1034
* https://github.com/getsentry/rfcs/pull/74

The changes in symbolic could add the URLs to the event payload so we can  [render 'stack trace linking'](https://docs.sentry.io/product/integrations/integration-platform/ui-components/stacktrace-link/). 
Reference PRs in Sentry to add Stack Trace Linking to other platforms:
* https://github.com/getsentry/sentry/pull/42117
* https://github.com/getsentry/sentry/pull/42167
* https://github.com/getsentry/sentry/pull/41936

We can send sourcelink information from the client, without the need to upload symbols. This will reach a lot more devs since setting up symbol upload is still not in the main onboarding process.
Experiment done in 2019:
* https://github.com/getsentry/sentry-dotnet/pull/230
* https://github.com/getsentry/sentry-dotnet/issues/400

**Comment by mattjohnsonpint** [comment]
Update:

Source link is fully working for frames marked `"in_app": true`.  However, we mostly _need_ source link to work for system frames, not in-app frames.  New issue opened to track this change request in Symbolicator:

https://github.com/getsentry/symbolicator/issues/1214

**Comment by jamescrosswell** [comment]
@bruno-garcia it looks like the only stuff left on the list is related to AOT, which I think would have to wait until v4.0 right? 

Can we close this meta issue?
