### ISSUE TITLE
Support for Crons on Hangfire 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2239]
### Problem Statement

Crons is in Beta: https://docs.sentry.io/product/crons/

Other SDKs:
* Celery beat PR: https://github.com/getsentry/sentry-python/pull/1935
* Laravel: https://github.com/getsentry/sentry-laravel/pull/659

### Solution Brainstorm

Spec is pending, this can be on hold until then.

@kanadaj already created something for Hangfire (and Quartz) that can be brought in or used as inspiration: https://github.com/kanadaj/Sentry.Monitor

**Comment by mattjohnsonpint** [comment]
Hangfire is mostly about fire-and-forget background tasks.  We'd be mostly interested their recurrent tasks feature.
https://docs.hangfire.io/en/latest/background-methods/performing-recurrent-tasks.html

We should also look at [Quartz.NET](https://www.quartz-scheduler.net/), which is primarily aimed at scheduling.

Also, there are several cloud-based schedulers offered by Azure, AWS & GCP - but I think those should be broader initiatives, not specific for .NET.

**Comment by mattjohnsonpint** [comment]
Also, this has already been started externally, by @kanadaj at https://github.com/kanadaj/Sentry.Monitor

**Comment by bruno-garcia** [comment]
I use it as a recurring job runner on: https://github.com/dotnet/nuget-trends and plan to dogfood there

**Comment by bruno-garcia** [comment]
Deleted Quartz from the title. Lets scope this to Hangfire only. if there's demand for Quartz we can create another issue and track separately.

**Comment by kanadaj** [comment]
@bruno-garcia My implementation already has both Quartz and Hangfire and seems to work fine unless the API changes for some reason.

**Comment by bruno-garcia** [comment]
> @bruno-garcia My implementation already has both Quartz and Hangfire and seems to work fine unless the API changes for some reason.

Edited the title to note that your code has both and we can talk about moving it in to this repo 🙏 Thanks!

**Comment by kanadaj** [comment]
For recordkeeping, if we want to make these more generic libraries (Sentry.Hangfire and Sentry.Quartz) we'd probably want to also add facilities for tracing the jobs. This could be done for non-recurring jobs too.

**Comment by bruno-garcia** [comment]
Related to Crons (but not Hangfire, an alternative): https://www.nuget.org/packages/ncrontab

**Comment by pinkpawkitty** [comment]
> Deleted Quartz from the title. Lets scope this to Hangfire only. if there's demand for Quartz we can create another issue and track separately.

For reference, I'd love to have an implementation for Quartz.

**Comment by bruno-garcia** [comment]
> > Deleted Quartz from the title. Lets scope this to Hangfire only. if there's demand for Quartz we can create another issue and track separately.
> 
> For reference, I'd love to have an implementation for Quartz.

* https://github.com/getsentry/sentry-dotnet/issues/3150

**Comment by kanadaj** [comment]
@bruno-garcia @pinkpawkitty The repo linked from me includes both Hangfire and Quartz support
