### ISSUE TITLE
Asynchronous version of SentrySdk.CaptureException

### ISSUE THREAD

**Issue by georgehemmings** [getsentry/sentry-dotnet#2271]
### Problem Statement

Do you plan on adding a SentrySdk.CaptureExceptionAsync version of SentrySdk.CaptureException?

**Comment by mattjohnsonpint** [comment]
No.   That would be counterproductive, as our SDK is already asynchronous internally.

When you call `CaptureException`, it generates the event to send to Sentry - but does not directly send it.  Instead, it is added to an internal queue.  A separate background worker reads from that queue to send those events to Sentry.

In other words, _capturing_ is a non-blocking operation - so it would not benefit from being async.

Thanks for the question though!
