### ISSUE TITLE
Consistent transaction name in ASP.NET Core projects

### ISSUE THREAD

**Issue by SeanFeldman** [getsentry/sentry-dotnet#2276]
A transaction name with ASP.NET Core should follow the following structure: `HTTP-VERB /path`.

For example, for a controller, resulting in a URL https://localhost/UserStatus/GetCurrentStatus

```
[ApiController]
[Route("[controller]")]
public class UserStatusController : ControllerBase
{
    [HttpGet]
    [Route("[action]")]
    public Task<string> GetCurrentStatus(string userId)
    {
        throw new Exception("oops");
    }
}
```

The transaction name should be **`GET /UserStatus/GetCurrentStatus`**, not `GET UserStatus/GetCurrentStatus`.

For an endpoint, resulting in a URL https://localhost/sad-endpoint

```
// program.cs, minimal API with .NET 6
app.MapGet("sad-endpoint/", _ => throw new Exception("oy vey"));
```

The transaction name should be **`GET /sad-endpoint`**, not `GET sad-endpoint/` as it is today.

The inconsistent naming is happening with Sentry.AspNetCore 3.29.1

**Comment by mattjohnsonpint** [comment]
I agree this should be consistent, and the leading slash should definitely be there.  I'm not so sure about the trailing slash.

Our developer docs shows a slash on both ends:
https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations

The screenshot in our product docs shows transactions from other SDKs with the leading slash, but not the trailing slash
https://docs.sentry.io/product/performance/

Either way, changing them from whatever they presently are would affect issue grouping for the majority of users, so we'll need to wait until a major release (v4.0) to make this change.

Thanks!
