### ISSUE TITLE
`HashCode` polyfills can be replaced with a reference to `Microsoft.Bcl.HashCode`

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#2279]
Seeing as there's ✨ innovation ✨ in the polyfill space recently, I decided to point out a small improvement.

When I added polyfill for the `HashCode` class in late 2019, there was no official compatibility package for it yet:

https://github.com/getsentry/sentry-dotnet/blob/da1fea7ba19aabc2817557639f17560fd7e3614f/src/Sentry/Internal/Polyfills.cs#L3-L30

However, now there is: https://www.nuget.org/packages/Microsoft.Bcl.HashCode

So you may consider adding a reference to that instead.

**Comment by mattjohnsonpint** [comment]
Thanks for letting me know about that.  I'd rather not add another package dependency.  Looking closer, we currently only have one call to `HashCodeCombine`, so I'll just inline it instead of having it in polyfills.

**Comment by mattjohnsonpint** [comment]
FYI, I ended up putting it back in #2283 - because we'll want to use it in a few places in upcoming work, such as #2206.

I did find that the implementation can be simplified, since we have `System.ValueTuple` available (transitive dependency of `System.Text.Json`), we can do `(value1, value2).GetHashCode()`.

**Comment by Tyrrrz** [comment]
> (as a transitive dependency of `System.Text.Json`)

I know it's unlikely to happen, but I'd recommend not relying on the presence of transitive dependencies. You'll end up getting a run-time type error on existing versions of your package if `System.Text.Json` ever decides to no longer depend on `System.ValueTuple` in a future version.
