### ISSUE TITLE
Unused mechanism fields

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2290]
### Problem Statement

Reference: https://develop.sentry.dev/sdk/event-payloads/types/#mechanism

Compare to our [`Mechanism`](https://github.com/getsentry/sentry-dotnet/blob/8093e26ecbd805d32a59b5708ef6772056b3d791/src/Sentry/Protocol/Mechanism.cs) class:

- `Description` is defined but unused
- `Data` is defined but unused
- `Meta` is defined but unused
- `Synthetic` is not defined

### Solution Brainstorm

- `Description` can be populated with a short description of the integration that caught it.  This will help users.
- `Data` can be used for the `Exception.Data` (see #2289)
- `Meta` we can't really use it presently.
  -  We _could_ consider updating Sentry to use this for `Exception.HResult` and/or `Win32Exception.NativeErrorCode`, but it would need a new meta key.  None of the current ones are compatible.
- `Synthetic` should be added to our class.

Even if unused, both `Meta` and `Synthetic` should be defined for purposes of serialization compatibility with native SDKs.

**Comment by codecat** [comment]
I'm interested in displaying `Win32Exception.NativeErrorCode` on the Sentry web interface, was this implemented as part of the referenced PR, or can it currently not be done?

**Comment by bitsandfoxes** [comment]
The error code does get captured in both `handled` and `unhandled` exceptions.
<img width="928" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/25725783/5a20b67a-499f-4d1a-a0eb-08896b8c0e13">
Please let us know if something does not work as expected.

**Comment by codecat** [comment]
I would have expected the numeric error to appear as part of the "mechanism" and "handled" fields. For example, when the error is not unknown, you will only see the description. Having the number available too can help avoid a case where you need to manually look up the number if an exception needs to be handled in a specific way.

**Comment by bitsandfoxes** [comment]
Good catch. It's not adding it to the mechanism but it does render the message for known status codes.
<img width="652" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/25725783/8427316f-c62f-4249-b343-0cb025b75465">
<img width="928" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/25725783/1fdc6a6c-f4b0-44ec-942b-b0db4e7288e5">

**Comment by bitsandfoxes** [comment]
Ah, I see what you mean. The number `additionally` to the message. Let me see what I can find out.
