### ISSUE TITLE
Improve Sentry CLI messages

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2307]
> I am trying to upload some debug / source data from a docker build /w NuGet sentry-cli (which I authed with token, logs are OK) and I see a weird ie. non informant msg:

> PENDING 8..guid (MyProj.pdb; unknown sources)

From: https://twitter.com/vekzdran/status/1648015516517146656

**Comment by bruno-garcia** [comment]
I imagine it's: https://github.com/getsentry/sentry-cli/blob/dc499b14344dbd660e69e56d6ce806e5170260f7/src/utils/file_upload.rs#L365

@mattjohnsonpint @Swatinem or @vaind might be able to confirm

**Comment by mattjohnsonpint** [comment]
Yep.  This is normal.  I'll reply to the twitter thread.

**Comment by mattjohnsonpint** [comment]
Breaking this down a bit:

### Debug file upload shows `PENDING` in the output

This means the file upload has succeeded, and is _pending_ processing by Sentry.  If desired, one could add `<SentryCLIOptions>--wait</SentryCLIOptions>` to change this behavior, though I don't recommend it.  See https://docs.sentry.io/product/cli/dif/#upload-options

It might be better if Sentry CLI said something like "SENT" or "ACCEPTED", as "PENDING" makes it seem like there's something that wasn't correctly done client-side.

### Debug file shows `unknown sources`

This is normal for .NET assemblies that aren't compiled for a specific architecture.  In other words, if you aren't explicitly setting `x86`, `x64`, or `arm64`, then there is no architecture.  Visual Studio uses the terminology "Any CPU", but Sentry CLI (via Symbolic) uses the term "unknown".   This makes it seem like something is wrong when it isn't.  For .NET assemblies and pdbs, that string should probably just be omitted.

"sources" means the source bundle was included.  That's controlled by `<SentryUploadSources>true</SentryUploadSources>`.  It's only when strung together as "unknown sources" that it seems like something is wrong.  It would be better if Sentry CLI used commas to separate the types of data included in the debug file.

All of these issues are either with Sentry CLI or Symbolic.  We can keep this issue open to track how they affect .NET, but ultimately they need to be resolved in those respective projects.

**Comment by vaind** [comment]
> It might be better if Sentry CLI said something like "SENT" or "ACCEPTED", as "PENDING" makes it seem like there's something that wasn't correctly done client-side.

`Sent` would make sense, `Accepted` not really because at the time I think.

There's a `--wait` option that might be useful exposing.

**Comment by mattjohnsonpint** [comment]
Right. you can pass that with `SentryCLIOptions` today.  I could add another more-specific MSBuild parameter for it though, if folks would use it.

**Comment by vmandic** [comment]
Thank you so much for clarifying @mattjohnsonpint 🤝 and @bruno-garcia for opening the thread here.

Guess I need to specify the arch in my `dotnet publish` during my CI build then.

**Comment by mattjohnsonpint** [comment]
@vmandic - I wouldn't create an architecture-specific build just for the sake of changing the `unknown` message in the build logs.  That's our problem to fix not yours. 😅 

In most cases, .NET defaults to architecture-neutral builds.  You should only be more specific when you need to, such as when your app/library bundles a native library compiled for a specific architecture.

**Comment by mattjohnsonpint** [comment]
Also, feel free to chat with us on [Sentry's Discord server](https://open.sentry.io/) any time.  We hang out on the `#dotnet` channel.

**Comment by mattjohnsonpint** [comment]
Upstream issue: https://github.com/getsentry/sentry-cli/issues/1583

**Comment by vmandic** [comment]
Thank you so much once again, wanted to ping just to brighten your day a bit. Works / looks great now.

![Image](https://github.com/user-attachments/assets/5754035c-b3bd-480d-9255-3d470c85bd1d)
