### ISSUE TITLE
Add integration to  TaskScheduler.UnobservedTaskException

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#231]
Pretty much a copy paste of the `UnhandledException` integration:

https://github.com/getsentry/sentry-dotnet/search?q=UnhandledException&unscoped_q=UnhandledException

Subscribe automatically as it's done with UnhandledException right now.

**Comment by lucas-zimerman** [comment]
@bruno-garcia  you can mark this issue as closed.

**Comment by bruno-garcia** [comment]
Thanks @lucas-zimerman !
