### ISSUE TITLE
API docs are broken

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2313]
API documentation is missing from https://getsentry.github.io/sentry-dotnet/api/index.html

Also the other pages that are there should probably be moved to the [main docs](https://docs.sentry.io/platforms/dotnet/) or deleted.

**Comment by bruno-garcia** [comment]
> Also the other pages that are there should probably be moved to the [main docs](https://docs.sentry.io/platforms/dotnet/) or deleted.

That was added before we had .NET docs back in 2018 😅

**Comment by bruno-garcia** [comment]
Removed references to it from the readme until this is resolved: https://github.com/getsentry/sentry-dotnet/commit/5c549d15aca8f6b12e6b500c531bc267d25e5ee3

**Comment by bruno-garcia** [comment]
API docs are still broken btw: https://getsentry.github.io/sentry-dotnet/api/index.html

New versions are published:  https://github.com/getsentry/sentry-dotnet/deployments/github-pages but no API stuff, just some [old docs before we had .NET in docs.sentry.io](https://getsentry.github.io/sentry-dotnet/manual/log4net.html) we should remove.

I noticed that we can link to API docs now from docs.sentry.io: 
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/d10e252a-ad6f-4f7d-b688-b0d89995cb8c)

Once fixed, we should link to it too

**Comment by jamescrosswell** [comment]
I'm not super clear on what should be documented at https://getsentry.github.io/sentry-dotnet/api/index.html. 

The main docs are at https://docs.sentry.io/platforms/dotnet/ and I'm guessing those stay put. 

Should getsentry.github.io be removed entirely? Or is this where docs generated from XML in the source code would go? Would anyone ever want to read that like a book? I think that stuff is more for getting contextual help in an IDE... not sure there's much value in trying to turn it into anything more structured.

**Comment by jamescrosswell** [comment]
Doesn't seem like a quick fix. 

My guess is it would take me a day or two to familiarize myself with DocFX and work through whatever it's issues are. It might be quicker for someone who's already worked a lot with DocFX. 

I'm not sure how much value these docs add. The XML docs are great context in an IDE, but don't translate well to structured documentation. I think we should remove them entirely and use our [main docs](https://docs.sentry.io/platforms/dotnet/) instead. 

I might be biased though 😜

**Comment by bruno-garcia** [comment]
> I think we should remove them entirely and use our [main docs](https://docs.sentry.io/platforms/dotnet/) instead.

We don't document out APIs at all there. Only a sub-set of the options

**Comment by bruno-garcia** [comment]
We should at least remove them if not going to fix it.
