### ISSUE TITLE
Bring `Sentry.Profiling` into `Sentry`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2314]
Our goal is to have all the profiling work available with `Sentry` without adding any dependencies. That's because Profiling is part of Performance and installing Sentry should give you errors and performance without complex installation steps, packages, etc.

We only need this as we get close to releasing GA. No need to do it during alpha/beta.

A few suggestions on how to tackle that:

## Using git submodule

We have a similar approach with `Ben.Demystifer`.

1. Add a submodule for the dependencies https://github.com/getsentry/sentry-dotnet/blob/1cf825cd42aa430df4ee827a1f4340b5307c9f1b/src/Sentry.Profiling/Sentry.Profiling.csproj#L14-L15
in https://github.com/getsentry/sentry-dotnet/tree/1cf825cd42aa430df4ee827a1f4340b5307c9f1b/modules
3. Change to a new branch to disable nullability `#nullable disable:` through some script (e.g [this](https://github.com/getsentry/sentry-dotnet/blob/1cf825cd42aa430df4ee827a1f4340b5307c9f1b/modules/make-internal.sh))
4. Include relevant `C#` files. See: https://github.com/getsentry/sentry-dotnet/blob/1cf825cd42aa430df4ee827a1f4340b5307c9f1b/src/Sentry/Sentry.csproj#L33-L46

## Fixing upstream and shipping a second package

Problem here is the more complex installation steps since we'd have dependencies

**Comment by mattjohnsonpint** [comment]
Many of those warnings are coming from `Roslynator.Analyzers`, which we add in the root `Directory.Build.props`.  

If it were kept in a separate project, you could disable it for that project with:

```xml
  <ItemGroup>
    <PackageReference Remove="Roslynator.Analyzers" />
  </ItemGroup>
```

But that approach won't work with integrating directly into `Sentry.csproj` - where we'd definitely want to keep that enabled.

A more palatable approach might be to suppress certain errors for the containing namespace.  See https://github.com/JosefPihrt/Roslynator/blob/main/docs/HowToConfigureAnalyzers.md#suppress-diagnostic-for-namespace

**Comment by mattjohnsonpint** [comment]
`AllowUnsafeBlocks` is fine.  We just need to be careful in how we use the actual `unsafe` code to ensure (for example) no memory leaks.

AFAIK, `AllowUnsafeBlocks` is constrained to the compilation of a single project, so it doesn't leak to consumers.

I would not make any public APIs that require unsafe code allowed in the _consuming_ project though.  Anything unsafe should be internal or private.

**Comment by bruno-garcia** [comment]
> AFAIK, AllowUnsafeBlocks is constrained to the compilation of a single project, so it doesn't leak to consumers.

👍 


> I would not make any public APIs that require unsafe code allowed in the consuming project though. Anything unsafe should be internal or private.

Right now I don't think that's possible due to CLSCompliant: https://github.com/getsentry/sentry-dotnet/blob/93c5fa8900b29a6a037ff3b285546b64b173f9f2/src/Sentry/Properties/AssemblyInfo.cs#L49

**Comment by bruno-garcia** [comment]
Related: https://github.com/dotnet/runtime/issues/92734

**Comment by vaind** [comment]
We've pivoted and the package is going to stay separate for now, due to adding dependencies that don't necessarily need to be on the main package. This can be revisited at a later point if/when it makes more sense.
