### ISSUE TITLE
Use System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#233]
To decide: 
* Should change be done to all targets and publish as part of 2.0?
* Should it only affect target `netcoreapp3.0`?

Blockers: Tests in `Sentry.Protocol` would first need to pass using `System.Text.Json`.
At this point blocked by https://github.com/dotnet/corefx/issues/38758

PR to update `Sentry.Protocol` [is here](https://github.com/getsentry/sentry-dotnet-protocol/pull/42).

**Comment by Tyrrrz** [comment]
This makes sense to do after .NET 5 because System.Text.Json is very lackluster for full serialization/deserialization scenarios right now.

**Comment by bruno-garcia** [comment]
For a next major, I'd be happy to replace the attributes and just get it working with `System.Text.Json`.

for the `net5.0` target it would mean 0 dependency (maybe ns2.1 too?) which would be great see; #498 

Note that we dont' have deserialization (yet) it'll come soon because of envelopes, caching, rate limit, etc.

**Comment by bruno-garcia** [comment]
Also worth noting we'll need support to hold unmapped keys somehow into the object.

This is to support a round trip serialization of a format in a different version (with new/unknown keys)

**Comment by Tyrrrz** [comment]
@bruno-garcia this is done.
