### ISSUE TITLE
Log to sentry doesn't work without addMvc()

### ISSUE THREAD

**Issue by staticdev** [getsentry/sentry-dotnet#236]
I am using the following dependency versions:

```
<PackageReference Include="Sentry.AspNetCore" Version="1.2.0" />
<PackageReference Include="Sentry.Serilog" Version="1.2.0" />
<PackageReference Include="Serilog" Version="2.8.0" />
<PackageReference Include="Serilog.Extensions.Logging" Version="2.0.4" />
<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

I am creating a Log in Startup.cs:

```csharp
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;

            Log.Logger = new LoggerConfiguration()
             .WriteTo.Console()
             .WriteTo.Sentry("mydsn")
             .Enrich.FromLogContext()
             .CreateLogger();
        }
```

Exceptions stop being logged to Sentry if I comment from Startup.cs the lines:
`//services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);`
```csharp
/*app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "/{controller=Home}/{action=Index}/{id?}");
            });*/
```

 Is there any workaround for not using Mvc?

This does not occur in https://github.com/olsh/serilog-sinks-sentry (but this lib has other problems).

**Comment by bruno-garcia** [comment]
Sounds like a big. It works without AddMvc https://github.com/getsentry/sentry-dotnet/tree/master/samples/Sentry.Samples.AspNetCore.Basic

Could you please provide a repro so I can debug it through?
Also, you can enable Debug on the SDK to see the SDK logs.

**Comment by bruno-garcia** [comment]
Closing since there was no reply. If this is still an issue, feel free to reopen.
