### ISSUE TITLE
Update .NET docs to use SetBeforeSend in code samples

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2383]
Currently the docs for things [like filtering](https://docs.sentry.io/platforms/dotnet/configuration/filtering/) demonstrate use of the obsolete `SentryOptions.BeforeSend` property. These need to be updated to use the newer `SetBeforeSend` method instead.

Other examples may exist - probably best to run _find in files_ or something across a local clone of the doc repository.

**Comment by bitsandfoxes** [comment]
Resolved in https://github.com/getsentry/sentry-docs/pull/7477
