### ISSUE TITLE
95 .Net system dll's in build folder

### ISSUE THREAD

**Issue by BusinessSupportVeenendaalDevelopment** [getsentry/sentry-dotnet#239]
When adding the "Sentry" nuget and build my project it adds 95 system .dll's, why is that
I am using .net 4.6.1 winforms

![image](https://user-images.githubusercontent.com/48724734/60713120-b9fe6800-9f18-11e9-91fc-06e9a7197ec0.png)

**Comment by bruno-garcia** [comment]
All Sentry's NuGet package multi-target `.NET Standard 2.0` and `.NET Framework` to avoid the .NET Standard 1.x dependency tree issue. This is quite strange.
Could you please provide a small repro so we can debug this build?

**Comment by BusinessSupportVeenendaalDevelopment** [comment]
[SentryBug.zip](https://github.com/getsentry/sentry-dotnet/files/3362075/SentryBug.zip)

Thanks for the quick response, in the attachment you can see the test project
All I did was create a new project in visualstudio professional 2017, select "Visual C#", "Windows Desktop", "Windows Forms App (.Net Framework)" "Framework: .NET Framework 4.6.1" and add the "Sentry" nuget

**Comment by bruno-garcia** [comment]
The issue happens if you target .NET Framework 4.6.1. 
If you re-target to .NET 4.7.2 or 4.8 the DLLs are no longer copied.
The package `Sentry.PlatformAbstractions` has a build for .NET 4.5 and one for 4.7.1 and the first depends :

<img width="552" alt="image" src="https://user-images.githubusercontent.com/1633368/60718830-1ddb5d80-9f26-11e9-9458-da737d78a4b7.png">

This is not really a Sentry bug as it is a .NET dependency resolution one. This happened with the .NET Standard 1.x packages and multi targeting to .NET 4.6.1 supposed to have fixed it but if you pack for 4.7.2 it's fixed.

**Comment by CADbloke** [comment]
Explained here: https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies/47366401#47366401

My fix: 
## Step 1 - in your CSPROJ file ...
```xml
<!--https://stackoverflow.com/questions/2387456/msbuild-exec-task-without-blocking/21181071#21181071-->
  <!--Launch a Process in Parallel-->
  <UsingTask TaskName="ExecAsync" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <!--The file path is the full path to the executable file to run-->
      <FilePath ParameterType="System.String" Required="true" />
      <!--The arguments should contain all the command line arguments that need to be sent to the application-->
      <Arguments ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs"><![CDATA[
  System.Diagnostics.ProcessStartInfo processStartInfo = new System.Diagnostics.ProcessStartInfo(FilePath, Arguments);
  processStartInfo.UseShellExecute = true;
  System.Diagnostics.Process.Start(processStartInfo);
  ]]></Code>
    </Task>
  </UsingTask>
  <Target Name="AfterBuild">
    <ExecAsync FilePath="$(ProjectDir)\Deployment\DeleteSuperfluousSystemDlls.cmd" Arguments="$(TargetDir)" />
  </Target>
````

## Step 2. The batch file ...

[DeleteSuperfluousSystemDlls.txt](https://github.com/getsentry/sentry-dotnet/files/3430177/DeleteSuperfluousSystemDlls.txt)

## Step 3
Figure out what you shouldn't have deleted. Oops. Chek your project references, every project is different

**Comment by bruno-garcia** [comment]
Closing this since there's nothing we can do about it. We already support .NET Framework targets for the sole reason of simplifying dependency resolution.

Also, we'll be dropping all pre-new461 targets soon (on version 3.0)
