### ISSUE TITLE
Expose the current IHub as a public property

### ISSUE THREAD

**Issue by saul** [getsentry/sentry-dotnet#240]
Hi

I'm using the `Sentry` NuGet package, and I'm struggling to get access to the current `IHub`. It's available on `SentrySdk._hub` as a private static - why is this not public? Am I completely misunderstanding how to use IHub?

Thanks

**Comment by bruno-garcia** [comment]
@saul The current hub can be accessed via `SentrySdk` static methods.
If you need to use dependency injection, you'd depend on `IHub` and register with your container the accessor: `HubAdapter.Instance`.

Other than that I'd be interested in what is your use case. What are you trying to do?

If you need to configure the scope that the current `Hub` holds, you can do:

```csharp
SentrySdk.ConfigureScope(s => s.SetTag("..", ".."));
```

**Comment by saul** [comment]
I was looking for `HubAdapter.Instance` - sorry I didn't see it mentioned in the docs anywhere.

Thanks

**Comment by bruno-garcia** [comment]
No problem.
