### ISSUE TITLE
Logging configuration not passed to logger on .NET MAUI

### ISSUE THREAD

**Issue by jenscski** [getsentry/sentry-dotnet#2422]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Android

### SDK Version

8.0.100

### Steps to Reproduce

I'm testing with Sentry and the logger provider, but it seems that the configuration for the logger is not respected when I'm using the maui spesific UseSentry (`public static MauiAppBuilder UseSentry(this MauiAppBuilder builder, Action<SentryMauiOptions>? configureOptions)`)

When changing the MinimumEventLevel, MinimumBreadcrumbLevel  or adding filter using AddLogEntryFilter, they are not used in the logging implementation.

If I add the logging manually using 
```
logging.AddSentry(options =>
{
    options.MinimumBreadcrumbLevel = LogLevel.Error,
    options.MinimumEventLevel = LogLevel.Error,
});
````

the configuration is as expected

### Expected Result

That the logging configuration should be used when using the Maui spesific UseSentry

### Actual Result

The logging configuration is not respected ...

**Comment by mattjohnsonpint** [comment]
Thanks for reporting this.  I was able to reproduce the problem on 3.31.1 (latest).  We'll have a fix in the next release.
