### ISSUE TITLE
Add migration guide for SharpRaven

### ISSUE THREAD

**Issue by mrmonday** [getsentry/sentry-dotnet#243]
We currently use the legacy [SharpRaven nuget package](https://www.nuget.org/packages/SharpRaven), and are looking to migrate.

Some things that are not immediately obvious from reading the documentation (my apologies if I've missed this information):

 * What is the replacement for [SentryUserFactory](https://github.com/getsentry/raven-csharp/blob/678d83f8784f107bcb4acf6439aaee50fe4f8f5e/src/app/SharpRaven/Data/SentryUserFactory.cs)?
 * Is ASP.NET (Framework) integration supported?
 * What is the replacement for [LogScrubber](https://github.com/getsentry/raven-csharp/blob/678d83f8784f107bcb4acf6439aaee50fe4f8f5e/src/app/SharpRaven/Logging/LogScrubber.cs)?
 * What is the recommended way to move away from [RavenClient](https://github.com/getsentry/raven-csharp/blob/678d83f8784f107bcb4acf6439aaee50fe4f8f5e/src/app/SharpRaven/RavenClient.cs)? Currently we create a global instance at application startup, and use this throughout. With `SentrySdk.Init()`, all the examples use a `using` statement - should we initialise whenever we log an exception, or continue using a global instance and disposing on application shutdown?

**Comment by bruno-garcia** [comment]
Fair point. It's overdue actually.
I'll address your points here but I'll get something on `docs.sentry.io` after that:

> What is the replacement for SentryUserFactory?

For ASP.NET Core, you'd just register [`IUserFactory`](https://github.com/getsentry/sentry-dotnet/blob/16ec03e04ecdbfc452c76f20cd8224c660597f01/src/Sentry.AspNetCore/IUserFactory.cs) in the container. That'll replace the [DefaultUserFactory](https://github.com/getsentry/sentry-dotnet/blob/16ec03e04ecdbfc452c76f20cd8224c660597f01/src/Sentry.AspNetCore/DefaultUserFactory.cs) Sentry's SDK registers. There's no `UserFactory` for ASP.NET classic at the moment. If you'd need that, [we'll need to add it here](https://github.com/getsentry/sentry-dotnet/blob/5e467299cde43c3133062aa8c5bafa869bc48b42/src/Sentry/Internal/Web/SystemWebRequestEventProcessor.cs).

> Is ASP.NET (Framework) integration supported?

Yes. When an exception goes out we look for the static `HttpContext.Current` and read the request data into the event. The [code for populating the event is this](https://github.com/getsentry/sentry-dotnet/blob/5e467299cde43c3133062aa8c5bafa869bc48b42/src/Sentry/Internal/Web/SystemWebRequestEventProcessor.cs#L57). We have an internal abstraction over HttpRequest [which includes an adapter to System.Web's](https://github.com/getsentry/sentry-dotnet/blob/5e467299cde43c3133062aa8c5bafa869bc48b42/src/Sentry/Internal/Web/SystemWebHttpRequest.cs).

> What is the replacement for LogScrubber?

It's creating [an `IEventProcessor`](https://github.com/getsentry/sentry-dotnet/blob/5e467299cde43c3133062aa8c5bafa869bc48b42/src/Sentry/Extensibility/ISentryEventProcessor.cs). With that you can modify the event, returns a new instance, or drop the event altogether (return null).
In ASP.NET Core you just register as many `ISentryEventProcessor` as you want`. In other environments you can add an instance to the options:

```csharp
SentrySdk.Init(o =>
{
   o.AddEventProcessor(new MyEventProcessor());
});
```

You can also do that with the `BeforeSend` callback (defined in the options) which is a simply `Func<SentryEvent, SentryEvent>`.

> What is the recommended way to move away from RavenClient? Currently we create a global instance at application startup, and use this throughout. With SentrySdk.Init(), all the examples use a using statement - should we initialise whenever we log an exception, or continue using a global instance and disposing on application shutdown?

The `Init()` method returns a `IDisposable` which you can hold on to for the whole lifetime of the app. Calling `Dispose` on it will ensure we drain the queue before your apps shuts down. You can also call `SentrySdk.Close()`.

**Comment by mrmonday** [comment]
Thanks for your quick, and thorough, response.

> There's no UserFactory for ASP.NET classic at the moment. If you'd need that, we'll need to add it here.

Shall I open another issue for this?

> It's creating an IEventProcessor.

So we should write our own logic for scrubbing credit card/phone data? This was included directly in SharpRaven.

> Calling Dispose on it will ensure we drain the queue before your apps shuts down.

Is there a way to ensure the queue is drained earlier/ensure events are sent synchronously? That is, without disposing the object returned from `Init()`.

**Comment by mrmonday** [comment]
>> Shall I open another issue for this?
>
> Please feel free. Hasn't been requested yet.

Done - #244 

> We have that scrubbing on the server.

This won't cut it for cardholder data - for PCI-DSS compliance we cannot send Sentry cardholder data. There shouldn't be any such data in exceptions anyway, but it needs to be filtered on our side just in case.

Again, thanks for your response.

**Comment by bruno-garcia** [comment]
Lets finally tackle this, it's been too long.

The task should:

- [ ] Create a migration page in the docs such as (https://docs.sentry.io/platforms/react-native/migration/)
- [ ] To simplify, it can be a single file on the `dotnet` level and there we note migration for any integration like ASP.NET
- [ ] First entry will be titled: _Migrating from `SharpRaven` to `Sentry`_ and it should include:
* Note the minimum .NET Framework version required: SharpRaven can run on .NET Framework 3.5 or later. `Sentry` on the other hand only support .NET Framework 4.6.1 and later.
* How to Init the SDK. How to Init it for ASP.NET (install the package and `AddAspNet`).
* Events are sent in the background. The `IDisposable` returned from `Init` needs to be invoked before the problem exists. On ASP.NET classic, mention `Sentry.AspNet` must be installed to get HTTP related information.
* A series of: Before: `await client.CaptureAsync(..)` After: `SentrySdk.CaptureEvent(..)` (the event will be sent on a background thread and so it'll not block the calling thread. The SharpRaven approach would not block the thread but only continue your code (i.e: return the HTTP request) once the SDK communicated with Sentry which was suboptimal.
* Before: `client.Capture(..)` After: `SentrySdk.CaptureEvent(..)` 
* Before:
```
ravenClient.BeforeSend = requester =>
{
    // Here you can log data from the requester
    // or replace it entirely if you want.
    return requester;
};
```
After:
```
SentrySdk.Init(o => o.BeforeSend = e {
// Mutate the event or return null to drop it altogether
}
```

This should be a good start ^

**Comment by Tyrrrz** [comment]
https://github.com/getsentry/sentry-docs/pull/3401

**Comment by bruno-garcia** [comment]
Docs are live: https://docs.sentry.io/platforms/dotnet/migration/#migrating-from-sharpraven-to-sentry-sdk
