### ISSUE TITLE
Transaction name not reporting correctly when using UseExceptionHandler(string errorHandlingPath)

### ISSUE THREAD

**Issue by goelze** [getsentry/sentry-dotnet#2433]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

7.0.5

### OS

macOS

### SDK Version

3.33.1

### Steps to Reproduce

1. With an ASP.NET Core MVC project, configure the pipeline with `UseExceptionHandler("/errors")` somewhere before `MapDefaultControllerRoute`.
2. Create the controller `ErrorsController` with an action `Index` that returns a view.
3. In some other controller action, throw an exception.

I have a minimal project to reproduce here: https://github.com/goelze/sentry-error-example

### Expected Result

If the exception was thrown in the Index action on the HomeController, the expected transaction name reported in Sentry should be `GET /Home/Index/{id?}`

### Actual Result

The actual transaction name is `GET /Errors/Index/{id?}`
![sentry error screenshot](https://github.com/getsentry/sentry-dotnet/assets/1897512/fd8f68ff-3a0c-43f4-b0d3-b3afdcceef85)

**Comment by goelze** [comment]
I'm not sure if I have something configured incorrectly here, but most of our errors on our main project report the transaction as `METHOD Errors/Index/{id?}`

The `UseExceptionHandler(string)` method re-executes the request using the provided `errorHandlingPath` after catching an exception. Not sure of the best solution, but the `IExceptionHandlerFeature` provides the path, endpoint, and route values of the original request, which could be used to construct the correct transaction name.

**Comment by jamescrosswell** [comment]
Hey @goelze thanks heaps for the example project. I can reproduce this so we should be able to fix it. 👍🏻
