### ISSUE TITLE
Baggage propagation doesn't seem to work when Exception captured in middleware

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2441]
I'm updating NuGet Trends with the latest JavaScript (Angular) and .NET SDKs.

One of the things since the last update is the introduction of this feature: https://changelog.getsentry.com/announcements/connect-session-replays-to-backend-errors

Unfortunately it doesn't seem to work:

I throw an exception from my C# controller, but only the Frontend error shows on the Replay: 
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/c279ce77-fb9c-4e38-a484-d6f9d42dfbd7)

Using the Replay Network details to capture the `baggage` header, I can confirm the JS SDK is sending it:

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/1cd1e9f7-791a-4c00-8ad9-01017250637a)

Value (from [replay](https://nugettrends.sentry.io/replays/spa:8f9bf18820be4450b62868dc460be8d8/?f_n_type=resource.xhr&n_detail_row=1&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=network&yAxis=count%28%29)):
```
sentry-environment=local,sentry-transaction=%2F,sentry-public_key=85a592e835c64ca3a97d93776c12e947,sentry-trace_id=20b4f41dc98f49e2b25b5f88ffae1901,sentry-sample_rate=1,sentry-replay_id=8f9bf18820be4450b62868dc460be8d8
```

The exception captured by the .NET SDK included the envelope header:

```
[23:11:08 DBG] Envelope 'c0736a5e8f594176a65a9c0129b05cdd' successfully sent. Content: {"sdk":{"name":"sentry.dotnet","version":"3.33.1"},"event_id":"c0736a5e8f594176a65a9c0129b05cdd","sent_at":"2023-06-23T03:11:08.488511+00:00"}
{"type":"event","length":19132}
{"modules":{"System.Private.CoreLib":"7.0.0.0",.....
```

Note that replay_id isn't included.

## Investigation

The PR that added support here is: 
* https://github.com/getsentry/sentry-dotnet/pull/2332

Note that we look for a Span from an exception to support the case where a transaction is closed when unwinding the stack due to an exception bubbling up. Which is the case in ASP.NET Core where the root middleware captures the exception but further in the call chain we start/stop transactions:

https://github.com/getsentry/sentry-dotnet/blob/060480e1dfb42ca2044a8445c1d8e71b84b23f73/src/Sentry/Internal/Hub.cs#L275-L290

But on this PR adding support for DSC on exceptions, we don't consider the lookup, and only expect the transaction on the scope:

https://github.com/getsentry/sentry-dotnet/blob/060480e1dfb42ca2044a8445c1d8e71b84b23f73/src/Sentry/Internal/Hub.cs#L163-L166

I tried to validate that by not throwing from the controller, but instead just calling `CaptureMessage`. With a transaction on the scope, thing should work. That wasn't the case.

The exception included the DSC details, but no `replay_id`:

```
[23:44:21 DBG] Envelope '60ce0fe4d9294f27acbb429d3a7c858f' successfully sent. Content: {"sdk":{"name":"sentry.dotnet","version":"3.33.1"},"event_id":"60ce0fe4d9294f27acbb429d3a7c858f","trace":{"trace_id":"0c6188d56e9e49ffba45e31e5b697b3c","public_key":"57331596a25b4c3da49750b292299e09","sample_rate":"1","release":"NuGetTrends.Web@1.0.0\u002Ba678a0d59db0bcef71578b7c341c10c48ac5c80f","environment":"development","transaction":"GET api/package/history/{id}"},"sent_at":"2023-06-23T03:44:21.916599+00:00"}

```

**Comment by jamescrosswell** [comment]
Quick update: Currently trying to get [a javascript app that will send trace headers](https://github.com/getsentry/sentry-javascript/discussions/8461)... then will try to reproduce this. Have tried with Svelte and React so far... will try with Angular I guess (I probably should have started there).

**Comment by jamescrosswell** [comment]
@bruno-garcia I haven't been able to reproduce this. 

See [this replay](https://sentry-sdks.sentry.io/replays/javascript-angular:37af25405d7c475297ce871e8a2b5488/?project=4504961175519232)... which is a simple Angular app that makes two calls to a .NET Core app. 
1. One of the calls is to a .NET endpoint that responds with a 200 OK and some text in the body
2. The other calls is to a .NET endpoint that throws an error

And this is the [event details for the error that gets thrown in the .NET application](https://sentry-sdks.sentry.io/performance/aspnet-core:e2dce101f7cd40c693013ebac3df7f22/?n_detail_row=8&project=4504961175519232&t_main=trace&transaction=GET+%2Fthrow%2F%7Bmessage%3F%7D). 

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/6545c9ae-1a2d-46b6-aa5c-1a510ed09d2c)

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/4524203a-2498-4274-b27f-16a0f21803f0)

There's a `sentry-replay_id` in the `baggage` header and a `Sentry-Trace` header present. 

The app in question is a minor variant of the `Sentry.Samples.AspNetCore.Basic` sample in the .NET SDK, that has a CORS anything policy:

```csharp
using Microsoft.AspNetCore;

namespace Sentry.Samples.AspNetCore.Basic;

public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    private const string MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureServices(services =>
                {
                    services.AddCors(options =>
                    {
                        options.AddPolicy(name: MyAllowSpecificOrigins,
                            policy  =>
                            {
                                policy.AllowAnyHeader();
                                policy.AllowAnyMethod();
                                policy.AllowAnyOrigin();
                            });
                    });
                }
            )
            .UseSentry(o =>
            {
                // A DSN is required.  You can set it here, or in configuration, or in an environment variable.
                o.Dsn = "https://b887218a80114d26a9b1a51c5f88e0b4@o447951.ingest.sentry.io/6601807";

                // Enable Sentry performance monitoring
                o.EnableTracing = true;

#if DEBUG
                // Log debug information about the Sentry SDK
                o.Debug = true;
#endif
            })

            // The App:
            .Configure(app =>
            {
                app.UseRouting();

                app.UseCors(MyAllowSpecificOrigins);

                // Enable Sentry performance monitoring
                app.UseSentryTracing();

                // An example ASP.NET Core middleware that throws an
                // exception when serving a request to path: /throw
                app.UseEndpoints(endpoints =>
                {
                    endpoints.MapGet("/hello", context => context.Response.WriteAsync("Hey bro!"));
                    // Reported events will be grouped by route pattern
                    endpoints.MapGet("/throw/{message?}", context =>
                    {
                        var exceptionMessage = context.GetRouteValue("message") as string;

                        var log = context.RequestServices.GetRequiredService<ILoggerFactory>()
                            .CreateLogger<Program>();

                        log.LogInformation("Handling some request...");

                        var hub = context.RequestServices.GetRequiredService<IHub>();
                        hub.ConfigureScope(s =>
                        {
                            // More data can be added to the scope like this:
                            s.SetTag("Sample", "ASP.NET Core"); // indexed by Sentry
                            s.SetExtra("Extra!", "Some extra information");
                        });

                        log.LogInformation("Logging info...");
                        log.LogWarning("Logging some warning!");

                        // The following exception will be captured by the SDK and the event
                        // will include the Log messages and any custom scope modifications
                        // as exemplified above.
                        throw new Exception(
                            exceptionMessage ?? "An exception thrown from the ASP.NET Core pipeline");
                    });
                });
            })
            .Build();
}
```

**Comment by bruno-garcia** [comment]
> There's a sentry-replay_id in the baggage header and a Sentry-Trace header present.

@jamescrosswell The [event](https://sentry-sdks.sentry.io/issues/4295249777/events/8d6a4e4dd3f64433b53d4bb53da616c5/?project=6601807) you linked has a callout for Replay: 
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/a0300221-151a-40ff-96d3-6153201e9781)
It should show the replay recorded in the frontend instead. 

The replay_id in the baggage does [load up in Sentry](https://sentry-sdks.sentry.io/replays/37af25405d7c475297ce871e8a2b5488/).

**Comment by jamescrosswell** [comment]
Hm, I don't see the callout. I do see that there are `0 replays` associated with that event though:

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/3e260f4c-14af-4e13-8e29-51856ecf9a04)

If that replay id was is the envelope header then we'd expect to see it here right? It's in the baggage header but there's no specific header for replay_id so it looks like we need to make sure we're extracting it the baggage header and ensuring it sits on the envelope. 

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/09e3657f-af08-47c6-86c3-62a11034e173)

I'll see if I can get that wired up and hopefully we get more than 0 replays in the replays tab then 🙏🏻... making some (hopefully reasonable) assumptions about how the Sentry.io UI is designed.

**Comment by jamescrosswell** [comment]
OK, I think I've worked out what's going on. We have two bits of middleware: `SentryMiddleware` and `SentryTracingMiddleware`. When the later captures an exception, it [finishes the transaction](https://github.com/getsentry/sentry-dotnet/blob/5f6074d189234291c97cd55ea83ab9a353b5be9a/src/Sentry.AspNetCore/SentryTracingMiddleware.cs#L194C1-L204C18):
```
                else if (status == SpanStatus.Ok)
                {
                    transaction.Finish(exception);
                }
                else
                {
                    transaction.Finish(exception, status);
                }
```

Internally, that `Finish` method **_binds_** the transaction (which basically stores it in the Hub's internal `ExceptionToSpanMap`). `SentryTracingMiddleware` then throws the exception again.

Next the global exception handler in the `SentryMiddleware` gets activated. That creates an event from the exception and then [calls hub.CaptureEvent](https://github.com/getsentry/sentry-dotnet/blob/5f6074d189234291c97cd55ea83ab9a353b5be9a/src/Sentry.AspNetCore/SentryMiddleware.cs#L165)... which eventually ultimately executes `Hub.CaptureEventInternal`.

At this point, since the transaction has finished, the current scope no longer has a transaction associated with it and so when we [try to read the transaction off the scope and the DSC off the transaction](https://github.com/getsentry/sentry-dotnet/blob/5f6074d189234291c97cd55ea83ab9a353b5be9a/src/Sentry/Internal/Hub.cs#L365), it's nulls all the way down.

```csharp
            // When a transaction is present, copy its DSC to the event.
            var transaction = actualScope.Transaction as TransactionTracer;
            evt.DynamicSamplingContext = transaction?.DynamicSamplingContext;
```

Luckily, our `SentryTracingMiddleware` stored a map between the exception and the original span/transaction in the `ExceptionToSpanMap` and so we can get this information from there instead.

I'll put together a unit test and a fix.

**Comment by jamescrosswell** [comment]
k, I think that fixed it:

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/14ff2544-e5eb-4349-bdef-f5aea5d5798d)
