### ISSUE TITLE
TracesSampler callback TransactionContext.Name is empty

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2442]
In the tracesSampler callback I'd like to drop transactions for an endpoint, based on the transaction name: https://github.com/getsentry/sentry-dotnet/blob/060480e1dfb42ca2044a8445c1d8e71b84b23f73/src/Sentry/ITransactionContext.cs#L11

The API led me to:

```
o.TracesSampler = context => context.TransactionContext.Name is "POST /t"
                                ? 0 // tunneling JS events
                                : 1.0;
```

But `TransactionContext.Name` is an empty string:

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/b451df0b-9916-4fe5-bea4-931c865471a8)

I ended up finding URL details in:

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/dde10025-4c15-4551-889e-0ce6a36a825b)

At the end I got it working with:

```
o.TracesSampler = context => context.CustomSamplingContext.TryGetValue("__HttpPath", out var path)
                             && path is "/t"
    ? 0 // tunneling JS events
    : 1.0;
```

But this isnt' documented, and it's really not very obvious.

**Comment by jamescrosswell** [comment]
> At the end I got it working with:
> 
> ```
> o.TracesSampler = context => context.CustomSamplingContext.TryGetValue("__HttpPath", out var path)
>                              && path is "/t"
>     ? 0 // tunneling JS events
>     : 1.0;
> ```
> 
> But this isnt' documented, and it's really not very obvious.

Hm, interestingly the API has [some extensions](https://github.com/getsentry/sentry-dotnet/blob/e75d537c14ded617c99eb33f19cf4ce69ca4de36/src/Sentry.AspNetCore/SamplingExtensions.cs#L38-L47) to deal with that specifically. When Oleksii added that functionality originally, he included it in the ASP.NET Core MVC 5 sample project:
https://github.com/getsentry/sentry-dotnet/blob/ded83212f834ad6f5eb6281d37ee4962612b80bb/samples/Sentry.Samples.AspNetCore5.Mvc/Program.cs#L25-L34

What do you think @bruno-garcia @bitsandfoxes - should we add docs or add this back into one of the sample projects? Or both?

**Comment by bitsandfoxes** [comment]
> should we add docs or add this back into one of the sample projects? Or both?

It'd be a great if we were to add it to both. Access to the transaction's name should be as straight forward as possible tho.
I remember users asking for a way to access it in the BeforeSendTransaction as well and running into issues?

**Comment by bitsandfoxes** [comment]
Isn't setting the name something on the `TransactionContext` something we can provide? It'd feel a lot more natural.

**Comment by jamescrosswell** [comment]
> Isn't setting the name something on the `TransactionContext` something we can provide? It'd feel a lot more natural.

I think we do try to do that here:
https://github.com/getsentry/sentry-dotnet/blob/3e70c3126515c87b1851b6a9a7afd99ffbb9aeb7/src/Sentry.AspNetCore/SentryTracingMiddleware.cs#L48-L61

That's also when we set the http path etc. that can be accessed via those extensions:
https://github.com/getsentry/sentry-dotnet/blob/e75d537c14ded617c99eb33f19cf4ce69ca4de36/src/Sentry.AspNetCore/SamplingExtensions.cs#L38-L47

Maybe the route template isn't available at that point though, so sometimes the name gets set later in the middleware pipeline:
https://github.com/getsentry/sentry-dotnet/blob/3e70c3126515c87b1851b6a9a7afd99ffbb9aeb7/src/Sentry.AspNetCore/SentryTracingMiddleware.cs#L151-L171
