### ISSUE TITLE
Feature request: GraphQL integration

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2449]
.NET's most popular [GraphQL](https://github.com/graphql-dotnet/graphql-dotnet) library is `GraphQL`: https://www.nuget.org/packages/GraphQL

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/0f8f6cc7-fae8-4000-b19b-ee98db134b47)
https://nugettrends.com/packages?months=72&ids=GraphQL
Social: https://twitter.com/ue_man/status/1673228385542176768

There's a new spec for Sentry SDK's for GraphQL: https://develop.sentry.dev/sdk/features/#graphql-client-integrations

Example product docs for Apollo3: https://docs.sentry.io/platforms/android/configuration/integrations/apollo3/#graphql-client-errors

[internal](https://www.notion.so/sentry/d6e5846f30434770903cf3af20bc2568)

**Comment by smeubank** [comment]
dev spec needs to be updated to reflect the RFC: 

https://github.com/getsentry/rfcs/pull/93

https://github.com/getsentry/rfcs/pull/103

**Comment by jamescrosswell** [comment]
GraphQL Client integration completed in https://github.com/getsentry/sentry-dotnet/pull/2538

**Comment by nbarbettini** [comment]
This is cool to see!

We use [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) in our app (and Sentry). We do this to capture the incoming GQL request as part of the Sentry context, which has been very helpful in the debugging process:

```csharp
// GraphQlController.cs
public async Task Post(CancellationToken cancellationToken)
{
    GraphQLRequest? requestBody = await _graphQlFacade.Serializer.ReadAsync<GraphQLRequest>(Request.Body, cancellationToken);

    // Let Sentry peek at the raw request payload
    Sentry.SentrySdk.ConfigureScope(scope => scope.Contexts["graphql_request"] = requestBody);

    // snip! process the request, return it, etc...
}

**Comment by glen-84** [comment]
What about [Hot Chocolate](https://github.com/ChilliCream/graphql-platform)? 🌶️

https://nugettrends.com/packages?months=12&ids=GraphQL&ids=HotChocolate

**Comment by jamescrosswell** [comment]
> What about [Hot Chocolate](https://github.com/ChilliCream/graphql-platform)? 🌶️

Thanks @glen-84, we might have to see how uptake of graphql-dotnet goes first but we'll definitely keep Hot Chocolate in mind. It looks like a nice implementation of GraphQL (just not quite as much uptake as graphql-dotnet, which is why we prioritised that as a first integration).
