### ISSUE TITLE
Enhancements via netcoreapp3.0

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#245]
Milestone 3.0.0 for the SDK is intended to target `netcoreapp3.0` and get access to the new APIs introduced.

* [x] Send as Extra or Tags the values for `IsDynamicCodeCompiled` and `IsDynamicCodeSupported`.  [PR](https://github.com/getsentry/sentry-dotnet/pull/1418)
* [ ] IIS Server variables (accessible via ASP.NET Core now).
* [ ] Read request body via `System.IO.Pipelines`.
* [ ] Opt-in for `IConfigurationRoot.GetDebugView`.
* [x] GC info [GetMemoryInfo](https://docs.microsoft.com/en-us/dotnet/api/system.gc.getgcmemoryinfo?view=netcore-3.0)  and [GetTotalAllocatedBytes](https://docs.microsoft.com/en-us/dotnet/api/system.gc.gettotalallocatedbytes?view=netcore-3.0). See  [PR](https://github.com/getsentry/sentry-dotnet/pull/1337)

**Comment by jeanpoelie** [comment]
Do you have a targeted release date for this ticket? We are looking into upgrading to .net core 3.0 and Sentry is one of the blocking packages right now. Thank you for your response!

**Comment by bruno-garcia** [comment]
@jeanpoelie it should be working fine with .NET Core 3.0. What's blocking you?
This ticket is just for enhancements.
I hope to get around doing these sometime in December or early next year.

**Comment by jeanpoelie** [comment]
@bruno-garcia the stable version (1.2.0) does not work with .net core 3.0, when I use the pre-release version (2.0.0-beta4) it does work, but generally I don't like using prerelease versions and am wondering when it will be into stable mode :)

Thank you for the answer, we will for now keep using the beta version since I have not run into any issues regarding it being unstable yet :)

**Comment by bruno-garcia** [comment]
The only known bug we have right now (I'm working on it) also affects 1.2.0.

The reason 2.0.0-beta is not out of beta is not that it's unstable but that we want to add a few more breaking changes (likely not to affect most users) on the 2.0.0 release.
If you have issues with the latest preview please raise it and we'll help you as quick as we can with a fix.

**Comment by SimonCropp** [comment]
@bruno-garcia didnt we decide BackgroundWorker, SentryClient, and Hub should not be disposable?

**Comment by mattjohnsonpint** [comment]
Closing stale issue.
