### ISSUE TITLE
When running isolated durable function with Sentry, the orchestrator status stays stuck with Running status

### ISSUE THREAD

**Issue by nude-paco** [getsentry/sentry-dotnet#2469]
### Package

Other - Sentry.AzureFunctions.Worker (3.33.1-beta.1)

### .NET Flavor

.NET

### .NET Version

7.0.101

### OS

macOS

### SDK Version

3.33.1

### Steps to Reproduce

1. Clone this project https://github.com/nude-paco/SentryIssue
2. Run the project locally
3. Call the http trigger with GET http://localhost:7071/api/HttpStartFakeOrchestrator
4. Get the statusQueryGetUri from the response and access that uri to view the orchestrator status
5. You'll see that the status is stuck in Running
6. Go to `Program.cs`
7. Comment out the section that configures Sentry (Line 8 - Line 13)
8. Restart the app and follow step 3 and 4
9. Note that the orchestrator now completed

### Expected Result

The orchestrator should complete it's execution

### Actual Result

<img width="1412" alt="Screenshot 2023-07-10 at 13 30 45" src="https://github.com/getsentry/sentry-dotnet/assets/97242895/ae7ffc8c-c270-441e-beb4-f115f766bbbb">

**Comment by bitsandfoxes** [comment]
Hey @nude-paco! Thank you for reaching out. And thanks for the repo! We'll take a look.

**Comment by SeanFeldman** [comment]
@nude-paco, I was able to reproduce this issue. Will investigate to see what's causing it.

BTW it looks like you're mixing In-Process SDK (`Microsoft.Azure.WebJobs.Extensions.DurableTask`) with Isolated Worker SDK (`Microsoft.Azure.Functions.Worker.Extensions.DurableTask`) by referencing both. It's not the problem but though should mention it.

**Comment by SeanFeldman** [comment]
The issue [was resolved](https://github.com/getsentry/sentry-dotnet/pull/2491), and the fix will be available with the next release.
Thank you for helping with this, @nude-paco.

**Comment by nude-paco** [comment]
Thanks @SeanFeldman!
