### ISSUE TITLE
Document OpenTelemetry .NET integration

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2485]
- [x] Update the GH discussion: https://github.com/getsentry/sentry/discussions/40712
- [x] Something in the [main docs](https://docs.sentry.io/platforms/dotnet/)? https://github.com/getsentry/sentry-docs/pull/7430
- [x] Maybe make a tweet?

**Comment by jamescrosswell** [comment]
@bitsandfoxes do we have a product manager or someone who would typically help with PR (like tweets/announcements etc.)? I'm happy to put something together but I'm not a Sentry employee... so might make more sense for me to retweet something "official".

**Comment by bitsandfoxes** [comment]
Thanks!
