### ISSUE TITLE
Sentry should raise an exception if the DSN has not been configured

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2494]
### Problem Statement

At the moment, if the DSN is empty, you get a DisabledHub. But that's because we've decided to use ["" as the DSN for a disabled hub](https://github.com/getsentry/sentry-dotnet/blob/d6d531cb7d3699f7c4f1f7225433928fbcdab00d/src/Sentry/Constants.cs#L12).

This means the SentrySDK is unable to tell if someone forgot to supply the DSN or if they intentionally left it blank in order to disable Sentry.

### Solution Brainstorm

If the `DisableSdkDsnValue` was a non-empty string (e.g. `"disabled"`) then people could still disable Sentry via code/config. and we could then provide some useful guidance when initialising the SDK in cases where they forgot to supply the DSN (e.g. "Error: You forgot to supply a DSN. Sentry needs a DSN to do anything useful."). 

This is a breaking change, so would need to wait until the next major release.

**Comment by bruno-garcia** [comment]
This `""` behavior is 10 years old and set in all SDks. Not sure this is worth doing. Usualy not passing the DSN means `null` is passed (DSN should be nullable). And in this case, throwing would be OK.
