### ISSUE TITLE
SentryOptions should use 'HttpMessageHandler' instead of 'HttpClientHandler' to support NSUrlSessionHandler on iOS

### ISSUE THREAD

**Issue by AlexSchuetz** [getsentry/sentry-dotnet#2502]
### Problem Statement

The SentryOptions should accept the more general HttpMessageHandler instead of HttpClientHandler to provide to ability to use a custom-configured handler for the HttpClient.

Background:
It is recommended to use NSUrlSessionHandler on iOS (TLS 1.2, performance), but NSUrlSessionHandler only implements HttpMessageHandler.

Since NSUrlSessionHandler inherits from HttpMessageHandler and DefaultSentryHttpClientFactory also mainly uses this class to create the HttpClient, changes are going to be minor.

During creation of the HttpClient the DefaultSentryHttpClientFactory can take care of if it is a HttpClientHandler, a HttpMessageHandler or a NSUrlSessionHandler (which also accepts proxy and decompression properties.

### Solution Brainstorm

Going to file a PR.

**Comment by AlexSchuetz** [comment]
See [PR 2503](https://github.com/getsentry/sentry-dotnet/pull/2503)

**Comment by bruno-garcia** [comment]
Fix merged, we'll close once release is made

**Comment by bitsandfoxes** [comment]
Released with `3.25.0` 🎉
