### ISSUE TITLE
Performance p50/p90 wrong in 3.35.0

### ISSUE THREAD

**Issue by majordutch** [getsentry/sentry-dotnet#2543]
### Package

Sentry

### .NET Flavor

.NET Core

### .NET Version

7.0.10

### OS

Linux

### SDK Version

3.35.0

### Steps to Reproduce

Updated from 3.34.0 to 3.35.0 and started seeing 20k+ months for p50/p90 values in dashboard. Also affected Appdex value.

### Expected Result

Business as usual.

### Actual Result

Upgraded to 3.35.0 and deployed around the 11:

![image](https://github.com/getsentry/sentry-dotnet/assets/354294/4cb20119-a8e2-4db0-ab5b-e0ccf37d9f3e)

After downgrading back to 3.34.0 today, started to normalize:

![image](https://github.com/getsentry/sentry-dotnet/assets/354294/fbabdbbf-16a4-409f-a590-1c78e5043c7c)

**Comment by soer7022** [comment]
I have the same issue, my start date is the 1st of january year 0001
<img width="559" alt="Screenshot 2023-08-16 at 12 55 18" src="https://github.com/getsentry/sentry-dotnet/assets/17567175/ea09421b-d8d7-47d6-bb71-e9230e8cc797">

**Comment by bitsandfoxes** [comment]
Hey, and thanks for raising this issue. You can expect this to be fixed as soon as possible.
