### ISSUE TITLE
Crash Free rate in MAUI seems broken

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2551]
SDK: 3.35.1

New .NET MAUI, Added Sentry. Added button to crash (took from sample in this repo).
Running on Android.

Crashed the app a few times. Crash free rate says 100%

https://github.com/getsentry/sentry-dotnet/assets/1633368/096275dc-391e-4dff-8391-45dc8e577335

Project: https://bruno-test.sentry.io/issues/?project=4505687395270656&query=release%3Acom.companyname.mauiapp2%401.0%2B1+error.unhandled%3Atrue&sort=freq

The iOS Crashes seem to work properly: 
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/585902c9-d588-4f43-8da2-28a4219633d7)

**Comment by jamescrosswell** [comment]
Possibly something to do with [Session Reporting](https://develop.sentry.dev/sdk/sessions/).

Needs investigation.

**Comment by bitsandfoxes** [comment]
Resolves by #2895

**Comment by bruno-garcia** [comment]
Still missing tests? 

https://github.com/getsentry/sentry-dotnet/pull/2895#issuecomment-1824955349

This regressed a few times already
