### ISSUE TITLE
Drop Tizen support

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2562]
We have a bunch of pinned stuff like rollback.json and sdk version in CI due to Tizen but we don't know of anybody using this and it's just one more thing to maintain. We'll look at dropping support for this in the next major release (as this is technically a breaking change).

**Comment by jamescrosswell** [comment]
@bitsandfoxes can this be closed now (and maybe reference the PR where it was resolved)?

**Comment by bitsandfoxes** [comment]
Closed by https://github.com/getsentry/sentry-dotnet/pull/2734
