### ISSUE TITLE
MAUI MSB3231 Unable to remove directory

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2567]
@bitsandfoxes  
Hi All I did was 

1. Create a new Maui App
2. Add Sentry.Maui 3.34 
3. modify Maui.Program
4. Plug the iOS device
5. Use the .net automatic prov profile 
6. build the app and I get  below
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3231	Unable to remove directory "C:\Users\usernamehere\AppData\Local\Temp\Xamarin\HotRestart\Signing\SampleAppSentry.app\out\". Could not find a part of the path 'C:\Users\usernamehere\AppData\Local\Temp\Xamarin\HotRestart\Signing\SampleAppSentry.app\out\Payload\SampleAppSentry.app\SampleAppSentry.content\Sentry.Bindings.Cocoa.resources\Sentry.xcframework\ios-arm64\dSYMs\Sentry-iPhoneOS.dSYM\Contents\Resources\DWARF'.	SampleAppSentry	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets	359	
```
Hope is of any help

_Originally posted by @GBrienza in https://github.com/getsentry/sentry-dotnet/issues/2363#issuecomment-1640004652_

**Comment by jamescrosswell** [comment]
HI @GBrienza, 

Do you think you'd be able to push your solution up to a git repo that I could pull down and see if I get the same behaviour?

**Comment by bitsandfoxes** [comment]
Closing this as stale.

**Comment by bitsandfoxes** [comment]
Closing this as stale since the SDK and MAUI itself is moving quite fast.
