### ISSUE TITLE
Add integration test to proguard mapping upload

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2575]
We got integration test for sentry-cli upload commands here: https://github.com/getsentry/sentry-dotnet/pull/2191/

We'll need to change:

https://github.com/getsentry/github-workflows/blob/fe18d6efa7d9802333d50e8e4567afbdc99844cc/sentry-cli/integration-test/action.psm1#L14

To include the proguard mapping command

Then change the test file: 

https://github.com/getsentry/sentry-dotnet/blob/f7edf0e5578226358e2e780a4b0bffd377d38aa4/test/sentry-cli-integration.Tests.ps1#L89-L101

To include the Sample Android app, which is configured to upload.

This should avoid regressions.

**Comment by vaind** [comment]
Also, from what I can tell the proguard mapping is broken at the moment:

1. this should be `sentry-proguard.cfg`: https://github.com/getsentry/sentry-dotnet/pull/2450/files#diff-a00f24179d4fb2ec1e497e77c12422251f15c3c2e62c9c5155eff83f57bc606fR3
2. the mapping should only be uploaded when Sentry CLI is configured correctly, i.e. check `'$(SentryCLI)' != ''` in target's condition

**Comment by bruno-garcia** [comment]
Support to upload mapping added here:
* https://github.com/getsentry/sentry-dotnet/pull/2455

Before that we added some built-in rules that must be available at build time:
* https://github.com/getsentry/sentry-dotnet/pull/2450

An attempt to fix this:
* https://github.com/getsentry/sentry-dotnet/pull/2574
