### ISSUE TITLE
Distributed tracing does not seem to work in azure functions

### ISSUE THREAD

**Issue by soer7022** [getsentry/sentry-dotnet#2579]
### Package

Other

### .NET Flavor

.NET Core

### .NET Version

6.0

### OS

Any (not platform specific)

### SDK Version

3.36.0-beta.1

### Self-Hosted Sentry Version

23.8.0

### Steps to Reproduce

Enable distributed tracing by setting `tracePropagationTargets` in frontend to include url for backend.

Notice that the sentry-trace header contains a trace ID that doesn't match the trace in sentry.

### Expected Result

I expect the trace ID to be carried over.

### Actual Result

The trace ID for a call in the frontend is not picked up by the backend. I'm not exactly sure how to debug this.

We have logged the headers in the azure function and it does receive the required headers in the request.

**Comment by bitsandfoxes** [comment]
Hey @soer7022, I'll try to reproduce this locally. Let me get back to you.

**Comment by bitsandfoxes** [comment]
Heya! Just an update, I think I found the cause/missing bits. We'll see to it to get that up and running.

**Comment by soer7022** [comment]
Thanks for fixing this @bitsandfoxes . When is this expected to be released?

**Comment by bitsandfoxes** [comment]
I'd expect end of the week at the latest.
