### ISSUE TITLE
Get User.IpAddress from X-Forwarded-For

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#258]
Set the User.IpAddress regardless of other data being there:

https://github.com/getsentry/sentry-dotnet/blob/172269a5d7/src/Sentry.AspNetCore/DefaultUserFactory.cs#L55

At first we didn't want to send User IP if that was all we had from the user. But given that Sentry ends up showing the server IP, it's actually ideal to process X-Forwarded-For at the client and send Sentry the right IP address.

**Comment by olsh** [comment]
It would be nice to have the ability to extract the IP with some action or set header from which the IP will be taken.
For example, we use a non-standard header for setting client IP, so just using X-Forwarded-For won't work.

**Comment by bruno-garcia** [comment]
@olsh Good point. Although you can always add an event processor and override anything done to the event. Including the `User.IpAddress`. I think that's a good fallback to any custom scenario. Does that work for you?

**Comment by olsh** [comment]
Hi @bruno-garcia 

I didn't use custom processors yet, if there is HttpContext, then yes, this definitely will work. Thank you for the suggestion.

**Comment by bruno-garcia** [comment]
Cool. Here's an example adding an event processor with the ASP.NET Core integration.
https://github.com/getsentry/sentry-dotnet/blob/1040fe65575a47a3604f406956746500d6a6adcd/samples/Sentry.Samples.AspNetCore.Mvc/Startup.cs#L22

You can register as many `ISentryEventProcessor` as you like, with the lifetime you need.

Here you can see an implementation:

https://github.com/getsentry/sentry-dotnet/blob/master/samples/Sentry.Samples.AspNetCore.Mvc/ExampleEventProcessor.cs#L11-L18

Note you can just use DI and get what you need via constructor injection. 
I hope this helps

**Comment by bruno-garcia** [comment]
If it's not ASP.NET Core you can use the options:

```csharp
SentrySdk.Init(o => o.AddEventProcessor(new Proccessor());
or
SentrySdk.Init(o => o.AddEventProcessor(e => { e.SetTag("a","b"); return e; });
```

**Comment by olsh** [comment]
Is there any way to use `HttpContext` in EventProcessor in the legacy apps like MVC5 and Web API?

**Comment by bruno-garcia** [comment]
You can use the static API. There's an adapter only for testability. Ideally one constructor Taking IHttpContext to use for testing. And one parameterless that passes `SystemWebHttpContext.Instance` as a parameter to the second ctor.

But this already exists. Web Api2 is not based on system web I believe. Or is it? Otherwise it should work if u opt in

**Comment by olsh** [comment]
Thanks, @bruno-garcia

Is there any guaranteed order in which instances of `ISentryEventProcessor` are executed?
I'm curious if my custom `ISentryEventProcessor` will be executed after [this one](https://github.com/getsentry/sentry-dotnet/blob/172269a5d769a732cce1b2390492f4b5a0d65f0d/src/Sentry/Internal/Web/SystemWebRequestEventProcessor.cs)?

**Comment by bruno-garcia** [comment]
@olsh it's just a list so I assume last added is the last to run, but worth testing it out.
If that's true, any user defined event processor will run after the built-in ones.

**Comment by Genteure** [comment]
There's the [`UseForwardedHeaders` middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer) dedicated to setting user IP and scheme based on http headers sent from proxies, with a lot of customizability (custom header names, allowed networks).

Quote:

> The middleware updates:
> - HttpContext.Connection.RemoteIpAddress: Set using the X-Forwarded-For header value. Additional settings influence how the middleware sets RemoteIpAddress. For details, see the Forwarded Headers Middleware options.
> - HttpContext.Request.Scheme: Set using the X-Forwarded-Proto header value.
> - HttpContext.Request.Host: Set using the X-Forwarded-Host header value.

---

> At first we didn't want to send User IP if that was all we had from the user. But given that Sentry ends up showing the server IP, it's actually ideal to process X-Forwarded-For at the client and send Sentry the right IP address.

https://github.com/getsentry/sentry-dotnet/blob/1326a301e29b5cceae801b73430ad769e1f47b50/src/Sentry.AspNetCore/DefaultUserFactory.cs#L47-L56

I think it's safe to say you can use `HttpContext.Connection.RemoteIpAddress` as is.
(Although I'm not sure if sentry is run before the middleware, I'm not familiar with this repo yet.)

Maybe add a tip about `UseForwardedHeaders` to the documents for `Sentry.AspNetCore`?

**Comment by bruno-garcia** [comment]
> Maybe add a tip about UseForwardedHeaders to the documents for Sentry.AspNetCore?

Completely agreed, we should just document this

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-docs/pull/4892
