### ISSUE TITLE
How to change the status code and response based on type of exception

### ISSUE THREAD

**Issue by george-weare8** [getsentry/sentry-dotnet#259]
I love Sentry!

This is a question and it might be due to lack of knowledge but also related if it can be done using Sentry or just somehow capturing if an error happened in a custom middleware.

I want when a specific type of exception happens Sentry to do all the magic as usual but then another middleware to set the status code and response body.

For example let's say a `DomainException` occurred and I want to do the below.

```
context.Response.StatusCode = StatusCodes.Status400BadRequest;
context.Response.ContentType = MediaTypeNames.Application.Json;
var responseDto = new ErrorResponseDto(ex.Message);
var responseJson = JsonConvert.SerializeObject(responseDto, _jsonSettings);
await context.Response.WriteAsync(responseJson);
```

Thanks!

**Comment by bruno-garcia** [comment]
You can do that in a middleware but in this case, since there's "no error", Sentry won't be aware of it.
You can just use a logger `_logger.LogError(..)` in your middleware and that will include the request data too just as if you had thrown an exception.

**Comment by george-weare8** [comment]
OK, I believe this is our solution, use https://docs.sentry.io/platforms/dotnet/microsoft-extensions-logging/ and record the error.

If we do `_logger.LogInformation(..)` will it record an event of type information but not create an issue?

**Comment by bruno-garcia** [comment]
`LogInformation` by default only creates breadcrumbs.
The docs have more info: https://docs.sentry.io/platforms/dotnet/microsoft-extensions-logging/#features

**Comment by george-weare8** [comment]
Sounds good thank you, we will work around it. I appreciate your input and help.

**Comment by bruno-garcia** [comment]
You're welcome. I also suggest reaching out to the support: https://sentry.io/contact/support/

Or the forum: https://forum.sentry.io/
Cheers
