### ISSUE TITLE
DynamicSamplingContext Exceptions: Attempted to set the DynamicSamplingContext but the context exists already

### ISSUE THREAD

**Issue by ian-a-anderson** [getsentry/sentry-dotnet#2591]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

6.0.0

### OS

Linux

### SDK Version

3.36.0

### Steps to Reproduce

These errors seem to have begun at the beginning of August, after the following PR landed:
https://github.com/getsentry/sentry-dotnet/pull/2493

They fire intermittently as the result of cross-api backend calls where we are forwarding sentry headers along to another request (for distributed tracing). As a result I don't have a consistent repro. Mainly I would like a way to disable these from throwing until a resolution can be found, but since this is an exception coming from Sentry internals I'm not sure how best to avoid it.

It appears this functionality is tied to [Dynamic Sampling](https://develop.sentry.dev/sdk/performance/dynamic-sampling-context/) so I assumed that disabling Performance tracing would prevent the issue. But it appears that you can't disable backend/API performance tracing if it is enabled on an incoming request from a frontend client that has it enabled (for distributed tracing). 

### Expected Result

No exception thrown (possibly a logged error instead?)

### Actual Result

<img width="785" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/2657265/da62ce82-9fd0-4b39-aaba-af5fa1cecb13">

**Comment by bitsandfoxes** [comment]
Sorry about that. The SDK definitely should not just throw. Fix is coming asap.
