### ISSUE TITLE
Update BeforeSend documentation

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2598]
The docs for [filtering events using BeforeSend](https://docs.sentry.io/platforms/dotnet/configuration/filtering/#using-platformidentifier-namebefore-send-) are out of date. These still illustrate configuring this using the `SentryOptions.BeforeSend` property (which is [now obsolete](https://github.com/getsentry/sentry-dotnet/blob/db270dc1b048f46e650f7eb7cb6262ae53ad4e18/src/Sentry/SentryOptions.cs#L344)).

**Comment by bitsandfoxes** [comment]
Thanks for updating those!
