### ISSUE TITLE
Sentry.AspNet not being packaged in 3.39.0 release

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2610]
This happened when we [removed `Sentry-CI-Pack.slnf`](https://github.com/getsentry/sentry-dotnet/pull/2586/files) in favour of using `Sentry-CI-Build-macOS.slnf` to generate the NuGet packages. 

However `src\\Sentry.AspNet\\Sentry.AspNet.csproj` was removed from `Sentry-CI-Build-macOS.slnf` in this [#2576 Automatically generate solution filters](https://github.com/getsentry/sentry-dotnet/pull/2576/files#diff-46881cdd7821ad7176579363f56637c65f5f5fb0bf7e7ef39e7d6bd8b5e803a6) 😬

**Comment by bruno-garcia** [comment]
Note that Release Registry lists this package as being on 3.39.0 which gives new orgs a broken install command:

https://github.com/getsentry/sentry-release-registry/blob/master/packages/nuget/Sentry.AspNet/3.39.0.json


Relates to: https://github.com/getsentry/sentry-dotnet/issues/2609
