### ISSUE TITLE
Identifying Users with OpenTelemetry doesn't work

### ISSUE THREAD

**Issue by ldalonzo** [getsentry/sentry-dotnet#2616]
### Package

Sentry

### .NET Flavor

.NET Core

### .NET Version

7.0.0

### OS

Windows

### SDK Version

3.39.1

### Steps to Reproduce

1. Instrument an ASP.NET Core with Sentry.OpenTelemetry
2. Configure Sentry to opt-in for `SendDefaultPii`
3. Register a custom `IUserFactory` to populate the sentry username

### Expected Result

The custom user factory gets called and the username is reported to Sentry

### Actual Result

The custom `IUserFactory` is never called. Only the IP address is reported to Sentry.
A similar behaviour applies when setting the username through the hub's `ConfigureScope` method.

**Comment by bruno-garcia** [comment]
For context, came up from: https://stackoverflow.com/questions/58858092/sentry-sdk-dotnet-core-not-using-iuserfactory/58868882?noredirect=1#comment135908613_58868882

**Comment by jamescrosswell** [comment]
Hi @ldalonzo, thanks for raising a ticket for this. I can reproduce this easily enough, so we should be able to come up with a solution.

It doesn't necessarily require a custom `IUserFactory` either... we see the same behaviour using the `DefaultUserFactory`.

When not using OpenTelemetry, this is enabled via our `SentryMiddleware`:
https://github.com/getsentry/sentry-dotnet/blob/55ca61eb90b7a269b950d95500502e154f16787d/src/Sentry.AspNetCore/SentryMiddleware.cs#L107-L123

`Sentry.OpenTelemetry` is agnostic of the application type being deployed... so it doesn't know about things like `Microsoft.AspNetCore.Http.HttpContext`, that only exist in ASP.NET Core. 

@bruno-garcia @bitsandfoxes fyi - a bit of a pain but  I think to make this work I'll have to add a `Sentry.OpenTelemery.AspNetCore` package that takes dependencies on `Microsoft.AspNetCore.Http` (so we can get at the `HttpContext`.
