### ISSUE TITLE
Failing to build sentry-cocoa

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#2638]
Building the SDK completely from scratch leads to
macOS Ventura 13.5.2
```
EXEC : error : -static-stdlib is no longer supported for Apple platforms [/Users/bitfox/Workspace/sentry-dotnet/src/Sentry.Bindings.Cocoa/Sentry.Bindings.Cocoa.csproj::TargetFramework=once]
/Users/bitfox/Workspace/sentry-dotnet/src/Sentry.Bindings.Cocoa/Sentry.Bindings.Cocoa.csproj(53,5): error MSB3073: The command "../../scripts/build-sentry-cocoa.sh" exited with code -1. [TargetFramework=once]
```

**Comment by jamescrosswell** [comment]
That particular error seems to be coming from the make file. 

[Commenting out these lines](https://github.com/Carthage/Carthage/blob/89cb8c89db450c92ea315b303810990530addf01/Makefile#L18-L21) gets around it... possibly the check on line 18 is no longer appropriate? Would be good to check with our Swift experts though.
