### ISSUE TITLE
Maui app http requests don't complete on iOS simulator and Mac OS

### ISSUE THREAD

**Issue by mmiller-d8** [getsentry/sentry-dotnet#2652]
### Package

Sentry.Maui

### .NET Flavor

Xamarin

### .NET Version

7.0.0

### OS

iOS

### SDK Version

3.39.1

### Steps to Reproduce

1. Install Sentry and configure it.  I'll show my configuration below
2. Start the application

I have two app.  One that fails and one that doesn't.  I honestly do not see any difference between them in that regard.  I'm not doing anything special with the http clients - like a default handler or anything.  Other http connections work (Azure Maps, Storage Blobs, Cognitive Services, etc.)

Here is my configuration 

```
"Sentry": {
    "Dsn": "https:/xxxxxx"
    "MaxRequestBodySize": "Always",
    "SendDefaultPii": true,
    "MinimumBreadcrumbLevel": "Debug",
    "MinimumEventLevel": "Warning",
    "AttachStackTrace": true,
    "Debug": false,
    "DiagnosticsLevel": "Warning",
    "Environment": "Development"
  }
```

```
var sentryOptions = new SentryMauiOptions();
            configuration.GetSection("Sentry").Bind(sentryOptions);

 builder
      .UseSentry(options => options = sentryOptions);
```

### Expected Result

Http connections connect and the app is able to start.

### Actual Result

I am getting tons of breadcrumbs written to the console, so Sentry is "working," but it seems like the information never actually gets sent and it may be blocking other HTTP calls.  I see my own service calls in the console, but I never see the responses.   

The app seems to hang on initialization.  It doesn't crash it, just the http requests never come back, so it's sitting in a waiting state.  On Mac Catalyst, I don't see any errors or the breadcrumbs.  Maybe it logs to the console differently for Mac?. 

**Here are the errors I'm seeing in the console:**
```
ERROR: SentryCrashMachineContext.c (180): void sentrycrashmc_suspendEnvironment_upToMaxSupportedThreads(thread_act_array_t *, mach_msg_type_number_t *, mach_msg_type_number_t): thread_suspend (00000703): (ipc/send) invalid destination port
ERROR: SentryCrashCPU.c (59): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
ERROR: SentryCrashCPU.c (59): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
ERROR: SentryCrashMachineContext.c (209): void sentrycrashmc_resumeEnvironment(thread_act_array_t, mach_msg_type_number_t): thread_resume (00000703): (ipc/send) invalid destination port

...

2023-09-25 10:38:26.193276-0500 D8.Mobile[23267:47382151] Connection 2: received failure notification
2023-09-25 10:38:26.195683-0500 D8.Mobile[23267:47382151] Connection 2: failed to connect 3:-9816, reason -1
2023-09-25 10:38:26.195869-0500 D8.Mobile[23267:47382151] Connection 2: encountered error(3:-9816)
2023-09-25 10:38:36.221038-0500 D8.Mobile[23267:47382151] Connection 3: received failure notification
2023-09-25 10:38:36.221549-0500 D8.Mobile[23267:47382151] Connection 3: failed to connect 3:-9816, reason -1
2023-09-25 10:38:36.221733-0500 D8.Mobile[23267:47382151] Connection 3: encountered error(3:-9816)
2023-09-25 10:38:36.267056-0500 D8.Mobile[23267:47382151] [boringssl] boringssl_context_handle_fatal_alert(1991) [C4.1.1:2][0x7f951a0f7830] read alert, level: fatal, description: protocol version
2023-09-25 10:38:36.269640-0500 D8.Mobile[23267:47382151] [boringssl] boringssl_session_handshake_incomplete(88) [C4.1.1:2][0x7f951a0f7830] SSL library error
2023-09-25 10:38:36.270778-0500 D8.Mobile[23267:47382151] [boringssl] boringssl_session_handshake_error_print(43) [C4.1.1:2][0x7f951a0f7830] Error: 140278363430728:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/ssl/tls_record.cc:594:SSL alert number 70
2023-09-25 10:38:36.271386-0500 D8.Mobile[23267:47382151] [boringssl] nw_protocol_boringssl_handshake_negotiate_proceed(771) [C4.1.1:2][0x7f951a0f7830] handshake failed at state 12288: not completed
```

**Comment by bitsandfoxes** [comment]
Hey @mmiller-d8 , thanks for raising this. We'll try to reproduce this locally.

**Comment by bitsandfoxes** [comment]
Sorry for the delay. All you do is add Sentry and Http Requests are don't complete? You're not adding the `SentryHttpMessageHandler` to the client? Can you share more of your setup/code so I can test this locally?

**Comment by mmiller-d8** [comment]
In that particular app, yeah.  I tried to reproduce it in a different app, but couldn't.

I'm not adding the SentryHttpMessageHandler.  I am adding a different handler, but only for specific http clients.  Could they be conflicting somehow?

I did not try to add this to the test project, by the way.

`  
    // This method must be in a class in a platform project, even if
    // the HttpClient object is constructed in a shared project.
    private static HttpClientHandler GetInsecureHandler()
    {
        HttpClientHandler handler = new HttpClientHandler();
        handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
        {
#if DEBUG 
            if (cert == null)
                return errors == System.Net.Security.SslPolicyErrors.None;

            if (cert.Issuer.Equals("CN=localhost"))
                return true;
#endif

            return errors == System.Net.Security.SslPolicyErrors.None;

        };
        return handler;
    }
`
`
// This is from MauiProgram
services.AddD8ServiceClients(builder.Configuration, GetInsecureHandler)
`

`
// This is what actually adds the handler
services
            .AddHttpClient<IAuthenticationClient, AuthenticationClient>()
            .SetHandlerLifetime(lifetime)
            .ConfigurePrimaryHttpMessageHandler(x => builder.Invoke());
`

**Comment by stephanie-anderson** [comment]
@mmiller-d8, also for this issue - we will get back to you by the end of this week 👍

**Comment by bitsandfoxes** [comment]
I'm having a really hard time reproducing this locally. Could you provide a repro for me to look at?

**Comment by mmiller-d8** [comment]
I'll see if I can get something put together @bitsandfoxes

**Comment by bruno-garcia** [comment]
Any luck witht he repro @mmiller-d8 ? We'd like to fix this

**Comment by mmiller-d8** [comment]
@bruno-garcia So....  I do have a reproduction, but I guess I also don't - which kind of blows my mind.  I created a repo and then dropped a copy of the solution into the file location for the repo.  The original source in the original location reproduces it.  The new copy in the repo location does not.

**Comment by bruno-garcia** [comment]
> @bruno-garcia So.... I do have a reproduction, but I guess I also don't - which kind of blows my mind. I created a repo and then dropped a copy of the solution into the file location for the repo. The original source in the original location reproduces it. The new copy in the repo location does not.

oh that's tricky. Not sure I quite follow though. Can that setup help u narrow down further the problem perhaps diffing them?

**Comment by jamescrosswell** [comment]
> The original source in the original location reproduces it. The new copy in the repo location does not.

Is it possibly related to untracked files (e.g. stale stuff in the obj/bin directories)? Have you tried running `git clean -dfx` on your original repo?

**Comment by bitsandfoxes** [comment]
I'm closing this as stale. I can't reproduce this with the current version of the SDK. (4.0.0 beta)
Please feel free to reopen this issue if it persists for you.
