### ISSUE TITLE
Prepare migration guide for v4.0.0

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2673]
See https://docs.sentry.io/platforms/dotnet/migration/

**Comment by vaind** [comment]
There isn§t much of a migration necessary aside from following the list of breaking changes in the Changelog. Maybe we don't need to duplicate that to another place?

**Comment by bruno-garcia** [comment]
@bitsandfoxes it's mostly on the changelog already so mostly a copypaste to the docs

**Comment by bruno-garcia** [comment]
It's alive!! https://blog.sentry.io/sentry-dotnet-sdk-4-for-dotnet-8/
