### ISSUE TITLE
Initialising an instance of EKEventStore on MAUI iOS and MacCatalyst triggers WatchDogTermination issue

### ISSUE THREAD

**Issue by Lazareena** [getsentry/sentry-dotnet#2674]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

7.0

### OS

iOS

### SDK Version

3.39.1

### Steps to Reproduce

1. Create .NET MAUI app.
2. Initialise EventKit.EKEventStore in iOS and MacCatalyst projects. 
3. Add Sentry.
4. Run app.
5. App hangs indefinitely when trying to create an instance of EventKit.EKEventStore.

Sample: https://github.com/Lazareena/SentryErrorSample

### Expected Result

EKEventStore gets initialised as expected.

### Actual Result

App hangs indefinitely when trying to create an instance of EventKit.EKEventStore. In Sentry, there's a WatchDogTermination issue indicating possible overuse of RAM.

**Comment by bitsandfoxes** [comment]
Hey @Lazareena, thanks for raising this. We'll try to reproduce this locally.

**Comment by bitsandfoxes** [comment]
Thanks for the repro!
Unfortunately, I can't reproduce the issue you're describing. It runs on the simulator and the device for me. Can you confirm that you're facing the issue with the repro? (you might have to fix the `partial` too)

**Comment by bitsandfoxes** [comment]
I'm closing this as stale. Please feel free to reopen this issue if this issue still persists for you.

**Comment by Lazareena** [comment]
Thanks for trying this out. I had to remove Sentry to continue working on my project but the recent update of VSMac to 17.6.6 (build 408) seems to have fixed it for me.

**Comment by bitsandfoxes** [comment]
Thanks for the update!
