### ISSUE TITLE
Native AOT - attach debug images

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#2700]
Native AOT builds are really a native app and the stack traces come with instruction addresses. Therefore, to symbolicate this on Sentry, we need to append a list of debug images currently loaded, including the load address. We can either build this list manually by calling appropriate native platform-specific endpoints or use existing functionality from `sentry-native`. The latter seems like a better idea because in the future we may also want to use sentry-native for crash handling.

Related: #2247 and #2692 

* [x] linux & windows (sentry-native): #2704 
* [x] macos (sentry-native): #2767

**Comment by bruno-garcia** [comment]
do we have integration tests to avoid regressions on this? I imagine something like the unity repo with the app getting launched then asserting on envelope sent

**Comment by vaind** [comment]
> do we have integration tests to avoid regressions on this? I imagine something like the unity repo with the app getting launched then asserting on envelope sent

https://github.com/getsentry/sentry-dotnet/issues/2772
