### ISSUE TITLE
Single CaptureEvent with optional parameters Hint, Scope

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2713]
We've got a bunch of methods like this scattered throughout the SDK:

https://github.com/getsentry/sentry-dotnet/blob/0714fd20df8991dfc47ab066a63dbfd495dc009b/src/Sentry/SentryClient.cs#L62-L67

I suspect we created the overloads when we introduced hints. We don't really need multiple overloads - we could just have one method signature with optional parmeters.

**Comment by bruno-garcia** [comment]
Most people don't care about hints. Can we avoid this change?
