### ISSUE TITLE
Contexts should inherit from IDictionary<string, object>

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2718]
Contexts doesn't need to inherit from `ConcurrentDictionary<string, object>`. It would be better to inherit from `IDictionary<string, object>` instead, and encapsulate it instead. See comments : https://github.com/getsentry/sentry-dotnet/issues/1332#issuecomment-1251080640

**Comment by jamescrosswell** [comment]
Is there any reason Contexts should inherit from IDictionary at all? There's no requirement for people to be able to create their own custom contexts right? If they want to store custom stuff, we already have Scope.Extra and  Span.Extra for that right?

For one thing, having another Dictionary<string, object> in our public API will make the Serialization/Trimming trickier... so would be good to have one fewer, if not necessary.

**Comment by jamescrosswell** [comment]
Ah, I see... we do actually have a requirement to support [custom contexts](https://docs.sentry.io/platforms/dotnet/enriching-events/context/)...

**Comment by jamescrosswell** [comment]
> Yes. Additional data and extras are to be considered `deprecated` from the SDK's point of view.

OK, will these get replaced by Contexts? But not in v4.0.0? We're maintaining both Span.Data and Contexts in v4.0.0?

**Comment by jamescrosswell** [comment]
> > OK, will these get replaced by Contexts? But not in v4.0.0? We're maintaining both Span.Data and Contexts in v4.0.0?
> 
> The SDK can/should replace them internally. But there are no changes to the public API. So users will continue to have access to them.

OK... so does that mean Data/Extra should actually be stored, interenally, in Contexts? 

So maybe: 
- `Scope.Extra` ➝ `Contexts["Extra"]`
- `Span.Data` ➝ `Contexts["Data"]`

Something like that? That would be great - I think we could get rid of the `IHasExtra` interface entirely if we did that.

**Comment by bitsandfoxes** [comment]
Fixed by https://github.com/getsentry/sentry-dotnet/pull/2729
