### ISSUE TITLE
AspNetCore chaining UseRouting().UseEndpoints crash with InvalidOperationException

### ISSUE THREAD

**Issue by Julien-Mialon** [getsentry/sentry-dotnet#2721]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

7.0.12

### OS

Any (not platform specific)

### SDK Version

3.40.0 & 3.40.1

### Steps to Reproduce

Made a small repo for repro here : https://github.com/Julien-Mialon/SentryRoutingEndpointIssue/

But basically, create an AspNet API project, add Sentry, use this line of code in Startup Configure method
```csharp
app.UseRouting().UseEndpoints(endpoints => endpoints.MapControllers());
```
And it will crash with exception : 
```
System.InvalidOperationException: The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance. To use Endpoint Routing with 'Map(...)', make sure to call 'IApplicationBuilder.UseRouting' before 'IApplicationBuilder.UseEndpoints' for each branch of the middleware pipeline.
```

This is due to app being a SentryTracingBuilder but app.UseRouting() returning the default ApplicationBuilder which is normally wrapped in SentryTracingBuilder.

I'm not understanding every impact of this but maybe the Use method in SentryTracingBuilder should return itself in all case to avoid that ?

### Expected Result

No crash

### Actual Result

Exception above

**Comment by bitsandfoxes** [comment]
Hey @Julien-Mialon and thanks for raising this and providing a repro. I suspect https://github.com/getsentry/sentry-dotnet/pull/2602 being the culprit.

**Comment by jamescrosswell** [comment]
Thanks @Julien-Mialon - great catch!

I've tracked down the problem and put together a PR to resolve this. I'll put details in the PR about root cause and solution.
