### ISSUE TITLE
No logs appear on the web screen

### ISSUE THREAD

**Issue by gokhanwork** [getsentry/sentry-dotnet#2745]
### Package

Sentry

### .NET Flavor

.NET Framework

### .NET Version

4.6.1

### OS

Windows

### SDK Version

3.40.1

### Steps to Reproduce

I made the configurations in the global asax file, but no log records appear on the screen. What is the reason of this ?
![image](https://github.com/getsentry/sentry-dotnet/assets/23299481/4e1d6bfe-49a6-45c4-a054-1f5b5e388461)

### Expected Result

I want to see logs on the web

### Actual Result

![image](https://github.com/getsentry/sentry-dotnet/assets/23299481/a2de3bf9-9083-4091-bd57-d35bb1fb715e)

**Comment by bitsandfoxes** [comment]
Is your app experiencing any errors for Sentry to capture? 
If you want to capture logs you can send them manually by calling `SentrySdk.CaptureMessage("Hello World!");`

**Comment by gokhanwork** [comment]
> Is your app experiencing any errors for Sentry to capture? If you want to capture logs you can send them manually by calling `SentrySdk.CaptureMessage("Hello World!");`

Yes, we sent an error log but it did not arrive, but I solved the problem and added the `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` code to my configuration file. Error logs started to appear.
