### ISSUE TITLE
Crash not reported on iOS with Sentry.Maui

### ISSUE THREAD

**Issue by mmiller-d8** [getsentry/sentry-dotnet#2747]
### Package

Sentry

### .NET Flavor

Xamarin

### .NET Version

7.0.0

### OS

iOS

### SDK Version

3.40.1

### Steps to Reproduce

1. Upgrade to 3.40.1 from 3.39.1
2. Have an exception that crashes the app
3. Observe that no exception is logged in Sentry

Note: unexpectedly, downgrading to 3.39.1 did not resolve the issue.  

### Expected Result

Exceptions should be logged in Sentry

### Actual Result

Nothing was logged to Sentry.  I am in release mode, so I can't see if anything was logged to the output window.

**Comment by mmiller-d8** [comment]
So...  I did just get a message logged, finally.  I had downgraded to 3.39.1 a just before I submitted this.

**Comment by bitsandfoxes** [comment]
Thanks for raising this. Can you reproduce the issue with `3.40.1`?

**Comment by bitsandfoxes** [comment]
I've tested the SDK locally on a simulator but can't reproduce the issue with the sample we have via `throw new ApplicationException(msg);`. Could you provide some snippet or a repro for me to look at?

**Comment by mmiller-d8** [comment]
I'll give it a try @bitsandfoxes .  

In my case, I had a dependency that was missing from the IoC container.  I'll try upgrading to 3.40.1 first and make sure that it reproduces.  If it does, I'll try putting together a sample.

**Comment by mmiller-d8** [comment]
@bitsandfoxes I am able to repro it in a clean project with both 3.39.1 and 3.40.1.

I'm getting the following output from Sentry:

```
ERROR: SentryCrashMachineContext.c (180): void sentrycrashmc_suspendEnvironment_upToMaxSupportedThreads(thread_act_array_t *, mach_msg_type_number_t *, mach_msg_type_number_t): thread_suspend (00000703): (ipc/send) invalid destination port
ERROR: SentryCrashCPU.c (59): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
ERROR: SentryCrashCPU.c (59): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (ipc/send) invalid destination port
ERROR: SentryCrashCPU.c (59): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (os/kern) invalid argument
ERROR: SentryCrashCPU.c (59): _Bool sentrycrashcpu_i_fillState(const thread_t, const thread_state_t, const thread_state_flavor_t, const mach_msg_type_number_t): thread_get_state: (os/kern) invalid argument
ERROR: SentryCrashMachineContext.c (209): void sentrycrashmc_resumeEnvironment(thread_act_array_t, mach_msg_type_number_t): thread_resume (00000703): (ipc/send) invalid destination port
```

Here's my config:

```
.UseSentry(options =>
{
        // The DSN is the only required option.
        options.Dsn = "[Your DSN];

        // By default, we will send the last 100 breadcrumbs with each event.
        // If you want to see everything we can capture from MAUI, you may wish to use a larger value.
        options.MaxBreadcrumbs = 1000;
        options.Environment = "debug";

        options.TracesSampleRate = 1.0;
})
```

For the exception, I just threw an exception on a button click.

**Comment by mmiller-d8** [comment]
@bitsandfoxes 

The behavior here isn't entirely consistent, but it does seem like I never get the crash if something inside of Maui throws the exception - versus my own code causing the crash directly.  Meaning, if the renderer crashes, nothing is being sent up.

I can't really say whether the invalid port error is happening in that case, because I can't see that when I'm running a release build on the device.

**Comment by stephanie-anderson** [comment]
Thank you @mmiller-d8, we will get back to you by the end of this week!

**Comment by bitsandfoxes** [comment]
Do you have a hint how I can reproduce something like the renderer crashing? I'm having a hard time reproing this.

**Comment by mmiller-d8** [comment]
@bitsandfoxes Great question. 

The thing that happened when I ran into this is that I was missing a dependency in the IoC container, but that usually throws an exception on the simulator.  I've also had it happen when I misspell a static resource, although that isn't the case every time.  

I'll see if I can figure out something.  I can do it in my main project, but that's huge.

**Comment by bitsandfoxes** [comment]
I'm closing this as stale. I can't reproduce this with the current version of the SDK. (4.0.0 beta)
Please feel free to reopen this issue if it persists for you.
