### ISSUE TITLE
CaptureEvent_ActiveTransaction_UnhandledExceptionTransactionEndedAsCrashed is flaky

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2751]
When running on Ubuntu the `HubTests.CaptureEvent_ActiveTransaction_UnhandledExceptionTransactionEndedAsCrashed.Mono4_0.received.txt` sometimes fails as it has an additional DebugImage for `Microsoft.VisualStudio.TestPlatform.Common.dll`:

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/fafee5ab-c306-428f-aa83-faf52a3351dd)

See [discord thread](https://discord.com/channels/621778831602221064/1120391379055546429/1165937858771685467).

**Comment by bruno-garcia** [comment]
After merging `main` to `feat/blocking-detector` I get this test failing all the time.
Should we remove it?

**Comment by jamescrosswell** [comment]
I've had issues with that one as well. We could skip it on Mono maybe?
