### ISSUE TITLE
Experiencing high memory usage with tracing enabled

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2754]
I had the same problem today during performance tests of one application.
<img width="92" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/29433794/40600378-0052-4023-9401-5e5a43f7aa01">

Application running on .NET 7 (API) 
Sentry 3.39.1 Installed.

After commenting out the line for tracing the memory usage is under 1GB. (running the same tests).

_Originally posted by @thiagoloureiro in https://github.com/getsentry/sentry-dotnet/issues/2392#issuecomment-1775836358_

**Comment by jamescrosswell** [comment]
@thiagoloureiro any chance you'd be able to run those tests in a memory profiler to get some visibility into where all the memory allocations are being made? Ideally, we'd be able to take a peak at a memory snapshot when memory usage was peaking out at 5.2 GB...

**Comment by thiagoloureiro** [comment]
Hi James, thanks for opening this issue here. I will try to reproduce the scenario and post here on Github. I will keep you guys updated.

**Comment by bitsandfoxes** [comment]
Closing this as resolved in [3.40.0-bata.0](https://github.com/getsentry/sentry-dotnet/releases/tag/3.40.0-beta.0)
