### ISSUE TITLE
Merge Sentry.Bindings.Native into the main package

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#2768]
We shouldn't really need an additional package - instead, let's just package everything in the main package.

**Comment by jamescrosswell** [comment]
Sounds good. For context, do we know why these were kept separate historically? Have those circumstances changed now?

**Comment by vaind** [comment]
> Sounds good. For context, do we know why these were kept separate historically? Have those circumstances changed now?

I don't know about the Coco.Bindings and Android.Bindings, that happened at the time I haven't been involved with the SDK. As for Native, I've just followed what I've seen in the other two when creating it :)
