### ISSUE TITLE
SentryEvent.Message type change.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#277]
getsentry/sentry-dotnet-protocol#47 

docs.sentry.io/development/sdk-dev/event-payloads/message
This is a breaking change since message on SentryEvent is of type string.

We could have a `implicit` operator to assign a string into `SentryMessage` create an instance and set it to `formatted` so code doing `SentryEvent { Message = "bla" ` won't break.

[Similar how it works in Java](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/protocol/Message.java)

**Comment by Tyrrrz** [comment]
Easy:

https://github.com/getsentry/sentry-dotnet/blob/356da096824f7db7e3f8b2f7e325b679e330d901/src/Sentry/Protocol/SentryEvent.cs#L47-L58

**Comment by bruno-garcia** [comment]
lol! I definitely looked at it, what's worng with me.

![image](https://user-images.githubusercontent.com/1633368/104742124-10f11a00-5718-11eb-90f4-6646b64463cf.png)

That was an easy one eh? :)

**Comment by Tyrrrz** [comment]
:joy:
