### ISSUE TITLE
Deprecate `Sentry.Android.AssemblyReader`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2775]
`Sentry.Android.AssemblyReader` was added to share functionality between .NET 6+ Android and Xamarin.Android.

Since Xamarin is going out of support soon, and it's just a few lines of code, we could take advantage of the 4.0 and just delete this package and vendor the code

**Comment by bruno-garcia** [comment]
cc @bitsandfoxes thoughts?

**Comment by bitsandfoxes** [comment]
Let's make it so!

**Comment by bruno-garcia** [comment]
@bitsandfoxes turns out we can't get rid of the dependency it brings, so not much gains. We could keep this until 5.0 hopefully we have lz4 built-in by then. Asking on .NET Discord about this
