### ISSUE TITLE
Get Exception message in English by default

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#278]
This is a breaking change as it can affect grouping.

**Comment by bruno-garcia** [comment]
It can probably be done by:

```csharp
Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
Thread.CurrentThread.CurrentUICulture = System.Globalization.CultureInfo.InvariantCulture;
```

**Comment by SimonCropp** [comment]
i dont think this is possible? the exception message is defined at the time of exception construction, ie before it is thrown. So, to get the English message, the code throws the exception would need to be running in the correct culture

**Comment by SimonCropp** [comment]
this would fail whenever a resource is a string format, since it will be merged when it is received on the back end. 

also, given an arbitrary string, there is no way to work out what resource it came from

**Comment by SimonCropp** [comment]
closing this one since it is not possible
