### ISSUE TITLE
Extend Trimming to all Sentry packages

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2780]
In https://github.com/getsentry/sentry-dotnet/pull/2732 we added the `IsAotCompatible` property to `Sentry.csproj`. 

## Not planned (legacy or .net framework stuff)
- src/Sentry.Log4Net/Sentry.Log4Net.csproj
- src/Sentry.EntityFramework/Sentry.EntityFramework.csproj

## Low hanging fruit

Beyond Sentry.csproj many of the other projects can have this added as well with very little modification. We can leverage the same technique to mark these as AOT compatible in the respective csproj files:
```
  <PropertyGroup Condition="'$(FrameworkSupportsAot)' == 'true'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
```

Also, if they don't already, these projects will have to target `.net6.0` or later (since `FrameworkSupportsAot` doesn't have any effect otherwise). 

- https://github.com/getsentry/sentry-dotnet/pull/2793
  - src/Sentry.Serilog/Sentry.Serilog.csproj
  - src/Sentry.Profiling/Sentry.Profiling.csproj
  - src/Sentry.OpenTelemetry/Sentry.OpenTelemetry.csproj
  - src/Sentry.NLog/Sentry.NLog.csproj
  - src/Sentry.Log4Net/SentryAppender.cs

## ConfigureFromConfigurationOptions<TOptions>

Some  of our integrations use `ConfigureFromConfigurationOptions<TOptions>`, which isn't compatible with Trimming and we need to use the new [configuration binding source generator](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#configuration-binding-source-generator): 

This affects:

- `Sentry.Extensions.Logging`
- `Sentry.Maui`
- `Sentry.Azure.Functions.Worker`
- `Sentry.AspNetCore`

This needs some investigation.

## Sentry.DiagnosticSource

We don't need to do anything for `Sentry.DiagnosticSource` as it's included in the Sentry core package for all versions of .NET that support AOT:
https://github.com/getsentry/sentry-dotnet/blob/4080ac6b894ff263da6e01805bc91df1b3f84f2e/src/Sentry/Sentry.csproj#L53-L61

**Comment by bruno-garcia** [comment]
Doesn't really need to be on all.
It should be on stuff that makes most sense. Like `Sentry`. `Sentry.AspNetCore` All the serverless stuff.

We don't care about the mostly deprecated stuff (we can change that decision based on feedback later though). Likel Log4Net, EntityFramework, AspNet, etc

**Comment by jamescrosswell** [comment]
> Doesn't really need to be on all.
> It should be on stuff that makes most sense. Like `Sentry`. `Sentry.AspNetCore` All the serverless stuff.

I added another section in the issue sescription: "Not planned" and removed Log4Net and EntityFramework from PR2793.

@bitsandfoxes is going to have a got at the `ConfigureFromConfigurationOptions` stuff, which leaves `Sentry.DiagnosticSource` - I'll take a look at that.

**Comment by vaind** [comment]
@jamescrosswell  does it make sense to track the progress in this issue's description (as a checklist with project names)?
Also, if it won't require a breaking change, we can just remove this from the 4.0.0 milestone.

**Comment by jamescrosswell** [comment]
> @jamescrosswell does it make sense to track the progress in this issue's description (as a checklist with project names)?
> Also, if it won't require a breaking change, we can just remove this from the 4.0.0 milestone.

As far as I know, for all 4 remaining projects it's the same issue ([ConfigureFromConfigurationOptions](https://andrewlock.net/exploring-the-dotnet-8-preview-using-the-new-configuration-binder-source-generator/))... so you wouldn't want to work on these separately. At least that's the only issue you get from the compiler - it may be a different story at runtime. At runtime, I think we're likly to hit a few scenarios where additional Json Context needs to be supplied for the sourcegen serializers to be able to serialize everything for each integratino. 

We figured it'd be good to spread the knowledge a bit about how this stuff works, so @bitsandfoxes is digging into this...

**Comment by jamescrosswell** [comment]
Closing in favour of https://github.com/getsentry/sentry-dotnet/issues/2822 (as there's quite a bit of context worth capturing and too much in the details of this PR already).
