### ISSUE TITLE
Drop BreadcrumbLevel in favor of SentryLevel

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#279]
We have two enum types with similar values.

The goal of this task is to delete `BreadcrumbLevel` and replace it with `SentryLevel`.

One of the challenges as @Tyrrrz mentioned in the comment below, they don't match at the highest level `Fatal` vs `Critical`. It would require testing in Sentry to see what would the breadcrumb behave if one sent `Fatal` (the value from SentryLevel) instead of `Critical`. Mainly a "before and after".

**Comment by Tyrrrz** [comment]
It doesn't sound like it should be possible, given that `SentryLevel` has `Fatal` while `BreadcrumbLevel` has `Critical`.

**Comment by bruno-garcia** [comment]
Clarified better. This is a good first issue so added the `up-for-grabs` label.

**Comment by bruno-garcia** [comment]
Not really worth the breaking change
