### ISSUE TITLE
Event level ignored

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#28]
NuGet package version: 0.0.1-preview1

When I manually capture an event like so:
`SentrySdk.CaptureEvent(new SentryEvent() { Message = "GetRequest", Level = SentryLevel.Warning });`

Sentry on-premise web (version 9.0.0) displays as an error, and has the following message:

> Discarded invalid value for parameter 'level'
> Name: level
> Value: Warning

It looks like the level might be case sensitive?

**Comment by bruno-garcia** [comment]
Thank you for spotting this! Indeed that's a bug. 
I'll push a fix soon!

**Comment by bruno-garcia** [comment]
I'll just work on a few other fixes/improvements and there'll be a preview2.
Thank you so much again for trying it and communicating the issue!

I'll announce the previews on [gitter](https://gitter.im/getsentry/dotnet)
