### ISSUE TITLE
Rendering UI issue when Sentry SDK is enabled 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-dotnet#2804]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

7.0.0

### OS

Windows

### SDK Version

3.40.1

### Steps to Reproduce

When using UI components from SyncFusion, elements in the UI are not rendered with the Sentry SDK is enabled. 

1. Download the repro project
2. Restore packages and NUget
3. Run the app on debug mode

The first run with no changes will show 2 appointments rendered in a calendar. 

4. Stop the app
5. Enable Sentry SDK in MauiProgram.cs
6. Run the app again on debug mode

### Expected Result

To run as the 1st time, with two appointments rendered in the calendar. 

### Actual Result

The second run has no appointment is rendered. 

The original issue was reported as happening on Windows, but i was able to reproduce it on Mac as well.

**Comment by bitsandfoxes** [comment]
Hey @rodolfoBee, could you provide us with the repro? Much appreciated! 🙏

**Comment by rodolfoBee** [comment]
[Sentryrepo.zip](https://github.com/getsentry/sentry-dotnet/files/13335187/SentryBug.zip)
