### ISSUE TITLE
[Information] Sentry.ISentryClient: [0]: Replacing current logger with: '(null)'. 

### ISSUE THREAD

**Issue by george-weare8** [getsentry/sentry-dotnet#281]
I am trying to add ILogger with Sentry in AWS Lambda Function with no success. Below is my configuration.

```
private static void SetupLogger(bool isDevelopment, ILoggerFactory loggerFactory, IConfiguration configuration)
        {
            var loggerOptions = new LambdaLoggerOptions(configuration);
            loggerFactory.AddLambdaLogger(loggerOptions);
            loggerFactory.AddSentry(sentryOptions => OptionsConfiguration(sentryOptions, configuration));
            
            if (isDevelopment)
            {
                loggerFactory.AddConsole();
            }
        }

        private static void OptionsConfiguration(SentryLoggingOptions sentryLoggingOptions, IConfiguration configuration)
        {
            var sentryConfigurationOptions = configuration.GetSection("Sentry");
            sentryLoggingOptions.Dsn = sentryConfigurationOptions["Dsn"];
            sentryLoggingOptions.MinimumBreadcrumbLevel =
                sentryConfigurationOptions["MinimumBreadcrumbLevel"].ToEnum<LogLevel>();
            sentryLoggingOptions.MinimumEventLevel = sentryConfigurationOptions["MinimumEventLevel"].ToEnum<LogLevel>();
        }
```
When I configure the ILoggerFactory, I get the message 

> [Information] Sentry.ISentryClient: [0]: Replacing current logger with: '(null)'. 

Using the ILoggerFactory in a constructor.

```
public Program(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<Program>();
        }
```
When logging Error nothing really happens. Any ideas how to use Sentry in a Lambda?

**Comment by bruno-garcia** [comment]
That log message comes if the `DiagnosticLogger` is set to `null`:

https://github.com/getsentry/sentry-dotnet/blob/f6007f621d4935ca2570c0163ede944d7c86483f/src/Sentry/SentryOptions.cs#L317-L323

That's just the logging for debugging Sentry SDK itse. The SDK has `sourcelink` so it should be able to step in to the source code with a debugger and find out what's setting it to `null`.
If you remove `AddLambdaLogger` does it work? 

Could you provide the whole solution (deleting unrelated code) so I can debug it through?

**Comment by george-weare8** [comment]
[Sentry.LambdaFunction.Issue281.zip](https://github.com/getsentry/sentry-dotnet/files/3690734/Sentry.LambdaFunction.Issue281.zip)
Hi. Thanks for the quick response, I have created a small reproducible sample based on my project setup.

Let me know if there is anything I can help.

**Comment by bruno-garcia** [comment]
@george-weare8 There's a sample that fits your use since you have ASP.NET Core:

https://github.com/getsentry/sentry-dotnet/tree/main/samples/Sentry.Samples.Aws.Lambda.AspNetCoreServer

Could you give this a try? There's a screenshot on that link too. I hope it helps.

**Comment by bruno-garcia** [comment]
Closing as I believe this is resolved but please feel free to reopen otherwise.
