### ISSUE TITLE
Serilog Properties as Tags

### ISSUE THREAD

**Issue by davidames** [getsentry/sentry-dotnet#282]
Hi there,

We use SeriLog log context properties extensively in our project. 

Is there any way to push select ones to Sentry as Tags instead of additional data?

**Comment by bruno-garcia** [comment]
Not at this time:

https://github.com/getsentry/sentry-dotnet/blob/f6007f621d4935ca2570c0163ede944d7c86483f/src/Sentry.Serilog/SentrySink.cs#L99

This would require some new API. 
We don't want to automatically send every property as a tag .
How do you current differentiate what should go as a tag vs extra?

**Comment by davidames** [comment]
We have a fairly static list of properties that we would like to use as tags.  I wrote a handler for BeforeSend which takes care of this quite nicely.

I'm happy to close this issue.

**Comment by ckuehl** [comment]
@davidames Are you open to sharing your implementation? We have a similar need (with a static list of properties) that we'd like to be tags versus additional data.

**Comment by bruno-garcia** [comment]
From the comment he wrote a `BeforeSend` callback that added data as tags (since the data was static).

`options.BeforeSend = e => { e.SetTag("..", ".."); return e; }`
