### ISSUE TITLE
Automatically trigger all events in the application when using the Sentry. 

### ISSUE THREAD

**Issue by saiganesh-sakthivel** [getsentry/sentry-dotnet#2827]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Run the sample.
2. In the view, I have a button, and all events in the button are automatically triggered.
[MauiApp1.zip](https://github.com/getsentry/sentry/files/13319792/MauiApp1.zip)

### Expected Result

1. It should not trigger events automatically.

### Actual Result

<img width="877" alt="MicrosoftTeams-image (34)" src="https://github.com/getsentry/sentry/assets/61176526/8d93a83a-ac28-446d-ada2-04e55abc498f">

### Product Area

Issues

### Version

3.40.1

**Comment by bitsandfoxes** [comment]
Hey @saiganesh-sakthivel,
Thanks for providing a repro! We're going to look into this.

**Comment by bruno-garcia** [comment]
Thanks hanging in there, btw this PR might help fix this: https://github.com/getsentry/sentry-dotnet/pull/2900

**Comment by saiganesh-sakthivel** [comment]
Hi @bitsandfoxes ,

Still issue in there
<img width="677" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/61176526/cd1e05bb-f7ad-4ee4-a820-481cca9b5daf">

**Comment by bitsandfoxes** [comment]
Hi @saiganesh-sakthivel,
I'm not sure what I'm looking at. The SDK does hook into a couple of events to automatically add breadcrumbs but the amount is drastically reduced.
Can you give me some more details of what it is that does not work for you?
