### ISSUE TITLE
ISentryUserFactory doesn't work unless it also implements the obsolete IUserFactory interface

### ISSUE THREAD

**Issue by ian-a-anderson** [getsentry/sentry-dotnet#2844]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

6.0.0

### OS

Linux

### SDK Version

3.40.1

### Steps to Reproduce

1. Sentry currently warns against using IUserFactory and recommends users switch to ISentryUserFactory:
<img width="1210" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/2657265/9c1e7c03-4cba-4f0f-8a72-f70e21ea4a80">

2. However, if you only implement and register ISentryUserFactory your custom code is never hit, because Sentry itself only looks for the obsolete IUserFactory implementation:
https://github.com/getsentry/sentry-dotnet/blob/343d921c78e9cd1bd47734cc70be95a34cef8fe7/src/Sentry.AspNetCore/ScopeExtensions.cs#L42
<img width="709" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/2657265/bd81a6fb-7da4-4380-9ce6-1a1e6bf22d4f">

### Expected Result

Implementing and registering ISentryUserFactory should work without having to continue implementing the obsolete IUserFactory interface.

### Actual Result

No custom user code is hit when running with only a ISentryUserFactory implementation registered. 

In order to allow users to transition away from IUserFactory, the underlying code in ScopeExtensions should look for implementations of ISentryUserFactory and reference them if registered.

**Comment by bitsandfoxes** [comment]
Thanks for raising this @ian-a-anderson. A fix is on its way.

**Comment by ian-a-anderson** [comment]
> Thanks for raising this @ian-a-anderson. A fix is on its way.
Just to confirm, is the fix coming in the v3.40 codebase or only with v4?

**Comment by vaind** [comment]
> > Thanks for raising this @ian-a-anderson. A fix is on its way.
> Just to confirm, is the fix coming in the v3.40 codebase or only with v4?

v4.0+
