### ISSUE TITLE
Source generators to maintain Bindable classes

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2849]
Breaking https://github.com/getsentry/sentry-dotnet/issues/2822 down into more bite sized chunks.

**Comment by bitsandfoxes** [comment]
As discussed during the sync: Before setting up source generation having some tests in place that check for newly added properties on the core `options` and compares that to the `BindableOptions` so we won't miss propagating them would be great.

**Comment by jamescrosswell** [comment]
@bitsandfoxes do we still want source generators to maintain the BindableOptions classes? I'm thinking now we have the unit tests in place, it's probably more effort than it's worth. The unit tests will pick up on any new properties that get added to the underlying Options classes and it's pretty trivial to then add those (where relevant) to the BindableOptions classes... so source generators would take quite a bit of time to build and wouldn't save us much time in terms of code maintenance.

**Comment by bitsandfoxes** [comment]
I agree. It would be a nice-to-have but I don't think it's worth the effort either. The tests really free us up there. Thanks for those.
