### ISSUE TITLE
Add Metrics API

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2880]
Sentry is building a new metrics product: https://github.com/getsentry/sentry/discussions/58584

**_Note:_** We need to be clear that the API itself would be preview, perhaps through xml docs.

## Developer Docs
https://develop.sentry.dev/sdk/metrics/

## Progress in other SDKs
- **Python**:  
    - trailblazer to dogfood/build the product...
    - [Initial implementation](https://github.com/getsentry/sentry-python/pull/2385/files)
    - [Metric Span Summaries](https://github.com/getsentry/sentry-python/pull/2522)
- **PHP**:  https://github.com/getsentry/sentry-php/pull/1619 (draft)
- **Javascript**: https://github.com/getsentry/sentry-javascript/issues/9691 (WIP)
    - https://github.com/getsentry/sentry-javascript/pull/9304
    - https://github.com/getsentry/sentry-javascript/pull/9698
    - Browser: https://github.com/getsentry/sentry-javascript/pull/9794
- **Rust**: https://github.com/getsentry/sentry-rust/pull/618 

## Testing / Dogfooding in .NET

Would be great to dogfood this through [Symbol Collector](https://github.com/getsentry/symbol-collector) which today uses StatsD and emits metrics

The mobile app also has some metrics but it just dumps the `Extra` on events (can see it anywhere other than individual events).

**Comment by bruno-garcia** [comment]
There are actually develop docs on this: https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/

Please note this is very early stage so not worth adding a ton of tests, we could have this on a branch and ship `alpha`'s from it for example

**Comment by bruno-garcia** [comment]
see also https://github.com/getsentry/sentry-python/pull/2522

**Comment by bruno-garcia** [comment]
JS: https://github.com/getsentry/sentry-javascript/issues/9691

**Comment by bruno-garcia** [comment]
https://github.com/getsentry/sentry-rust/pull/618

**Comment by jamescrosswell** [comment]
## Open Telemetry

Eventaully we might be able to build a bridge between Sentry's metrics and [OpenTelemetry Metrics](https://opentelemetry.io/docs/specs/otel/metrics/api/), if people wanted to use OpenTelemetry for instrumentation (similar to what we've done for Tracing)

### Metric Types

For the following [metric types](https://develop.sentry.dev/delightful-developer-metrics/#metric-types):
- **Counter**: OpenTelemetry  has a [Counter](https://opentelemetry.io/docs/specs/otel/metrics/api/#counter)
- **Distribution**: The closest thing OTel has is a [Histogram](https://opentelemetry.io/docs/specs/otel/metrics/api/#histogram)
- **Gauge**: OpenTelemetry has a [Gauge](https://opentelemetry.io/docs/specs/otel/metrics/api/#gauge)
- **OpenTelemetry** also has an [UpDownCounter](https://opentelemetry.io/docs/specs/otel/metrics/api/#updowncounter)


### Tags

Tags can be used to attach meta-data to metrics. These could be implemented [using OpenTelemetry Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute). 

### Additional Context

Sentry DDM allows associating code locations with metrics. This could be achieved by convention using an [OpenTelemetry Attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute) with a specific name. Note that attributes are provided on metric values, not on the metrics overall [e.g. Counter.add in the Metrics API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#add). 

### Timers

The OpenTelemetry docs don't mention anything like the [Timers described in Sentry's DDMs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)... Although the timers themselves are just a mechanism to collect a fairly specific metric (the amount of time taken to execute a particular piece of code). So these could be implemented in the Sentry SDK... and the results passed as a regular metric of one of the above types, using milliseconds as the unit and also accompanied by a code location (as an attribute). 

### Sending Metrics to Sentry

A custom exporter can be created to [extend OpenTelemetry dotnet](https://github.com/open-telemetry/opentelemetry-dotnet#extensibility).

**Comment by bruno-garcia** [comment]
Useful to send as default metrics: https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool.getavailablethreads?view=net-8.0
