### ISSUE TITLE
Serilog API improvement ideas

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#2897]
@jamescrosswell I just want to highlight the fact that `dsn` is an optional argument of `WriteTo.Sentry()`: https://github.com/getsentry/sentry-dotnet/blob/0ea0f0ace66ddf2a7d76235c590d36edd068d740/src/Sentry.Serilog/SentrySinkExtensions.cs#L86

So supplying the dsn is required, but the dsn argument is not? It's kind of super confusing as a user of the library, especially since the Serilog provider doesn't seem to read the value from `IConfiguration` unlike `UseSentry()`.

I guess a solution would be to have 2 alternative calls with `WriteTo.Sentry()`, one that takes a non-null string as the first argument, and one that takes a boolean for `initializeSdk` as the first non-optional argument.

_Originally posted by @kanadaj in https://github.com/getsentry/sentry-dotnet/issues/2883#issuecomment-1824696606_

**Comment by jamescrosswell** [comment]
Merging into https://github.com/getsentry/sentry-dotnet/issues/2494
