### ISSUE TITLE
Unable to modify event data.

### ISSUE THREAD

**Issue by Seeker1437** [getsentry/sentry-dotnet#291]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [X] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.6.1

Please mark the NuGet packages used:

- [X] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

Please describe the the steps to reproduce the issue or link to a repository with a small reproducible code.

I am confused on whether or now I am actrually supposed to be able to edit data in a Breadcrumb or SentryEvent.

Extra Data and other such information are set up as `IReadOnlyDictionary`s which makes modifying existing data impossible.

DO you guys want me to just create a new dictionary copy all the info from the existing one, then create a new readonly dictionary and then set that tot he property?

I just don't feel like that is good but then again i am currently frustrated I apologize if any of my working is poor.

**Comment by bruno-garcia** [comment]
Breadcrumbs are immutable and Extra and Tags are a readonly collection but you should be able to modify things (by making a modified copy) before sending the event.

We might have to review the API if this is not the case right now. For 2.0.0 we'll have some breaking changes and one of them might be to get Scope and Event decoupled (to make @mitsuhiko happy) and in this case we can have only Scope holding thread-safe or immutable collections and let Event hold normal List where you can fiddle around with the items.

**Comment by Seeker1437** [comment]
It seems that things like Tags and Extras can be modified using the extension methods.

To be honest I feel like extension methods should only be created and used by consumers of the API instead of being used as part of the API.

I was taught that as an example being the library developer if you have control over the structure of the object, the methods should be built in where reasonable, whereas me for an example I am a consumer, since I cannot change the object I would make extensions methods to add functionality.

Much like creating an extension method that does something with the string type:

**Comment by bruno-garcia** [comment]
ASP.NET Core is basically only extension methods over interfaces. It's a very flexible approach for an API. We don't extend base types like String or Object though.
I don't want to polute the interface by hanging a ton of methods in it that are all just specialities of the main method. 

Take this interface:

https://github.com/getsentry/sentry-dotnet/blob/ea7ed46734ef686f07f3292249f490f825985e02/src/Sentry/ISentryClient.cs#L23

It's a perfect use case. Where Sentry takes an Event, not a message or an exception. 
Those are pure extensions: 
https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry/SentryClientExtensions.cs#L33-L46

Now if you implement the interface yourself, you get those extension method for free. There's no need for you to implement CaptureMessage.

**Comment by bruno-garcia** [comment]
Closing this which seems resolved. Feel free to open otherwise.
