### ISSUE TITLE
NativeAOT iOS transactions crash the app

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#2933]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

iOS

### SDK Version

4.0.0-beta

### Steps to Reproduce

finish a transaction

https://github.com/getsentry/sentry-dotnet/pull/2930/files#diff-50abe4e6e14dddceba523af718c74653995c40e81c3799be650f4257d12c7977R54

### Expected Result

don't crash 

### Actual Result

https://sentry-sdks.sentry.io/issues/4688390166/events/757b396e07ef4335b17a13b656140c45/

**Comment by bruno-garcia** [comment]
Stack trace for reference:
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/8bdad604-c1bb-4d19-95d6-7a6452013f1f)

Is this a problem in .NET itself?

**Comment by bruno-garcia** [comment]
No idea what's up here

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/82a4f2f9-3a80-4066-8697-1c92978d20a7)
