### ISSUE TITLE
Native iOS/Cocoa options naming - 4.0.0-beta.3

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2934]
On **4.0.0-beta.3** we renamed the public prop from iOS to Cocoa: https://github.com/getsentry/sentry-dotnet/pull/2929/files

We talked on Discord, I didn't realize we were renaming this exactly. The message made me think it was the folder and since the submodule was cocoa etc, made sense.

This is pretty user facing but sadly it's not a name modern iOS devs use.
Even on our docs, we stopped surfacing Cocoa since this is dead terminology:

> Cocoa is [Apple](https://en.wikipedia.org/wiki/Apple_Inc.)'s native [object-oriented](https://en.wikipedia.org/wiki/Object-oriented_programming) [application programming interface](https://en.wikipedia.org/wiki/Application_programming_interface) (API) for its [desktop](https://en.wikipedia.org/wiki/Desktop_computer) [operating system](https://en.wikipedia.org/wiki/Operating_system) [macOS](https://en.wikipedia.org/wiki/MacOS).

<img width="682" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/1633368/f6e3e403-db21-4e53-a97f-02292b922b4c">

Opening it gives this old/retired doc:

<img width="894" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/1633368/bf7fa3d6-3cfa-4727-9110-bb8dfc0f600c">

On our docs we call it Apple:

<img width="327" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/1633368/1f15a823-2ce9-415a-927b-b145ae94e34c">

.NET calls the repos `macios` Not saying that's better, just another data point.

I honestly prefer `iOS` here but indeed it's a challenge with Mac. MacCatalyst has it's own TFM so can we #ifdef and set a equivalent class (or just the same class is suddently named `Mac`?

**Or we call generally `Native` ? And use that on all platforms?**
I think this could be good because that's what that property is for. To expose options bindings from the native layer.
So we could have property called Native and the type will vary depending on the native SDK it binds to (sentry-native, android or cocoa)

We can discuss other names (and this is still preview so we can change it again).

**Comment by bruno-garcia** [comment]
cc @bitsandfoxes @vaind

**Comment by vaind** [comment]
Native sounds good to me.

Also platform specific name like iOS, macOS, Android, if we expect there to be separate Android and Native confs. Although that doesn't translate to windows/Linux native config naming which would be the same thing.

**Comment by bruno-garcia** [comment]
The Sentry Android SDK itself has a single options object so we should be OK with only `Native` representing the Android SDK for both ART+NDK
