### ISSUE TITLE
Add In Foreground to App context

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2945]
Relevant for all UI-based apps (WPF, WInForms, MAUI, Xamarin, etc)

See: 

* https://github.com/getsentry/team-mobile/issues/36
* https://github.com/getsentry/sentry/issues/44251

Same as:
* https://github.com/getsentry/sentry-dart/pull/1260

**Comment by bruno-garcia** [comment]
@Giorgi:

>  In the Add In Foreground to App context ticket https://github.com/getsentry/sentry-dotnet/issues/2945  in case of Windows apps, does in foreground mean if the app has focus? Or only check if the app is in foreground?


hm, how about in that case we don't set `in_foreground` at all, and instead set `in_focus` ? We can document the difference, and if searching and you care about either you can `in_foreground`=true && `is_focus`=true?

**Comment by Giorgi** [comment]
We can do that but I think from a Windows developer perspective the naming is a bit confusing. In Windows, foreground window is the windows that has focus: [GetForegroundWindow](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getforegroundwindow)

**Comment by bitsandfoxes** [comment]
I assume the the definition `if it's visible it's in the foreground` comes from the mobile perspective. In our case, I would use `in_focus` and `in_foreground` synonymously and stick with `in_foreground`.

What we care about with this is: Was the user actively interacting with the application vs was it just floating around somewhere/just being visible on the monitor?

**Comment by bruno-garcia** [comment]
> I assume the the definition if it's visible it's in the foreground comes from the mobile perspective. In our case, I would use in_focus and in_foreground synonymously and stick with in_foreground.

works for me, just worth being clear on the docs about all these terminologies
