### ISSUE TITLE
SDK Backpressure and 100% Sampling

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2946]
Description in this issue:
* https://github.com/getsentry/team-sdks/issues/10

Java implementation: https://github.com/getsentry/sentry-java/pull/3072

Python PRs: https://github.com/getsentry/sentry-python/pulls?q=is%3Apr+sort%3Aupdated-desc+backpressure+is%3Aclosed

Additional context; Internal doc (sorry): https://vanguard.getsentry.net/p/clnlv0iuj0010s60q9e09ba3f

**Comment by bitsandfoxes** [comment]
Superseded by https://github.com/getsentry/sentry-dotnet/issues/2410
