### ISSUE TITLE
Ui Component Crash When Sentry is Initialized

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-dotnet#2971]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

iOS

### SDK Version

3.41.3

### Steps to Reproduce

Repro provided by user and some more context will be attached to synced Jira Ticket at bottom of this comment.  User uses SyncFusion and is observing the crash within a component called SfDataGrid.

1. Change DSN inside MauiProgram.cs
2. Run user provided repro, I used `dotnet build -t:Run -f net8.0-ios`
3. Scroll Down on table in the middle and observe crash.
4. Go to `MauiProgram.cs` and remove `.UseSentry()`
5. Rerun app and scroll down the table normally without crash

### Expected Result

No Crashes

### Actual Result

Crash, and [here is a link to the crash in my test org](https://francisorg.sentry.io/issues/4728642028/events/0cba91de0fc9448eacb07718316fd1cd/?project=4506400462209024).

[Jira Ticket With Repro](https://getsentry.atlassian.net/browse/FEEDBACK-2042)

**Comment by jamescrosswell** [comment]
@bitsandfoxes are you able to copy the relevant context from Jira back here? I think that Jira account is only accessible to Sentry employees.

**Comment by bitsandfoxes** [comment]
This was fixed in https://github.com/getsentry/sentry-dotnet/pull/2900 and is available in `4.0.0-beta.3` and newer.
