### ISSUE TITLE
Send frame `filename` including project root

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2978]
Source link doesn't work on .NET right now. We send `abs_path` with the full path to root, plus a `filename` that has only literally the name, without path.
 
* https://github.com/getsentry/sentry/issues/61730

But here:

https://github.com/getsentry/sentry-dotnet/blob/2e00a5c5509744a3f4fdb830952cb5aa176f3d0c/src/Sentry/buildTransitive/Sentry.targets

We create at build time an attribute `Sentry.ProjectDirectory` that contains the path to the project root. 
With that we can, truncate off the root path that's irrelevant (build server paths etc).

This can help unblocking **DDM code locations** but also Source Link without the fix for `abs_path` (that hopefully happens so all these years of SDK shipped also work). 

## References
 
* See [Frame Attributes](https://develop.sentry.dev/sdk/event-payloads/stacktrace/#frame-attributes)

**Comment by jamescrosswell** [comment]
I played around with this briefly. I don't think the `Sentry.ProjectDirectory` will work for us... what we really need is the `RepoRoot`.

See attached PR.

**Comment by bitsandfoxes** [comment]
Closed by product! It works like a charm now!
