### ISSUE TITLE
OpenTelemetry causes sentry transactions loop

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry-dotnet#2998]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

7.0

### OS

Browser

### SDK Version

3.35.0
Issue also occurs in 4.0.0-beta.6

### Steps to Reproduce

Use `OpenTelemetry.Instrumentation.Http`, `OpenTelemetry.Instrumentation.AspNetCore`, and `OpenTelemetry.Extensions.Hosting` version `1.7.0`

Observe an opentelemetry span become a transaction,
that transaction creates a POST request to Sentry with the event,
that POST request adds a new span in opentelemetry,
https://org2-w7.sentry.io/performance/dotnet-aspnetcore-mywebapp:cc08e21292b4408cabb04a1cc41bb292/?project=4504492492390400&query=&referrer=performance-transaction-summary&statsPeriod=1h&transaction=POST&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29
![Screenshot 2024-01-02 at 4 16 14 PM](https://github.com/getsentry/sentry-dotnet/assets/99350819/45255484-23ca-469c-8690-adc36d0b97bb)

that new span becomes a new Sentry transaction,
repeat

https://org2-w7.sentry.io/discover/homepage/?end=2024-01-02T20%3A50%3A59&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=4504492492390400&query=transaction%3APOST&sort=-timestamp&start=2024-01-02T20%3A26%3A00&yAxis=count%28%29

https://github.com/getsentry/sentry-dotnet/assets/99350819/904711ae-fb92-497e-80f6-541e9a097b77

### Expected Result

The POST requests made to Sentry are not reported

### Actual Result

Sentry recursively generates events for its calls

**Comment by bitsandfoxes** [comment]
Hey, thanks for reaching out. The SDK should most definitely not instrument itself calling home. We'll be fixing that ASAP.

**Comment by knd775** [comment]
> Hey, thanks for reaching out. The SDK should most definitely not instrument itself calling home. We'll be fixing that ASAP.

Thanks for fixing it so quickly, this was a fun bug 😅 
![image](https://github.com/getsentry/sentry-dotnet/assets/1235055/ce3ff419-eab8-4784-9935-0edfb6d1b62c)

**Comment by bitsandfoxes** [comment]
Ooof.. Sorry about that 😓
