### ISSUE TITLE
[Question] How to differentiate unhandled vs handled exceptions?

### ISSUE THREAD

**Issue by tgreenman** [getsentry/sentry-dotnet#300]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [X] WPF
- [X] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

4.7.2
4.8

Please mark the NuGet packages used:

- [X] Sentry
- [ ] Sentry.Serilog
- [X] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Versions:

2.0.0-beta6
1.2.0

Please describe the the steps to reproduce the issue or link to a repository with a small reproducible code.

For my project, I want to immediately know what exceptions are handled vs unhandled. With the code below, I'm seeing the exception being logged as an error when it actually crashes the program. SDKs on Android, Cocoa, and sentry-native (crashpad) log unhandled exceptions as LogLevel.Fatal and/or with a tag handled:no. How can I differentiate what's handled vs unhandled on the c# lib?

```
namespace SentryTest
{
    class Program
    {
        static void Main(string[] args)
        {
            using (SentrySdk.Init("myDsnHere"))
            {
                int a = 0, b = 1;
                int c = b / a;
            }
        }
    }
```

**Comment by bruno-garcia** [comment]
Thanks for raising this! I agree we're missing this.

We should set the exception mechanism as `Handled=false`:

https://github.com/getsentry/sentry-dotnet-protocol/blob/afd65b92ed7122a628dc3631711b407f56e9a8a8/src/Sentry.Protocol/Exceptions/Mechanism.cs#L52

One way would be to set to the `exception.Data` a known key like `Sentry:Mechanism:Handled` to `false`, like here:

https://github.com/getsentry/sentry-dotnet/blob/8f76db7d3360cc76c7121ac5fcfd2d4a2b8448ee/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L33

And when processing the exception into a `SentryException`, look for that known key in the exception data, and if found, set the value:

https://github.com/getsentry/sentry-dotnet/blob/8f76db7d3360cc76c7121ac5fcfd2d4a2b8448ee/src/Sentry/Internal/MainExceptionProcessor.cs#L113

Would you be willing to open a PR with this change?

**Comment by tgreenman** [comment]
Yes, I'm willing to open a PR. I need to get some approvals to contribute to open source packages from my company but I can take it up after.

**Comment by ibm5155** [comment]
"How to differentiate unhandled vs handled exceptions?"
I do that the following way:
When my application opens I call SentrySdk.ConfigureScope and set a tag called "error.crash" to true

And every time I'm going to call CaptureException I do that inside of WithScope, where inside of it I set the tag "error.crash" to false.
It sure would be more interesting to use the handled tag since it's the one that's used on the dashboard

**Comment by bruno-garcia** [comment]
This was implemented:

https://github.com/getsentry/sentry-dotnet/blob/1ab7c273d569b356c2f32a0d16fac9749275507e/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L36-L40
