### ISSUE TITLE
Sentry causing major slowdown after update

### ISSUE THREAD

**Issue by TE-TBS** [getsentry/sentry-dotnet#3007]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0

### OS

Android

### SDK Version

3.41.3

### Steps to Reproduce

After updating from package 3.31.0 to 3.41.3 we are encountering major slowdowns in api responses (responses that took 20ms  now take up to 5000ms)

We are using both serilog and sentry.
Our (simplified) program.cs contains the following 
```
public static WebApplication CreateWebHostBuilder(string[] args) {
    var simpleLog = new LoggerConfiguration()
        .Destructure.AddApiDestructuring()
        .WriteTo.Console(LogEventLevel.Information)
        .CreateLogger();
    InitialSink = new RedirectableLogger(simpleLog);

    var logging = new LoggerConfiguration()
        .MinimumLevel.Information()
        .WriteTo.Logger(InitialSink);

    var builder = WebApplication.CreateBuilder(args);
    builder.Host.UseSerilog(logging.CreateLogger());
    .UseSentry();

    //configure startup below
}
```

The following two messages keep appearing in the (serilog) logs since the update. They appear with nearly any call to the api, and without any server interaction every few seconds.
`[Information] Sentry trace header is null. Creating new Sentry Propagation Context.`
`[Information] Started transaction with span ID '"xxxxxx"' and trace ID '"xxxxxxx"'.`

I suspected this might be caused by some logic for transactions or traces, 
I tried disabling traces (since we only use Sentry for error logging, we don't have any performance/health monitoring through Sentry). but this had no effect, the messages kept showing, and performance stayed poor.

`.UseSentry(o => {
         o.EnableTracing = false;
         o.TracesSampleRate = 0;
     })`

For now the only thing able to recover the performance is removing the '.UseSentry()' statement entirely (with the obvious consequences :P)

I tried to into the log messages online, but i couldn't find any useful references, so if this turns out to be a configuration fault on our side, sorry for reporting it as a bug, and any help would still be greatly appreciated. 

### Expected Result

normal performance

### Actual Result

subpar performance

**Comment by jamescrosswell** [comment]
Hey @TE-TBS, thanks for reaching out. I haven't seen this before. Is it possible to create a minimal reproduction of the issue in a sample project?

**Comment by bitsandfoxes** [comment]
Hey @TE-TBS, sorry to see you run into issues. I did some load testing with the SDK to see if I could reproduce this locally and this is what I came up with

```
| Version   | Sentry Configuration   | Requests/sec  |
|-----------|------------------------|---------------|
| Baseline  | Without Sentry         |       3903.43 |
| 3.31.0    | No Logs                |       3829.14 |
|           | With Debug Logs        |       2599.49 |
| 3.41.3    | No Logs                |       3885.60 |
|           | With Debug Logs        |       1950.94 |
```

So while there is not a noticeable difference in the SDK's base performance we do see a reduction in performance with debug logs enabled.
Is this what you're seeing in your project? Could you share more about your configuration?

The log `Sentry trace header is null. Creating new Sentry Propagation Context.` informs you that the incoming header did not contain a Sentry trace ID so the SDK is going to generate a new one to allow for [Distributed Tracing](https://docs.sentry.io/platforms/dotnet/usage/distributed-tracing/) even without performance enabled. Arguably this could be moved from level `Info` to `Debug`.

**Comment by TE-TBS** [comment]
Thanks for your reaction!

I checked, and our environment was running with 'debug = true' in the appsettings. setting it to was completely fixed the performance issues we were having.

**Comment by bitsandfoxes** [comment]
Hey @TE-TBS, glad to see this working out.
I'm closing this as I think optimizing for debug builds will probably be a disservice. We do need those logs there. :D
