### ISSUE TITLE
Send js sentry event from C# sdk

### ISSUE THREAD

**Issue by voltcode** [getsentry/sentry-dotnet#301]
Please mark the type framework used:

- [x ] ASP.NET MVC
- [x] ASP.NET Web API (OWIN)
- [x] ASP.NET Core

Please mark the type of the runtime used:
- [x ] .NET Framework
- [ x] .NET Core

* Version:
9.0.0

Please mark the NuGet packages used:

- [x ] Sentry

I have a fairly complex application and some custom error-catching logic. My application has to be able to run on-premises with restricted access to internet. In such cases, I'd like to catch frontend errors on-prem in C# sdk, save them offline, and recover either manually or by some periodically running batch process.

How can I send a sentry event (with exception information) for javascript Sentry Platform with support for source-maps ? 

I managed to send a sentry event with exception that is recognized by sentry as javascript, by overriding the Platform event in BeforeSend. This gives me stacktrace in sentry but no source maps support, no matter what I try.  I know this is a sort of cross-sdk issue but since I want to send this event from C# (because this is what I already use and what can have access to disk, etc.), I decided to first put it here. If this is not a good idea then please point me where to report this issue.

**Comment by voltcode** [comment]
I would also be grateful for any hints where to look at the logs for information on what could be going on wrong with source maps integration in my case.

**Comment by petrosmm** [comment]
![image](https://user-images.githubusercontent.com/8779484/68975335-fa240000-07c0-11ea-85f3-21ce28307bb7.png)

Hi @voltcode, I have an incomplete answer for you (similar question) but I was advised by a Sentry dev to follow these instructions and use a custom TransportClass.

**Comment by voltcode** [comment]
Thanks @petrosmm . I'm not sure how this would help in my case, as the JSON I send from C# seems ok when compared to json sent from JS - overriding event fields' values in BeforeSend seems to work (it's a hack though) . The problem I have is to find out, what should be present in the JSON so that the js source maps can work properly. I suspect it's something in C# sdk that prevents the sentry from looking up JS source maps for such hacked event.

**Comment by voltcode** [comment]
@petrosmm  can you post a link to the question you mentioned?

**Comment by petrosmm** [comment]
@voltcode I was in the discord JS chatroom and a nice dev answered me, (what I posted was a screenshot)

**Comment by iliya-timofeev** [comment]
Hi, I have the the same issue. Any solution so far?

**Comment by bruno-garcia** [comment]
I don't fully understand. It's the JS events you want to cache?
Why do you need the .NET SDK?
