### ISSUE TITLE
Add default metrics

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3020]
There are various metrics that have already been instrumented in .NET which users might be interested in sending to Sentry:

- [Built In Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics) that are accessible via the [System.Diagnostics.Metrics](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics) API.
- [Well known Counters](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters) 
- [Polly](https://github.com/App-vNext/Polly) resilience metrics
- [Available Threads](https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool.getavailablethreads?view=net-8.0)
- FirstChanceException
- [ObservableInstruments](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.meterlistener.recordobservableinstruments?view=net-8.0#system-diagnostics-metrics-meterlistener-recordobservableinstruments)

We'll likely resolve this issue in multiple Pull Requests:

- [ ] https://github.com/getsentry/sentry-dotnet/pull/3052
- [ ] https://github.com/getsentry/sentry-dotnet/pull/3100

**Comment by bruno-garcia** [comment]
> Furthermore, the Polly.Extensions package now provides seamless integration with IServiceCollection and facilitates the export of Polly’s telemetry events into .NET metrics.

https://devblogs.microsoft.com/dotnet/building-resilient-cloud-services-with-dotnet-8/

maybe something interesting to tap into

**Comment by jamescrosswell** [comment]
See [Built in Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics)

**Comment by bruno-garcia** [comment]
Added `FirstChanceException` to the list (I recall we talked about it but I couldn't find a ticket)

**Comment by jamescrosswell** [comment]
> Added `FirstChanceException` to the list (I recall we talked about it but I couldn't find a ticket)

Yeah I remember discussing it. Were we just thinking of a counter for that one (# of first chance exceptions)?

**Comment by optical** [comment]
I wanted to double check that sampling of Observable instruments (eg ObservableCounter) is on the radar for this? Just had a play with the experimental feature and noticed it wasn't reporting any of the observable instruments yet ([MeterListener.RecordObservableInstruments](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.meterlistener.recordobservableinstruments?view=net-8.0#system-diagnostics-metrics-meterlistener-recordobservableinstruments) is never invoked)

We are otherwise looking forward to trying out Metrics with Sentry

**Comment by bitsandfoxes** [comment]
> I wanted to double check that sampling of Observable instruments (eg ObservableCounter) is on the radar for this?

It is now!

**Comment by bitsandfoxes** [comment]
Sorry, we won't address this.
Superseded by https://github.com/getsentry/sentry-dotnet/issues/3597
