### ISSUE TITLE
[Sentry.OpenTelemetry] SentrySpanProcessor does not ignore Sentry requests

### ISSUE THREAD

**Issue by fastfend** [getsentry/sentry-dotnet#3028]
### Package

Other

### .NET Flavor

.NET Core

### .NET Version

8.0.0

### OS

Any (not platform specific)

### SDK Version

3.41.3

### Steps to Reproduce

1. **Use latest OpenTelemetry (version 1.7.0)**
2. Use `AddHttpClientInstrumentation` from `OpenTelemetry.Instrumentation.Http`
3. Use `AddSentry` in OTEL tracing and `UseOpenTelemetry` in Sentry

### Expected Result

Sentry should not include requests from HttpClient instrumentation to itself

### Actual Result

HUGE amount of transactions (managed to obliterate my selfhosted sentry instance)
From my debug its because OTEL library no longer use `http.url`. They moved to `url.full`

Releated PRs:
- open-telemetry/opentelemetry-dotnet#4606
- open-telemetry/opentelemetry-dotnet#4639
- open-telemetry/opentelemetry-dotnet#5068

**Comment by fastfend** [comment]
I found that this was fixed in #3001. Can you tell what's the ETA of next release?

**Comment by fastfend** [comment]
Also marking as duplicate of #2998

**Comment by bitsandfoxes** [comment]
It's already been released in `4.0.0-beta.7` but I guess having to bump the major version of the SDK for the fix is not very appealing.
I'll see if we can backport it and get another `3.41.x` out.

**Comment by bitsandfoxes** [comment]
Resolved in the `3.41.4` release. Sorry for the delay.
