### ISSUE TITLE
Method not found: 'Sentry.Protocol.SentryId Sentry.SentrySdk.CaptureException(System.Exception)'

### ISSUE THREAD

**Issue by zahidcakici** [getsentry/sentry-dotnet#3031]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

8.0.0

### OS

macOS

### SDK Version

3.41.3

### Steps to Reproduce

I was using ```Sentry.AspNetCore 2.1.x``` with .Net Core 3.1
I updated project to .Net 8 and package to ```Sentry.AspNetCore 3.41.3```

SDK config:
```
builder.WebHost.UseSentry();
```

app.settings.json:
```
"Sentry": {
    "Dsn": "<myDsn>",
    "IncludeRequestPayload": true,
    "IncludeActivityData": true,
    "Logging": {
      "MinimumBreadcrumbLevel": "Warning"
    }
  }
```

Usage:
```
catch (Exception ex)
{
    SentrySdk.CaptureException(new IntegrationEventException(data: @event, ex));
    throw ex;
}
```

### Expected Result

no crashes

### Actual Result

```
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'Sentry.Protocol.SentryId Sentry.SentrySdk.CaptureException(System.Exception)'.
         at Storex.AspNetCore.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Storex.AspNetCore.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by rfink** [comment]
Having this same issue with .NET 8 and Sentry 4.1.0

**Comment by jamescrosswell** [comment]
> Having this same issue with .NET 8 and Sentry 4.1.0

@rfink have you [checked our samples](https://github.com/getsentry/sentry-dotnet/blob/9d52929356ef8285ba188aea81809902b587f4fd/samples/Sentry.Samples.AspNetCore.Basic/Program.cs#L63-L64), demonstrating this functionality? If so, it'd be good to understand what you're doing differently to the samples (which do work).
