### ISSUE TITLE
Wrong line number with debug symbols

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#3035]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

6.41.3

### OS

Windows

### SDK Version

3.41.3

### Self-Hosted Sentry Version

24.1.0

### Steps to Reproduce

I am still investigating how it happened since it didn't happen on my machine, but it seems like the Sentry SDK made this error?

### Expected Result

One group of issues with the correct line number

### Actual Result

The below issue seems to be correct
https://sentry.lkp.app.br/share/issue/5323129ddeb3486fb37b0ef8fcaf6379/#images-loaded

The second group seems to have a bad line number for `SentryMiddleware.cs`
and on `Dictionary.cs`  the error happened on `bool modified = TryInsert(key, value, InsertionBehavior.ThrowOnExisting);` but instead it marked on `}`
NOTE: on the correct stacktrace log there are two extra lines before the `public void Add(TKey key, TValue value)`, since the stacktrace is off by two, maybe it's correlated by the lack of the first two lines on the wrong log?
https://sentry.lkp.app.br/share/issue/1aa570f7e2c446dab2b7176f8baaf04d/

Also the Debug ID for the symbols on both issues are the same

**Comment by bruno-garcia** [comment]
We get the line number from .NET itself. There's an open ticket on dotnet/runtime:

* https://github.com/dotnet/runtime/issues/44986

**Comment by jamescrosswell** [comment]
@lucas-zimerman closing this for now. If it's still an issue and you can describe how to reproduce then let me know and we can reopen.
