### ISSUE TITLE
Extract endpoint routing information and add to event

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#304]
Today the `Transaction` field is not being populated. 

Now with ASP.NET Core 3.0 and Endpoint Routing it should be possible to get the route template from the Sentry Middleware and add the route template to outgoing events.

[The docs say](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0):
```
    Calling HttpContext.GetEndpoint gets the endpoint.
    HttpRequest.RouteValues gets the collection of route values.
```

**Comment by lucas-zimerman** [comment]
Transaction field is now set:

https://github.com/getsentry/sentry-dotnet/blob/ea877c7ad6e7eb53abc2b4582841b048ad00594e/src/Sentry.AspNetCore/SentryMiddleware.cs#L107

When evaluating the event, we retrieve the TransactionName on Populate
https://github.com/getsentry/sentry-dotnet/blob/ea877c7ad6e7eb53abc2b4582841b048ad00594e/src/Sentry.AspNetCore/ScopeExtensions.cs#L90

And after evaluating the scope we apply the TransactionName to the Event
https://github.com/getsentry/sentry-dotnet/blob/ea877c7ad6e7eb53abc2b4582841b048ad00594e/src/Sentry/Scope.cs#L367
