### ISSUE TITLE
4.0.0 breaking change announcements in bindings

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3041]
Not sure we recorded this on the changelog:

<img width="398" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/1633368/bca2572a-88c5-43d1-9ffc-d241613f6c33">

But this broke because we renamed `Android`here to `Native`.
Also `EnableAndroidSdkTracing` became `EnableTracing` which is short for TracesSampleRate = 1.0

**Comment by bruno-garcia** [comment]
Realized while doing this: https://github.com/getsentry/symbol-collector/pull/176

**Comment by bitsandfoxes** [comment]
We have both Android and iOS -> Native: https://github.com/getsentry/sentry-dotnet/blob/24c159fac119315e21df6138dc04bfe3ccd573c2/CHANGELOG.md?plain=1#L110

And `Also EnableAndroidSdkTracing became EnableTracing` https://github.com/getsentry/sentry-dotnet/blob/24c159fac119315e21df6138dc04bfe3ccd573c2/CHANGELOG.md?plain=1#L111

**Comment by bruno-garcia** [comment]
@bitsandfoxes 

>  Also EnableAndroidSdkTracing became EnableTracing which is short for TracesSampleRate = 1.0
