### ISSUE TITLE
add mask config

### ISSUE THREAD

**Issue by EngRajabi** [getsentry/sentry-dotnet#305]
Please mark the type framework used:

-  ASP.NET Core

Please mark the type of the runtime used:

-  .NET Core

* Version:
1.2.0

Please mark the NuGet packages used:

- Sentry
- Sentry.AspNetCore

add mask config, like 
```json
  "Sentry": {
    "Dsn": "https://<key>@sentry.io/<project>",
    "IncludeRequestPayload": true,
    "SendDefaultPii": true,
    "MinimumBreadcrumbLevel": "Debug",
    "MinimumEventLevel": "Warning",
    "AttachStackTrace": true,
    "Debug": true,
    "DiagnosticsLevel": "Error",
    "SanitizeKeys": "[/_token$/, /password/i, 'someHidiousKey']"
  },
```

**Comment by bruno-garcia** [comment]
We currently have no plans to add data scrubbing to the SDKs.
We're releasing soon a `relay` process where you can configure all data to be scrubbed before it's sent to Sentry or stored anywhere. You can make rules that apply for the whole event etc.

You can scrub data in the SDK though via the `BeforeSend` or creating an event processor. You get a reference of an event each time they are about to be sent out.

**Comment by bruno-garcia** [comment]
Sentry has improved even further the data scrubbing capabilities on the server.
Other than that you have access to the complete event through BeforeSend and EventProcessors.

We still don't plan to add some data scrubbers to the SDK so closing this for now.
