### ISSUE TITLE
Source context missing in UI, .pdbs missing, build seems configured, Sentry CLI warning in build

### ISSUE THREAD

**Issue by vmandic** [getsentry/sentry-dotnet#3056]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

7.0.203

### OS

Linux

### SDK Version

3.31.0

### Steps to Reproduce

1. Build AspNet Core web app SDK v7.0.203 project with Sentry.AspNetCore 3.31.0 under Ubuntu 20 linux with a Dockerfile based build

2. Produces a build command like:

```log
...
#30 [build 21/23] RUN dotnet publish -c release -o /app -r linux-musl-x64 --no-restore -p:TieredPGO=true     --self-contained true -p:DebugType=Portable -p:DebugSymbols=true     -p:Version=2024.01.16.1748-sha-878ac24 -p:UseSentryCLI=true -p:SentryOrg=CompanyName -p:SentryProject=api -p:SentryUploadSymbols=true -p:SentryUploadSources=true
#30 1.326 MSBuild version 17.5.1+f6fdcf537 for .NET
#30 24.20   CompanyName.Common -> /source/CompanyName.Common/bin/linux-musl-x64/release/net7.0/CompanyName.Common.dll
#30 24.26     INFO    2024-01-16 17:49:33.836737675 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.31.0/tools/sentry-cli-Linux-x86_64" "info" "--no-defaults"

// is this maybe problematic?
#30 24.43   The Sentry CLI is not fully configured with authentication, organization, and project.

#30 40.74   CompanyName.Data -> /source/CompanyName.Data/bin/linux-musl-x64/release/net7.0/CompanyName.Data.dll
#30 40.83     INFO    2024-01-16 17:49:50.400973806 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.31.0/tools/sentry-cli-Linux-x86_64" "info" "--no-defaults"
...
```

3. Run the web app on a server and produce an exception that is sent successfully to Sentry.io

4. Missing source context, missing pdbs reported in UI.

### Additional info

- Issue ID: 4875845601
- Project: 5239187

We do not have any specific .csproj configurations for Sentry, we relay on the build -p flags as you can see above.

Can you please instruct what are we missing or what we should do to have .pdbs pushed to your service? As much as we have investigated, we have not made any changes but this has been going on now for some time (months).

Should we first try upgrading to latest library version? Do you have known issues related to this?

I went thru the ref doc but don't see a solution to this: https://docs.sentry.io/platforms/dotnet/data-management/debug-files/source-context/

Thank you,
V.

### Expected Result

Expect to see own source not only stack trace and pdbs reported as received on sentry.io, no build warnings.

### Actual Result

Missing source context and .pdb files in Sentry.io UI, only stack trace available.

**Comment by vmandic** [comment]
The issue is caused if we are missing SENTRY_AUTH_TOKEN in env or the rc file?

**Comment by jamescrosswell** [comment]
> // is this maybe problematic?
> #30 24.43   The Sentry CLI is not fully configured with authentication, organization, and project.

The CLI is what uploads the symbols to Sentry so, yeah, that will be the problem.

Here are [the docs on how to configure the Sentry CLI](https://docs.sentry.io/product/cli/configuration/) (or [here](https://docs.sentry.io/platforms/dotnet/data-management/debug-files/upload/)).

**Comment by vmandic** [comment]
Thanks @jamescrosswell, so I have ensured that the ENV now has the token by the name Sentry expects in our Dockerfile build but we are still getting the same warning.

```dockerfile
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
```

I will try next replacing all of the -p: flags with ENV variables per your instructions.

I observed one strange (but somewhat secure and expected thing) while debugging this token value locally. I could not see it (the passed value from ARG to ENV) in the debugged container in my attached shell. I guess Sentry (CLI) removes it after using it during build?

Is there a way to get more debug info to see what am I missing for the CLI setup?

**Comment by jamescrosswell** [comment]
Mysterious.  The Sentry CLI has various other commands that might help you... like [sentry-cli debug-files find](https://docs.sentry.io/product/cli/dif/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-dotnet%2Fissues%2F3056#finding-files).

You could try calling [sentry-cli debug-files upload](https://docs.sentry.io/product/cli/dif/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsentry-dotnet%2Fissues%2F3056#uploading-files) directly as well... even if it doesn't work, hopefully the output from that command would give you some clues?

**Comment by vmandic** [comment]
The env auth token is gone as we use another docker stage... figures, so locally I do not have it. But, locally I retested the docker build and it works when I force the same upload options through --build-arg, but doing the exact same (from what I understand so far and have observed) from a CI Linux builder does not work.

In CI I pass the token from protected env vars of the git management system.

On the CI I managed to enforce the token to be saved to the container even and check if it is not a network issue with sentry-cli (had to install it via your docs by curl call to your .sh) to your servers and it is not I managed to run a manual upload as per docs here: https://docs.sentry.io/platforms/apple/sourcecontext/

I tried creating an ORG auth token (as now I have used the custom integration one due to more scopes) and that causes a different error to start showing up:

```log
#30 [build 21/23] RUN dotnet publish -c release -o /app -r linux-musl-x64 --no-restore -p:TieredPGO=true     --self-contained true -p:DebugType=Portable -p:DebugSymbols=true     -p:Version=2024.01.29.1118-sha-73bc619 -p:UseSentryCLI=true -p:SentryOrg=Company -p:SentryProject=company-project-name -p:SentryUploadSymbols=true -p:SentryUploadSources=true
#30 1.243 MSBuild version 17.5.1+f6fdcf537 for .NET
#30 17.20   Company.ProjectLib1 -> /source/Company.ProjectLib1/bin/linux-musl-x64/release/net7.0/Company.ProjectLib1.dll
#30 17.26     INFO    2024-01-29 11:18:49.106078410 +00:00 sentry-cli was invoked with the following command line: "/root/.nuget/packages/sentry/3.31.0/tools/sentry-cli-Linux-x86_64" "info" "--no-defaults"
#30 17.48 /root/.nuget/packages/sentry/3.31.0/buildTransitive/Sentry.targets(104,5): warning : Sentry API request failed.  Either the authentication info is invalid, or the Sentry server could not be reached. [/source/Company.ProjectLib1/Company.ProjectLib1.csproj]
... repeates the same error for all of our project referenced libs
```

Next, I will try by forcing it directly the -p:SentryAuthToken MSBuild flag (just for test, I read your guide: https://docs.sentry.io/platforms/dotnet/configuration/msbuild/).

For some reason, my docker build inside a git system docker builder container fails with this, and it can't be missing project and org name as they are passed directly.

Also, I could try the /root/.sentryclirc file first.

**Comment by vmandic** [comment]
Solved, I am very sorry to drag you around for this, but the token was missing as some stuff changed in the CI configs.

To give some value out of this, it would be VERY useful if you guys wold just print out the token is missing :- )

I will let you close this when you acknowledge my update, thanks once again.

**Comment by bitsandfoxes** [comment]
Thanks for letting us know! I'm glad it worked out.
We're going to improve the logging there.
