### ISSUE TITLE
Allow uploading commits through `set-commits` 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3058]
`sentry-cli` is bundled in the SDK adn invoked via msbuild
* https://github.com/getsentry/sentry-dotnet/issues/2074

The ticket was resolved but 2 items were not completed:

* Uploading [commit info](https://docs.sentry.io/product/cli/releases/#sentry-cli-commit-integration), to unlock [suspect commits](https://docs.sentry.io/product/issues/suspect-commits/)
* [Uploading release details](https://docs.sentry.io/product/cli/releases/), to enable features like [Release Health](https://docs.sentry.io/product/releases/health/), resolving [issue by release](https://docs.sentry.io/product/releases/#track-release-health) and "First seeing in Release X".

But we don't upload any commit information. This would be helpful when doing a CI run for publishing a new version. For example:

```sh
dotnet publish -c Release /p:SentrySetCommits
```

Associating commits allows Sentry to link to source code at the correct commit sha.
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/caa27b44-6627-4ecc-9972-03bf1f33511f)

As well as suggest suspect commits, and other features.

If we can land this on 4.0.0 we could default to making this call when msbuild `publish` target is running

**Comment by jamescrosswell** [comment]
[Source Link included in the .NET SDK](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link) for version 8.0 and later.
