### ISSUE TITLE
Sentry only logging when an exception is thrown

### ISSUE THREAD

**Issue by flockoftanks** [getsentry/sentry-dotnet#309]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core

* Version: 2.1

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [x] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 1.2.0

This is a .NET Core console application.  To make logging available to other classes and services, I'm injecting it in my ConfigureServices method.

```cs
string env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
var sentryConfig = Configuration.GetSection("Sentry");
services.AddLogging((b) => {
    b.AddSentry((o) => {
        o.Dsn = sentryConfig["Dsn"];
        o.Environment = env;
        o.Release = sentryConfig["Release"];
    });
});
````

Later I can retrieve this logger from the available services and log to Sentry.

```cs
var logger = serviceProvider
    .GetService<ILoggerFactory>()
    .CreateLogger<Program>();

logger.LogError("Logger is working!");
```

The problem is, this error only ever makes it to Sentry if, somewhere after I call this LogError message, an actual exception is thrown.  It's behaving as if "logger.LogError" adds the error to a list of things to be sent out eventually, but is never actually sent. Not until, that is, until

```cs
throw new Exception("this is an exception");
```
completes whatever circuit it completes and sends ALL the logged errors to Sentry.  I see no reason from the samples and documentation why `logger.LogError()` shouldn't work on its own, but I can't tell if this is a bug or if I've configured something incorrectly.

Thanks, all.

**Comment by bruno-garcia** [comment]
@flockoftanks `LogError` doesn't block the calling thread while attempts to send the event to Sentry. It adds the message to an in-memory queue where a worker picks it and flushes to Sentry in the background. If you `throw` and that crashes your app, the SDK detects the app is about to be terminates and makes sure the in-memory queue is flushed before quitting (does that by blocking the calling thread while it waits for the worker to finish).

You can flush the events with `await SentrySdk.FlushAsync(timeout)`.
`SentrySdk.Init` returns a `IDisposable` which serves this purpose too. It will flush any pending events before exiting, to make sure you don't lose any events.

**Comment by josh-degraw** [comment]
@flockoftanks was the above answer able to resolve your issue?

**Comment by flockoftanks** [comment]
@josh-degraw The question regarding why I was seeing this behavior was definitely answered, yes, and thank you @bruno-garcia!

Maybe this should be converted from a question to a feature request as the stated behavior makes this library useful when logging errors from a stack of errors, but if I never explicitly tell the events log to flush (something that may be difficult to do consistently across an entire application, I may never see the notices I'm sending to the logs, and flushing every time I type `logger.LogError(...)` feels dirty.

I guess I would expect `logger.LogError(...)` to log an error to Sentry, not hold on to it until it just happens to flush for some reason, but this is just me thinking out loud.

Thanks all!
I guess I'd be looking f
