### ISSUE TITLE
AppSettings values not working using latest Sentry

### ISSUE THREAD

**Issue by elfico** [getsentry/sentry-dotnet#3114]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

8.0.0

### OS

Windows

### SDK Version

4.0.0

### Steps to Reproduce

This bug has to do with the AspNetCore library. It also affects deployments on Azure when using Azure Application Settings.

1. Upgrade Sentry.AspNetCore nuget packages to "4.0.0" 

2. Add Sentry in appsettings.json 
```
"Sentry": {
  "Dsn": "<Your DSN>",
  "MaxRequestBodySize": "Always",
  "IncludeRequestPayload": true,
  "SendDefaultPii": true,
  "IncludeActivityData": false,
  "MinimumBreadcrumbLevel": "Information",
  "MinimumEventLevel": "Warning",
  "AttachStackTrace": false,
  "Debug": false,
  "DiagnosticsLevel": "Error",
  "TracesSampleRate": 1.0
}
```

3. Run project

### Expected Result

Project should run and initialize sentry.

### Actual Result

Throws an error:
HTTP Error 500.30 - ASP.NET Core app failed to start 

Details:

ArgumentNullException: Value cannot be null. (Parameter 'You must supply a DSN to use Sentry.To disable Sentry, pass an empty string: "".See https://docs.sentry.io/platforms/dotnet/configuration/options/#dsn')

In Azure if we set the Application setting using the key : `SENTRY_DSN`, then it works.

**Comment by jamescrosswell** [comment]
Are you using Serilog by any chance?

**Comment by jamescrosswell** [comment]
Curious... I'm not able to reproduce this. Do you think you could provide a small example program that demonstrates this issue (e.g. as a GitHub repo)?

**Comment by jamescrosswell** [comment]
Here's the Minimal API that I tested (binding configuration to appsettings.json and using NLog for logging):

```csharp
using NLog;
using NLog.Config;
using Sentry;

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseSentry(); 

LogManager.Configuration = new LoggingConfiguration();
LogManager.Configuration
    .AddSentry(o =>
    {
        // Optionally specify a separate format for message
        o.Layout = "${message}";
        // Optionally specify a separate format for breadcrumbs
        o.BreadcrumbLayout = "${logger}: ${message}";

        // Debug and higher are stored as breadcrumbs (default is Info)
        o.MinimumBreadcrumbLevel = NLog.LogLevel.Debug;
        // Error and higher is sent as event (default is Error)
        o.MinimumEventLevel = NLog.LogLevel.Info;

        // Send the logger name as a tag
        o.AddTag("logger", "${logger}");

        // All Sentry Options are accessible here.
    });

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
    {
        SentrySdk.CaptureMessage("Retrieving the weather forecast");
        var forecast = Enumerable.Range(1, 5).Select(index =>
                new WeatherForecast
                (
                    DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
            .ToArray();
        app.Logger.LogInformation("Retrieved weather forecast: returning to client");
        return forecast;
    })
    .WithName("GetWeatherForecast")
    .WithOpenApi();

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

**Comment by elfico** [comment]
> Curious... I'm not able to reproduce this. Do you think you could provide a small example program that demonstrates this issue (e.g. as a GitHub repo)?

Sorry for the late reply. I will do a minimal reproduction and send it.

**Comment by Silvenga** [comment]
Might be related to https://github.com/getsentry/sentry-dotnet/issues/3134 - but in our case, we want to not configure Sentry when no DSN is specified.

**Comment by jamescrosswell** [comment]
> Might be related to #3134 - but in our case, we want to not configure Sentry when no DSN is specified.

Possibly related. If you were having issues with the config bindings more generally, that would explain why you ended up with a null DSN (even though you'd supplied it as an environment variable). If there's any way you can provide a small sample project that reproduces this, that would really help. So far I haven't been able to reproduce the issue @elfico reported.

**Comment by elfico** [comment]
@jamescrosswell 
Here is a repo that shows a minimal working example: https://github.com/elfico/sentry-extension-example

**Comment by jamescrosswell** [comment]
> [@jamescrosswell](https://github.com/jamescrosswell) Here is a repo that shows a minimal working example: https://github.com/elfico/sentry-extension-example

Hey @elfico , thanks for the repo. 

I noticed in your Startup class [you have the following](https://github.com/elfico/sentry-extension-example/blob/main/SentryExtensionExample/Startup.cs#L56-L64) to initialize the SDK:

```csharp
            //initialize sentry sdk
            SentrySdk.Init(sentry =>
            {
                SentryOptions options = new SentryOptions();

                // Add this to the SDK initialization callback
                // To set a uniform sample rate
                options.TracesSampleRate = 1.0;
```

So none of the options you're configuring there are being used for anything (that `options` variable passes out of scope and gets garbage collected at the end of the callback). 

You wouldn't generally new up any options in the callback - rather the options get passed in as a parameter... so that code should look like this instead:

```csharp
            //initialize sentry sdk
            SentrySdk.Init(options =>
            {
                // Add this to the SDK initialization callback
                // To set a uniform sample rate
                options.TracesSampleRate = 1.0;
```
 
Also, if you're initializing via `SentrySdk.Init` (which you'd typically do in a Console app) then you don't get configuration bindings out of the box... meaning none of the config from your `appsettings.json` file will be used. You could wire it up to work but it's a bit unusual. 

Instead, I'd just move all of that initialization from your `Startup` class to `Progra.CreateHostBuilder` (you're calling `UseSentry` there and that's where you do get configuration bindings). 

This fixes the problem. The reason you were getting the null DSN error is that you were calling SentrySdk.Init without any DSN (and since this method doesn't read the configuration from your appsettings.json, it was throwing an exception).

**Comment by elfico** [comment]
Thanks @jamescrosswell 
I followed your suggestions and it works well now.
I wonder why it was working well prior to the upgrade.
