### ISSUE TITLE
Performance Query Logging for SqlClient in Asp.Net 4.8

### ISSUE THREAD

**Issue by jayholliday** [getsentry/sentry-dotnet#3115]
### Package

Sentry.AspNet

### .NET Flavor

.NET Framework

### .NET Version

4.8

### OS

Windows

### SDK Version

3.41.4

### Steps to Reproduce

1) We're trying to automatically capture SQL Queries in a very old and large application but no queries are being captured after following the instructions. To reproduce problem in a much smaller scale that can be shared I've taken an old Sentry sample app from https://github.com/getsentry/examples/tree/81fb90b957ce9a8c1f6222d1603d0fa499ecba7e/dotnet/AspNetMvc5Ef6 and updated it to use current framework and Sentry versions, this was very simple.  I also added a button to make a SqlClient call in the application. This is the simple function called when the new button gets clicked;
```
// Example: A SqlClient call to be captured by Sentry:
[HttpPost]
public ActionResult SqlClientLookup()
{
    string mConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
    string sql = "SELECT [ID], [Name] FROM [dbo].[AspNetRoles]";
    using (var conn = new SqlConnection(mConnectionString))
       {
           conn.Open();
           using (var cmd = new SqlCommand(sql, conn))
           {
                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Console.WriteLine(reader["Name"]);
                    }
                }
            }
        }

    return View("Index");
}
```
I can share that small (140MB) updated sample app with you if you'd like it.
2) We're using the Sentry, Sentry.AspNet, Sentry.DiagnosticSource and Sentry.EntityFramework packages from Nuget, all at version 3.41.4 
3) I find that it does log the EF queries but not the SqlClient queries.

### Expected Result

Based on the documentation I'm expecting the SqlClient queries to be logged just like the EF queries are logged.

### Actual Result

No Sql Client queries get logged.

**Comment by jayh13** [comment]
I've tried sending the link to the project files to the supplied email and am getting back a response of "The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces." Can you double check the email address you supplied please? I guess I could also break the zip into 5 parts and upload them here if you prefer.

**Comment by bitsandfoxes** [comment]
Sorry about that. A typo in my own name.. It's corrected now.

**Comment by jayh13** [comment]
Hi Stefan

I wanted to check-in to make sure you were able to download the sample
project and to see if you've had a chance to look at it yet?

Sorry about the slow follow up, I was out on Thursday and Friday and I'm
just getting back to it now. Unfortunately I'll be out the first half of
next week too in case you try to get a hold of me then, bad few weeks.

Thanks
    Jay

**Comment by bitsandfoxes** [comment]
Yes @jayh13! Thanks for providing the sample! I will get back to you as soon as possible.

**Comment by bitsandfoxes** [comment]
Thanks again for the repro. It's odd and I'm not entirely sure what's going on there. The integrations are subscribing all correctly but the queries are not getting picked up. It's not what I would expect. We're going to look into this.

**Comment by jamescrosswell** [comment]
Sorry for the delay on this... it took me a while to get the tooling going to debug an ASP.NET project in the context of the Sentry solution.

In any case, I found [this thread from Simon Cropp back in 2022 ](https://github.com/dotnet/SqlClient/issues/1529#issuecomment-1063166442). Apparently DiagnosticSource isns't supported on .NET Framework.

We do have this issue open in the Sentry repository to come up with some kind of workaround using Event Source:
- https://github.com/getsentry/sentry-dotnet/issues/1974
