### ISSUE TITLE
Mark uncaught exceptions as `handled=false`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#313]
We need to mark exceptions that were not handled by user code as `handled=false`.

That means when we capture something via the the UnhandledExceptionHandler like:

https://github.com/getsentry/sentry-dotnet/blob/f4f9c908183f462b6ed6e703ae77e3e5093b3d61/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L33

We should give some context so while building the SentryException, we can define the Mechanism, and whether it was handled or not.

https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry/Internal/MainExceptionProcessor.cs#L109

**Comment by bruno-garcia** [comment]
@lucas-zimerman you've done this right?

**Comment by lucas-zimerman** [comment]
yup, my first PR :D
