### ISSUE TITLE
Run tests on LTS runtimes

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#314]
Multi-target test projects to run on LTS runtimes .NET Core 2.1, 3.0 (then 3.1 when it's out)

**Comment by snakefoot** [comment]
LTS is 2.1 (Not 2.2)

**Comment by snakefoot** [comment]
NetCore 3.1 is now out

**Comment by bruno-garcia** [comment]
That’s great news. Would you like to submit a PR? Tks

**Comment by bruno-garcia** [comment]
We're running tests on both .NET Core LTS versions: 3.1 and 2.1

https://github.com/getsentry/sentry-dotnet/blob/6e71b6c7794bb8cb99584477ed1a9cb64821a1cb/test/Sentry.Tests/Sentry.Tests.csproj#L4
