### ISSUE TITLE
Should config values from Environment variables override other settings?

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3140]
@slonopotamus [suggested in another issue](https://github.com/getsentry/sentry-dotnet/issues/3134#issuecomment-1936099357) that setting the DSN in an environment variable should override an empty string (i.e. disabled) value that has been set via other bindings (like appsettings.json). 

This would be more consistent with [how things are done in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0#non-prefixed-environment-variables):

> Using the [default](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0#default) configuration, the [EnvironmentVariablesConfigurationProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.environmentvariables.environmentvariablesconfigurationprovider) loads configuration from environment variable key-value pairs after reading appsettings.json, appsettings.{Environment}.json, and [user secrets](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-8.0). Therefore, key values read from the environment override values read from appsettings.json, appsettings.{Environment}.json, and user secrets.

I think if we do this, it shouldn't be just for the DSN and shouldn't be just for the disabled DSN value... but that env variables trump other provider sources more generally. 

However this is likely a breaking changes as we may have many customers who have their production environments configured based on the current behaviour.

**Comment by bitsandfoxes** [comment]
See https://github.com/getsentry/sentry-dotnet/issues/3143#issuecomment-1970955309
