### ISSUE TITLE
Sentry init fails with empty DSN string

### ISSUE THREAD

**Issue by klemmchr** [getsentry/sentry-dotnet#3144]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

8.0.100

### OS

Windows

### SDK Version

4.1.0

### Steps to Reproduce

1. Create an ASP.NET application and add Sentry to the Web Host using `UseSentry`.
2. Create the configuration section in `appsettings.json` and specify an empty DSN

### Expected Result

Sentry skips initialization without throwing any error.

### Actual Result

Sentry throws an error that an empty DSN should be specified.

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'You must supply a DSN to use Sentry.To disable Sentry, pass an empty string: "".See https://docs.sentry.io/platforms/dotnet/configuration/options/#dsn')
   at Sentry.Internal.SettingLocator.GetDsn()
   at Sentry.SentrySdk.InitHub(SentryOptions options)
   at Sentry.Extensions.Logging.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c__0`1.<AddSentry>b__0_3(IServiceProvider c)
```

I can confirm that the DSN value is taken from the configuration as the DSN is already an empty string in the configuration callback.
![image](https://github.com/getsentry/sentry-dotnet/assets/6552521/09f6fd40-48e2-43ef-a6a6-46d805c6f80e)

Manually setting the DSN using the code shown above does not work either. Manually assigning `string.Empty` to the DSN also does not work.

**Comment by jamescrosswell** [comment]
@klemmchr is this an ASP.NET Core application? Are you able to share some code (a tiny demo app illustrating the problem)?

**Comment by klemmchr** [comment]
Sorry, my bad. There was some code that was setting the dsn to null using PostConfigure. Totally missed that.
