### ISSUE TITLE
Filters not being honored

### ISSUE THREAD

**Issue by RobTF** [getsentry/sentry-dotnet#3149]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0 (MAUI)

### OS

Android

### SDK Version

4.1.0

### Steps to Reproduce

Maybe I'm doing something obviously wrong, but I want to intercept transactions/errors/exceptions anything and none of the filters and interception points are ever called. Data ends up in the Sentry portal and my filters or callbacks never fire.

1. Add sentry to an app with the following;

```c#
        return builder
            .UseSentry(options =>
            {
                options.Environment = "myenv";
                options.Release = "1.0.0";
                options.Distribution = "1";
                options.IncludeTitleInBreadcrumbs = true;
                options.IncludeBackgroundingStateInBreadcrumbs = true;
                options.CaptureFailedRequests = false;
                options.SetBeforeSendTransaction(tran =>
                {
                    Console.WriteLine("!!!!!!!!!!!!!!AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
                    return tran;
                });
            });
```

### Expected Result

Before send transaction callback is called.

### Actual Result

Callback is not called.

**Comment by jamescrosswell** [comment]
Hi @RobTF ,

This is working fine for me.

Are you setting the DSN and the TracesSampleRate? See the [MAUI getting started docs](https://docs.sentry.io/platforms/dotnet/guides/maui/) for details. 

You'd also need to create a transaction somewhere in your code in order to observer this filter. For example:

```csharp
    private void OnCounterClicked(object sender, EventArgs e)
    {
        var transaction = SentrySdk.StartTransaction("MainPage", "CounterClicked");
        try
        {
            count++;

            if (count == 1)
                CounterBtn.Text = $"Clicked {count} time";
            else
                CounterBtn.Text = $"Clicked {count} times";

            SemanticScreenReader.Announce(CounterBtn.Text);
        }
        finally
        {
            transaction.Finish();
        }
    }
```

**Comment by RobTF** [comment]
Hi @jamescrosswell,

Thanks for the reply - I've just figured it out. With MAUI it looks like the handlers and callbacks _do_ work after all as I see the side effects, but you cannot set breakpoints within them as they just get ignored. I was sticking a breakpoint in to see if it got hit so I could look at the `SentryEvent` object, Breakpoints seem to work everywhere else.

I think this is yet another MAUI issue, not a Sentry client issue. This can be closed, thanks!
