### ISSUE TITLE
`SentryOptions.BeforeSend` is no longer testable

### ISSUE THREAD

**Issue by jozefizso** [getsentry/sentry-dotnet#3161]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

4.6.2

### OS

Windows

### SDK Version

4.1.2

### Steps to Reproduce

We upgraded the `Sentry.Serilog` to v4.1.2 from v3.30.0.

The public `SentryOptions.BeforeSend` function was changed to `SentryOptions.SetBeforeSend()`.

The original `BeforeSend` was a public function so we could unit test the `BeforeSend` handler.

```cs
public Func<SentryEvent, SentryEvent?>? BeforeSend { get; set; }
```

Because `SetBeforeSend()` makes the function private, there is no way to test if the `BeforeSend` correctly modifies the `SentryEvent` data.

### Expected Result

The `BeforeSend` handler function must be public and testable.

### Actual Result

Sentry code for before send filter is no longer testable.

**Comment by jamescrosswell** [comment]
Hi @jozefizso,

There are a bunch of tests for `SetBeforeSend` in this repository, which I think is the right place for these tests to live. 

If you did want to write integration tests in your code, you could probably copy the pattern from one or more of those tests. Something like this, for example:

https://github.com/getsentry/sentry-dotnet/blob/5fab09efd4204fd07d95c818df79f7aa71d61e88/test/Sentry.Tests/SentryClientTests.cs#L271-L282

What you're really testing in your code is that the way you're using SetBeforeSend has the effect you want it to... not that the SetBeforeSend method itself works (that's the job of the unit and integration tests for the Sentry SDK).

**Comment by jozefizso** [comment]
Hi @jamescrosswell, thanks for the hint, yeah, that's kind of integration test we need for our `BeforeSend` handler.
