### ISSUE TITLE
Make sure Sentry.AspNetCore works with Blazor

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#317]
https://forum.sentry.io/t/sentry-is-not-captureing-errors-in-my-aspnetcore-3-0-blazor-app/8269

**Comment by DominikPf** [comment]
Client-Side Blazor (WebAssembly) also don't work.

My Setup: Serilog with Serilog.Sentry Sink.
```c#
services.AddLogging(builder =>
{
    builder
        .ClearProviders()
        .AddSerilog(new LoggerConfiguration()
            .MinimumLevel.Information()
            .WriteTo.Sentry("mydsn")
            .CreateLogger())
        .SetMinimumLevel(LogLevel.Trace);
});
```

I think for Blazor WebAssembly (Client-Side) a little bit more of configuration is needed. The internal HttpClient of Sentry cannot be created manually (or i don't found it). In Blazor the HttpClient can be injected via DI. Sentry only allows to create a HttpClientMessageHandler or to configure a already created HttpClient. Maybe a CreateHttpClient func can help?

**Comment by bruno-garcia** [comment]
I'd expect `new HttpClient` to work normally in blazor wasm. 

Does a simple: `SentrySdk.Init` and `SentrySdk.CaptureMessage("..")` work though?

**Comment by DominikPf** [comment]
@bruno-garcia Yes, you are right about the `new HttpClient()`. Sorry for that.

The Init call doesn't work, there is a CORS error.
![image](https://user-images.githubusercontent.com/20923469/77792717-2867f500-7069-11ea-8532-473e755b72af.png)

**Comment by bruno-garcia** [comment]
@DominikPf [sentry.io already has a fix for that](https://forum.sentry.io/t/cors-error-when-capturing-an-exception-in-blazor-webassembly-app/9256). If you're running Sentry on-prem you'd need to update to the latest build.

**Comment by DominikPf** [comment]
@bruno-garcia Oh ok, thanks i will check that next week. I installed Sentry locally to test it with Blazor. Sentry on Docker is currently on v9.1.2 https://hub.docker.com/_/sentry

**Comment by bruno-garcia** [comment]
Here you can get the image created from the latest commit merged to master:

https://hub.docker.com/r/getsentry/sentry

Also, you can also get a free (developer) account on sentry.io to test things out. I think up to 10k events per month.

**Comment by bruno-garcia** [comment]
This works now. I'll close the issue, there's a sample already in this PR: #574 

If specific parts of the integration don't work, lets open new issues for each specific thing.
