### ISSUE TITLE
Metrics Improvement

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3175]
The following parts have been added to the dev docs since the initial implementation
- [x] [Trace Seeking](https://develop.sentry.dev/sdk/metrics/#trace-seeking) - Attach Tags
- [x] [Span Aggregation](https://develop.sentry.dev/sdk/metrics/#span-aggregation)

**Comment by jamescrosswell** [comment]
> [x] Timings don't need to create a span themselves. Which means the whole `IMetricHub` can probably go?

@bitsandfoxes are you sure about this? The [reference implementation creates spans for Timings](https://github.com/getsentry/sentry-python/blob/0901953c93071e858f4da67c1e864766ae19c002/sentry_sdk/metrics.py#L800) and the RFC still contains this:

>  Most of the metrics APIs are span seeking which means that they record a measurement in relation to that span. Some APIs (such as metrics.timing when used with a code block) will instead create a span and bind it.

**Comment by bitsandfoxes** [comment]
Looks like I missed that. So spans stay!
