### ISSUE TITLE
How do I send additional information to a custom EventProcessor or EventExceptionProcessor?

### ISSUE THREAD

**Issue by udlose** [getsentry/sentry-dotnet#319]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [X ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [X ] .NET Core

* Version: 2.2.7

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [X ] Sentry.AspNetCore

* Version: 1.2.0

It's not clear to me from the samples or your documentation how I can send additional information to a custom `ISentryEventProcessor` or `ISentryEventExceptionProcessor` since they seem to be called by the SentryClient in the SDK instead of me having to consume them in my application directly.  While that is a great design (since the SDK calls it for me), I'd like to know what the recommendation is to add additional info to the `SentryEvent`.  I see the samples just adding hardcoded strings in the `Process(SentryEvent)` and `Process(Exception, SentryEvent)` methods, but I need to pass a DTO so that it can be serialized with the `SentryEvent` (via `SetExtra()`).

There are two options I can think of but unsure if there is a better way to do this.

1. Stuff this data in the `HttpContext.Items` and then pull it out in the EventProcessor via an injected `IHttpContextAccessor`.  Though this seems brittle and I try to avoid using `IHttpContextAcessor`.
2. Stuff this extra data in the [Exception's `Data` dictionary](https://docs.microsoft.com/en-us/dotnet/api/system.exception.data).  However, this will only work for a custom `ISentryEventExceptionProcessor` and not `ISentryEventProcessor`.

Is there a recommendation on how to accomplish this?

**Comment by bruno-garcia** [comment]
I noticed this was discussed on Sentry's forum.

Please refer to this thread for details: https://forum.sentry.io/t/how-do-i-send-additional-information-to-a-custom-eventprocessor-or-eventexceptionprocessor/8289/6
