### ISSUE TITLE
Failed to send envelopes persist on disk

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3209]
## Problem Summary

First raised through Unity SDK [here](https://discord.com/channels/621778831602221064/1215954412384817292). 

Repro with an attachment bigger than 50mb
```
SentrySdk.CaptureEvent(new SentryEvent(), scope =>
{
    scope.AddAttachment("/path/to/something/big");
});
```

What ends up happening: The SDK tries to send the envelope, fails but keeps the envelope around indefinitely.

**Comment by jamescrosswell** [comment]
> What ends up happening: The SDK tries to send the envelope, fails but keeps the envelope around indefinitely.

What do we want to happen instead @bitsandfoxes ?

We could maintain a list in memory of envelopes that we've failed to send along with a retry count. When the count hits X, we could just log the failure and throw it away?

**Comment by bitsandfoxes** [comment]
I think we should handle this differently based on the reason the envelope got rejected. The attachment being too big won't change during a retry so we should log and delete the envelope.
Alternatively, we could think about dropping the attachment and sending the envelope without it?
