### ISSUE TITLE
Crons Hangfire integration - find job names automatically

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3219]
Can we get the job manager, eg:
        var jobManager = app.ApplicationServices.GetRequiredService<IRecurringJobManager>();

Then with it find all registered jobs? 

Having to add `SentryMonitorSlug` to all my jobs is pretty annoying

**Comment by bitsandfoxes** [comment]
Will be fixed with https://github.com/getsentry/sentry-dotnet/issues/3262
