### ISSUE TITLE
Enable Ben.Demystifier for AOT apps

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3230]
Off the back of the [comments](https://github.com/dotnet/runtime/issues/96528#issuecomment-1996743590) that triggered https://github.com/getsentry/sentry-dotnet/issues/3222 and https://github.com/getsentry/sentry-dotnet/issues/3223, could Ben.Demystifier be compiled with AOT now?

Maybe not, but needs further investigation when we have time. 

### Ben.Demystifier

Remaining work [described here](https://github.com/benaadams/Ben.Demystifier/pull/222#issue-2185532253):
> someone will need to do the work to enable the AOT/trim/single file safety analyzers and [address all the warnings](https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/), but this is enough to have a golden path that makes sample/StackTrace project produce the same results under native AOT as under JIT.

### Testing

Need to test to ensure this actually works with Sentry, of course. That will require some tweaks to the Sentry codebase to ensure it's possible to generate enhanced stack traces when compiling AOT (currently that's not possible).

**Comment by jamescrosswell** [comment]
See:
- https://github.com/getsentry/sentry-dotnet/issues/3282

**Comment by bitsandfoxes** [comment]
I take it we can now try to enable it and see what happens?

**Comment by jamescrosswell** [comment]
There are some tasks [described here](https://github.com/benaadams/Ben.Demystifier/pull/222#issue-2185532253). 

I'll copy them into the description for this issue.
