### ISSUE TITLE
Prepare Metrics for GA

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3245]
When Sentry moves Metrics to GA we need to change our APIs so that they don't look intentionally so [Experimental](https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/ExperimentalMetricsOptions.cs). 

`ExperimentalMetricsOptions` could be marked as Obsolete and inherit from a vanilla `MetricsOptions` class that would replace this (and not be marked obsolete of course). That way code for customers who've been using these experimentally will continue to work without change, but we'll give people a heads up that this will require code changes on their part eventually. 

- https://github.com/getsentry/sentry-dotnet/pull/3246
- https://github.com/getsentry/sentry-docs/pull/10119

**Comment by bitsandfoxes** [comment]
Sorry, we won't address this.
Superseded by https://github.com/getsentry/sentry-dotnet/issues/3597
