### ISSUE TITLE
WinForms bug using SentryHttpMessageHandler

### ISSUE THREAD

**Issue by shivasuri** [getsentry/sentry-dotnet#3253]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

4.7.2

### OS

Windows

### SDK Version

4.2.1.0

### Steps to Reproduce

Hi, I'm running into an issue in my WinForms app that I've seen has been an issue in dotnet apps as well https://github.com/getsentry/sentry-dotnet/issues/103#issuecomment-2029044050

I am trying to add sentry logging to `async void logInButtonClick() { SentryHTTPMessageHandlerStuff(); } `

Easy way to reproduce would be to add a button to windows forms app, and add the following code in the event handler:
```
string route = "http://some-route";

public async void onButton1_Click(object sender)
        {
            var request = new HttpRequestMessage(HttpMethod.Get, route);
            var client = new HttpClient(new SentryHttpMessageHandler());

            HttpResponseMessage response = await client.SendAsync(request);
        }
```

This will crash the app and result in an error taking you to the project's `Program.cs` line where you run the app:
```
using (SentrySdk.Init(sentryOptions))
        {
            Application.Run(new Form1());
        }
```

Any tips on how to proceed? I can't change the return type of the function from void because of how WinForms does event handling.

### Expected Result

Http exception shows in dashboard and doesn't crash app.

### Actual Result

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StreamContent'.
```

**Comment by jamescrosswell** [comment]
Hey @shivasuri, so this isn't really anything to do with Sentry but you're in luck... by pure chance, I [wrote a blog post about this](https://www.jamescrosswell.dev/posts/catching-async-void-exceptions/) on the weekend ;-)

I just tested this out in a WinForms application and it works fine. I pushed up a NuGet package in case you want to use that... but all the [source code is available here](https://github.com/mentaldesk/asyncvoid) as well, if you wanted to copy/paste it into your solution instead.

The readme in that repo describes how you can modify your event handler to be able to catch any exceptions from async code you're running inside the handler. In the readme, I described showing the exception message in a dialog... but it would be easy enough to call `SentrySdk.CaptureException` instead or as well. 

Let me know how you get on.

**Comment by shivasuri** [comment]
Perfect, appreciate it and the blog. This seems straightforward enough to follow. I'll let you know if I run into any issues here. Thank you!
