### ISSUE TITLE
Java.Lang.IllegalArgumentException when setting MaxBreadcrumbs to 0

### ISSUE THREAD

**Issue by tipa** [getsentry/sentry-dotnet#3255]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.2

### OS

Android

### SDK Version

4.2.1

### Steps to Reproduce

```
Sentry.SentrySdk.Init(o =>
{
    ....
    o.MaxBreadcrumbs = 0;
}
```

According [to the docs](https://docs.sentry.io/platforms/android/configuration/options/#max-breadcrumbs):

> This variable controls the total amount of breadcrumbs that should be captured. This defaults to 100, **but you can set this to any number**. 

### Expected Result

no crash and collection of breadcrumbs is disabled

### Actual Result

```
java.lang.IllegalArgumentException: The size must be greater than 0
  at io.sentry.CircularFifoQueue.< init > (CircularFifoQueue.java:91)
  at io.sentry.Scope.createBreadcrumbsList(Scope.java:738)
  at io.sentry.Scope.< init > (Scope.java:90)
  at io.sentry.Hub.createRootStackItem(Hub.java:77)
  at io.sentry.Hub.< init > (Hub.java:43)
  at io.sentry.Sentry.init(Sentry.java:238)
  at io.sentry.Sentry.init(Sentry.java:167)
  at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:87)
```

**Comment by tipa** [comment]
Is there any other way to disable breadcrumbs completely? What I also tried:
- Disable the breadcrumbs programmatically, like `options.Native.EnableActivityLifecycleBreadcrumbs = false`. However, the property to disable network events (`io.sentry.breadcrumbs.network-events`) is not present
- Specify the options as `meta-data` tags in the AndroidManifex.xml (as documented [here](https://docs.sentry.io/platforms/android/enriching-events/breadcrumbs/#disable-automatic-breadcrumbs)). However, `io.sentry.auto-init` is set to `false`

**Comment by jamescrosswell** [comment]
Hi @tipa ,

You could use the [SetBeforeBreadcrumb](https://github.com/getsentry/sentry-dotnet/blob/0531ac7d68c61dece4d29342a8084bfb8f1edcda/src/Sentry/SentryOptions.cs#L512-L522) callback. Returning null from that callback will discard the breadcrumb.

**Comment by tipa** [comment]
Thanks. I thought of that workaround as well. But this would still come with the overhead at runtime of the Sentry SDK setting up all the integrations & handlers.
What is the "correct" way to disable all breadcrumbs? Settings the `MaxBreadcrumbs` to 0? Specifying the `SetBeforeBreadcrumb` callback? Manually remove the `Integration`?

At the moment, I don't see a way to specifically disable the [NetworkBreadcrumbsIntegration](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/NetworkBreadcrumbsIntegration.java) in the .NET SDK.
Even when discarding the breadcrumb with the `SetBeforeBreadcrumb` handler, there is some overhead of registering the callback [here](https://github.com/getsentry/sentry-java/blob/a1f394cd001c90e674153bc498c110750337e6a4/sentry-android-core/src/main/java/io/sentry/android/core/NetworkBreadcrumbsIntegration.java#L65-L88). Is the .NET SDK missing a binding here?

**Comment by jamescrosswell** [comment]
> Is the .NET SDK missing a binding here?

If it's just that setting you're after, this [exists in the NativeOptions on the .NET SDK](https://github.com/getsentry/sentry-dotnet/blob/bd62cf0421cc7a5d7b7804f8461fae00d47d43b8/src/Sentry/Platforms/Android/NativeOptions.cs#L105-L104) as well.

**Comment by tipa** [comment]
But does that disable **all** breadcrumbs?
There are different properties for different types of breadcrumbs (`EnableActivityLifecycleBreadcrumbs`, `EnableAppComponentBreadcrumbs`, ...) but the one for network events seems to be missing in the .NET bindings

**Comment by jamescrosswell** [comment]
> There are different properties for different types of breadcrumbs (`EnableActivityLifecycleBreadcrumbs`, `EnableAppComponentBreadcrumbs`, ...) but the one for network events seems to be missing in the .NET bindings

You're quite right @tipa... my mistake. Kicked off https://github.com/getsentry/sentry-dotnet/pull/3267 to address.

**Comment by jamescrosswell** [comment]
> Oddly enough, there seem to be a couple of options missing. The networking one.
> And specifically for your ask There is a [`enableAllAutoBreadcrumbs`](https://github.com/getsentry/sentry-java/blob/e7d4adc49251868f8a2f5a8c1bb37704166fbfed/sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java#L331C15-L331C39) that should take care of.. all.. of them.

May as well do that in the same PR eh?
