### ISSUE TITLE
Sentry fails to initialize in Blazor with AoT enabled

### ISSUE THREAD

**Issue by klemmchr** [getsentry/sentry-dotnet#3263]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Browser

### SDK Version

4.2.1

### Steps to Reproduce

Repro: [sentry-blazor-repro.zip](https://github.com/getsentry/sentry-dotnet/files/14895178/sentry-blazor-repro.zip)

1. Build included Dockerfile
2. Start docker image and bind port 8080
3. Open http://localhost:8080 and open console

### Expected Result

Web app loads properly and starts up. This works fine when using `Sentry.Extensions.Logging` `3.41.4` but breaks after doing the major upgrade to 4.

### Actual Result

Web app fails to load

```
Error: AggregateException_ctor_DefaultMessage (sentry-native)
    at Jn (dotnet.runtime.8.0.3.b85ar3xvhg.js:3:31614)
    at xl (dotnet.runtime.8.0.3.b85ar3xvhg.js:3:182162)
    at dotnet.native.wasm:0xb7f885
    at dotnet.native.wasm:0xb8125f
    at dotnet.native.wasm:0xb86cc5
    at dotnet.native.wasm:0xe6866
    at dotnet.native.wasm:0x130d162
    at dotnet.native.wasm:0x132a1bb
    at dotnet.native.wasm:0x1309ad4
    at dotnet.native.wasm:0x12fced1
```

**Comment by bitsandfoxes** [comment]
Thanks, @klemmchr for the detailed issue and the repro in particular!

**Comment by jamescrosswell** [comment]
OK so it might be this:
https://github.com/getsentry/sentry-dotnet/blob/790e40dcf7eb863ed505ebe578f639112fc7d988/src/Sentry/Internal/ProcessInfo.cs#L119

Apparently that method can throw a `PlatformNotSupportedException`:
> The operating system platform does not support this operation on remote computers.

And we are calling that in the constructor:
https://github.com/getsentry/sentry-dotnet/blob/790e40dcf7eb863ed505ebe578f639112fc7d988/src/Sentry/Internal/ProcessInfo.cs#L97

**Comment by jamescrosswell** [comment]
Dang, dead end... all of that is just this (which is wrapped in a try catch and logging the exception - it won't be what's crashing the process then) 😞 :
https://github.com/getsentry/sentry-dotnet/blob/790e40dcf7eb863ed505ebe578f639112fc7d988/src/Sentry/Internal/ProcessInfo.cs#L100-L108

**Comment by bitsandfoxes** [comment]
After our sync: We think we should disable `sentry-native` when targeting Blazor.

**Comment by klemmchr** [comment]
Is there any ETA on when this fix can be expected? I'm desperate to update the SDK to v4.

**Comment by bitsandfoxes** [comment]
Doubleconfirming: I can reproduce this locally with our own samples/Sentry.Samples.AspNetCore.Basic/Program.cs sample. A fix should follow shortly.

**Comment by klemmchr** [comment]
@bitsandfoxes may I ask for an update? It has been over a month now where this critical bug has not been fixed. There is a bit of irony to it, given that Sentry proudly announced [AoT support in v4 for non-console apps](https://blog.sentry.io/sentry-dotnet-sdk-4-for-dotnet-8/#what-is-ahead-of-time-aot) (which is not working) while having working AoT in v3 without any trouble.

**Comment by bitsandfoxes** [comment]
Hey @klemmchr, sorry about that. The issue fell through the cracks. We'll pick it back up and you can expect a fix early next week.

**Comment by klemmchr** [comment]
@bitsandfoxes great to see that this got fixed. Is this going to be released as a patch or do we need to wait for the next minor release? And if so, is there any timeline/release cycle for this?
