### ISSUE TITLE
Send project root path with events

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#327]
IDE's (at least Rider) can open relative path and line:

`src/SymbolCollector.Android/Resources/layout/activity_main.axml:5`

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1633368/71259960-f80e0d80-2339-11ea-9f9c-fdfa847e8e5b.png">

[New changes for .NET stack traces are incoming to Sentry](https://github.com/getsentry/sentry/pull/16199) and it includes an easy way to copy the path.

Currently, the rooted path is copied, which is often useless since code is built on a build server and that rooted path doesn't match the developer's file structure.

This task is to include in events the root path of the project so that in the UI we can trim the build server specific part of the path.

A line number can then be appended to it with `:` and pasting in the IDE as above will work.

**Comment by kanadaj** [comment]
ReSharper can also do this in Visual Studio:
![image](https://user-images.githubusercontent.com/3247357/71261383-22a99780-2335-11ea-8ef7-b1ed5a14caed.png)

Visual Studio's `Go to All` can also do this, but not with the line number:
![image](https://user-images.githubusercontent.com/3247357/71261507-6ef4d780-2335-11ea-974a-a2420d3ba9fa.png)

![image](https://user-images.githubusercontent.com/3247357/71261518-74eab880-2335-11ea-9e49-fd02d4b0b750.png)
