### ISSUE TITLE
Hangfire not in cron

### ISSUE THREAD

**Issue by TimVerheul** [getsentry/sentry-dotnet#3309]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

8.0.202

### OS

Any (not platform specific)

### SDK Version

4.3.0

### Steps to Reproduce

use AddHangfire with UseSentry() in Program.cs. Use RecurringJob.AddOrUpdate and BackgroundJob.Enqueue.

### Expected Result

RecurringJob.AddOrUpdate and BackgroundJob.Enqueue should show up in the crons. But it doesn't

### Actual Result

For the RecurringJob.AddOrUpdate and BackgroundJob.Enqueue the crons are not showing up. It looks like UseSentry is doing nothing.

**Comment by bitsandfoxes** [comment]
Hi @TimVerheul. Thanks for raising this. We're working and prioritizing fixing up our Crons support next and are tracking it over here: https://github.com/getsentry/sentry-dotnet/issues/3262

Closing this issue as duplicate.
