### ISSUE TITLE
Add auto formatting tool

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#331]
Should apply rules from `.editorconfig`.

Consider: https://github.com/dotnet/format

**Comment by xt0rted** [comment]
Shameless plug warning. I published a [GitHub Action](https://github.com/marketplace/actions/dotnet-format) that will run dotnet-format on your PRs. There's also a problem matcher action that will highlight the formatting results in the build log and create annotations for them.

This can also be setup to apply fixes automatically. One of the example workflows is triggering it via a PR comment such as `/dotnet format` (can be restricted to only repo admins).

**Comment by bruno-garcia** [comment]
Started: #473

**Comment by bruno-garcia** [comment]
@xt0rted yeah, we can plug that when we add GH Actions

**Comment by bruno-garcia** [comment]
Seems like we can use dotnet-format and add it so that in CI it pushes the reformatting into the PR:
https://github.com/dotnet/format/releases/tag/v5.0.211103

Similar to how it's done on sentry-cocoa:
https://github.com/getsentry/sentry-cocoa/blob/9c04875e3c67492aa93c8a22a28fbff4bf5f82d5/.github/workflows/format-code.yml#L20

https://github.com/getsentry/sentry-cocoa/blob/9c04875e3c67492aa93c8a22a28fbff4bf5f82d5/scripts/commit-formatted-code.sh#L6-L11

**Comment by bruno-garcia** [comment]
Finally #1166
