### ISSUE TITLE
Filter out health check transactions

### ISSUE THREAD

**Issue by TomRoelofsWhyellow** [getsentry/sentry-dotnet#3317]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

6.0.0

### OS

Any (not platform specific)

### SDK Version

4.4.0

### Steps to Reproduce

1. Enable inbound filter for filtering out health check transactions
2. Create a health check endpoint (e.g. `/healthcheck/database`)
3. Assure that the health check is unhealthy
4. Perform a health check call to the endpoint

### Expected Result

According to the docs (https://docs.sentry.io/product/data-management-settings/filtering/#transactions-coming-from-health-check), the health check transaction should be filtered out.

Number of other things I've tried:
1. Add `SetBeforeSendTransaction` and `SetBeforeSend`. Tried to filter on Transaction Name/Tags.

`options.SetBeforeSendTransaction((sentryTransaction, _) =>
{
    return sentryTransaction.Name.Contains("healthcheck") ? null : sentryTransaction;
});`

2. Add `TracesSampler`

`options.TracesSampler = samplingContext =>
 {
     return samplingContext.TransactionContext.Name.Contains("healthcheck") ? 0 : 1;
 };`

When I check the logs, it says the events/transactions are dropped, but I'm still receiving them in Sentry.
![image](https://github.com/getsentry/sentry-dotnet/assets/128492925/7594284b-b7af-4408-8969-4f3026ab5b4c)

### Actual Result

The health check is not filtered out.

**Comment by bitsandfoxes** [comment]
So it looks like our docs are ahead of our implementation! I don't find anything related to `heathcheck` in our SDK. We're going to put that on our To-Do.

**Comment by bitsandfoxes** [comment]
You should definitely be able to filter those. The automatically created transaction's name should be in the format `{method} {route}` e.g. `GET /pets/{id}`. Can you confirm this?
Returning `null` drops the event.
The only way I see your filter not work would be if the SDK fails to extract the route from the route template.

**Comment by TomRoelofsWhyellow** [comment]
Yes, the format is indeed `{method} {route}`. I debugged the `BeforeSend`/`BeforeSendTransaction`/`TracesSampler` filters and the routes do get extracted correctly.

I've noticed that even after dropping a transaction, still some tracing information is sent to Sentry. Does this count towards my performance units limit?

**Comment by bitsandfoxes** [comment]
With the transaction dropped we update the client report. You can see that here: https://github.com/getsentry/sentry-dotnet/blob/7213a8cb8550381e88156119e98f69ff79b231da/src/Sentry/SentryClient.cs#L172-L178
This does **not** count towards your quota.

**Comment by TomRoelofsWhyellow** [comment]
Okay, I'll check if the filters are working once I have performance units again.

**Comment by jamescrosswell** [comment]
> So it looks like our docs are ahead of our implementation! I don't find anything related to `heathcheck` in our SDK. We're going to put that on our To-Do.

I couldn't find anything implemented for this in the Python or Java SDKs. [The docs](https://docs.sentry.io/concepts/data-management/filtering/#inbound-data-filters) appear to be describing functionality in the Relay rather than by the SDKs:
> These filters are exclusively applied at ingest time

Those docs also appear to relate to events/crashes rather than transaction.

@TomRoelofsWhyellow that code you posted originally should work to prevent transactions from being sent:

```csharp
options.SetBeforeSendTransaction((sentryTransaction, _) => sentryTransaction.Name.Contains("healthcheck") ? null : sentryTransaction);
```

@bitsandfoxes given none of the other SDKs have this functionality, do you want to check whether it makes sense to add this or not?

**Comment by bitsandfoxes** [comment]
Sorry, took me a bit to get back to this. Yes, you're correct @jamescrosswell. This should be done (and is) by Relay as an Inbound Data Filter. I did some testing with out basic sample just to confirm.
![Screenshot 2024-07-04 at 15 01 59](https://github.com/getsentry/sentry-dotnet/assets/25725783/6ab1676d-7db4-4015-9ee2-2fa6f8eb6041)

It's fine for the SDK to send those transactions. If you really don't want them to then filtering them in `BeforeSendTransaction` is the way to go.

The only thing in this issue I'm concerned right now is `but I'm still receiving them in Sentry.`

**Comment by bitsandfoxes** [comment]
Looking at your logs again: Those seem from your tests with the traces sampler. `Transaction dropped by sampling.` is the expected log for when you drop sending a transaction based on the sampling decision.
In case of implementing your own filter in the `BeforeSendTransaction` look out for a log `Transaction dropped by BeforeSendTransaction callback.`.

So this is intended behaviour. Please feel free to reopen this issue if it's still giving you problems. Thanks!
