### ISSUE TITLE
install instructions for profiling have the wrong version

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3336]
Wrong version for profiling.
Is it already on release registry

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/1bc65eb1-57b8-406e-8d93-37421015e20d)

**Comment by bruno-garcia** [comment]
It's here:

https://github.com/getsentry/sentry-dotnet/blob/5bcb9cac8b54f283a4ce5cc16573bfdf2970cdf9/.craft.yml#L22

Maybe we need to make a new release?

**Comment by jamescrosswell** [comment]
> Maybe we need to make a new release?

Kicked off a [4.5.0 release](https://github.com/getsentry/sentry-dotnet/actions/runs/8902118889).

**Comment by jamescrosswell** [comment]
> Wrong version for profiling.
> Is it already on release registry

@bruno-garcia where are you seeing this? In the [Setup Profiling Docs](https://docs.sentry.io/platforms/dotnet/profiling/) I'm seeing:
<img width="940" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/00b2da50-e1b4-495f-ab35-7897f4084090">

**Comment by bruno-garcia** [comment]
It's fixed! thanks

> @bruno-garcia where are you seeing this? In the [Setup Profiling Docs](https://docs.sentry.io/platforms/dotnet/profiling/) I'm seeing:

I saw it when creating a new project in Sentry. verified it's working through a new aspnet core project:

![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/c4c2e7c3-7e25-42ca-afe9-c4fa91ee4c21)

Also, made a PR to remove the `--prerelease` from the docs: https://github.com/getsentry/sentry-docs/pull/9912 good catch
