### ISSUE TITLE
Profiling: Error out in the editor if added to unsuported platform

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3354]
Set Up is quite complex:

In some platforms you need `Sentry.Profiling` in some you don't and others neither are supported
We have series of notes and warnings, and tabs:
<img width="708" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/1633368/cd199709-a073-4464-9daa-84d75b39c33e">

Ideally we have a compiler error if `Sentry.Profiling` is added to an unsupported version, so it's clear `Sentry.Profiling` isn't supported on Android

Customers are copying the snippet and adding both packages without picking on the fine print and having a bad experience during set up.

**Comment by bitsandfoxes** [comment]
Can we do that with a bit of MSBuild magic? Can we pick up the targeted platform there together with what packages are installed?

**Comment by bitsandfoxes** [comment]
@jamescrosswell raised a good point: We could put the platform specific options behind guards like we do here
https://github.com/getsentry/sentry-dotnet/blob/a8859d8da96a01120261dfb1771f57f49a4af3d1/src/Sentry/SentryOptions.cs#L26-L28

**Comment by vaind** [comment]
> Can we do that with a bit of MSBuild magic? Can we pick up the targeted platform there together with what packages are installed?

this should do the trick 🤞 https://github.com/getsentry/sentry-dotnet/pull/3371/files
