### ISSUE TITLE
OOTB metrics

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3368]
Metrics being stable and all we could and should consider what the SDK can offer OOTB:
Potential candidates:
- CPU usage
- Memory usage
- GC heap size
- Garbage collections

**Comment by jamescrosswell** [comment]
We could [mimic Aspire in this respect](https://blog.sentry.io/aspire-insights-in-production-with-sentry/#sending-metrics-to-sentry). That's quite a few metrics though.

**Comment by bitsandfoxes** [comment]
Sorry, we won't address this.
Superseded by https://github.com/getsentry/sentry-dotnet/issues/3597
