### ISSUE TITLE
Don't add frames to the list when all available is whether it's InApp or not

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#337]
While sending events from an Android device, a weird frame rendering showed up:

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1633368/72204757-98f47200-347b-11ea-94b1-12114dc9f5de.png">

The reason was the JSON payload including a single frame with `inApp=true` and nothing else.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/1633368/72204753-942fbe00-347b-11ea-99af-79c6a9d672ce.png">

Avoid adding such frames to the Stacktrace object.

**Comment by bitsandfoxes** [comment]
I guess we could add the check here and simply drop the frame if it's "empty"
https://github.com/getsentry/sentry-dotnet/blob/d955f6fb53464bd54b5378d441e458e426376b63/src/Sentry/Internal/DebugStackTrace.cs#L177

**Comment by bruno-garcia** [comment]
Might not be relevant, without a repro is also challenging so closing
