### ISSUE TITLE
Url parameter secrets are not sanitized by default in ASP.NET

### ISSUE THREAD

**Issue by klemmchr** [getsentry/sentry-dotnet#3374]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Any (not platform specific)

### SDK Version

4.6.2

### Steps to Reproduce

1. Create endpoint with an url parameter named `secret`
2. Send trace using Sentry

### Expected Result

Url parameter would be masked (like with user ids).

### Actual Result

Url parameter is not masked and full unmasked path is send to Sentry.

**Comment by jamescrosswell** [comment]
It looks like we have something to redact PII but nothing for secrets or *sensitive* information more generally:

https://github.com/getsentry/sentry-dotnet/blob/c96e3ef488014a57b8c918cb195374a9cb0e8b1f/src/Sentry/SentryClient.cs#L167-L170

If we did add something more generic to redact sensitive information, it would have to be flexible/configurable, as the kinds of things that indicate whether something is sensitive or not would definitely be cultural specific and likely domain specific as well.

Possibly something like `List<Regex> RedactUrlParameters` on the `SentryOptions`.

**Comment by bitsandfoxes** [comment]
> Possibly something like List<Regex> RedactUrlParameters on the SentryOptions.

I really like this idea. Let me check with the other SDKs if they have something like that in place.

**Comment by bitsandfoxes** [comment]
I found an [`event scrubber`](https://docs.sentry.io/platforms/python/data-management/sensitive-data/#event_scrubber) on the Python SDK that has an extendable deny-list.

**Comment by jamescrosswell** [comment]
> I found an [`event scrubber`](https://docs.sentry.io/platforms/python/data-management/sensitive-data/#event_scrubber) on the Python SDK that has an extendable deny-list.

Looks like that [scrubs everything](https://github.com/getsentry/sentry-python/blob/b496a7131d64f61f3473e9e1a9807760bec217c1/sentry_sdk/scrubber.py/#L100-L154).

I can't see any reference to this in the Developer Docs but we could just mimic the behaviour of the Python SDK.

**Comment by bitsandfoxes** [comment]
Python has a [default deny-list](https://github.com/getsentry/sentry-python/blob/6f87c0deebb279d5ed2b5cd3b044777b2d9e6f70/sentry_sdk/scrubber.py#L14).
