### ISSUE TITLE
Windows Service memory grows indefinitely with Tracing and Profiling enabled.

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3375]
From jforward5 on [Discord](https://discord.com/channels/621778831602221064/1240369245779525632/1240369245779525632).

> I've added Sentry to my .Net core project and see the project using an infinite amount of memory.  My question is, how do i make it stop using all the memory?
> 
> If I comment out this code my app runs normally, and only uses about 24MB of memory, but uncommenting causes the memory to grow endlessly by 2-3MB per second:
> builder.ConfigureLogging(loggingBuilder =>
>     {
>         loggingBuilder.AddSentry(o =>
>         {
>             o.Dsn = "https://my_dsn/";
>             o.Debug = true;
>             o.TracesSampleRate = 1.0;
>             o.ProfilesSampleRate = 1.0;
>             o.AddIntegration(new ProfilingIntegration(
>                 TimeSpan.FromMicroseconds(500)
>             ));
>         });
>     });
> 
> I should also mention this is a Windows Service using .Net Core 8

## Demo project to reproduce

> i've attached a sample app that reproduces the issue.  The app is a plain, "empty" windows service.  It is using .Net 8 and Sentry.  Run the app from VS and watch your task manager, you will see the process memory grow as long as the service is running.  If you turn off the profiling and tracing it no longer consumes memory, and stabilizes.  You'll need to add your own "DSN" since i removed mine, for security reasons.

[Memory Test Worker Service.zip](https://github.com/getsentry/sentry-dotnet/files/15340965/Memory.Test.Worker.Service.zip)

**Comment by jamescrosswell** [comment]
So there does appear to be an issue here. This is what I'm seeing when I run the service in a memory profiler:
<img width="1650" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/912a682d-7e2e-416a-95f0-859d8e0abb89">

Although the LOH and POH do get cleaned up occassionally (somewhat), over time these just keep growing and growing. Heap Gen 0, 1 and 2 all appears stable. 

The only thing that I can think might be using the LOH or POH is profiling, which might need to pin objects when passing pointers to unsafe code. I see a number of instances where the PerView module pins objects (e.g. [here](https://github.com/getsentry/perfview/blob/3bebe16b1c13dedf70967f5507768248c13f31a6/src/TraceEvent/Ctf/CtfChannel.cs#L30)).

That's consistent with the call tree, which indicates 99% of the memory is being used by instances of `EventMarker`, which is an internal class used by `modules/perfview/src/TraceEvent/EventPipe/EventCache.cs`: 
<img width="1366" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/518c19ec-1689-4696-8e3f-0c6c02bca42a">

The `EventMarker` constructor takes a `PinnedBuffer` as an argument. 

It looks like the [ProcessEventBlock](https://github.com/getsentry/perfview/blob/3bebe16b1c13dedf70967f5507768248c13f31a6/src/TraceEvent/EventPipe/EventCache.cs#L18) method creates multiple `EventMarker` instances and never explicitly cleans any of these up. 

I'll play around to see if I can explicitly free these up.

**Comment by jamescrosswell** [comment]
When I look at the generations I can see:
<img width="776" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/842de22b-27d4-43c3-b159-820db51758f3">

Pretty much all of that is accounted for by `Microsoft.Diagnostics.Tracing.Etlx.TraceLog+EventsToStackIndex[]`

<img width="787" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/6b653bfa-ff4b-43f3-a149-896d181bac5d">

I see events get added to that stack [here](https://github.com/getsentry/perfview/blob/3bebe16b1c13dedf70967f5507768248c13f31a6/src/TraceEvent/TraceLog.cs#L4374) but the only place I see them being removed is in the [internal FlushRealtimeEvents](https://github.com/getsentry/perfview/blob/3bebe16b1c13dedf70967f5507768248c13f31a6/src/TraceEvent/TraceLog.cs#L819) method, which in turn gets called by [TraceLogProcess](https://github.com/getsentry/perfview/blob/3bebe16b1c13dedf70967f5507768248c13f31a6/src/TraceEvent/TraceLog.cs#L4465), which we call here when starting the profiling:
https://github.com/getsentry/sentry-dotnet/blob/ca3744ba0730c675f1e6ce0d77e4687ff6bc8910/src/Sentry.Profiling/SampleProfilerSession.cs#L88

As far as I can tell then, that GrowableArray just gets bigger and bigger, and there are no public APIs that we can use to flush out old item. 

@vaind any ideas?

**Comment by jamescrosswell** [comment]
> @jamescrosswell any chance you could verify the fix in #3382 ?

It works - thanks @vaind!🕺🏻 

<img width="1700" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/2b493c94-f377-4277-8697-8988e05c20f3">

**Comment by vaind** [comment]
thank you!

for reference: this was the actual fix: https://github.com/microsoft/perfview/pull/1867/commits/36d2e2c28c1ebeaa780908dc6f831144872a37a5#diff-31ffbfdad96fc84f3aa7d25e1980cdca5a4d7870529c669ac9cc975cf24969c8R342
