### ISSUE TITLE
Envelopes stuck in `__processing` until restart

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3384]
When offline, the `CachingTransport` will leave envelopes stuck in `__processing`. Even if the client goes online again and starts sending new events, the old ones remain there.
Only during restart will those envelopes get moved back to the cache and then sent by the worker.

**Comment by bitsandfoxes** [comment]
I might be missing something but how is the retry supposed to work
https://github.com/getsentry/sentry-dotnet/blob/5bd8c8a4297804a90520ca6e59e8e478d46189ea/src/Sentry/Internal/Http/CachingTransport.cs#L162-L166
if we're waiting for a signal here before doing any processing?
https://github.com/getsentry/sentry-dotnet/blob/5bd8c8a4297804a90520ca6e59e8e478d46189ea/src/Sentry/Internal/Http/CachingTransport.cs#L147-L152

**Comment by jamescrosswell** [comment]
Lines 162-170 wait for either 500ms or the cancellation token (so basically just delays 500ms in normal circumstances). 

... then back at the start of the loop, lines 149-151 execute. 

It looks like the only time the `_workerSignal` gets released is here:
https://github.com/getsentry/sentry-dotnet/blob/d64358e1036e9fb7c20e88a10047f7eb09c1871e/src/Sentry/Internal/Http/CachingTransport.cs#L448

Possibly we could call that back on line 166 as well, after delaying. That would try every 500ms when offline though... so some kind of progressive backoff might be good here... 500ms after the first successive failure, 1000ms after the second etc. up to some maximum backoff that gets reset back to 500ms after a successful iteration.
