### ISSUE TITLE
.NET Core 3.1 requires Sentry.AspNetCore 2.0.0-beta7

### ISSUE THREAD

**Issue by VictorGazzinelli** [getsentry/sentry-dotnet#339]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [X] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [X] .NET Core

* Version: .NET Core 3.1.0

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [X] Sentry.AspNetCore

* Version: Sentry.AspNetCore 1.2.0

Hi! This is my first Issue ever, so bare with me please. I read the docs and yet couldn't integrate Sentry.AspNetCore. I tried adding it to my main webAPI, no luck (Maybe some dependency issues).

I Also tried adding Sentry.AspNetCore to default .Net Core API Example. No luck.

Steps to reproduce (Running on Windows):
 - Initialize Visual Studio
 - Go to File -> New -> Project
 - Use Web App ASP.NET Core template
 - Click Create
 - Select ASP.NET Core 3.1 version as well as API template
 - Click Create
 - Add the following items to appsettings.json (key and project has real value) : 

   "Sentry": {
    "Dsn": "https://<key>@sentry.io/<project>",
    "IncludeRequestPayload": true,
    "SendDefaultPii": true,
    "MinimumBreadcrumbLevel": "Debug",
    "MinimumEventLevel": "Warning",
    "AttachStackTrace": true,
    "Debug": true,
    "DiagnosticsLevel": "Error"
  },

 - Add Sentry.AspNetCore 1.2.0 using NuGet
 - Go to Controllers -> WeatherForecastController
 - Switch code in IEnumerable<WeatherForecast> Get() to

     [HttpGet]
     public IEnumerable<WeatherForecast> Get()
     {
         throw new Exception("Error");
     }
 - Use the following code in CreateHostBuilder:

            public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>().UseSentry();
                });
- Start IIS Express with the https://localhost:44360/weatherforecast url
- Exception Page does not render, neither Sentry register  the exception in Issues section.
- Check stack trace in output window:

System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

link to example github repo : https://github.com/VictorGazzinelli/SentryNetCore3.1Example

I thought that the exception page would render, as well as Sentry would be able to recieve the alert. Am I missing something from the instalation ? Any thoughts?

**Comment by bruno-garcia** [comment]
[This was raised before.](https://github.com/getsentry/sentry-dotnet/issues/307) Please use the latest beta.

Apologies this hasn't been released as `2.0.0`. It will soon.

For now please just use the latest beta.

**Comment by VictorGazzinelli** [comment]
Thank you! Thought this was a core 3.1 issue.  using Sentry.AspNetCore 2.0.0-beta7 fixed the error.

**Comment by bruno-garcia** [comment]
Glad it worked.

We need to release 2.0.0 but there are some outstanding tasks we'd like to add to the 2.0.0 release..
