### ISSUE TITLE
ASP.NET Core Telemetry: Failed invoking event handler in anonymous routes

### ISSUE THREAD

**Issue by renanrcp** [getsentry/sentry-dotnet#3395]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Linux

### SDK Version

4.7.0

### Steps to Reproduce

After following the [telemetry tutorial](https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/performance/instrumentation/opentelemetry/#aspnet-core-applications), I started receiving the following error when accessing unauthenticated routes:

```css
[May 28 - 01:16:38] [EROR] [Sentry.ISentryClient][0]
Failed invoking event handler.
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options)
   at Sentry.AspNetCore.SentryMiddleware.PopulateScope(HttpContext context, Scope scope)
   at Sentry.AspNetCore.SentryMiddleware.<>c__DisplayClass16_0.<InvokeAsync>b__5(Object _, Scope activeScope)
   at Sentry.Scope.Evaluate()
```

After investigation, I discovered that the error is triggered [here in the .NET runtime](https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs#L23).

This suggests that there is likely an issue when using HttpContext.RequestServices with unauthenticated routes.

Through some tests, I found that the error does not occur if:

- I disable SendDefaultPii.
- I remove AddAspNetCoreInstrumentation.
- I use only routes with mandatory authentication.

Here is what I use in Program.cs to add telemetry:

```cs
builder.WebHost.UseSentry(options =>
{
    options.UseOpenTelemetry();

    options.ExperimentalMetrics = new ExperimentalMetricsOptions
    {
        EnableCodeLocations = true
    };

    options.AddIntegration(new ProfilingIntegration(
        // During startup, wait up to 500ms to profile the app startup code.
        // This could make launching the app a bit slower so comment it out if you
        // prefer profiling to start asynchronously.
        TimeSpan.FromMilliseconds(500)
    ));
});

builder.Services.AddOpenTelemetry()
    .WithTracing(tracerProviderBuilder =>
        tracerProviderBuilder.AddSentry() // <-- Configure OpenTelemetry to send trace information to Sentry
            .AddAspNetCoreInstrumentation() // <-- Adds ASP.NET Core telemetry sources
            .AddHttpClientInstrumentation() // <-- Adds HttpClient telemetry sources
    );

builder.Services.AddSingleton<ISentryUserFactory, PolarisSentryUserFactory>();
```

Here are the package versions used:

```xml
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.8.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.8.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.8.1" />
<PackageReference Include="Sentry.AspNetCore" Version="4.7.0" />
<PackageReference Include="Sentry.OpenTelemetry" Version="4.7.0" />
<PackageReference Include="Sentry.Profiling" Version="4.7.0" />
```

### Expected Result

No errors.

### Actual Result

```css
[May 28 - 01:16:38] [EROR] [Sentry.ISentryClient][0]
Failed invoking event handler.
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options)
   at Sentry.AspNetCore.SentryMiddleware.PopulateScope(HttpContext context, Scope scope)
   at Sentry.AspNetCore.SentryMiddleware.<>c__DisplayClass16_0.<InvokeAsync>b__5(Object _, Scope activeScope)
   at Sentry.Scope.Evaluate()
```

**Comment by jamescrosswell** [comment]
Hi @renanrcp, I don't seem to be able to reproduce this. I've copied **_almost_** all of the settings you shared. The only one I could mimic locally was:
```csharp
builder.Services.AddSingleton<ISentryUserFactory, PolarisSentryUserFactory>();
```

Could it possibly be related to this, do you think? Do you encounter this problem if you comment out this line?

**Comment by renanrcp** [comment]
Hi @jamescrosswell, Indeed, the error only occurs if you use or inject a SentryUserFactory. If you return SentryUser as null, this error will consistently occur as seen in the log.

```css
[May 28 - 15:58:07] [INFO] [Polaris.Backend.Core.Services.Sentry.PolarisSentryUserFactory][0]
User is not authenticated.
[May 28 - 15:58:07] [EROR] [Sentry.ISentryClient][0]
Failed invoking event handler.
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options)
   at Sentry.AspNetCore.SentryMiddleware.PopulateScope(HttpContext context, Scope scope)
   at Sentry.AspNetCore.SentryMiddleware.<>c__DisplayClass16_0.<InvokeAsync>b__5(Object _, Scope activeScope)
   at Sentry.Scope.Evaluate()
```

**Comment by jamescrosswell** [comment]
> Hi @jamescrosswell, Indeed, the error only occurs if you use or inject a SentryUserFactory. If you return SentryUser as null, this error will consistently occur as seen in this log.

Hey @renanrcp, I'm still not able to reproduce this. I tried the following:

```
builder.Services.AddSingleton<ISentryUserFactory, NullUserFactory>();

// ... all the other stuff

public class NullUserFactory : ISentryUserFactory
{
    public SentryUser? Create() => null;
}
```

Do you think you could try to put together a small sample program that reproduces the issue, that could be shared?

**Comment by renanrcp** [comment]
Hello @jamescrosswell , I've created a small [WebApi sample](https://github.com/renanrcp/Sentry-.NET-Telemetry-Error-Demo) from my original project.

To reproduce the issue, you just need to run `dotnet watch run` and try to access the `/version` endpoint.

**Comment by jamescrosswell** [comment]
> Hello @jamescrosswell , I've created a small [WebApi sample](https://github.com/renanrcp/Sentry-.NET-Telemetry-Error-Demo) from my original project.

Awesome, thanks @renanrcp ! I can reproduce this now, which is the most important step 😉
