### ISSUE TITLE
DiagnosticSource FileLoadException at sentry init

### ISSUE THREAD

**Issue by nihad-prosaldo** [getsentry/sentry-dotnet#3416]
### Package

Sentry.AspNet

### .NET Flavor

.NET Framework

### .NET Version

4.6.1

### OS

Windows

### SDK Version

3.41.4

### Steps to Reproduce

1. I installed Sentry.Aspnet (3.41.4) as nuget package in a .net framework 4.6.1 project.
2. I added the code from the startup section without the entity framework part.
3. When I try to start the app I get a System.IO.FileLoadException as soon as the SentrySDK.Init code gets executed.

I tried the following:
1. Explicitly add the System.Diagnostics.DiagnosticSource nuget package with different versions
2. Add a binding for the DiagnosticSource from 4.0.3.0 to 6.0.0 (highest supported version for .net461)

### Expected Result

It works as intended

### Actual Result
```
System.IO.FileLoadException: Die Datei oder Assembly "System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" ---> System.IO.FileLoadException: Die Datei oder Assembly "System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Dateiname: "System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Users/sample/Source/company.Mvc.Web/
LOG: Ursprünglicher PrivatePath = C:\Users\sample\source\repos\company\Source\company.Mvc.Web\bin
Aufruf von Assembly : Sentry.DiagnosticSource, Version=3.41.4.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0.
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\Users\sample\source\repos\company\Source\company.Mvc.Web\web.config
LOG: Die Hostkonfigurationsdatei wird verwendet: C:\Users\sample\Documents\IISExpress\config\aspnet.config
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config wird verwendet.
LOG: In der Anwendungskonfigurationsdatei wurde eine Umleitung gefunden. 4.0.3.0 wird nach 6.0.0.0 umgeleitet.
LOG: Verweis nach der Richtlinie: System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: Download von neuem URL file:///C:/Users/sample/AppData/Local/Temp/Temporary ASP.NET Files/root/01965f05/e350756f/System.Diagnostics.DiagnosticSource.DLL.
LOG: Download von neuem URL file:///C:/Users/sample/AppData/Local/Temp/Temporary ASP.NET Files/root/01965f05/e350756f/System.Diagnostics.DiagnosticSource/System.Diagnostics.DiagnosticSource.DLL.
LOG: Download von neuem URL file:///C:/Users/sample/source/repos/company/Source/company.Mvc.Web/bin/System.Diagnostics.DiagnosticSource.DLL.
WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Revisionsnummer.
ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.

   bei Sentry.Internal.DiagnosticSource.SentryDiagnosticListenerIntegration.Register(IHub hub, SentryOptions options)
   bei Sentry.Internal.Hub..ctor(SentryOptions options, ISentryClient client, ISessionManager sessionManager, ISystemClock clock, IInternalScopeManager scopeManager, RandomValuesFactory randomValuesFactory)
   bei Sentry.SentrySdk.InitHub(SentryOptions options)
   bei Sentry.SentrySdk.Init(SentryOptions options)
   bei Sentry.SentrySdk.Init(Action`1 configureOptions)
   bei company.Mvc.Web.MvcApplication.Application_Start() in C:\Users\sample\source\repos\company\Source\company.Mvc.Web\Global.asax.cs:Zeile 26.
```

**Comment by bitsandfoxes** [comment]
@nihad-prosaldo, sorry to see you run into issues. With version `4.0` of the .NET SDK we replaced support for .NET Framework `4.6.1` with `4.6.2`. 
The SDK relies on `System.Diagnostics.DiagnosticSource (>= 4.5.0)`.
Are you able to upgrade your project?

**Comment by nihad-prosaldo** [comment]
@bitsandfoxes we started the migration process but it will take some time until all of our needed projects are migrated. In the meantime I would like to try out sentry already though as we are currently also testing another monitoring tool.

**Comment by jamescrosswell** [comment]
> @bitsandfoxes we started the migration process but it will take some time until all of our needed projects are migrated.

If upgrading to 4.7.2 isn't an option immediately, you could maybe use version 3.41.4 of the Sentry .NET SDK?

**Comment by nihad-prosaldo** [comment]
> > @bitsandfoxes we started the migration process but it will take some time until all of our needed projects are migrated.
> 
> If upgrading to 4.7.2 isn't an option immediately, you could maybe use version 3.41.4 of the Sentry .NET SDK?

I think so, yes and that's what I tried. That's the version with which I ran into the issue marked above though.

**Comment by jamescrosswell** [comment]
That's what I get for not reading properly 😉 

So it looks like a dependency issue. The error message you're getting is complaining it can't find a suitable version of System.Diagnostics.DiagnosticSource.

[Sentry.AspNet 3.41.4](https://www.nuget.org/packages/Sentry.AspNet/3.41.4#dependencies-body-tab) depends on [Sentry.DiagnosticSource 3.41.4](https://www.nuget.org/packages/Sentry.DiagnosticSource/3.41.4#dependencies-body-tab) which depends on [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/) (>= 4.5.0).

So you'd need version 4.5.0 or later of System.Diagnostics.DiagnosticSource. 

Do you have something else in your project that has a dependency on System.Diagnostics.DiagnosticSource 4.0.3.0? It would be odd to pin to a specific version like that (whatever depends on version 4.0.3 should also be able to use 4.5.0).

**Comment by bitsandfoxes** [comment]
Closing this as it looks like a dependency conflict on the application's side of things. Please don't hesitate to reach out again if you're running into any trouble at all!
