### ISSUE TITLE
Session Replays Not Working for Front End Errors in AspNetCore

### ISSUE THREAD

**Issue by karl-gardner** [getsentry/sentry-dotnet#3429]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8

### OS

Windows

### SDK Version

newest

### Steps to Reproduce

Create a new project in with visual studio as an AspNetCore Web App (Model-View-Controller):
![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/5fbf1d6c-da7c-4321-a502-15ad75fcd33f)

Should have the following folder structure:
![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/d499d9fa-0f20-4272-8299-2ca524e46f21)

Create new project in Sentry with browser javascript:

![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/333c6308-74da-44b5-8ed4-6401e308d6fe)

Add the following line of code to the header in the Views/Home/Shared/_Layout.cshtml file with the correct dsn number for that project:
![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/5a356f9f-1979-45e7-a926-7c00cd147687)

Add the following line of code to the Views/Home/Privacy.cshtml file to trigger an error that is sent to sentry:
![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/72f6d711-c950-45fe-8f59-9c6d64a3b6bb)

Run the solution and click on the Privacy tab at the top and the error will be triggered and sent to the Sentry project:
![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/a309100d-88fa-4331-a484-18fa9b2a5fa9)

### Expected Result

Since session replays are on by default with the loader script:

https://docs.sentry.io/platforms/javascript/install/loader/

This should trigger an Error with a session replay as we threw an error in the <script> tag and you will see this in the sentry project. However, this will not show up in the session replays for that specific error. Since the default is at session replays will trigger after every error it should show up in that issue:

![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/a6616f70-4acb-4378-b7a4-36cd8cf5d4cc)

After running it a few times however I do see a session replay in the normal replays but do not see any issues attached to that session replay.

### Actual Result

Should be seeing it in this tab of the issue since it is an error but I do not:

![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/ca0525eb-a222-42b4-af29-c4b1ee1850d9)

**Comment by bitsandfoxes** [comment]
Hey @karl-gardner, thanks for reaching out. Could you confirm that there's no adblock or somesuch blocking the SDK?
I followed your repro and errors do show up as expected.
![Screenshot 2024-06-17 at 19 39 07](https://github.com/getsentry/sentry-dotnet/assets/25725783/d245057a-e6a1-43e3-94f7-61b7aa2d6aba)

**Comment by karl-gardner** [comment]
Hello @bitsandfoxes ,

Exactly! The error is showing up for me as well:

![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/0517c968-7f26-4aa9-86d6-de22f1670a45)


However, their are no session replays attached to this error:

![image](https://github.com/getsentry/sentry-dotnet/assets/91646805/2bd62b47-0d8f-4a98-894a-223d2f63121c)


Thanks,

Karl

**Comment by bitsandfoxes** [comment]
Ah, gotcha.
After playing around with it for a bit I think this looks like a current limitation of the loader script. I've forwarded the issue internally. It seems like the script is executing too early for the replay integration to kick in. You can modify the SDK's capabilities to include logging via `Project Settings -> DSN` on Sentry.
What I tested and what works right now is delaying the error (i.e. putting it inside a button `<button onclick="throw new Error('Sentry Test Error')"></button>`)

**Comment by karl-gardner** [comment]
Hello @bitsandfoxes,

So, this would be a bug and it's on the queue to be fixed? or should I look into the directions that you say to do to try to get it working?

Thanks,

Karl

**Comment by bitsandfoxes** [comment]
Maybe @lforst can chime in here to see whether this is a limitation or a bug.

**Comment by karl-gardner** [comment]
Thanks for looking into this @bitsandfoxes and @lforst

**Comment by bruno-garcia** [comment]
dupe: https://github.com/getsentry/sentry/issues/72511
