### ISSUE TITLE
Missing Trace Root

### ISSUE THREAD

**Issue by kdma** [getsentry/sentry-dotnet#3440]
### Package

Sentry

### .NET Flavor

.NET Core

### .NET Version

6.0

### OS

Windows

### SDK Version

4.7.0

### Steps to Reproduce

Following the samples I have integrated sentry 
```
webHostBuilder.UseSentry(conf =>
 {
     conf.Dsn = _configuration.GetValue<string>("Sentry:Dsn");
     conf.TracesSampleRate = _configuration.GetValue<double>("Sentry:SampleRate");
 });
```

### Expected Result

I am not sure about the expected result, since this looks like a misconfiguration of some sorts

### Actual Result

 The problem is that when I am looking at the tracing window, for every controller route hit, I see this warning about missing the trace root
  
![image](https://github.com/getsentry/sentry-dotnet/assets/2982255/7da78a61-2f31-4ca0-ad45-f6cc0c79ac17)

**Comment by jamescrosswell** [comment]
Thanks for reaching out @kdma .

I'm seeing this too for any traces from our ASP.NET Core MVC sample:
<img width="1781" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/43eccba1-1a98-4fa9-b5a2-d16aec0ddf05">

@bitsandfoxes  do you know what the requirements are for traces to show up correctly in the new Traces dashboard?

**Comment by ericsampson** [comment]
I'm also seeing this, it's really not great. Thanks!

**Comment by bitsandfoxes** [comment]
> @bitsandfoxes do you know what the requirements are for traces to show up correctly in the new Traces dashboard?

Not yet but I'm working on getting them!

**Comment by patrickklaeren** [comment]
We just started using this and are amazed at what Sentry are building.

I can see a fix for this was merged 2 days ago. Is this already in circulation or is there a planned release?

**Comment by jamescrosswell** [comment]
> I can see a fix for this was merged 2 days ago. Is this already in circulation or is there a planned release?

Change #3453 was included in the 4.8.0 release. See changelog for details:
- https://github.com/getsentry/sentry-dotnet/blob/main/CHANGELOG.md#480

**Comment by ericsampson** [comment]
@jamescrosswell dang, I was really hoping to get that fix.

Would it be possible for y'all to create a quick-turn 4.9.0 with it?

**Comment by bitsandfoxes** [comment]
> Would it be possible for y'all to create a quick-turn 4.9.0 with it?

We'll follow up with a release tomorrow!

**Comment by monowai** [comment]
Howdy - Having just wired Sentry up to my NextJS/Spring project, I'm seeing this same issue.  Regression or configuration?

![Image](https://github.com/user-attachments/assets/937770d9-67da-4a1d-b9b9-3ff735b28d19)

[Link to Trace](https://monowai-developments-ltd.sentry.io/performance/trace/0b904769565947e8a3684b8cdf17a868/?environment=mini-mike&pageEnd&pageStart&source=traces&statsPeriod=3m&timestamp=1729556325.9)

**Comment by jamescrosswell** [comment]
> Howdy - Having just wired Sentry up to my NextJS/Spring project, I'm seeing this same issue. Regression or configuration?

@monowai NextJS would be the JS SDK and Spring would be the Java SDK... so not anything to do with the .NET SDK (this repo).
