### ISSUE TITLE
Allow SDK/CLI/MSBuild integration to create a Release

### ISSUE THREAD

**Issue by ericsampson** [getsentry/sentry-dotnet#3442]
### Problem Statement

We currently use the integrated functionality of the SDK to upload debug symbols and sources, but also need to add a separate GitHub Action as a workflow step to create a Release.
It would be kinda nice to be able to do this via the SDK integration and MsBuild properties.

Cheers

### Solution Brainstorm

Add new properties to MsBuild support that would control a) whether to create a Release, b) the Environment it's for, and c) anything else needed.

**Comment by bitsandfoxes** [comment]
Hey @ericsampson! Thanks for reaching out! This is something we want to improve upon and we have a couple of issues open tracking the lack of utilization of sentry cli collected here https://github.com/getsentry/sentry-dotnet/issues/3376
Particularly https://github.com/getsentry/sentry-dotnet/issues/2142 seems to cover your ask.
Could you update the issue if there's anything missing? It really helps us gauge interest and prioritize.

**Comment by ericsampson** [comment]
Thanks, I normally search first! Oops
