### ISSUE TITLE
[Bug/question] ISentryEventProcessor not being invoked w/ Sentry.Extensions.Logging

### ISSUE THREAD

**Issue by KristinHansen** [getsentry/sentry-dotnet#3454]
### Package

Sentry.Extensions.Logging

### .NET Flavor

.NET

### .NET Version

8.0.200

### OS

Any (not platform specific)

### SDK Version

4.8.0

### Steps to Reproduce

1. Create basic Worker-project
1. Add Sentry.Extensions.Logging dependency
1. Configure logging and add Sentry
1. Configure services, adding a simple `ISentryEventProcessor` implementation that adds a specific tag with a value from an injected provider
1. Configure Sentry's minimum log level to error
1. Inject an ILogger into a Worker and use `ILogger.LogError("Foo")`

I've included a minimal reproducible project showing this. 
[WorkerService1.zip](https://github.com/user-attachments/files/16010430/WorkerService1.zip)

This might be "by design", or I might be overlooking a particular options that isn't true by default. 

I can't use the `SentryLoggingOptions.AddEventProcessor`, as I need certain dependencies injected into the `ISentryEventProcessor` implementation.

### Expected Result

After step 6 I expect that the `ISentryEventProcessor` implementation is invoked before sending the event to Sentry.

### Actual Result

The `ISentryEventProcessor` implementation is never invoked, and the expected tag and injected value is never added.

![image](https://github.com/getsentry/sentry-dotnet/assets/6368410/764261e9-9899-4d1a-b938-0045acc9555c)

**Comment by bitsandfoxes** [comment]
Hey @KristinHansen, sorry to see you run into issues. Thanks for the repro!
It looks like this is a duplication of https://github.com/getsentry/sentry-dotnet/issues/2529
We're going to need to reprioritize fixing that. Thanks!
