### ISSUE TITLE
Gauges not reporting custom metrics

### ISSUE THREAD

**Issue by patrickklaeren** [getsentry/sentry-dotnet#3479]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Windows

### SDK Version

4.9.0

### Self-Hosted Sentry Version

24.6.0

### Steps to Reproduce

1. Clone this repository 
2. Configure and Run the console metrics sample @ https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.Console.Metrics/Program.cs
3. Wait for metrics to report to Sentry

### Expected Result

All custom metrics reported.

### Actual Result

All metrics **EXCEPT** gauges are reported.

**Comment by bitsandfoxes** [comment]
Hey @patrickklaeren, thanks for reaching out!
I really don't like saying it but "it works on my machine". I'm running our samples and I do see the `guesses`: https://github.com/getsentry/sentry-dotnet/blob/e68c8c7e2d165715077e12578679be15192e3537/samples/Sentry.Samples.Console.Metrics/Program.cs#L82 
![Screenshot 2024-07-15 at 19 25 03](https://github.com/user-attachments/assets/4f99ba5a-5514-447a-9446-7072efb4ab67)

**Comment by bitsandfoxes** [comment]
Looking at it now, the `min`, `max` and `sum` does not seem right tho.

**Comment by patrickklaeren** [comment]
> Looking at it now, the `min`, `max` and `sum` does not seem right tho.

Is this on a self hosted or SaaS instance?

**Comment by bitsandfoxes** [comment]
> Is this on a self hosted or SaaS instance?

That's the SaaS instance.

**Comment by patrickklaeren** [comment]
Yeah this just isn't coming through on my self hosted instance. I don't know why. The debug output shows it picking up the metric and then it seems to blackhole.

Everything else is sending over.

I will wait for a new version of self hosted to land for now.

**Comment by patrickklaeren** [comment]
Ok looks like this might be related to https://github.com/getsentry/self-hosted/pull/3177 if I understand correctly?

**Comment by bitsandfoxes** [comment]
> Ok looks like this might be related to https://github.com/getsentry/self-hosted/pull/3177 if I understand correctly?

I'd agree. This does not seem to be an SDK-specific issue. I'm closing this issue in favor of the already ongoing PR but please feel free to reopen in any case.
