### ISSUE TITLE
`db.connection` and `db.query` disconnected

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3495]
Coming from an ASP.NET Core application and out EntityFrameworkCore instrumentation:

![Image](https://github.com/user-attachments/assets/0d42bd42-0a52-4686-88c5-2211f39bd16c)

**Comment by bitsandfoxes** [comment]
As per https://github.com/getsentry/sentry-dotnet/pull/2409#issuecomment-1581692139 this is per design as the relationship between a `db.connection` and a `db.query` is not necessarily a 1:1 relationship.

**Comment by jamescrosswell** [comment]
> As per [#2409 (comment)](https://github.com/getsentry/sentry-dotnet/pull/2409#issuecomment-1581692139) this is per design as the relationship between a `db.connection` and a `db.query` is not necessarily a 1:1 relationship.

We could/should maybe add the context from that comment to a FAQ or something somewhere in the docs? I think this is the 3rd or 4th time this has come up.
