### ISSUE TITLE
Enable NetworkStatusListener for specific platforms

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3510]
Currently if network connectivity is lost temporarily, envelopes sent while the network was unavailable will only be sent again once the application restarts _**if**_ not using MAUI _**and**_ publishing for a specific platform (e.g. Android or Windows). 

We could **_always_** initialise the `SentryOptions.NetworkStatusListener` to a `new PollingNetworkStatusListener` but let the `SentryMauiOptionsSetup` override this... or some similar solution.

_Originally posted by @jamescrosswell in https://github.com/getsentry/sentry-dotnet/pull/3438#discussion_r1695837252_

**Comment by bitsandfoxes** [comment]
I don't see any downsides to set the `PollingNetworkStatusListener` by default. As long as we make sure not to overwrite anything users have already set I think this is a great improvement.

**Comment by jamescrosswell** [comment]
> As long as we make sure not to overwrite anything users have already set I think this is a great improvement.

Looking at the comments, this was never designed to be exposed to users in the first place:
https://github.com/getsentry/sentry-dotnet/blob/d5d4b663b4c6c9ba5fc23f3a82cc66a555cfdcac/src/Sentry/SentryOptions.cs#L1116-L1121

None the less, we'll set the default in the constructor so it should have the lowest precedence.
