### ISSUE TITLE
Sentry.Maui 4.10 not including native iOS library

### ISSUE THREAD

**Issue by MichaelLHerman** [getsentry/sentry-dotnet#3538]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0

### OS

iOS

### SDK Version

4.10

### Steps to Reproduce

Open Sentry.Samples.Maui

Replace project reference with package reference
```
<PackageReference Include="Sentry.Maui" Version="4.10.0" />
```

Start app in VS Code targeting iOS 17.2 simulator 

Click on "Cause Native Crash" button.  
Nothing happens.
If using 4.9, app will crash.

If the native library isn't included, this means native crash reporting isn't working?

### Expected Result

![Image](https://github.com/user-attachments/assets/ee7d3f36-f48c-46ae-9d26-91343459fdbb)

### Actual Result

![Image](https://github.com/user-attachments/assets/6d9450e9-1bd9-4902-80fc-561dd35a8e95)

**Comment by MichaelLHerman** [comment]
Workaround: if I specifically target 17.5 sdk and do a dotnet workload restore, it now works (crashes), even if I revert the sdk version

<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks);net8.0-ios17.5;net8.0-maccatalyst</TargetFrameworks>

**Comment by bitsandfoxes** [comment]
Thanks @MichaelLHerman for the detailed issue and the workaround!

This seems to coincide with a bump in in `Microsoft.iOS` where we had to [update CI to 17.5 as well](https://github.com/getsentry/sentry-dotnet/pull/3528).
```
This version of Microsoft.iOS requires the iOS 17.5 SDK
```

Since the `dotnet workload restore` seems to have resolved this I guess this is an development environment related issue and not an issue with the functionality of the SDK.

**Comment by bitsandfoxes** [comment]
@jamescrosswell do you think it makes sense to pin to a specific version of `net8.0-ios`?

**Comment by jamescrosswell** [comment]
> [@jamescrosswell](https://github.com/jamescrosswell) do you think it makes sense to pin to a specific version of `net8.0-ios`?

I thought `net8-ios` (a part from being a target framework) was basically a transitive dependency for MAUI?

[The source](https://github.com/xamarin/xamarin-macios/releases) includes this comment in this change log:
> Note: these are the base SDKs that add support for the platforms in question. For MAUI (which is built on top of our SDKs), visit: https://learn.microsoft.com/dotnet/maui/.

What's odd is that usually, if you don't have the correct workloads installed, dotnet build or dotnet run or whatever gives you an error message telling you to run `dotnet workload restore`. I'm wondering why @MichaelLHerman didn't get such an error in this case.

**Comment by bitsandfoxes** [comment]
Closing this as `dotnet workload restore` seems to resolve the environment/dependencies and there doesn't seem to be anything actionable for the SDK.
