### ISSUE TITLE
Releases Aren't Setup

### ISSUE THREAD

**Issue by BillChirico** [getsentry/sentry-dotnet#355]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core

* Version: 3.1.1

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x] Sentry.AspNetCore

* Version: Latest

Hello,

I've successfully created releases into Sentry using GitHub actions, but my dashboard is saying that releases aren't 100% setup and the next step is to add tabs to associate errors with releases and commits. Here is my workflow:

```
# Install Sentry CLI
curl -sL https://sentry.io/get-cli/ | bash

# Create new Sentry release
export SENTRY_RELEASE=$(sentry-cli releases propose-version)
sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
sentry-cli releases set-commits --auto $SENTRY_RELEASE
sentry-cli releases finalize $SENTRY_RELEASE

# Create new deploy for this Sentry release
sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_DEPLOY_ENVIRONMENT
```

What am I doing wrong here?

**Comment by josh-degraw** [comment]
I'm assuming you have set all of your keys and/or environment variables correctly.. If that's the case then what is the output of the commands you run above?

**Comment by BillChirico** [comment]
@josh-degraw I believe all the keys are set correctly because I see releases in the tab. Just to confirm, I'm setting the SENTRY_AUTH_TOKEN to an organizational internal integration correct?

Output:
```
    # Install Sentry CLI
  curl -sL https://sentry.io/get-cli/ | bash
  
  # Create new Sentry release
  export SENTRY_RELEASE=$(sentry-cli releases propose-version)
  sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
  sentry-cli releases set-commits --auto $SENTRY_RELEASE
  sentry-cli releases finalize $SENTRY_RELEASE
  
  # Create new deploy for this Sentry release
  sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_DEPLOY_ENVIRONMENT
  shell: /bin/bash -e {0}
  env:
    SENTRY_AUTH_TOKEN: ***
    SENTRY_ORG: volvox
    SENTRY_PROJECT: volvoxapollo
    SENTRY_DEPLOY_ENVIRONMENT: Production
This script will automatically install sentry-cli 1.49.0 for you.
Installation path: /usr/local/bin/sentry-cli
#=#=#                                                                         

######                                                                     8.9%
#######################################################################   98.7%
######################################################################## 100.0%
Done!
Created release bc1d952ade60b1539a6767648670a897b4468ac4.
+---------------------------+--------------+
| Repository                | Revision     |
+---------------------------+--------------+
| BillChirico/Volvox.Apollo | bc1d952ade60 |
+---------------------------+--------------+
Finalized release bc1d952ade60b1539a6767648670a897b4468ac4.
Created new deploy unnamed for 'Production'
```
Releases:
![image](https://user-images.githubusercontent.com/13951316/74109645-24cced00-4b53-11ea-9f88-fc39d8514471.png)

**Comment by josh-degraw** [comment]
Have you set up your sentry org with your repositories from the sentry side?

**Comment by BillChirico** [comment]
@josh-degraw  Yes sir!

![image](https://user-images.githubusercontent.com/13951316/74112955-fc52ec00-4b6e-11ea-9afe-a3b27a71d31e.png)

**Comment by BillChirico** [comment]
@josh-degraw What Auth Token should I be using? An internal integration on the organization?

**Comment by josh-degraw** [comment]
From the CLI you should only have to use your Sentry Auth token that you get in the Sentry UI.

My other question would be are you referencing that release in your code? It seems to me like what you're doing on the CLI side is correct, so then you should just need to make sure that in your code you're setting the release correctly. 

This part could require some more manual effort. For example, I run my builds in Azure DevOps, where I store the Release number (in my case the build number) to a config file, then read that at runtime and assign that to the sentry options.

So for example (if using `SentrySdk.Init`):

```c#
SentrySdk.Init(o =>
{
   o.Release = GetRelease(); // Some method that can read the sentry release number at runtime
});
```

**Comment by BillChirico** [comment]
@josh-degraw That's exactly what I'm missing! How would you recommend to read the sentry release number at runtime?

**Comment by bruno-garcia** [comment]
It's common to patch the `AssemblyInfo` or `AssemblyInformationalInfo` during build.
The Sentry SDK already reads from those by default (if you haven't set a `Release` explicitly via code or via `SENTRY_RELEASE` environment variable).

More at: https://getsentry.github.io/sentry-dotnet/manual/manual.html#release

And:

https://github.com/getsentry/sentry-dotnet/blob/b770762dc3ecd93a10d6a9038799e1377b7cfd5d/src/Sentry/Internal/ApplicationVersionLocator.cs#L6-L23

**Comment by josh-degraw** [comment]
@BillChirico If what @bruno-garcia suggested doesn't work/isn't applicable, what we do in my case is write the release number to a file (in my case an XML configuration file) at build-time, and then at runtime when the app starts up it reads from that file and assigns it to the sentry release.

**Comment by bruno-garcia** [comment]
Sentry also supports the environment variable `SENTRY_RELEASE`.
If you can set that on your container or server, it'll be reported automatically.

**Comment by bruno-garcia** [comment]
The SDK reports now 1.0.0 or whatever is set
