### ISSUE TITLE
Failed to parse metric

### ISSUE THREAD

**Issue by miscusi-marcoaceti** [getsentry/sentry-dotnet#3551]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

8.0.7

### OS

Windows

### SDK Version

4.10.2

### Self-Hosted Sentry Version

24.8.0

### Steps to Reproduce

1. Enable metrics in the self-hosted instance (untested on sentry.io)
2. Create a ASP.NET Core application
3. Install Sentry.AspNetCore and enable tracing
4. Start a transaction (e.g. HTTP request to a endpoint)

### Expected Result

(Screenshot taken before enabling metrics on the server)

![Image](https://github.com/user-attachments/assets/901925d4-4aa9-467c-a696-34e06e7e968c)

### Actual Result

![Image](https://github.com/user-attachments/assets/db5ded4b-ad48-41f2-b23e-f6810252382c)

![Image](https://github.com/user-attachments/assets/8b25f56e-94a8-45cd-9244-3b9f030a9785)

**Comment by jamescrosswell** [comment]
I can't reproduce this on sentry.io.

Reading the docs, it looks like you might have to also [setup metrics in your self hosted sentry installation](https://develop.sentry.dev/self-hosted/#enabling-preview-features):
> Only features that have reached General Availability (GA) status will be enabled by default for self-hosted. As users, you can try new features before it reaches GA by adding required infrastructure components and feature flags. 

This issue in the self hosted repo looks like it might be relevant:
- https://github.com/getsentry/self-hosted/issues/2698

**Comment by bitsandfoxes** [comment]
Closing this as stale. Please feel free to reopen this issue if it persists for you.
