### ISSUE TITLE
How to capture an unhandeled exception

### ISSUE THREAD

**Issue by zuhairamahdi** [getsentry/sentry-dotnet#3553]
Hi All,

first of all, I'm not a dot net developer so take what I will say with an open mind.
we have a very large application with many issues and exception that are mostly unhandled (we get approx. more than 7000 errors a day). we are trying to implement Sentry in our application as it will be very useful for fixing all these issues.
the issue we are facing is that we have to use `SentrySdk.CaptureException(err);` which comes as `New Issue` and we have to create `try catch` in our code to handle it. is there a way to capture `Exception` as it occurs without calling SentrySdk every time or maybe im missing some `option` that need to be configured.

**Comment by zuhairamahdi** [comment]
Thanks @jamescrosswell 

this issue can be closed. we figured it out by following the example provided ([ASP.NET Core](https://github.com/getsentry/sentry-dotnet/blob/43e28adab2859d8defc0c67692e3e00b4b2060bc/samples/Sentry.Samples.AspNetCore.Basic/Program.cs#L41-L45))

**Comment by trydalch** [comment]
Is there any specific guidance on how to use Sentry with Uno? Which package should be used? Does it depend on which target you build for?

The docs mention Maui, Xamarin and Xamarin.Forms are supported. This is the first place I’ve seen uno mentioned.

**Comment by jamescrosswell** [comment]
> Is there any specific guidance on how to use Sentry with Uno?

There's no specific guidance for Uno no. Generally if you want to wire Sentry up when there isn't a specific integration, you'd just use `SentrySdk.Init` (see the [getting started docs](https://docs.sentry.io/platforms/dotnet/#configure)). I've never used Uno so I'm not sure how it would work there.
