### ISSUE TITLE
Replace SubstringOrRegexPattern with an IStringOrRegexMatcher

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#3560]
We have a better abstraction for this now:
https://github.com/getsentry/sentry-dotnet/blob/34b55980cd9f84d3922f80ff70c87b76d38ae01d/src/Sentry/SubstringOrRegexPattern.cs#L5-L10

**Comment by bitsandfoxes** [comment]
Closed by #3566
