### ISSUE TITLE
Remove Metrics API

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3597]
More about the what and why: https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Metrics-Beta-Coming-to-an-End

Metrics have been marked as `obsolete` in https://github.com/getsentry/sentry-dotnet/pull/3619

**Comment by jamescrosswell** [comment]
Resolved by:
- https://github.com/getsentry/sentry-dotnet/pull/3718
