### ISSUE TITLE
SentrySdk.FlushAsync not EditorBrowsable

### ISSUE THREAD

**Issue by josh-degraw** [getsentry/sentry-dotnet#360]
What was the reasoning for marking the static `SentrySdk.FlushAsync` method with `EditorBrowsableState.Never`? I was trying to flush sentry via the static method and I had come here to request the method be added when I discovered it was there, just hidden. I'm just wondering what the reasoning was for that and if that's the best thing to do in this case.

**Comment by bruno-garcia** [comment]
That's a bug. It should have been `[DebuggerStepThrough]`. 😢
