### ISSUE TITLE
Alignment warnings when targeting net9.0-android - MAUI

### ISSUE THREAD

**Issue by bcaceiro** [getsentry/sentry-dotnet#3633]
### Problem Statement

Building dotnet maui with .net 9 there are warnings regarding Sentry lib:

NuGet package '<unknown>' version '<unknown>' contains a shared library 'libsentry-android.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
NuGet package '<unknown>' version '<unknown>' contains a shared library 'libsentry.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
NuGet package '<unknown>' version '<unknown>' contains a shared library 'libsentry-android.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
NuGet package '<unknown>' version '<unknown>' contains a shared library 'libsentry.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
NuGet package '<unknown>' version '<unknown>' contains a shared library 'libsentrysupplemental.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
NuGet package '<unknown>' version '<unknown>' contains a shared library 'libsentrysupplemental.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details

**Comment by jamescrosswell** [comment]
Thanks @bcaceiro. We're still working on .NET 9 support and I've associated this with the main ticket that is being used to track progress against that.

I wouldn't recommend using Sentry 4.x with net9.0.

**Comment by bcaceiro** [comment]
Thank you for the information @jamescrosswell ! Will keep an eye on updates!

**Comment by supervacuus** [comment]
duplicate: https://github.com/getsentry/sentry-dotnet/issues/3672
