### ISSUE TITLE
Event '00000000000000000000000000000000' queued, Sentry events not being sent or ingested

### ISSUE THREAD

**Issue by vmandic** [getsentry/sentry-dotnet#3646]
I started missing any alerts on new events in my prod env API which uses Sentry to send events and warn me about ERR and FTL events.

In my latest deployment of a dockerized C# dotnet API service I am observing a message in docker service logs:

```log
info: Sentry.AspNetCore.SentryMiddleware[0]
  Event '00000000000000000000000000000000' queued.
```

It seems to be for every Sentry event that should register an event.

The service is on .NET 7.0.203 SDK using Sentry for dotnet:

```
    <PackageReference Include="Sentry.AspNetCore" Version="3.31.0" />
```

I am aware I could do an upgrade of the lib, this is not the topic here (even tho could be the solution), but I am concerned why this started happening as in last deployed changeset there is nothing related to Sentry. No cross-cutting changes that could affect it and similar.

What is even stranger is that this persists after restarting the service. This started roughly on Sept 27th 2024 around 13:00 UTC

I register Sentry in my Program.cs as.

```csharp
WebHost.CreateDefaultBuilder(args)
...
               .UseSentry(s => s.AddServerAppSentry())
...

...

  public static void AddServerAppSentry(this SentryAspNetCoreOptions s) => SetupSentryBaseConfiguration(s);

...

private static void SetupSentryBaseConfiguration(SentryOptions s)
        {
            s.AddExceptionFilterForType<OperationCanceledException>();
            s.StackTraceMode = StackTraceMode.Enhanced;

            var dockerImageBuildTimestamp = Environment.GetEnvironmentVariable("SEMVER_BUILD_DT_UTC");
            if (!string.IsNullOrWhiteSpace(dockerImageBuildTimestamp))
            {
                // tracked with "tags" and allows us to get a sense of time when a release was made or an issue fired
                s.Distribution = dockerImageBuildTimestamp;
            }

            s.BeforeSend += sentryEvent =>
            {
                sentryEvent.SetExtra(
                    "STARTUP_DATETIME_UTC",
                    StartupDateTime);

                return sentryEvent;
            };
        }
```

Any ideas please? This is a bit scary as this like walking blind now. 

I will take a look into your source to see how you form this Event ID. What is strange to me is it works on my staging API service, and I observe that other services also lack events, what is super confusing is that we see events from Sept 29th in Sentry, which is 2 days after the issue I describe in the title. I am just trying to correlate this if it is related at all.

So the last issue I see in my API is with ID: 5292033590 (of project ID: 5239187)
And also an example of last issue is see for other "consumers" service is with ID: 5926198617 (of project ID: 6323756)

To make things even more interesting there is third (among other) service, which sent for prod environment an event 20h ago, ID: 5916455273 (of project ID: 5534740)

Atm you have an incident, is it related? https://status.sentry.io/incidents/f2nr1rnzcx0l

**Comment by vmandic** [comment]
Digging up in your source, this ID comes from here: https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Internal/Hub.cs#L423

So I guess the zeros ID can come from the catch there also?

**Comment by jamescrosswell** [comment]
@vmandic, given that you didn't change anything, it seems likely that something else changed. Possibly a new release of [Sentry](https://github.com/getsentry/sentry/releases/tag/24.9.0) or the Relay?

We're pretty slammed at the moment so it'll be hard to carve out time to investigate an issue with v3.31.0 unless there's a really compelling reason you can't upgrade to 4.12.0. If you're still experiencing issues with 4.12.0 I can take a look though.

**Comment by vmandic** [comment]
Thanks for reaching out @jamescrosswell, very much.

We are pretty confused about this. And, now even more after the latest attempt we have tried. So, we had to do a hotfix and issue a new deployment for one of the N services we have. This was a single line of business logic fix in C#. After redeploying this service it started issuing events without 0000 IDs to Sentry. I just checked logs of all the services and figured out that the worker ones which use global mode and auto session have not had any issues in last 8h (when I deployed) but the 2 API ones have had (they don't use global mode and auto session).

After this deployment we started getting "some" (like just a dozen of them which is a lot less then what we expect in the baseline) events from API also, then a silence again... :-( 

I have a strange feeling that it is related to the non-global mode of APIs and that somehow hitting some log line messes up Sentry SDK somehow.

Thanks on the outside of the box thinking, but the Sentry release was 2wk ago and does not correlate with our first notice of missing events from Sept 27th.

I guess the upgrade of lib is the next step.

**Comment by vmandic** [comment]
I think I finally correlated sth meaningful in the logs by time and 0000 IDs. Seems to be a System.OperationCanceledException somewhere in here.

![Image](https://github.com/user-attachments/assets/1ecf5143-72d5-4eff-ab19-c882bbb9bdd7)

This is why we get 0000 IDs.

```csharp
private SentryId DoSendEvent(SentryEvent @event, Scope? scope)
    {
        if (_options.SampleRate != null)
        {
            if (!_randomValuesFactory.NextBool(_options.SampleRate.Value))
            {
                _options.ClientReportRecorder.RecordDiscardedEvent(DiscardReason.SampleRate, DataCategory.Error);
                _options.LogDebug("Event sampled.");
                return SentryId.Empty;
            }
        }

        var filteredExceptions = ApplyExceptionFilters(@event.Exception);
        if (filteredExceptions?.Count > 0)
        {
            _options.ClientReportRecorder.RecordDiscardedEvent(DiscardReason.EventProcessor, DataCategory.Error);
            _options.LogInfo("Event was dropped by one or more exception filters for exception(s): {0}",
                string.Join(", ", filteredExceptions.Select(e => e.GetType()).Distinct()));
            return SentryId.Empty;
        }

...
```

**Comment by jamescrosswell** [comment]
> Ugh, this is by intention in the setup code (pasted in the initial message also) that we have... which means I have been chasing the "wrong ghost" all of this time. Oh my.

Aha, great sleuthing. So you found/fixed the problem?

**Comment by vmandic** [comment]
We can't confirm with 100% certainty that this is fixed as we do not know the source of it. After rebuilding and issuing the deployment we started getting back issues, but are uncertain of the amount of them and we are now monitoring and correlating with our docker logs for the next few days.

In the meantime we are preparing to issue a new deployment, likely tomorrow with the new v4.12.0 (looks good in staging so far).

**Comment by vmandic** [comment]
Considering closing this now after deploying the upgrade. We saw that we have a bit more logs now like "Too many requests" but we belive this was due to TracesSampleRate=1. 

Sorry for an off-topic question but can you confirm if Sentry__TracesSampleRate=0.1 is a valid thing to set up through environment variables?

**Comment by jamescrosswell** [comment]
> Considering closing this now after deploying the upgrade. We saw that we have a bit more logs now 

Good stuff!

> Sorry for an off-topic question but can you confirm if Sentry__TracesSampleRate=0.1 is a valid thing to set up through environment variables?

That should be fine - that's stock standard **configuration binding** behaviour and Sentry doesn't disable the environment variable configuration binding provider.
