### ISSUE TITLE
4.12: SentryMauiOptions.Native not available on IOS anymore (was ok on 4.11)

### ISSUE THREAD

**Issue by softlion** [getsentry/sentry-dotnet#3648]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

iOS

### SDK Version

4.12

### Steps to Reproduce

![Image](https://github.com/user-attachments/assets/9304cfdb-0b39-40a5-981c-258eb4438c60)

### Expected Result

No error building this code.
This code does compile ok on 4.11

![Image](https://github.com/user-attachments/assets/7cc40426-814d-4014-a8dd-b09a1b14cc68)

### Actual Result

The `Native` property is not available anymore.

**Comment by jamescrosswell** [comment]
@softlion the Native options are used in the sample apps, e.g. here:
https://github.com/getsentry/sentry-dotnet/blob/43e28adab2859d8defc0c67692e3e00b4b2060bc/samples/Sentry.Samples.Ios/AppDelegate.cs#L25

So the solution wouldn't compile and we couldn't make a release if these weren't available. 

Possibly clean your solution and restore workloads/packages?

**Comment by espenrl** [comment]
I'm experiencing the same thing. Had to downgrade. Even fails in CI where the caches start out from scratch.

**Comment by yguillermin** [comment]
> [@softlion](https://github.com/softlion) the Native options are used in the sample apps, e.g. here:
> 
> [sentry-dotnet/samples/Sentry.Samples.Ios/AppDelegate.cs](https://github.com/getsentry/sentry-dotnet/blob/43e28adab2859d8defc0c67692e3e00b4b2060bc/samples/Sentry.Samples.Ios/AppDelegate.cs#L25)
> 
> Line 25 in [43e28ad](/getsentry/sentry-dotnet/commit/43e28adab2859d8defc0c67692e3e00b4b2060bc)
> 
>              options.Native.EnableAppHangTracking = true; 
> So the solution wouldn't compile and we couldn't make a release if these weren't available.
> 
> Possibly clean your solution and restore workloads/packages?

I have the same issue too. It work's on the sample project because sentry is referenced using a project reference. If you replace it using the NuGet package, the compilation will failed.

**Comment by bruno-garcia** [comment]
Diff: https://github.com/getsentry/sentry-dotnet/compare/4.11.0...4.12.0

We [didn't update `sentry-cocoa`](https://github.com/getsentry/sentry-cocoa) nor the [bindings project](https://github.com/getsentry/sentry-dotnet/tree/main/src/Sentry.Bindings.Cocoa).

The only thing related to iOS that changed, was the xcode version.

Went from xcode 15.4 to 16

![Image](https://github.com/user-attachments/assets/1a4c1ff9-9cc5-49b9-a857-5f8c0c76d7d0)

I wonder if the .NET tooling has some issues with this version of xcode.

**Comment by jamescrosswell** [comment]
I'm unable to reproduce this. Here's my `MauiProgram.cs` which I tested first referencing Sentry.Maui 4.11.0 and then with 4.12.0:
```
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            // This adds Sentry to your Maui application
            .UseSentry(options =>
            {
                // The DSN is the only required option.
                options.Dsn = "MY_SENTRY_DSN";
                options.Debug = true;
#if __IOS__                
                options.Native.EnableSwizzling = true;
#endif
            })   
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });

#if DEBUG
        builder.Logging.AddDebug();
#endif

        return builder.Build();
    }
}
```

If anyone can provide a minimal reproduction then I can look into this though.

**Comment by espenrl** [comment]
If I do decompiled sources (ReSharper / Visual Studio) I get this for Android:

![Image](https://github.com/user-attachments/assets/181c6029-a2b5-48d9-b4ed-91f12a757bb4)

But doing the same for iOS there is no Native property at all.

PS: Just deleted all Sentry packages from NuGet cache forcing a fresh download.

**Comment by espenrl** [comment]
And using DotPeek I have a hard time finding the existence of the property Native as well as its type NativeOptions. In this case for both Android and iOS. Something is not right.

**Comment by espenrl** [comment]
Here is a hint :)

![Image](https://github.com/user-attachments/assets/ce70eecc-7984-4844-9b1b-01db545b174e)

Seems like `https://www.nuget.org/packages/Sentry.Bindings.Cocoa/4.12.0` isn't being referenced. Can't find traces of it in `project.assets.json` either on v4.12. On v4.11 I find this 

![Image](https://github.com/user-attachments/assets/d774a20d-bff0-4df1-b16a-4eefaeeb151d)

**Comment by espenrl** [comment]
Seems to be issues with MAUI and XCode 16. Might be related as Sentry is using v16.

https://github.com/dotnet/maui/issues/24819

![Image](https://github.com/user-attachments/assets/13579d59-886f-4c0c-b2e0-7778ffb31865)

**Comment by espenrl** [comment]
And there are different targets between 4.11 and 4.12 in the NuGet packages. `net8.0-ios17.5` vs `net8.0-ios18.0`. My project which fails building is targeting net8.0-ios17.5

**Comment by softlion** [comment]
> And there are different targets between 4.11 and 4.12 in https://www.nuget.org/packages/Sentry. `net8.0-ios17.5` vs `net8.0-ios18.0`. My project which fails building is targeting `net8.0-ios` and MAUI build system resolves it to `net8.0-ios17.5` (project.assets.json).
> 
> I guess not everyone is building with the latest MAUI workload, which is true in my case. CI is locked to an older MAUI workload for iOS due to bugs introduces in the latest one.
> 
> ![Image](https://github.com/user-attachments/assets/0531e722-ee3c-4b13-a09f-55c1bc7a0e40)

You found the issue !!

To use this mew sentry nuget we all should use the latest net SDK which is 18 and requires xcode 16. 

Sentry devs could instead specify both net8.0-ios and net8.0-ios17.5 in the targets.
That will fix the issue

**Comment by jamescrosswell** [comment]
> To use this mew sentry nuget we all should use the latest net SDK which is 18 and requires xcode 16.

Aha, that makes sense. That was the main reason for making the 4.12 release (to support XCode 16).
 
> Sentry devs could instead specify both net8.0-ios and net8.0-ios17.5 in the targets.

I'm not sure if that's practical. The reason we bumped to `net8.0-ios18.0` is because `net8.0-ios17.5` doesn't work with XCode 16... so in order to support both, we'd need two separate versions of the Sentry/Sentry.Maui packages: one set built using XCode 15.4 and the other built using XCode 16... and NuGet wouldn't know which one to pull because XCode isn't one of the dependencies it manages. 

We'll discuss internally but for the time being I'll put a big warning about the change in dependencies in the change log, so hopefully fewer people get caught out by this.

Apologies in advance for any trouble this has caused folks. We'll definitely look into what happened here and try to avoid it happening again in future. Changes to tooling from multiple vendors who don't coordinate doesn't help things, but that's the world we live in so we need some good checks and balances in place to mitigate the impact of that on Sentry SDK users.
