### ISSUE TITLE
Report correct SDK name on native (NDK) Android crashes

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3654]
Crashes coming form `sentry.native` under the Android SDK should be reported as:

`sentry.native.android.dotnet`

Currently, it's reported as `sentry.native.android`, which is the same as standalone Android apps.

On the Unity SDK, we override it at compile time, and here we don't recompile the SDK so not sure if it can be easily done:

https://github.com/getsentry/sentry-unity/blob/e4d3d4d13ed0ab3f4e2a05534bfb8592c92e319d/Directory.Build.targets#L190

**Comment by jamescrosswell** [comment]
Yeah it looks like in the Java repo it's baked in at build time:
https://github.com/getsentry/sentry-java/commit/66140be425f581aaf57584f2f927b67402a3fca7

I think we'd need some other mechanism to be made available to set this for the .NET SDK.

**Comment by vaind** [comment]
Runtime setting:

https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java#L145

**Comment by jamescrosswell** [comment]
> Currently, it's reported as `sentry.native.android`, which is the same as standalone Android apps.

Hm, something is off here. We set this in the .NET SDK already:
https://github.com/getsentry/sentry-dotnet/blob/b0a19968ceb0ec5103f3e1887afe2c865351aca3/src/Sentry/Platforms/Android/SentrySdk.cs#L170

So whilst we could change that to `sentry.native.android.dotnet`, if it's coming through as `sentry.native.android` at the moment then that mechanism isn't working as it should at the moment.

**Comment by bruno-garcia** [comment]
> > Currently, it's reported as `sentry.native.android`, which is the same as standalone Android apps.
> 
> Hm, something is off here. We set this in the .NET SDK already:
> 
> [sentry-dotnet/src/Sentry/Platforms/Android/SentrySdk.cs](https://github.com/getsentry/sentry-dotnet/blob/b0a19968ceb0ec5103f3e1887afe2c865351aca3/src/Sentry/Platforms/Android/SentrySdk.cs#L170)
> 
> Line 170 in [b0a1996](/getsentry/sentry-dotnet/commit/b0a19968ceb0ec5103f3e1887afe2c865351aca3)
> 
>              o.NativeSdkName = "sentry.native.dotnet"; 
> So whilst we could change that to `sentry.native.android.dotnet`, if it's coming through as `sentry.native.android` at the moment then that mechanism isn't working as it should at the moment.

This is definitely wrong. If we're passing this down to the Java layer, it should be `sentry.java.android.dotnet` (appending `.dotnet` to the original name).
If we're passing this to the NDK layer (sentry-native). Appending `.dotnet` would result in: `sentry.native.android.dotnet`

**Comment by bitsandfoxes** [comment]
Either the PR description is off or I'm missing something here:
- [Event](https://sentry-sdks.sentry.io/issues/5743360551/events/daf28a4e79cc48c46a3175b7570fc723/) prior to #3682 coming from our Samples.Android
![Image](https://github.com/user-attachments/assets/5d384ef6-a957-46b9-be78-cf8fca4a5f4b)
- [Event](https://sentry-sdks.sentry.io/issues/5743360551/events/5398fb3bc03e4b370bf99f4b44a287b0/) after #3682 coming from our Samples.Android
![Image](https://github.com/user-attachments/assets/f1102196-9fc2-4211-9911-07ef56bb4b94)

**Comment by bitsandfoxes** [comment]
Overwriting via the option seems to work just fine. 
![Image](https://github.com/user-attachments/assets/537dc8af-eb95-45a5-8fbc-5968f4a98bb2)

I think we can close this one.

**Comment by jamescrosswell** [comment]
Ah cool, presumably our frantic manager made a typo in the description.
