### ISSUE TITLE
Crash on Launch When Including Maui Sentry SDK Without Configuration in Release Builds

### ISSUE THREAD

**Issue by mgr44** [getsentry/sentry-dotnet#3681]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Android

### SDK Version

4.12.1

### Steps to Reproduce

1. Create a new Maui app project
2. Include the Sentry.Maui nuget package 4.12.1
3. Do not configure or reference the sentry package anywhere (don't change anything in the code).
4. Build and Deploy either a release build, or a Debug build with trimming enabled in the Android options

### Expected Result

The app should launch normally without issue.

### Actual Result

The app crashes during launch. If this is done in a debug build then the following exception is observed: 

Java.Lang.RuntimeException
  Message=Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.IllegalArgumentException: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.

**Comment by mgr44** [comment]
This issue isn't a big problem on it's own. Once sentry is configured properly it goes away. Or the package can just be removed. However, it did cause me issues when I was trying to reproduce a different trimming related problem: https://github.com/getsentry/sentry-dotnet/issues/3680

When I tried to simplify my project I inadvertently caused this error with similar symptoms as 3680, so i took me a while to understand what was going on. In and case, simply including a package should not cause a crash.

**Comment by jamescrosswell** [comment]
> simply including a package should not cause a crash

Agreed, thanks for reporting. We'll look into it!

**Comment by mgr44** [comment]
Thanks for looking into this @bricefriha. Yes that seems tricky if the auto init is set at runtime i don't know of anyway to ensure that it is executed if none of the code is being referenced.

**Comment by bruno-garcia** [comment]
it's by design though. We don't want you to add sentry and accidentally mia configure it and go to prod, blind

**Comment by bruno-garcia** [comment]
Perhaps we need to document this better so it's not a surprise to folks.
@bricefriha is this something you can do?

**Comment by bricefriha** [comment]
@bruno-garcia 
> is this something you can do?

I'll see what I can do
