### ISSUE TITLE
[MSB4186] Invalid static method invocation syntax: "[MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetPlatformIdentifier

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3717]
A customer reached out via zendesk:

> I have added Senty to my C# project without issue while running Visual Studio in Parallels on my Mac. Now, with the free release of JetBrains Rider, I wanted to give it a shot on my Mac side.

> However, when I try to load my solution I'm getting an error from Sentry, and the project won't load?

> [MSB4186] Invalid static method invocation syntax: "[MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetPlatformIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. /Users/rgb/Repositories/cadsys-www/packages/Sentry.4.10.2/build/Sentry.targets at (171:47)

> This is the Sentry.targets file, row 171 is the one with =='iOS' in it:

```
<ItemGroup Condition="'$(SentryCLIUploadNativeAOT)' != 'true'">
  <SentryCLIUploadSymbolType Include="pdb" />
  <SentryCLIUploadSymbolType Include="portablepdb" />
  <SentryCLIUploadSymbolType Include="dsym" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" />
  <SentryCLIUploadSymbolType Include="dsym" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'" />
  <SentryCLIUploadSymbolType Include="elf"  Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" />
</ItemGroup>
```

I see this here:
* https://github.com/dotnet/sdk/issues/14106
* https://github.com/mono/mono/issues/20250

Seems like a mono issue on Mac. Since Rider uses Mono still that explains

**Comment by jamescrosswell** [comment]
Hm, tricky. A quick search suggests this [might be related to MSBuild](https://stackoverflow.com/questions/47670576/invalid-static-method-invocation-syntax-msbuildisrunningfromvisualstudio).

These are my own MSBuild settings in Rider:
![Image](https://github.com/user-attachments/assets/3f1467dc-d903-4e5d-8c19-0a3a37018484)
 
Might be worth checking what version of MSBuild the customer is using. Ideally they can install .NET8.0 and then make sure that Rider is correctly configured to point to this.

**Comment by bruno-garcia** [comment]
Seems to be more of an issue if someone is on a very old version of .NET
