### ISSUE TITLE
Unable to search traces via OTel attributes

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3772]
Are we grabbing and adding OTel attributes adding them to our transaction/spans.

## Creating the `"otel"` context:
###.NET
https://github.com/getsentry/sentry-dotnet/blob/cbe1af4c722b22eb6ee0cbe5c70b25a8d7056d41/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs#L227C1-L228C1

### Python:
https://github.com/getsentry/sentry-python/blob/3e2885322a633398d62e8f1dae6315eefec35a34/sentry_sdk/integrations/opentelemetry/span_processor.py#L201-L203

### .NET
https://github.com/getsentry/sentry-dotnet/blob/cbe1af4c722b22eb6ee0cbe5c70b25a8d7056d41/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs#L422C6-L437C6

### Python
https://github.com/getsentry/sentry-python/blob/3e2885322a633398d62e8f1dae6315eefec35a34/sentry_sdk/integrations/opentelemetry/span_processor.py#L246C1-L260C19

But the traces don't seem to be seachable in the product based on the OTel attributes.

**Comment by jamescrosswell** [comment]
Initial reaction is that the SDKs are [doing what they should](https://develop.sentry.dev/sdk/telemetry/traces/opentelemetry/#step-5-add-opentelemetry-context) so the issue is more likely in sentry.io. 

@bitsandfoxes should this issue maybe go in the getsentry/sentry repository?

**Comment by bitsandfoxes** [comment]
This is getting handled by the product and has nothing to do with the SDK specifically.
