### ISSUE TITLE
Replacing current logger with: 'null'.

### ISSUE THREAD

**Issue by mikebollandajw** [getsentry/sentry-dotnet#383]
This is spamming all our logs, any idea how to disable it?

**Comment by bruno-garcia** [comment]
The issue template asks you to fill details such as what SDK you are using and which frameworks.
I'm not sure what "this is" means nor what type of logs you have.

Some hints:
* If you have enabled SDK debugging (it's disabled by default), make sure `SentryOption.Debug = false`
* You can remove the `DSN` to disable the SDK.
* Use the `SentryOptions.BeforeSend` to filter events by inspecting them
* Enable sample rate to reduce the overall number of events.

**Comment by nbarbettini** [comment]
@mikebollandajw It's emitted at startup/bootstrap time, see this code: https://github.com/getsentry/sentry-dotnet/blob/c3dc13efa6de90bf0d5a5248934c4efe07b02a0d/src/Sentry/SentryOptions.cs#L330-L345

This part helped answer the question for me:

> When debugging is turned off, this property is made null and any internal logging results in a no-op.

So it's just a message from the internal Sentry logger telling you that Sentry will not output internal debug messages.

@bruno-garcia To reduce confusion that message could be made more helpful, perhaps:

> Sentry will not emit debug messages because debug mode is off.

**Comment by bruno-garcia** [comment]
Agree @nbarbettini , would you be willing to open a PR? Thanks

**Comment by nbarbettini** [comment]
> Agree @nbarbettini , would you be willing to open a PR? Thanks

Sorry @bruno-garcia, I got busy and this got buried in my todo list. Thanks for fixing it!
