### ISSUE TITLE
Is Queries and Performance Monitoring supported on .NET Framework 4.7.2 and Entity Framework 6.4.0?

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/sentry-dotnet#3836]
I can't seem to get this to work, I thought it was automatically configured.

Using packages `Sentry`, `Sentry.AspNet`, `Sentry.DiagnosticSource`, and `Sentry.EntityFramework` v4.13.0

This is my Global.asax.cs file:

```
using System;
using System.Web.Http;

using Sentry;
using Sentry.AspNet;
using Sentry.Extensibility;

using Picsoft.Common;

namespace MyApp.API
{
    public class WebApiApplication : System.Web.HttpApplication
    {
        private IDisposable _sentry;

        protected void Application_Start()
        {
            // Initialize Sentry to capture AppDomain unhandled exceptions and more.
            _sentry = SentrySdk.Init(o =>
            {
                // DSN for CiraNet API Sentry project
                o.Dsn = ConfigurationHelper.SentryDsn;

                // Sets the release version in Sentry, for local developments this will default to 0.0.0.0
                o.Release = ConfigurationHelper.ReleaseVersion;

                // Sets the current environment in Sentry
                o.Environment = Platform.IsWebServer() ? ConfigurationHelper.Environment : "Local";

                // Automatically captures HTTP client errors, like bad response codes, as error events and reports them to Sentry
                o.CaptureFailedRequests = true;

                // Opt-in to send things like UserId and UserName if a user is logged-in
                o.SendDefaultPii = true;

                // Sample rate for your traced transactions: Captures 100% of transactions if not defined in appSettings
                o.TracesSampleRate = ConfigurationHelper.SentryTracesSampleRate;

                // If you also installed the Sentry.EntityFramework package
                o.AddEntityFramework();

                // RequestSize.Always sends the request body to Sentry
                o.AddAspNet(RequestSize.Always);
            });

            GlobalConfiguration.Configure(WebApiConfig.Register);
        }

        // Global error catcher
        protected void Application_Error()
        {
            Server.CaptureLastError();
        }

        protected void Application_BeginRequest()
        {
            Context.StartOrContinueTrace();
        }

        protected void Application_EndRequest()
        {
            Context.FinishSentryTransaction();
        }

        protected void Application_End()
        {
            // Flushes out events before shutting down.
            _sentry?.Dispose();
        }
    }
}
```

**Comment by jamescrosswell** [comment]
@edgariscoding what do you mean by "can't seem to get this to work"? What are you seeing vs what you're expecting to see?

**Comment by edgariscoding** [comment]
@jamescrosswell 

I guess I was expecting certain tabs in the Sentry dashboard to be populated with database queries and such, as can be seen on [this documentation](https://docs.sentry.io/product/insights/backend/queries/).

This is all I see though:

![Image](https://github.com/user-attachments/assets/15816dc6-d0e9-48f3-9fff-f82ccff68412)

![Image](https://github.com/user-attachments/assets/b26f725e-dc0b-48a7-810d-9d6a4c26c471)

**Comment by jamescrosswell** [comment]
Thanks @edgariscoding - Performance reporting is supported in .NET Framework - I don't think you'll get queries unless you get transactions so first step would be to work out why you're not seeing transactions come through in the performance dashboard. 

It looks like you're calling `StartOrContinueTrace`:

```csharp
        protected void Application_BeginRequest()
        {
            Context.StartOrContinueTrace();
        }
```

Can you try calling `StartSentryTransaction` there instead and see whether you start seeing transactions coming through to Sentry?

It looks to me like there might be an issue with the implementation of `StartOrContinueTrace` (this returns a transaction context but doesn't appear to use that context to start a new transaction)...

**Comment by jamescrosswell** [comment]
Hey @edgariscoding , just following up to confirm that you should be using `StartSentryTransaction` (not `StartOrContinueTrace`) if you want to see performance data and queries in Sentry. 

I've created another ticket to ensure the `StartOrContinueTrace` method is documented better (to make this clear). 

I assume this fixes the problem for you so I'll close this ticket for now. Feel free to open if you've still got issues though.

**Comment by edgariscoding** [comment]
Hey @jamescrosswell  sorry for the late response, I'll try using `StartSentryTransaction` and report back if it doesn't, thanks for your help!

**Comment by edgariscoding** [comment]
@jamescrosswell Just reporting back that this resolved all of my issues, I'm now getting all the performance and query data. Thanks again!

**Comment by edgariscoding** [comment]
@jamescrosswell, one more question. Transactions are now working properly and so performance and query data in being logged for this ASP.NET web api backend project.

We have a frontend and a backend and I would like to make sure that distributed tracing is configured for them. 

Looking at the Trace Propagation documentation page: 

https://docs.sentry.io/platforms/dotnet/guides/aspnet/tracing/trace-propagation/

It says to use `Context.StartOrContinueTrace();` for ASP.NET. But this causes transactions to stop working.

Do you know if I need to choose one or the other?

Looking at Sentry issues for the backend project, i don't see `sentry-trace` or `baggage` headers, which i assume means they're not being added by Sentry within my project.

![Image](https://github.com/user-attachments/assets/1d074cee-a0e1-4c93-9d30-40b9a8317e5b)

**Comment by jamescrosswell** [comment]
> Looking at the Trace Propagation documentation page:
> 
> https://docs.sentry.io/platforms/dotnet/guides/aspnet/tracing/trace-propagation/
> 
> It says to use `Context.StartOrContinueTrace();` for ASP.NET. But this causes transactions to stop working.
> 
> Do you know if I need to choose one or the other?

Hi @edgariscoding ,

I looks like the docs are a bit misleading. Basically you'd use `StartOrContinueTrace` method to ensure headers get propagated from upstream applications through to any downstream components in an application that was not instrumented for tracing. So if you had a front end, your ASP.NET Web API server and then a database, the front end could start traces, the database could add spans to those traces, but your Web API app wouldn't add any spans of it's own. 

If also want transactions/spans to be created by your Web API server though, you need to call `StartSentryTransaction`... When you do that, your Web API will create transactions/spans that will show in the full distributed trace.

I'll create another ticket to get the docs you referenced updated - thanks for pointing that out!
