### ISSUE TITLE
Deprecate and Remove User Segment

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-dotnet#3840]
### Description

As per https://github.com/getsentry/sentry/issues/58767#issuecomment-1808116241, user segment is deprecated from the user interface and the SDK.

Segment should be deprecated from the User struct to be removed in a future major version, and all user segment logic should be removed from dynamic sampling context functionality (see [DSC spec for more details](https://develop.sentry.dev/sdk/telemetry/traces/dynamic-sampling-context/#dsc-specification)).

Meta issue https://github.com/getsentry/team-sdks/issues/44

**Comment by jamescrosswell** [comment]
This was addressed already in https://github.com/getsentry/sentry-dotnet/pull/3563:
- https://github.com/getsentry/sentry-dotnet/pull/3563
