### ISSUE TITLE
Skip allocating new SdkVersion for every LogEvent

### ISSUE THREAD

**Issue by snakefoot** [getsentry/sentry-dotnet#386]
`SentryEvent` inherits from `BaseScope` that has the following property:

```c#
        [DataMember(Name = "sdk", EmitDefaultValue = false)]
        public SdkVersion Sdk { get; internal set; } = new SdkVersion();
```

And `SdkVersion` has this member:

```c#
        private readonly Lazy<ConcurrentBag<Package>> _lazyPackages =
            new Lazy<ConcurrentBag<Package>>(LazyThreadSafetyMode.PublicationOnly);
```

Forexample the NLog-target does this for every LogEvent:

```c#
                var evt = new SentryEvent(exception)
                {
                    Sdk =
                    {
                        Name = Constants.SdkName,
                        Version = NameAndVersion.Version
                    },
                }
                evt.Sdk.AddPackage(ProtocolPackageName, NameAndVersion.Version);
```

Instead of allocating a new `SdkVersion` and allocating a new `ConcurrentBag` for every LogEvent, then it could be nice if one of the following became true:
1. Hub could apply a default (reusable) `Sdk` (If the the logger haven't assigned one).
    - Initialize the `SentryOptions` with default Package-Version instead
2. The setter stopped being internal `public SdkVersion Sdk { get; set; }`
    - Allowing the caller to provide a reusable `SdkVersion`-object for all LogEvents.

Both options requires that the Sdk-getter becomes a little more lazy, so it allocates the  `SdkVersion` when requrested.

I can make a PullRequest if it is decided to go with one of the options (My favorite is option no. 1)

**Comment by bruno-garcia** [comment]
Well spotted @snakefoot, thanks!
Would be awesome to get a PR improving this.

**Comment by snakefoot** [comment]
Think I will abort this idea. the SentryEvent is very much about being clean and fresh and isolated.

Trying to guarantee that no one messes around with the Sdk-object make code ugly and fragile.

Also notice that capture of stacktrace from every SentryEvent (without Exception) is much more expensive, and one will never see the improvement of optimizing SdkVersion in a benchmark.

**Comment by bruno-garcia** [comment]
Yeah the type would need to become readonly. And agreed that couple of allocations is is def not a bottleneck here
