### ISSUE TITLE
Using UseSentry next to Ocelot api gateway is problematic

### ISSUE THREAD

**Issue by EngRajabi** [getsentry/sentry-dotnet#387]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ x] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [ x] .NET Core

* Version: 2.2

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ x] Sentry.AspNetCore

* Version: 2.1.1

Using UseSentry next to Ocelot api gateway is problematic.
If the method is post, request body will collapse

**Comment by bruno-garcia** [comment]
Seems related to this: https://github.com/getsentry/sentry-dotnet/issues/276

Are you using the `Sentry.AspNetCore` feature to capture request body? If so, did you configure the `Size`?

**Comment by EngRajabi** [comment]
yes, im use Sentry.AspNetCore. set MaxRequestBodySize  to Alwayes

**Comment by bruno-garcia** [comment]
It seems like Ocelot has an issue with request buffering. 
I suggest opening an issue with them and providing a repro (add a middleware that calls `request.EnableBuffering()`:

https://github.com/getsentry/sentry-dotnet/blob/598ab4fbdee2df3966c9bb00ae9d16b78e6bace9/src/Sentry.AspNetCore/SentryMiddleware.cs#L91

**Comment by bruno-garcia** [comment]
Another option is to disable request buffering:
leave `MaxRequestBodySize` as the default value which is `None`

**Comment by bruno-garcia** [comment]
The buffering code since then. Feel free to reopen if this is still an issue
