### ISSUE TITLE
How to know event has successfully captured?

### ISSUE THREAD

**Issue by mogikanin** [getsentry/sentry-dotnet#389]
Hello,
we are trying to switch to this new sentry client from raven-sharp, but it seems some functionallity is missing. In raven-sharp was possibility to know that event captured successfully or not. For that we used `RavenClient.Send()` which returns non-empty string on success.
Is there a way to know this with sentry-dotnet?
P.S.
This needed for ensuring all events will be captured (even if app restarts when e.g. was no internet connection). We cache all failed event to file, and re-send them on next app start.

**Comment by bruno-garcia** [comment]
Short answer is that event delivery is best effort. Sentry's `Capture` methods return the event id if it was possible to queue the event for submission. If it was sampled out, rejected by a callback or event processor, it would return an empty GUID instead. The event is queued and flushed to Sentry in the background so there's no guarantee it'll actually make it to Sentry.
Neither SharpRaven (so you had to build your own) or Sentry have offline caching at the moment. It's been requested (#80) and we plan to prioritize this and have it built-in.

**Comment by mogikanin** [comment]
Thanks, it would be nice to see this feature in nearest future. Event\callback is best approach, yes.
For SharpRaven we used custom inheritor (just making protected Send() public), and it did job well.

 ```
private class RavenClientEx : RavenClient
        {
            private static readonly JsonPacketFactory _jsonPacketFactory = new JsonPacketFactory();

            public RavenClientEx(string dsn)
                : base(dsn, _jsonPacketFactory)
            {

            }

            public JsonPacket CreatePacket([NotNull] SentryEvent @event)
            {
                if (@event == null) throw new ArgumentNullException(nameof(@event));
                return _jsonPacketFactory.Create(CurrentDsn.ProjectID, @event);
            }

            public string SendPacket([NotNull] JsonPacket packet)
            {
                if (packet == null) throw new ArgumentNullException(nameof(packet));
                return Send(packet);
            }
        }
```

**Comment by mogikanin** [comment]
@bruno-garcia please take a look into my commit here
https://github.com/mogikanin/sentry-dotnet/commit/bd63e01394b7dab31f998632e068ce49aeca29a0

If these changes are fine for you, it would be nice to have it inside official repo.

**Comment by bruno-garcia** [comment]
@mogikanin Unfortunately we won't be able to merge that at the time. Event though it would technically work right now for the .NET SDK, we're making changes to the transport which adding this callback would be in the way of. We've created something called `Envelope` that allows sending different types of payloads, it's just that this didn't land in this SDK yet, but will hopefully soon.

If you need such a callback, I suggest maintaining a fork or implementing your own transport.

**Comment by kanadaj** [comment]
@bruno-garcia Couldn't he technically make a custom ISentryHttpClientFactory and use the HttpClient to track events being sent?

**Comment by mogikanin** [comment]
It would be nice if you provide a method inside SentryClient (or somewhere else) to send events directly, without adding them into your internal background worker. Or use my trivial approach with callback which is just several lines of code, or at least provide a factory for ITransport inside SentryOptions so I can override it. I believe this is needful thing and doesn't require much coding, but still (from 2018-2019) not done.

**Comment by bruno-garcia** [comment]
@mogikanin if you need to "block" while an event is flushed out, you can use `SentrySdk.FlushAsync`. 

@kanadaj that's true, they can always hook through `ISentryHttpClientFactory` if needed.

**Comment by CADbloke** [comment]
You could implement the diagnostic logger, it logs when an event has been successfully received, queue depth etc. . See https://github.com/getsentry/sentry-dotnet/issues/185#issuecomment-486726027

Here's a sample of the output from my Serilog file for the Diagnostic logger ...

```
[v1.1.2901.20181] 13:05:51.062 -   Debug: Initializing Hub for Dsn: 'https://<redacted>@sentry.io/<redacted>'. 
[v1.1.2901.20181] 13:05:51.086 -   Debug: Using 'GzipBufferedRequestBodyHandler' body compression strategy with level Optimal. 
[v1.1.2901.20181] 13:05:51.094 -   Debug: Registering integration: 'AppDomainUnhandledExceptionIntegration'. 
[v1.1.2901.20181] 13:05:51.099 -   Debug: Registering integration: 'AppDomainProcessExitIntegration'. 
[v1.1.2901.20181] 13:05:51.108 -   Debug: New scope pushed. 
[v1.1.2901.20181] 13:05:54.572 -    Info: Capturing event. 
[v1.1.2901.20181] 13:05:54.589 -   Debug: Running main event processor on: Event 9a85161fb80842859474e652cd367b84 
[v1.1.2901.20181] 13:05:54.607 -   Debug: Creating SentryStackTrace. isCurrentStackTrace: True. 
[v1.1.2901.20181] 13:05:54.629 -   Debug: Event queued up. 
[v1.1.2901.20181] 13:05:54.722 -   Debug: Event <redacted> in-flight to Sentry. #1 in queue. 
[v1.1.2901.20181] 13:05:55.690 -   Debug: Event <redacted> successfully received by Sentry. 
[v1.1.2901.20181] 13:07:42.863 -    Info: Disposing the Hub. 
[v1.1.2901.20181] 13:07:42.869 -   Debug: Disposing SentryClient. 
[v1.1.2901.20181] 13:07:42.873 -   Debug: Disposing BackgroundWorker. 
[v1.1.2901.20181] 13:07:42.878 -   Debug: Shutdown scheduled. Stopping by: 00:00:02. #0 in queue. 
[v1.1.2901.20181] 13:07:42.882 -    Info: Exiting the worker with an empty queue. 
[v1.1.2901.20181] 13:07:42.887 -   Debug: Disposing scope. 
[v1.1.2901.20181] 13:07:42.891 -   Debug: Disposing SentryScopeManager. 
```
