### ISSUE TITLE
Request is not available in this Context

### ISSUE THREAD

**Issue by ocdi** [getsentry/sentry-dotnet#397]
Please mark the type framework used:

- [X] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

Please mark the NuGet packages used:

- [X] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.1

During application startup, an Exception might occur. In this case we are logging a failed database migration that occurs in Application_Start.

This appears to be captured in Sentry, however when the event processor runs, it doesn't handle the fact Request might not actually be available. Looking at the code, there is a try/catch around the QueryString, I imagine this should be extended to accessing Request also. These are some output logs from our application:

```
iisexpress.exe Information: 0 : New scope pushed.
iisexpress.exe Information: 0 : Capturing event.
iisexpress.exe Information: 0 : Running processor on exception: Initialisation Migration Result
iisexpress.exe Information: 0 : Creating SentryStackTrace. isCurrentStackTrace: False.
iisexpress.exe Information: 0 : No stack frames found. AttachStacktrace: 'False', isCurrentStackTrace: 'False'
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/3/ROOT-1-132332893632116671): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
iisexpress.exe Information: 0 : Running main event processor on: Event e6d265602cda437d9c26d10a5ed524c1
iisexpress.exe Information: 0 : An error occured when capturing the event System.Web.HttpException (0x80004005): Request is not available in this context
   at System.Web.HttpContext.get_Request()
   at Sentry.Internal.Web.SystemWebRequestEventProcessor.Process(SentryEvent event)
   at Sentry.SentryClient.DoSendEvent(SentryEvent event, Scope scope)
   at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope).
iisexpress.exe Information: 0 : Disposing scope.
Exception thrown: 'System.Data.SqlClient.SqlException' in Microsoft.EntityFrameworkCore.dll
```

**Comment by bruno-garcia** [comment]
Available on: https://github.com/getsentry/sentry-dotnet/releases/tag/2.1.2-beta2
