### ISSUE TITLE
When sourcelink data is available send with event

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#400]
There's a draft PR: #230

This post from Microsoft could be referred from our docs to suggest users to bundle pdbs in the assemblies. Also to suggest embedding sources, and read the source.

https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/

In Sentry it could link to the source code repository/commit.

Server-side could also fetch the actual source and render SourceContext.

**Comment by bruno-garcia** [comment]
Related #230

**Comment by Lonli-Lokli** [comment]
Any update?

**Comment by bruno-garcia** [comment]
@Lonli-Lokli none yet. Also, we'd need to change the server to fetch the source code.

**Comment by bruno-garcia** [comment]
There was a initial work on this that didn't get completed but we'd love to see this feature land: https://github.com/getsentry/sentry-dotnet/pull/230

**Comment by SimonCropp** [comment]
we will close this one since the larger issue https://github.com/getsentry/sentry-dotnet/issues/1740 tracks this
