### ISSUE TITLE
AddLogEntryFilter not triggering for Breadcrumbs

### ISSUE THREAD

**Issue by johnhamm** [getsentry/sentry-dotnet#436]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x ] .NET Core

* Version: 3.1

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x ] Sentry.AspNetCore

* Version: 2.1.1

I am trying to filter out repeated warnings from XmlKeyManager from being sent to Sentry from our asp.net core application by adding options.AddLogEntryFilter but it doesn't seem to be working.  The warning are still sent to Sentry:

```
options.AddLogEntryFilter((category, level, eventId, exception) =>
                       { // I set a breakpoint on next line but it doesn't trigger nor does the Console.WriteLine
                           Console.WriteLine($"Category: {category}, Level: {level}, Event ID: {eventId}, Exception: {exception}");
                           var result = category == "Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager" && level == LogLevel.Warning && (eventId == 50 || eventId == 59 || eventId == 35);
                           return result;
                       });
```

**Comment by bruno-garcia** [comment]
The filter doc suggested it would drop both Events and Breadcrumbs but the code only dropped events.

I've changed it in #440 to also avoid adding a breadcrumb. Ideally we'd have a `Enum` indicating what's about to be added so that the callback could drop breadcrumbs but not events or vice-versa but to avoid a breaking change, we'll just drop breadcrumbs now too.

**Comment by bruno-garcia** [comment]
Please try out 2.1.3 for the fix: https://github.com/getsentry/sentry-dotnet/releases/tag/2.1.3
