### ISSUE TITLE
LogError not receiving in sentry 

### ISSUE THREAD

**Issue by dharmeshsharma** [getsentry/sentry-dotnet#444]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x ] .NET Core

* Version: 3.1

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x ] Sentry.AspNetCore

* Version:

simply updated own sentry configuration in "**Sentry.Samples.AspNetCore3.Mvc**" both file in **appsetting.json , Program.cs** and run Sentry.Samples.AspNetCore3.Mvc but  `  _logger.LogError("Index was called.");`  not sending or not able to receive but in same sentry configuration working fine in "**Sentry.Samples.AspNetCore.Mvc**"  sample with .net core 2.1.

**Comment by bruno-garcia** [comment]
That's an issue with the sample.

The SDK doesn't send events from types in the namespace `Sentry.` to avoid a infinite loop:

https://github.com/getsentry/sentry-dotnet/blob/54a6436be35917bc762cc7027e287ebd467a6a81/src/Sentry.Extensions.Logging/SentryLogger.cs#L130-L131
