### ISSUE TITLE
Setting the environment

### ISSUE THREAD

**Issue by xt0rted** [getsentry/sentry-dotnet#45]
I'm trying to setup the `ILogger` implementation in my project and I want to set the environment like I'm doing with the javascript client. On the `SentryOptions` class there's `Dsn` and `Release` properties but I'm not seeing anything for the `Environment`. How would this be set on the logger, or is it not implemented yet?

**Comment by xt0rted** [comment]
After looking at this more I figured out that the `Environment` could be set using `BeforeSend` like so:

```c#
loggerFactory.AddSentry(c =>
{
    c.Init(o =>
    {
        o.BeforeSend = sentryEvent =>
        {
            sentryEvent.Environment = environment;
            sentryEvent.Release = ApplicationInformation.Version;

            return sentryEvent;
        };
        o.Dsn = new Sentry.Dsn(dsn);
    });
});
```

(I'm setting `Release` like this because the current version on NuGet doesn't have it on `SentryOptions` yet)

**Comment by bruno-garcia** [comment]
The new release (preview3) will automatically get the version from AssemblyInformationalVersion if you are using that. 
If not, it'll use AssemblyVersion.

Of course, if that doesn't work for you, you can set it via the `SentryOptions` (as you said, in preview3) or also via `BeforeSend`.

**Comment by xt0rted** [comment]
Just tested preview3 and couldn't figure out why my version wasn't being set, then I found https://github.com/getsentry/sentry-dotnet/blob/dbb5a3af054d0ca6f801de37fb7db3632ca2c65a/src/Sentry/Internal/ApplicationVersionLocator.cs#L14-L21

Since my versions default to `1.0.0` this wasn't being set. If this functionality stays it'd probably be good to mention it in the docs.

**Comment by bruno-garcia** [comment]
Yeah! Good point. 
I figured that 1.0.0 would be useless, since basically it means it's not being set.

You are right this should be documented. Now [we have some docs](https://getsentry.github.io/sentry-dotnet/), I can document that ;)

**Comment by bruno-garcia** [comment]
@xt0rted would you please review?
https://github.com/getsentry/sentry-dotnet/pull/48

**Comment by xt0rted** [comment]
The docs update looks good.

My only issue with filtering out values is someone really could use `1.0.0` which would require an extra setup step. It's probably a really low number that do though with most being non-production versions where it doesn't really matter.

**Comment by bruno-garcia** [comment]
yeah it would really only affect someone who's using sentry with version 1.0.0-beta and then releases 1.0.0 as their final version. 
Usually people already have version being 1.0.0.

Not reporting seemed like a better approach than reporting the (most likely) wrong version which would enable the release feature at sentry but all the application versions would always be under the same release.

Worst case for that one (likely rare) case of being on version 1.0.0, one would need to set the version via Options manually.
