### ISSUE TITLE
Strong naming error with version 0.0.1-preview2

### ISSUE THREAD

**Issue by xt0rted** [getsentry/sentry-dotnet#46]
I have an MVC5 site and some Azure WebJobs (plain .net 4.7.1 console apps) that are all using `Microsoft.Extensions.Logging` so I wanted to give the `ILogger` implementation a try. The WebJobs are running fine and exceptions are being logged as expected, but with the website I'm getting the following error when the site starts up:

>Could not load file or assembly 'Sentry.PlatformAbstractions' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

I'm not sure if it matters but the WebJobs are using the new SDK style project files while the website is the old style.

- **Sentry**: 0.0.1-preview2
- **Sentry.Extensions.Logging**: 0.0.1-preview2
- **Sentry.PlatformAbstractions**: 1.0.0-dev-00070
- **System.Collections.Immutable**: 1.5.0

**Comment by bruno-garcia** [comment]
Strong naming is done but not published.
I'll publish the preview3 today and all assemblies will be strong named.

**Comment by bruno-garcia** [comment]
Hi @xt0rted,
So I was actually only publicSigning the assemblies. The error you received from PlatformAbstractions would also affect the packages coming from this repo.

It's solved now. I've verified the signature and it's working propertly.

Thanks a lot for letting me know of this issue!

**Comment by bruno-garcia** [comment]
Preview3 release: https://github.com/getsentry/sentry-dotnet/releases/tag/0.0.1-preview3

Thanks again for reporting the error!

**Comment by xt0rted** [comment]
Just tested it out and it's working.

I'm really liking where this new library is going, it's super easy to use if you're already using `ILogger` in your project. I'm able to remove my custom exception logger now and it works great with Azure WebJobs (v2 added support for `ILogger` at some point so this just drops in and gives unhandled exception logging without any custom code).

**Comment by bruno-garcia** [comment]
You just made my day! :)
Once again thanks for reporting the bug. If you have any issues or ideas on how things can be better, please let us know ;)
