### ISSUE TITLE
SentrySdk.ConfigureScope doesn't configure events sent by Serilog + Sentry

### ISSUE THREAD

**Issue by CADbloke** [getsentry/sentry-dotnet#468]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [X] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

Please mark the NuGet packages used:

- [X] Sentry
- [X] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:  2.1.4

````csharp
           SentrySdk.ConfigureScope(scope => { scope.User.Email = authenticatedLicense?.UserEmailAddress ?? "TRIAL"; 
                                                scope.User.Username = Environment.UserName;
#if OpenDesign
                                                scope.SetTag("CAD", "OpenDesign");
#else
                                                scope.SetTag("CAD", "Autodesk");
#endif
            }); 

#if DEBUG
            SentrySdk.CaptureMessage($"Sentry test for {AssemblyName}"); 
#endif
````

Sentry sends the data in the scope when I use `SentrySdk.CaptureMessage` but it doesn't send it when Serilog sends and event. How do I add tags to Serilog + Sentry ?

**Comment by bruno-garcia** [comment]
Unless you've pushed a scope, it should include the Scope data through Serilog too.
Is there a `SentrySdk.PushScope` anywhere? Or if you're using `ILogger`: `logger.BeginScope`?
`ConfigureScope` configures the current scope. If you push a scope, it clones the current one, so data you've set on the parent, are available in its children. But now if you `ConfigureScope` on the child scope, it does not affect the parent.

If it's unrelated to a new scope, would you please create a small repro?

**Comment by CADbloke** [comment]
Nope, the only mention of "Scope" in the whole solution is in the code above. That code is part of an internal instance method in the `App` class that is only called once. Does the "scope" configured only last the lifetime of that method? The only logger for Sentry is a static `Serilog iLogger` property of `App` that the whole application uses. 

I'm probably misusing this (surprise!) - all I want to do is set a tag in the payloads sent to Sentry to identify which CAD SDK is is using. The SDKs are (mostly) interchangeable, I have build versions for both at the moment. I wanted to set it with the user email address because the email is parsed when the app reads their license, after the logging has started.

Here is the Serilog config which is in a different method and precedes the call to `ConfigureScope()` above.

````c#
.WriteTo.Sentry(s =>
  {
#if DEBUG
      s.Debug = true;
      s.DiagnosticLogger = new SentryDiagnosticLogger(SentryLevel.Debug); // Serilog that writes to a file
#endif
      s.MinimumBreadcrumbLevel = LogEventLevel.Verbose; // stored as breadcrumbs (default os Information)
      s.MinimumEventLevel = LogEventLevel.Error;   // Error and higher is sent as event (default is Error)
      s.Dsn = new Dsn(sentryDSN);
      s.AttachStacktrace = true;
      s.SendDefaultPii = true; // send PII like the username of the user logged in to the device
      // Other configuration
      s.IsEnvironmentUser = true;
      s.Environment = AppUser;
      s.Release = AppFileVersion;
      s.AddEntityFramework();
  }
````

**Comment by bruno-garcia** [comment]
Looks like the scope you're configuring is not the same that the Serilog logger is reading from. Not sure where/how they fork but since it's `AsyncLocal` it's possible.

Sounds like you need a "Global Hub" mode, which is common on single-user apps like desktop/mobile as opposed to servers (where each request has an isolated Hub/Scope). #448 is trying to address that. 

I suggest as a work around to register a `IEventProcessor` or some code in the `options.BeforeSend` callback during init, that will add the correct tag to outgoing events. In a way where you can provide that code the correct tag after the fact (once you figure out the SDK version/e-mail) as you described.
Once the global hub approach lands, you should be able to simple set the _globalHub=true_ option to make sure that any `ConfigureScope` call affects the whole app.

**Comment by CADbloke** [comment]
Thanks Bruno. I'll hold out for the Global Hub option, that seems like the most sensible approach. It's not a deal-breaker.
