### ISSUE TITLE
How is the 'values' object created inside the exception and how do I access it?

### ISSUE THREAD

**Issue by nathanjwtx** [getsentry/sentry-dotnet#469]
Please mark the type framework used:

- [X] ASP.NET MVC

Please mark the type of the runtime used:

- [X] .NET Framework

* Version:
4.6.2

Please mark the NuGet packages used:

- [X] Sentry
* Version:
2.1.1

In the JSON output from the Sentry console I can see that there is a `exception` object, presumably the one passed into the event, and it has a values property which is an array. As there isn't a `values` property on the .NET exception object, how is this created and how do I access it? This seems to be the place to obtain the exception type.

In case I am heading in the wrong direction with this, I am attempting to filter out a specific error type.

![image](https://user-images.githubusercontent.com/1558027/86269503-73753500-bb8f-11ea-87bf-c056c7c1c96f.png)

**Comment by bruno-garcia** [comment]
That's the serialized version of the event. It doesn't map 1 to 1 with the public C# API.
What exactly are you trying to acomplish? It'll make it easier to help you out if you describe your goal

**Comment by nathanjwtx** [comment]
I'm trying to filter out a specific type of sql error but I don't want to do it by type as that would remove all exceptions so i was trying to read the message contained in value.

**Comment by lucas-zimerman** [comment]
In BeforeSend, check if the event has the desired type, if true, return null, else the event.
Or instead of checking by type you could use some Linq like 
`SentryEvent().SentryExceptions.Any(p => p.Value == "X");`

**Comment by nathanjwtx** [comment]
@lucas-zimerman i'll give that a go. from memory though, a sql deadlock exception just throws a generic sql error.

**Comment by bruno-garcia** [comment]
`SqlException` has a `ErrorCode` field so you can match against that too

**Comment by nathanjwtx** [comment]
does that error code come back in the alert to Sentry as part of the api?

**Comment by bruno-garcia** [comment]
The SDK has no special case for `SqlException` but sends all data from `Exception.Data`. 

> I can see it in the additional data section on the Sentry UI

So you confirm it's there?

I meant you can take advantage of that and filter things out like:

```csharp
BeforeSend = e => {
if (e.Exception is SqlException ex && ex.Number == 1205) {
   return null; //drop
}
return e;
}
```

**Comment by nathanjwtx** [comment]
Ah, we were inspecting `SentryException`  rather `Exception`. What is the difference? I don't see `SentryException` in the API documentation.

**Comment by nathanjwtx** [comment]
I tried this with a more easily generated sql exception and it worked. Searching for the specific error code should be a more robust way of checking. Thanks for your help :)

**Comment by bruno-garcia** [comment]
SentryException is documented here: https://getsentry.github.io/sentry-dotnet/api/Sentry.Protocol.SentryException.html

Glad it worked out! No problem at all.
