### ISSUE TITLE
Module initializer to trigger SentrySdk.Init

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#470]
Consider the [new C# Module initializer](https://github.com/dotnet/csharplang/issues/2608) to init the SDK.

It would also be interesting to capture errors like [when reflection is used.](https://github.com/dotnet/csharplang/issues/2608#issuecomment-611391903)

**Comment by bddckr** [comment]
Would this be optional? I assume so, but I'm curious how that would work. Perhaps another NuGet package that takes over this single responsibility, to allow users to decide whether this is what they want?

**Comment by bruno-garcia** [comment]
It's definitely up for discussion. One option is to try to Init looking for a dsn via env var. If it's available it uses it. A follow up user defined I it would override things but at least a bootstrapping crash would be captured

**Comment by SimonCropp** [comment]
@bruno-garcia @mattjohnsonpint IMO this is too much magic. i would prefer we dont implement this

**Comment by bruno-garcia** [comment]
Does this run before or after `Main`? We'd need an opt-out then, so users can init by themselves and pass options properly.
Yeah probably too much magic. But also we wouldn't capture crashes if a module initializer crashed before `Main` ran and Sentry was initialized

**Comment by bruno-garcia** [comment]
Decided not to do this as there are to many reasons why this would be hard to maintain and make sense of
