### ISSUE TITLE
Office VSTO Plugin not emitting any events

### ISSUE THREAD

**Issue by Herz3h** [getsentry/sentry-dotnet#472]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [x] Other:

Please mark the type of the runtime used:

- [x] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.6.1

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.4

When I run application in debug or release mode in vs studio, i  receive all the events  (either from CaptureException or CaptureMessage).

But when I run the app once it's deployed using ClickOnce, same code doesn't emit any event. I have checked with fiddler and nothing is happening on the network.

Tried different codes, from doing this everywhere:

```csharp
using (Sentry.Init('mydsnhere'))
{
Sentry.CaptureMessage('Startup');
}
```

To simply initializing this one in the startup method:

```csharp
Sentry.Init('mydsnhere'))
Sentry.CaptureMessage('Startup');
```

And everywhere else calling simply:

```csharp
Sentry.CaptureMessage('Othermethod');
```

Nothing of them work once deployed...

**Comment by bruno-garcia** [comment]
I'm not familiar with VSTO Plugins work.
What's the runtime there? What type of environment does it run, does it have access to the Internet to send the events to Sentry?
Does it need a proxy in order to do so?

**Comment by Herz3h** [comment]
It runs withing a microsoft office application. In this case Outlook. It has access to internet, and every c# feature since it required .net framework being installed. No proxy needed. Also the addin communicate with a remote API without any problem, so no internet issue. 

It works in dev/release mode when executed from visual studio. But once a clickonce setup installer is generated, and the plugin installed from there, no event is ever captured somehow.

**Comment by bruno-garcia** [comment]
Is there a way to see the logs?
You can initialize the SDK with `SentrySdk.Init(o => o.Debug = true)` and it'll print out all its inner workings.

if there's no "console" that you can look at the output, you can create a logger that logs to a file for example, and pass that like `options.DiagnosticLogger = new MyLogger();`, since it's just for testing, you can just write `File.AppendLine` or something simple.

**Comment by Herz3h** [comment]
Uhm thank you for your help attempt. Unfortunately didn't have time to test. So this week, I just removed Raven as it was installed along with Sentry, and updated Sentry. Now it's working fine 👍

**Comment by bruno-garcia** [comment]
Awesome! Happy it works with Office VSTO. Thanks for the update
