### ISSUE TITLE
`UseSentry` not working for ASP.NET

### ISSUE THREAD

**Issue by hanselsen** [getsentry/sentry-dotnet#487]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core

* Version: 3.1.7

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x] Sentry.AspNetCore

* Version: 2.1.5

I used the code snippet from the instructions in the dashboard, but it does not seem to work.  
However, the "regular" way with the `using` statement does work.

```
    //This one DOES work
    public class Program
    {
        public static void Main(string[] args)
        {
            using (SentrySdk.Init("[copied-sdk]"))
            {
                throw new Exception("This one works");
            }
            CreateHostBuilder(args).Build().Run();
        }
       
        {...}
    }
```

```
    // Does NOT work
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                    .UseSentry("[copied-dns]")
                    .UseStartup<Startup>();
                });
    }
```
With in my controller:

```
...
throw new Exception("This one does not work");
...
```

How can I fix this?

**Comment by bruno-garcia** [comment]
Can you please set `Debug=true` and paste the debug output?

```
                    .UseSentry(o => o.Dsn = "[copied-dns]"; o.Debug=true);
```
It should show up on your console or anywhere else you have your aspnet core logs going to.

**Comment by hanselsen** [comment]
Ah yes. Thank you.
It seems that a **Converter** I had caused some trouble writing a `DateTimeOffset` object to JSON.
It works now thanks!
