### ISSUE TITLE
Override or Hook into User detection

### ISSUE THREAD

**Issue by Seeker1437** [getsentry/sentry-dotnet#497]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [X] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [X] .NET Core

* Version:

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [X] Sentry.AspNetCore

* Version: 2.0.0-beta6

Is there a way to override the user information? I don't use Identity, there is a custom solution in place for handling the User information.,... is there a way to hook into sentry to have it get that information?

I am not sure of BeforeSend is a good place because I don't actually appear to get access tot he information i would normally use (HttpContext) and pull it myself unless maybe I did something wrong.

**Comment by bruno-garcia** [comment]
You can implement your own `IUserFactory` and register in the DI container.

https://github.com/getsentry/sentry-dotnet/blob/3c3d19d0a84e2c4ba4535968bcfc764227b1b0d7/src/Sentry.AspNetCore/IUserFactory.cs

The SDK tries to resolve one from there before doing its own stuff:

https://github.com/getsentry/sentry-dotnet/blob/454aa6aadc7b2979d78ca1416eb732dbdf8750f3/src/Sentry.AspNetCore/ScopeExtensions.cs#L38

**Comment by Seeker1437** [comment]
Hey guys, having a slight issue. At this point I am not able to access sessions yet whoch males it so that aquiring user info is more difficult. Do you have a trick you uae to see user stuff or is it usually separate from sessions (like with built Identity).

**Comment by bruno-garcia** [comment]
I'll close this since this issue is resolved. If there's another issue please raise a new one and follow the issue template so we can help you out.
