### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#498]
This will likely become multiple issues but for now to communicate the long term goal:

Vision: Have 0 dependencies.

This will improve the experience using Sentry with game engines, mobile. Avoid binding redirect issues with .NET Framework, and generally improve things.

- [x] Move code from Sentry.Protocol to namespace Sentry.Protocol in Sentry. Archive package on NuGet. Move SentryLevel to Sentry namespace
- [x] Move code from Sentry.PlatformAbstractions to Sentry (drop anything below ns2.0 and net461). Archive repo and project. First attempt is here: https://github.com/getsentry/sentry-dotnet/pull/264

~- [ ] Attempt to use System.Json (since it's not a dependency on netcore3.0+) See: https://github.com/getsentry/sentry-dotnet-protocol/pull/42 https://github.com/dotnet/runtime/issues/29975 (maybe .NET 5 [introduces a easy way into it](https://github.com/dotnet/runtime/issues/41313)) (Seems we'll be blocked by the lack of `JsonExtensionData`)~

- [x] Remove System.Web reference from the netfx target. To work on Mono builds on Android (i.e https://gatomalo.dev/blog/2020/03/21/error-monitoring-godot-sentry/ ) Alternative is creating `Sentry.AspNet` which will bring this dependency.

```
RROR: get_assembly_dependencies: Cannot load assembly (refonly): 'System.Web'.
   At: modules/mono/editor/godotsharp_export.cpp:93.
ERROR: get_assembly_dependencies: Cannot load one of the dependencies for the assembly: 'Sentry'.
   At: modules/mono/editor/godotsharp_export.cpp:98.
```

- [x] Docs for ASP.NET needs to be updated: https://docs.sentry.io/platforms/dotnet/guides/aspnet/

**Comment by Tyrrrz** [comment]
@bruno-garcia seems like only the last point is left on the ticket.
Looking at https://docs.sentry.io/platforms/dotnet/guides/aspnet/, the only change seems to be the initialization (i.e. `SentrySdk.Init(o => o.AddAspNet())`), correct?
Also, how should we sync docs with the release cycle? Seeing as this change won't be in until the next major version.

**Comment by bruno-garcia** [comment]
Good point. Maybe just leave a draft ready to be merged there? On the docs

**Comment by bruno-garcia** [comment]
Or we could merge now the following:

```
Note: Version 3.0.0
We're in the processes of relasing a new package, Sentry.AspNet version 3.0.

A major difference there is which package to install and how to intitalize.

Try our latest preview package and give us feedback
```

Then we can merge it already and at the end just kind of move the text above and delete the note about being preview?

**Comment by Tyrrrz** [comment]
Draft PR sounds better I think.
Can you point me to the docs repo again?

**Comment by bruno-garcia** [comment]
Sure: https://github.com/getsentry/sentry-docs/edit/master/src/platforms/dotnet/guides/aspnet/index.mdx

Tip: There's an _edit this page_ link at the footer:
![image](https://user-images.githubusercontent.com/1633368/94466007-c199d480-018e-11eb-9c82-826ebeee8fe7.png)

**Comment by Tyrrrz** [comment]
Created it here: https://github.com/getsentry/sentry-docs/pull/2383
