### ISSUE TITLE
SentrySDK not sending/Backend not receving event

### ISSUE THREAD

**Issue by fengyuan213** [getsentry/sentry-dotnet#506]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [1 ] WPF
- [ ] WinForms
- [ ] Xamarin
- [1 ] Other: Console

Please mark the type of the runtime used:

- [ 1] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.7.2

Please mark the NuGet packages used:

- [1 ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.6

For some reason, I was developing my WPF as normal, then somehow I found that the sentry is not sending the error event to the backend anymore. I have no idea what is actually going on. To avoid a problem with my myth project, I created a new Console Project(.Net 4.7.2), Installing the default package with settings below. I tried several times and capture exception in several ways. No idea what's going on. [Firewall is OFF]

    class Program
    {
        static void Main(string[] args)
        {
            using (SentrySdk.Init("http://8c03d576f6104cc8b78c7a024088fada@o402191.ingest.sentry.io/5427284"))
            {
                //throw new Exception("Sentry");
                //SentrySdk.CaptureMessage("Test", SentryLevel.Fatal);
                //SentryClient.CaptureEvent(new SentryEvent(babababab))
                var a = 0;
                Console.WriteLine(1 /a);
                
            }
        }

**Comment by bruno-garcia** [comment]
WPF requires some config

Did you check: https://docs.sentry.io/platforms/dotnet/guides/wpf/

Let us know if it helps

**Comment by fengyuan213** [comment]
Nopes, It doesn't help, I already configured the SDK in WPF. Any suggestion? please help

**Comment by fengyuan213** [comment]
I have an update, I tried to use fiddler to capture the connection of sentry.
The  dsn  first refers to https://vortex.data.microsoft.com/collect/v1 to post data.
The data collected in the request with Http 200 Response code.
I think it is probably a similar issue with #518

**Comment by bruno-garcia** [comment]
>  The dsn first refers to vortex.data.microsoft.com/collect/v1 to post data.

I don't understand what this means. Sentry's SDK doesn't have any connection to that endpoint.

To further troubleshoot initialize the SDK in debug mode so you can see what it's doing `o.Debug = true;`

```
    static void Main(string[] args)
    {
        using (SentrySdk.Init(o => {
o.Dsn = new Dsn("http://8c03d576f6104cc8b78c7a024088fada@o402191.ingest.sentry.io/5427284");
o.Debug = true;
}))
        {
            throw null;            
        }
    }
```

Since WPF doesn't have a console you could see the printing out, try to swap out the Diagnostic logger with something like:

```csharp

using System;
using System.Globalization;
using System.IO;
using Sentry.Extensibility;
using Sentry.Protocol;

public class FileAppenderDiagnosticLogger : IDiagnosticLogger
{
    private readonly SentryLevel _minimalLevel;
    private readonly StreamWriter _writer;

    public FileAppenderDiagnosticLogger(SentryLevel minimalLevel)
    {
        _minimalLevel = minimalLevel;
        var fileName = Guid.NewGuid().ToString("n") + ".txt";
        _writer = new StreamWriter(fileName);
    }

    public bool IsEnabled(SentryLevel level) => level >= _minimalLevel;

    public void Log(SentryLevel logLevel, string message, Exception exception = null, params object[] args)
    {
        lock (_writer)
        {
            _writer.Write("{0} - {1}: ",DateTimeOffset.UtcNow.ToString("yyyy-MM-ddTHH\\:mm\\:ss.ffffZ", DateTimeFormatInfo.InvariantInfo), logLevel);
            _writer.Write("");
            _writer.Write(message, args);
            if (exception is Exception)
            {
                _writer.Write("Exception: ");
                _writer.Write(exception);
            }
            _writer.WriteLine();
            _writer.Flush();
        }
    }
}
```

**Comment by fengyuan213** [comment]
Debug: Logging enabled with ConsoleDiagnosticLogger and min level: Debug
  Debug: Using 'GzipBufferedRequestBodyHandler' body compression strategy with level Optimal.
  Debug: Registering integration: 'AppDomainUnhandledExceptionIntegration'.
  Debug: Registering integration: 'AppDomainProcessExitIntegration'.
  Debug: New scope pushed.

That's the debug output, sorry for the previous post that I said refers. Actually,  The program doesn't seem to send any data to the server. Please help

**Comment by fengyuan213** [comment]
This log uses SentrySdk.CaptureMessage to collect data:
  Debug: Logging enabled with ConsoleDiagnosticLogger and min level: Debug
  Debug: Using 'GzipBufferedRequestBodyHandler' body compression strategy with level Optimal.
  Debug: Registering integration: 'AppDomainUnhandledExceptionIntegration'.
  Debug: Registering integration: 'AppDomainProcessExitIntegration'.
  Debug: New scope pushed.
   Info: Capturing event.
  Debug: Running main event processor on: Event 6149500869d14d679234642c02cd998b
  Debug: No Exception and AttachStacktrace is off. No stack trace will be collected.
  Debug: Event queued up.
   Info: Capturing event.
  Debug: Running processor on exception: Exception of type 'System.Exception' was thrown.
  Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
  Debug: No stack frames found. AttachStacktrace: 'False', isCurrentStackTrace: 'False'
  Debug: Running main event processor on: Event a29032dabbd44b338bce7fa47712cdbf
  Debug: Event queued up.
  Debug: Tracking depth: 2.
  Debug: Timeout when trying to flush queue.
   Info: Disposing the Hub.
  Debug: Disposing SentryClient.
  Debug: Disposing BackgroundWorker.
  Debug: Event 6149500869d14d679234642c02cd998b in-flight to Sentry. #2 in queue.
Warning: Worker stopped while 2 were still in the queue.
  Debug: Disposing scope.
  Debug: Disposing SentryScopeManager.

**Comment by fengyuan213** [comment]
I think I kind of figured out why this problem is happening.
I tried to use await SentrySdk.FlushAsync() method with a large configured time out. However, the last exception(System.DivideByZeroException: 'Attempted to divide by zero.') seems not to be captured/send to sentry.
Code:
            using (SentrySdk.Init(o =>
            {
                o.Debug = true;
                o.Dsn = new Dsn("https://8c03d576f6104cc8b78c7a024088fada@o402191.ingest.sentry.io/5427284");

            }))
            {
                SentrySdk.CaptureMessage("Test", SentryLevel.Fatal);
                var aaa = SentrySdk.CaptureException(new Exception());
                await SentrySdk.FlushAsync(new TimeSpan(0,20,0)).ConfigureAwait(true);
                var a = 0;
                Console.WriteLine(1 / a); //Exception:System.DivideByZeroException: 'Attempted to divide by zero.'

                Console.WriteLine("dwadwad");
            }

**Comment by bruno-garcia** [comment]
Two things I can read there:
Not enough time to flush events (do you have high latency to connect to Sentry?)
A simpler API is: `TimeSpan.FromSeconds(2)`

` Warning: Worker stopped while 2 were still in the queue.`
The process is exiting before it could send 2 events to Sentry.
Can you reach Sentry.io from your machine?

**Comment by fengyuan213** [comment]
I could access sentry.io , however, with a higher ping
Pinging sentry.io [35.188.42.15] with 32 bytes of data:
Reply from 35.188.42.15: bytes=32 time=205ms TTL=100
Reply from 35.188.42.15: bytes=32 time=207ms TTL=100
Reply from 35.188.42.15: bytes=32 time=209ms TTL=100
Request timed out.

**Comment by fengyuan213** [comment]
I do have a latency at the range of 200-300 pings and I can reach sentry IO from my machine. When the application crashes, I can't receive an event sent by the sentry, Is it possible because of the network operation times out when sending events to sentry? and how to solve it. (I can receive events only by doing SentrySdk.FlushAsync(timespan) with a large timespan)

**Comment by bruno-garcia** [comment]
It's always required to flush events before exiting the app. Even with low latency.
That's because, as I said before events are sent in the background and if the main thread exits, the background threads get killed and the app is gone.
Just make sure to call `await SentrySdk.FlushAsync(TimeSpan.FromSeconds(2))` and you should get your events just fine.

We'll add offline caching too which means even if the device is offline, after the app restarts, it'll attempt to send the event too.

**Comment by bruno-garcia** [comment]
You can now also save the file to disk so it can be captured after the app restart (when there's Internet for example). #80
