### ISSUE TITLE
Feature: Add ability to capture data/tags/etc with message/exception

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#51]
If possible, it would be nice to add extra data, add tags, modify the fingerprint, etc from the CaptureMessage/CaptureException/CaptureEvent methods.

Alternatively, it would also be nice to have an option to add tags or additional data via the SentrySdk method (i.e. SentrySdk.SetTag).  It appears the only way to add tags to the scope is via the ConfigureScope option, which is only run once per scope.

**Comment by bruno-garcia** [comment]
`ConfigureScope` can be called as many times as you need.

For example:

```csharp
SentrySdk.ConfigureScope(s => s.SetTag("k1", "v1");
SentrySdk.ConfigureScope(s => s.SetTag("k2", "v2");
SentrySdk.CaptureMessage("message");
```

Would result in a `message` in sentry with the 2 tags set above.

I guess it might not be clear. It's worth mentioning that on the documentation then.

With that in mind, we would like to avoid adding things that exists on the `Scope` into `SentrySdk` simply to get the call a bit shorter. (`AddBreadcrumb` is the exception).
