### ISSUE TITLE
Issues not getting logged?

### ISSUE THREAD

**Issue by stephenmichaelf** [getsentry/sentry-dotnet#518]
Please mark the type framework used:

- [x] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [x] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.7.2

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.6

I followed the example here:

https://github.com/getsentry/sentry-dotnet-samples/blob/master/AspNetMvc5Ef6/Global.asax.cs

I am able to get a SentryId back from SentrySdk.CaptureException(exception);

But then in the UI I see nothing under Issues.

I also checked the HTTP response with Fiddler and got a 200.

Am I missing something? Are delays expected? How can I debug this further?

I also tried:

```
SentrySdk.CaptureEvent(new Sentry.SentryEvent(exception));
SentrySdk.CaptureMessage("My Message");
```

cc: @bruno-garcia

**Comment by bruno-garcia** [comment]
Is this Sentry.io? If so could you please share a link to the project?

The `id` is returned when the event is successfully queued for submission inside the SDK. But you're saying you saw with Fiddler the HTTP status of a call to sentry.io/store being 200, right? In this case the event should've made it there unless it was dropped by some inbound filter in Sentry or rate limiting, or overquota.

**Comment by bruno-garcia** [comment]
A common problem on ASP.NET classic is that the server requires a proxy to connect to the Internet.
You can configure one via web.config

**Comment by stephenmichaelf** [comment]
Yes it is. I am starting to see the events now. Maybe it was because I was sending them from my dev box? It's very much not clear through the UI why I am not seeing the events.

Where can I see the inbound filters? IMO if that is the case it makes way more sense to me for users to opt in to that instead of it being magic.

**Comment by bruno-garcia** [comment]
There's no inbound filter by default. By default it works.

The proxy is unfortunately magic from ASP.NET where the `HttpClient` instance used by the Sentry SDK will expect a proxy set in the `web.config` to be able to connect to the Internet, nothing we can do here.

So you can see events now. What did you change? I don't follow anymore if there's an issue.

**Comment by bruno-garcia** [comment]
Seems resolved. So closing. Feel free to reopen otherwise
