### ISSUE TITLE
Feature: Add Flush/Close SentrySdk method

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#52]
For situations where the SentrySdk is not in a using block, it would be nice to have a way to formally close/flush pending methods and possibly await.  For example, this code in a console app will often result in no or missing messages:

```c#
public static async Task<int> Main(string[] args)
{
    SentrySdk.Init(s =>
    {
        s.Dsn = new Dsn("<url>");
    });

    SentrySdk.CaptureMessage("Message 1");
}
```
The primary reason for not simply having a using block involves multiple libraries/modules in my code.

Adding a function such as "SentrySdk.Flush();" or "await SentrySdk.FlushAsync(CancellationToken);" to ensure all messages have been sent would be nice.

**Comment by bruno-garcia** [comment]
I'm not sure I understand the reason not to use a `using` block. Could you please explain that?
Another option is to `try finally` but the idea is that before leaving Main, you should block in case there are events queued up.

If the app is about to exit, I don't see much value in `async await`. 

Now in all faireness, there is already a `Close` method, which is likely not showing on your intellisense:

![image](https://user-images.githubusercontent.com/1633368/42870459-3d3151b2-8a78-11e8-99f8-4ea58a652f8b.png)

We had the expectation that `Init` would always be called within a `using` block, and I made sure to have all samples written like that. I guess a Roslyn analyzer could come in handy. :)

**Comment by lunim** [comment]
Thanks for the response.  The request was mainly due to the way some older code was laid out.  It's more straight-forward for us to init the Sentry SDK in a central function, and then close it during our clean-up phase and would require some re-factor to wrap the all of the program code within a using block.  Since the close function is already available, this will meet our needs for our legacy projects.
