### ISSUE TITLE
Publish snupkg to nuget.org

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#530]
Even though currently the pdb is inside the nupkg, it doesn't mean it gets published with the final app.
A debugger (i.e VS) by convention will hit a symbol server to look for those. Lets publish our symbols as snupkg) to nuget.org when we publish the packages.

Include sources in the debug package.

**Comment by PureKrome** [comment]
@bruno-garcia could you please elaborate on this Issue a bit more, please?

- Add sourcelink integration _to each project_. I can't see it (currently) in the various csproj's.
- Publish the snupkgs to nuget.
  o) Which projects? All, I assume
  o) I'm not sure where the nugets are currently, automatically pushed up to NuGet? 

Previously, I've done snupkg's at the same time i'm pushing my nuget's up to NuGet.org. I do _that_ when I create a GH 'release' (which creates a Tag). In AppVeyor (and I assume GH & Travis) it check for release tag to determine if I push up to NuGet.

I'm not sure how this is done, here.

**Comment by PureKrome** [comment]
> * Add sourcelink integration _to each project_. I can't see it (currently) in the various csproj's

Thanks to @xt0rted - he [showed me the line of code](https://github.com/getsentry/sentry-dotnet/blob/f6aaeff0d010b272b1babc9d8c866f2af9ee305e/src/Directory.Build.props#L44) which shows that each project is already using sourcelink.
.
So SL already is wired up ✔️ .. just the other questions, then.

**Comment by bruno-garcia** [comment]
Today we just bundle the pdbs in the nupkg:

https://github.com/getsentry/sentry-dotnet/blob/f6aaeff0d010b272b1babc9d8c866f2af9ee305e/src/Directory.Build.props#L25

The goal here is to instead of doing this, during `dotnet pack` create a `snupkg` so we can publish to nuget.org.

Publishing I hope `dotnet nuget push` will already consider both nupkg and snupkg. This needs to be confirmed

**Comment by PureKrome** [comment]
Kewl! I'll see if I can get this up _before_ v3 goes RTM. I've done this in other repo's so I _should_ be able to get it working here.

I'll just need to get familar with how you're currently building/pushing up to nuget.

**Comment by PureKrome** [comment]
Okay - so CI passes with some good results:

`snupkg`'s are getting built:
![image](https://user-images.githubusercontent.com/899878/96271880-28394200-1019-11eb-94ec-6249030c8e47.png)

`nupkg`'s and `snupkg`'s are also getting collected as artifacts:
![image](https://user-images.githubusercontent.com/899878/96272088-5cacfe00-1019-11eb-8a11-c1d673c8b477.png)

... and getting uploaded into the artifact storage:
![image](https://user-images.githubusercontent.com/899878/96272161-72babe80-1019-11eb-958e-db6e31d79600.png)

and finally, uploaded to Zeus (if the zeus hook variable thingy was set ... which I have no idea why it was not .. i'm guessing because the branch was not `main` or `release/*` ?
![image](https://user-images.githubusercontent.com/899878/96272329-adbcf200-1019-11eb-904f-0022d71cc076.png)

So I hope this helps?

**Comment by bruno-garcia** [comment]
> Kewl! I'll see if I can get this up before v3 goes RTM. I've done this in other repo's so I should be able to get it working here.

we're probably going to release previews for over a months before GA so there's time to land lots of changes ;)

**Comment by PureKrome** [comment]
Just for reference, this is the CURRENT DETAILS for the `Sentry.dll` package that is currently up on NuGet.org servers

v 2.1.6 (i'm ignoring any previous that are up on NuGet.org and available as of right now -and- more recent that this)

![image](https://user-images.githubusercontent.com/899878/96364656-648ab080-1187-11eb-9a4b-71307a5718e3.png)


![image](https://user-images.githubusercontent.com/899878/96364674-7e2bf800-1187-11eb-98ad-6c916ecf2e90.png)


![image](https://user-images.githubusercontent.com/899878/96364684-8be17d80-1187-11eb-8221-706d97018a09.png)

![image](https://user-images.githubusercontent.com/899878/96364692-9734a900-1187-11eb-81b3-fd065985fad4.png)

**Comment by xt0rted** [comment]
Setting up deterministic builds should be pretty easy https://github.com/clairernovotny/DeterministicBuilds. Given the example there it'd probably be better to use the env var `CI` as that's set on all build servers that I'm aware of, [including GitHub Actions](https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/).

**Comment by bruno-garcia** [comment]
It's set in the main props already though:

https://github.com/getsentry/sentry-dotnet/blob/dc203d9756cab9136f37ec701873ea2b34c4cdf3/Directory.Build.props#L9
