### ISSUE TITLE
Failed invoking event handler: System.ObjectDisposedException: IFeatureCollection has been disposed.

### ISSUE THREAD

**Issue by twinmind** [getsentry/sentry-dotnet#543]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core

* Version:

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x] Sentry.AspNetCore

* Version: 2.1.6

I have the fire-and-forget action in my controller that launches a background task with its own DI setup as it's described in MS docs (3rd example) https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1#do-not-capture-services-injected-into-the-controllers-on-background-threads

CheckoutController.cs
```csharp
[ApiController]
[Route("checkout")]
public class CheckoutController : BaseController
{
        private readonly ICheckoutService _checkoutService;
        private readonly AppSettings _appSettings;

        public CheckoutController(ICheckoutService checkoutService, IOptions<AppSettings> appSettings)
        {
            _checkoutService = checkoutService;
            _appSettings = appSettings.Value;
        }

        [HttpPost]
        [Route("order")]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<ActionResult> Order([FromServices]IServiceScopeFactory serviceScopeFactory)
        {
            var request = HttpContext.Request;
            var json = await new StreamReader(request.Body).ReadToEndAsync();
            Action<string> action = async (json) =>
            {
                using (var scope = serviceScopeFactory.CreateScope())
                {
                    var service = scope.ServiceProvider.GetRequiredService<ICheckoutService>();
                    await service.CreateOrder(json);
                }
            };
            _ = Task.Run(() => action(json));
            return Accepted();
        }
}
```
When a runtime exception inside `service.CreateOrder(json)` occurs, it's correctly captured by Sentry, but on top of it there is this failure about IFeatureCollection disposal. It looks like this:
![image](https://user-images.githubusercontent.com/9801734/95041279-18ba1080-068b-11eb-8528-698b88f75133.png)

The only place where I set up Sentry in my project is in Program.cs:
```csharp
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace WebApi
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseSentry();
                });
    }
}
```

This is an ASP.NET Core 3.1.7 app which is running in AWS on Amazon Linux 2.0.2 instances.

**Comment by bruno-garcia** [comment]
In the middleware we hold a reference to the transaction in case there's an event so we can read data from it. If a background thread is kicked off, we continue to hold that reference even when the request has finished. There's no real negative side effect other than that breadcrumb.

As a work around you can silence that crumb with a callback.

Something like:
```csharp
UseSentry(o => o.BeforeBreadcrumb = c => c.Message == "...") : null ? c);

```

We should check if we're still running the requst before trying to read data from it to avoid poluting the crumbs

**Comment by chan18** [comment]
hi @bruno-garcia in this case, we will dispose right after the tread is dead. To stop throwing the exception, Right?

**Comment by bruno-garcia** [comment]
@chan18 sorry, I don't follow. Could you please elaborate?

**Comment by bruno-garcia** [comment]
This came up twice now: #764

We should just remove the breadcrumb and log it out internally.
