### ISSUE TITLE
Cache Envelopes

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#557]
Multiple users have requested a way to store events to disk. Either because the device is always offline or because it can be offline for long periods of time (laptops in the field, oil rigs etc).

Now that we have Envelopes #544 we can more easily implement caching by **optionally** storing envelopes to disk. This feature will help desktop apps and also Xamarin/.NET Mobile, given that mobile often needs to persist to disk before attempting to send out an event. This is supported by Android and iOS too.

* Offline caching is optional
  * A path to serve as root path for storing things must be provided via `SentryOptions`.
* Max files must be capped, default could be 30 to match other SDKs.
* If the cache directory is full, delete the oldest item first.
  * Ideally using the file timestamp date
  * Consider that envelopes might be edited later (changes last modified date), when sessions are added, to track `init=true`.
  * Consider that this can run on Android, Windows, Linux, macOS, the file timestamp API expected to work on these platforms.
* The order of files cached should be respected.
  * If an envelope is captured and files are queued for submission on the disk, send the files from disk first.
* If a file is cached and subsequently sent to Sentry, the cached file then is deleted.
* Consideration for retry:
  * If sending to Sentry fails due to timeout or no connection at all, the file continues to be cached
  * If Sentry returns **any** status code, the file should be deleted: Don't retry an envelope that hit Sentry and caused a 500, 200, 400 or any status.

This will resolve: https://github.com/getsentry/sentry-dotnet/issues/80

**Comment by lucas-zimerman** [comment]
@bruno-garcia this cap is per envelope type? (30 sessions, 30 transactions, and 30 user feedbacks) or it's shared across all envelopes?

Also the device.online could be set to false in case the device is offline

**Comment by bruno-garcia** [comment]
> @bruno-garcia this cap is per envelope type? (30 sessions, 30 transactions, and 30 user feedbacks) or it's shared across all envelopes?

The cap is for the whole directory, regardless of envelope item type

> Also the device.online could be set to false in case the device is offline

In the offline storage mode we'll write to disk first, then try to send. So we don't really amend the event once it's been cached. We could have the SDK set such flag while the event is being created if there's an API to tell if the device is online or not.
