### ISSUE TITLE
UWP (Xbox/Desktop): Unknown OS & Unknown Device

### ISSUE THREAD

**Issue by hupo376787** [getsentry/sentry-dotnet#560]
## Important Details

How are you running Sentry?

On Xbox, and Win10 devices, run sentry in uwp apps.

## Description

App report exceptions showing unknown os and device.

## Steps to Reproduce

1. Build a uwp app.
2. Use sentry to capture a event.
3. View sentry console.

### What you expected to happen

OS: show the correct OS and version.
Device: show Xbox, desktop, etc.

### Possible Solution

Add Windows 10 support.

Received bug showing unknown OS and unknown Device.

![image](https://user-images.githubusercontent.com/14960168/97152741-50a90500-17ac-11eb-9e00-e14a8a7ee9ca.png)

**Comment by bruno-garcia** [comment]
We get the OS name through a .NET API:

https://github.com/getsentry/sentry-dotnet/blob/5d764988f53e404bfd43024025b4583c966b479f/src/Sentry/Internal/MainSentryEventProcessor.cs#L69

What we can do here is use `#ifdef` and use some native API to get the right value.
A candidate API is:

https://docs.microsoft.com/en-us/uwp/api/windows.security.exchangeactivesyncprovisioning.easclientdeviceinformation.operatingsystem?view=winrt-19041

**Comment by lucas-zimerman** [comment]
@bruno-garcia not sure how native APIs would work, but if needed, I could also add those info for Xamarin.Android/IOS

**Comment by bruno-garcia** [comment]
@lucas-zimerman we can add another target for `UWP` and `#if ...` to access that API.
I can prepare the infrastrucutre for that if folks can help find the right APIs.

Since I don't have experience with UWP, I don't know what we could leverage here. @hupo376787 any ideas? If you were accessing that information directly in your app, what API would you use?

**Comment by hupo376787** [comment]
Hi, I usually use the following code to get the system infos.

```
                    string DeviceFamily = AnalyticsInfo.VersionInfo.DeviceFamily;
                    ulong version = ulong.Parse(AnalyticsInfo.VersionInfo.DeviceFamilyVersion);
                    ulong major = (version & 0xFFFF000000000000L) >> 48;
                    ulong minor = (version & 0x0000FFFF00000000L) >> 32;
                    ulong build = (version & 0x00000000FFFF0000L) >> 16;
                    ulong revision = (version & 0x000000000000FFFFL);
                    var osVersion = $"{major}.{minor}.{build}.{revision}";
                    string OperatingSystemArchitecture = Package.Current.Id.Architecture.ToString();
                    EasClientDeviceInformation deviceInfo = new EasClientDeviceInformation();
                    string OperatingSystem = deviceInfo.OperatingSystem;
                    string DeviceManufacturer = deviceInfo.SystemManufacturer;
                    string DeviceModel = deviceInfo.SystemProductName;
```

For os, I suggest to use `OperatingSystem` & `osVersion` & `OperatingSystemArchitecture `.
For device, we can use `DeviceFamily`, or `DeviceManufacturer ` & `DeviceModel `.

**Comment by hupo376787** [comment]
I looked into the source code, but I can't find out the code to get system infos.

**Comment by lucas-zimerman** [comment]
@hupo376787 
            var clientDeviceInformation = new EasClientDeviceInformation();
            var deviceManufacturer = clientDeviceInformation.SystemManufacturer;
            var deviceModel = clientDeviceInformation.SystemProductName;
            var operatingSystem = clientDeviceInformation.OperatingSystem;
            var systemHardwareVersion = clientDeviceInformation.SystemHardwareVersion;
            var systemFirmwareVersion = clientDeviceInformation.SystemFirmwareVersion;

**Comment by hupo376787** [comment]
@lucas-zimerman 
On my Xbox One X,
![image](https://user-images.githubusercontent.com/14960168/98060859-8f624d80-1e85-11eb-92d9-10a006be65e2.png)

On my Xbox One S
![image](https://user-images.githubusercontent.com/14960168/98061005-ee27c700-1e85-11eb-8941-13e658eef1f6.png)

**Comment by lucas-zimerman** [comment]
![image](https://user-images.githubusercontent.com/8229322/98444375-14e93600-20f0-11eb-8cb9-cdca09c5e54b.png)
Hopefully, there'll be a new alpha for adding support to UWP.

**Comment by hupo376787** [comment]
OK, please let me know if the new package version available, thanks.

**Comment by lucas-zimerman** [comment]
@hupo376787 would you mind giving it a try to this Package? https://www.nuget.org/packages/ContribSentry.UWP
(Works with Sentry SDK 2.1.8, I'll need to release another version for 3.x due to breaking changes)

All you need to do is to include UWPSentryIntegration on SentryOptions

```C#
    sealed partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            //You must initialize after the InitializeComponent();
            SentrySdk.Init(o =>
            {
                o.Dsn = new Dsn("your DSN");
                o.AddIntegration(new UwpSentryIntegration());
            });
            ...
        }
     ...
```C#

I have tried to integrate this with the Official .NET SDK but the UWP framework isn't too friendly with the current build system.

**Comment by hupo376787** [comment]
Hi, @lucas-zimerman 
Thanks for your work, I just test on my pc using my UWP project and send an event to the sentry. It shows the correct system and device model.
I don't have an Xbox at hand cause I'm on a weekend now, and I will test it on my Xbox next Monday.


![image](https://user-images.githubusercontent.com/14960168/101187102-e3cc3900-368e-11eb-8d23-9b17cb4cd13f.png)

**Comment by hupo376787** [comment]
Hi, @lucas-zimerman 
I just tested on my Xbox device, it shows the correct device model now.

Thanks again, closing this issue now.

![image](https://user-images.githubusercontent.com/14960168/101301559-2ef37100-3874-11eb-933a-d4e695dd67c5.png)

**Comment by hupo376787** [comment]
Hi, @lucas-zimerman I update the sentry to 3.1.0, now my app throws an exception.
![image](https://user-images.githubusercontent.com/14960168/111061106-8a20a980-84dc-11eb-8f4b-d73e9c9ebd05.png)

What should I do, thx.

**Comment by lucas-zimerman** [comment]
Hi @hupo376787 , I have just updated the SDK to version 2.0.0 for supporting the latest Sentry.NET SDK
