### ISSUE TITLE
Send user.ip_address = {{ default }} when sendDefaultPii is true

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#561]
If no explicit IpAddress was set by the user code (or framework integration) the SDK should set `{{ defaut }}` which tells the server to infer the IP Address to client connection as the `user.ip_address`.

**Comment by lucas-zimerman** [comment]
Oh that's a must have feature :D

**Comment by bruno-garcia** [comment]
@lucas-zimerman new tag ^ 😄
