### ISSUE TITLE
How to clear breadcrumbs when using Serilog integration?

### ISSUE THREAD

**Issue by dg-eparizzi** [getsentry/sentry-dotnet#575]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [X] Other: .NET Framework 4.7 Console Project

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

Please mark the NuGet packages used:

- [ ] Sentry
- [X] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.16

I have an always running console project on .NET Framework 4.7. I have an event that's get fired when something happens, I need to isolate each execution of this event.
The event uses a bunch of `using (LogContext.PushProperty(key, value))` to attach metadata to the event and inside there are several calls to log information and such. A catch captures any unhandled exception and calls `_logger.Error()` to send it out to Sentry.
Problem is, an error contains breadcrumbs from previous event executions.

How can I force clearing the breadcrumbs on each event execution so that I only get the breadcrumbs happening on that particular execution?

**Comment by bruno-garcia** [comment]
You need a new scope on each event subscriber: `SentrySdk.PushScope()`

```csharp
SentrySdk.PushScope()
try {
handle event
} finally {
SentrySdk.PopScope();
}

**Comment by dg-eparizzi** [comment]
> You need a new scope on each event subscriber: `SentrySdk.PushScope()`
> 
> ```cs
> SentrySdk.PushScope()
> try {
> handle event
> } finally {
> SentrySdk.PopScope();
> }
> ```

Thank you, but as I mentioned, I'm not using the SentrySdk class directly, but the Serilog integration. Does calling `SentrySdk.PushScope()` work well with subsequent Serilog `LogContext.PushProperty()` calls?

Also, SentrySdk does not contain a definition for 'PopScope'. I'm using latest Sentry 2.1.6.

**Comment by dg-eparizzi** [comment]
Ok, I got it working.

 For anybody interested, here's the code

```csharp
private void EventHandler(EventArgs e)
{
	SentrySdk.WithScope(scope =>
	{
		using (LogContext.PushProperty("PropKey", e.Something))
		{
			try
			{
				Log.Logger.Information("Processing new event.");
				// Do something
				Log.Logger.Information("Process completed successfully.");
			}
			catch (Exception ex)
			{
				Log.Logger.Error(ex, "Exception thrown when handling event");
			}
		}
	});
}
```

**Comment by bruno-garcia** [comment]
Doesn't even look like I wrote this code, sorry.

yeah `PushScope` returns `IDisposable`

https://github.com/getsentry/sentry-dotnet/blob/609839efdfc86fa737224f807bf793cc934e84e0/docs/manual/manual.md#L60-L65

Given that in your example you're not using the `scope` object available in the lambda, that would be a better API for you:

```csharp
private void EventHandler(EventArgs e)
{
	using (SentrySdk.PushScope())
    using (LogContext.PushProperty("PropKey", e.Something))
    {
        try
        {
            Log.Logger.Information("Processing new event.");
            // Do something
            Log.Logger.Information("Process completed successfully.");
        }
        catch (Exception ex)
        {
            Log.Logger.Error(ex, "Exception thrown when handling event");
        }
    }
```
