### ISSUE TITLE
State and/or tags are not preserved when using ILogger.BeginScope() with AspNetCore middleware

### ISSUE THREAD

**Issue by fearhq** [getsentry/sentry-dotnet#584]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core

* Version:

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x] Sentry.AspNetCore

* Version: 2.1.6

When using the Sentry.AspNetCore sentry integration, it seems that the sentry scope gets locked (https://github.com/getsentry/sentry-dotnet/issues/50#issuecomment-405887769). The side-effect is that the state and tags passed to the .net core logger through ILogger.BeginScope() are simply ignored. I understand that a new scope cannot be created due to current limitations, but is it possible to at least consider adding the tags provided by the logger scope? It seems that this is kind of what is done when using SentrySdk.WithScope - you think you have a new scope, but you're actually working with the same one. I believe it would be beneficial to allow the logger scope to affect the tags/state in the same way, as it would make our existing logging instrumentation useful without inserting new sentry-specific code for tag management

**Comment by bruno-garcia** [comment]
Makes sense. We should take in the new data, even though we're not going to push or pop scopes (not to lose the log messages) it makes sense to add the new variables.

**Comment by bruno-garcia** [comment]
This was resolved already on 2.1.8
