### ISSUE TITLE
Use [CallerMemberName] API in the tracing API

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#595]
Feature suggestion for the upcoming performance & tracing API:

It would be good to have the public tracing APIs use `[CallerMemberName]`, `[CallerFilePath]` and `[CallerLineNumber]` to automatically capture the caller without requiring a full stacktrace:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute?view=net-5.0

Since these attributes are compiler directives, this would result in interned strings added to the code where the parameter isn't explicitly specified, so it has no performance impact and would still provide some insight into where exactly a call came from.

**Comment by Tyrrrz** [comment]
I'm curious where would you pass that data. Description? Extras?
/cc @bruno-garcia

**Comment by bruno-garcia** [comment]
@Tyrrrz maybe it could be set as `tags` so gets indexed

**Comment by Tyrrrz** [comment]
Maybe then it's better to add an extension method like this:
`IHasTags.SetCurrentMemberDataTag([CallerMemberName] string name, ...)`?
This way we can also use it on event too.

**Comment by bruno-garcia** [comment]
That's a great idea. Oh except then we can't capture the caller into the Sentry API, since we'd be tracking the call form our integration into this method. 

So this API could be nice, but not a replacement to having it again elsewhere where users can call into the Sentry SDK like StartTransaction

**Comment by Tyrrrz** [comment]
We just need to carry it over everywhere, same as with `Assembly.GetCallingAssembly()`:
Unless I misunderstood.

**Comment by bruno-garcia** [comment]
It gives the value of the caller, so if we add the method you suggested, how would we get that into the transaction?

**Comment by Tyrrrz** [comment]
Pass the variable?

```csharp
public void Foo([CallerMemberName] string name = "")
{
    var transaction = scope.Transaction.
    transaction.SetTag("method_name", name);
}
```

**Comment by bruno-garcia** [comment]
Where does `IHasTags.SetCurrentMemberDataTag([CallerMemberName] string name, ...)` fit in there?

**Comment by Tyrrrz** [comment]
it would be an extension method that the user will be able to call to set the current's method name (and other info) as a tag.

**Comment by bruno-garcia** [comment]
So users would need:

`SentrySdk.StartTransaction()`
`SentrySdk.SetCurrent` .. 

The idea was to avoid the second all altogether

**Comment by Tyrrrz** [comment]
Ah now I understand. I don't think putting it onto StartTransaction() is a good idea.

**Comment by kanadaj** [comment]
I have a custom tracer implementation for manually instrumenting my code with APM-agnostic interfaces which gets the caller members, would be great if I could just pass the variables to Sentry so I can figure out where a trace came from in the code...

**Comment by Tyrrrz** [comment]
@kanadaj can you post here sample code of how you envision the API to look like? it's always better with examples

**Comment by kanadaj** [comment]
@Tyrrrz Here is my current usage:
```cs
public void StartTrace(string message, string traceType = "MethodCall",
    [CallerMemberName] string memberName = "",
    [CallerFilePath] string sourceFilePath = "",
    [CallerLineNumber] int sourceLineNumber = 0)
{
    foreach (var tracer in _tracers)
    {
        var trace = tracer.CreateTrace();
        _traces.Add(trace);
        trace.StartTrace(message, traceType, memberName, sourceFilePath, sourceLineNumber);
    }
}
```

I call `StartTrace` from my own code. In cases it's manually instrumented, I just ignore the 3 auto params, and in cases where I add instrumentation for other code I try to propagate the variables, e.g. my `ICache` implementation also has the same attributes and passes the variables, otherwise the caller member would be the `ICache` instance instead of the code calling the cache.

This would be simpler with stack traces, but those are expensive so it's not really possible to reliably collect them without a severe performance hit.

**Comment by kanadaj** [comment]
For reference, here is what it turns into in Sentry with the way I use it atm:
![image](https://user-images.githubusercontent.com/3247357/106358159-3f6b1980-6302-11eb-863f-34f6f4e8c2e8.png)

**Comment by Tyrrrz** [comment]
@kanadaj I see, it looks like your code won't benefit much from having caller member attributes on Sentry's public API because you also wrap it in your own abstraction, which would require you to pass them through anyway.

My idea was to make an extension method on `IHasTags` (i.e. Span, Event, etc) like this:

```csharp
public void SetCallerMemberNameTag(this IHasTags hasTags,  [CallerMemberName] string memberName = "") =>
    hasTags.SetTag("CallerMemberName", memberName);
```

And similar for others.

**Comment by SimonCropp** [comment]
@kanadaj looks like @Tyrrrz addressed this issue. I will close for now. Can you comment back if this is incorrect
