### ISSUE TITLE
Make Dispose only Flush

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#599]
The SDK is designed to run for the lifetime of the app. Dispose as in making it unusable is only a source of problems (ASP.NET Core creates multiple containers and we rely on a resolve of `IHub` to init the SDK, but when the (first) container is disposed, it disposes also that Hub so if an exception is generated in between that hub being disposed and the new container being created/hub taking over, those errors are lost.

**Comment by bruno-garcia** [comment]
@SimonCropp is this something you can help us with?

there are multiple environments where this doesn't work well. One of those is using a new DI Scope to get the client, then rethrowing an exception which is captured after that scope is disposed.

```
Object name: 'SentryClient'.
   at Sentry.SentryClient.CaptureTransaction(Transaction transaction) in /_/src/Sentry/SentryClient.cs:line 109
   at Sentry.Internal.Hub.CaptureTransaction(Transaction transaction) in /_/src/Sentry/Internal/Hub.cs:line 341  Debug: Configuring the scope.
```

**Comment by SimonCropp** [comment]
yep i can take a look.
