### ISSUE TITLE
Picking up the cached file to send on Mono JIT fails consistently

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#602]
```
  Error: Failed to send cached envelope: System.Runtime.Serialization.SerializationException: Member 'ClassName' was not found.
```

Tried on Unity and Xamarin (Android, JIT)

**Comment by Tyrrrz** [comment]
Possible related: **[Json.net fails when trying to deserialize a class that inherits from Exception](https://stackoverflow.com/questions/14186000/json-net-fails-when-trying-to-deserialize-a-class-that-inherits-from-exception)**

**Comment by bruno-garcia** [comment]
I found that but we don't inherit from Exception anywhere

**Comment by Tyrrrz** [comment]
Could it be that Json.NET reads `SentryException` and thinks it's an exception? I know it's dumb, but still.

**Comment by bruno-garcia** [comment]
yeah! I thought that would be a very stupid but possible reason

**Comment by Tyrrrz** [comment]
Just out of curiosity, can try renaming the file and see what happens.

**Comment by bruno-garcia** [comment]
@Tyrrrz to keep json.net

**Comment by bruno-garcia** [comment]
This is solved on the manual serialization branch
