### ISSUE TITLE
In .NET 5+ no line numbers for frames of the framework

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#604]
It seems the runtime doesn't ship with pdbs. With the move of symbols into nuget.org they might have added the runtime store symbols also there. In this case we'd to add support to symbolicating .NET frames

![image](https://user-images.githubusercontent.com/1633368/99890790-055e0700-2c31-11eb-9c44-df73ca1a0f4a.png)

to ger line numbers on the server, we need more metadata in the stack trace payload

**Comment by SimonCropp** [comment]
consider researching how to extract symbols from a symbols server and bundle them as part of a buil

**Comment by bruno-garcia** [comment]
> consider researching how to extract symbols from a symbols server and bundle them as part of a build

This would be a great work around to server-side symbolication for nuget or framework dependencies. We could add that to our docs to guide users how to get it done.

**Comment by mattjohnsonpint** [comment]
This appears to be working now, given that we have Portable PDB support.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1396388/219227414-a17e4cbd-0f96-4120-a4f3-a54ebd728c24.png">

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/1396388/219228085-ced9120e-df80-46c4-8801-3418a542ca63.png">
