### ISSUE TITLE
Flaky test FromOptions_NoDsn_DisposeDoesNotThrow

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#607]
[xUnit.net 00:00:01.99]     Sentry.Tests.Internals.OptionalHubTests.FromOptions_NoDsn_DisposeDoesNotThrow [FAIL]
Error: Sentry.Tests.Internals.OptionalHubTests.FromOptions_NoDsn_DisposeDoesNotThrow: System.InvalidOperationException : Attempt to instantiate a Hub without a DSN.
  Failed Sentry.Tests.Internals.OptionalHubTests.FromOptions_NoDsn_DisposeDoesNotThrow [< 1 ms]
  Error Message:
   System.InvalidOperationException : Attempt to instantiate a Hub without a DSN.
  Stack Trace:
     at Sentry.Internal.Hub..ctor(SentryOptions options)
   at Sentry.Internal.OptionalHub.FromOptions(SentryOptions options) in /Users/runner/work/sentry-dotnet/sentry-dotnet/src/Sentry/Internal/OptionalHub.cs:line 23
   at Sentry.Tests.Internals.OptionalHubTests.FromOptions_NoDsn_DisposeDoesNotThrow() in /Users/runner/work/sentry-dotnet/sentry-dotnet/test/Sentry.Tests/Internals/OptionalHubTests.cs:line 14

**Comment by Tyrrrz** [comment]
This one has a race condition with tests that use environment variables, I think. The environment variable lock does prevent other tests from entering, but only if they monitor that lock, which this test doesn't.

**Comment by bruno-garcia** [comment]
@Tyrrrz thanks for finding the culprit. Yes there's some EnvironmentLock.Something that wraps the tests that need access. Sounds like we need that here too

**Comment by Tyrrrz** [comment]
The way I think the race condition occurs:

1. Code enters `OptionalHub.FromOptions(...)`: https://github.com/getsentry/sentry-dotnet/blob/7e6d797b35ccbd9c99e07eef16dbf4394e94b210/test/Sentry.Tests/Internals/OptionalHubTests.cs#L14

2. Another test sets the DSN environment variable

3. It gets the DSN, which is not set from the options but from env var: https://github.com/getsentry/sentry-dotnet/blob/7e6d797b35ccbd9c99e07eef16dbf4394e94b210/src/Sentry/Internal/OptionalHub.cs#L15-L21

4. The other test resets the variable back

5. It tries to create a new hub with options: https://github.com/getsentry/sentry-dotnet/blob/7e6d797b35ccbd9c99e07eef16dbf4394e94b210/src/Sentry/Internal/OptionalHub.cs#L23

6. It tries to get the DSN **again** but this time it's no longer there, so an exception is thrown: https://github.com/getsentry/sentry-dotnet/blob/7e6d797b35ccbd9c99e07eef16dbf4394e94b210/src/Sentry/Internal/Hub.cs#L27-L36

This situation can be worked around with a lock, but I think we should avoid checking that environment variable multiple times. Ideally, maybe set the default value of `SentryOptions.Dsn` to the environment variable and allow the user to change it. No need to call `DsnLocator.FindDsnStringOrDisable()` more than once per session. This will fix this flakiness.

**Comment by Tyrrrz** [comment]
Also worth noting that it's technically something that can happen in real user code, but very unlikely.

**Comment by Tyrrrz** [comment]
`FindDsnStringOrDisable` is current invoked in 4 places (besides tests):

![image](https://user-images.githubusercontent.com/1935960/100111263-97a31c80-2e76-11eb-84bd-de1b8ff3c34e.png)

**Comment by bruno-garcia** [comment]
Sounds like Hub should take a `IDsnLocator` and on the public parameterless ctor take the current behavior and on `Hub` tests it should take a mock. So only the `SentrySdk` and the `DsnLocatorTests` tests need synchronization. The rest (instance based classes) shouldn't need any sort of lock around anywhere

**Comment by bruno-garcia** [comment]
btw env var is loaded with the process (doesn't change at runtime) so I don't think this could affect users, unless I'm mistaken here or varies by OS or something. It's a vague recollection

**Comment by Tyrrrz** [comment]
Well the user can also call `Environment.SetEnvironmentVariable`. It's unlikely, but that's what I meant.
