### ISSUE TITLE
Capture IDiagnosticLogger during testing

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#612]
Some of the tests are rather complex and test a mix of static state with filesystem.
It's hard to debug flaky tests without knowing what the SDK was doing.

We need a way to set the options.DiagnosticLogger to a type that will accumulate logs in memory and in the event of a failing test, dump them all ton the test output (via xunit `ITestOutputHelper` I'd assume).

Ideally nothing would go into `ITestOutputHelper` unless the test fails. If xunit had that control instead, it would be simpler (we map `IDiagnosticLogger` to `ITestOutputHelper` and let xunit only print logs for failing tests instead of spamming the build output)

**Comment by Tyrrrz** [comment]
> Ideally nothing would go into ITestOutputHelper unless the test fails.

I don't think that's necessary. If the test didn't fail, the output won't be printed to the console anyway, although it will still be accessible from other sources (e.g. in IDE).
