### ISSUE TITLE
Upgrade NSubstitute

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#626]
NSubstitute v4 was released a while ago and dependabot keeps opening a PR.
But there are breaking changes and CI fails.

We need to bump to the latest version and fix the tests.

**Comment by Tyrrrz** [comment]
Do you have a strong preference in NSubstitute? IMO, Moq is better (with its static API) as the code is much easier without extension methods on everything.

**Comment by Tyrrrz** [comment]
https://twitter.com/Tyrrrz/status/1327245894475984896?s=20

**Comment by bruno-garcia** [comment]
I would be happy to discuss this on a greenfield project and maybe go back to Moq (I used it between 2010 and 2015) but I wouldn't add a second library here. 

I'm assuming upgrading won't require a whole rewrite. NSubstitute has it's limitations (and Moq too, like out parameters that I can recall).

**Comment by SimonCropp** [comment]
done by https://github.com/getsentry/sentry-dotnet/pull/634
