### ISSUE TITLE
SentryOptions to offer DefaultTags and DefaultExtraData

### ISSUE THREAD

**Issue by PureKrome** [getsentry/sentry-dotnet#635]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [X] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [X] .NET Core

* Version:

Please mark the NuGet packages used:

- [X] Sentry
- [X] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: Latest / 2.1.8

This issue is based upon a conversation I had with @bruno-garcia in #588 

BG: 
> Sentry.AspNetCore has appsettngs.json support for default tags. This is missing from Serilog.Sinks.Sentry. A PR to accept this would be considered.

and 

> We could move default tags to SentryOptions so all integrations could leverage.

So my original idea was to have `Sentry,Serilog` be able to send `Tag` and `ExtraData` up to Sentry. (of course, any other Sentry 'sinks' could leverage this, too).

This convo happens to also be linked to how MEL + Scopes creates (I believe) Sentry `LoggingEventProperties` which sinks like `Serilog.Sinks` could leverage. 

Finally, `Sentry.Serilog` should then be able to report back any `Tags` and `ExtraData` to Sentry.

## MAIN GOAL: 
- configuration defined in `appsettings.json` which Serilog reads/respects.
- bare minimum Sentry code in program.cs (settings defined via configuration files / environmental settings)
- App and nuget libraries all leverage MEL throughout the code (Sentry agnostic)
- Code uses MEL + Scopes. These 'scoped/temp' logging values should be sent up with their appropriate logging event, up to Sentry.

---

Having a quick look at the code, I've noticed that currently default Tags do exist, but here:

https://github.com/getsentry/sentry-dotnet/blob/e17703a77a4a5f20b44f233ecfa4e937d42542f8/src/Sentry.Extensions.Logging/SentryLoggingOptions.cs#L24-L30

I'm not familiar with the full Sentry code base, so I'm not sure of the reason for `DefaultTags` existing in `SentryLoggingOptions` .. but based on what @bruno-garcia suggested,  this should be moved to `SentryOptions`. This would also mean this code would also be moved:

https://github.com/getsentry/sentry-dotnet/blob/e17703a77a4a5f20b44f233ecfa4e937d42542f8/src/Sentry.Extensions.Logging/SentryLoggingOptionsExtensions.cs#L40-L52

Next, the `AspNetCoreEventProcessor` shouldn't be the only thing to process this, but _all_ EventProcessors:

https://github.com/getsentry/sentry-dotnet/blob/e17703a77a4a5f20b44f233ecfa4e937d42542f8/src/Sentry.AspNetCore/AspNetCoreEventProcessor.cs#L40

so I was thinking of moving that out to the `MainSentryEventProcessor`.

Now this is for `DefaultTags`. I was then going to (more or less) copy all of that and add `DefaultExtraData` (or should it be called `DefaultExtra`) which then allows the developer to have default extra data.

- Tags = indexed
- Extra Data = not indexed

Next, update maybe the `Samples.Console.Customized` and maybe `Samples.ME.Logging` to test this out. (NOTE: I cannot access that DSN bucket, so I'm assuming I would make my own and not PR that DNS).

Finally, test out Serilog with `Samples.Serilog` and make sure the data is getting added.

This is the way.

UPDATE:

The official docs state [that `Extra` should be deprecated away in favour of the word `Context`](https://docs.sentry.io/platforms/dotnet/enriching-events/context/). So if you're still happy with having the Default Context added, I can use that terminology instead?

**Comment by bruno-garcia** [comment]
We're planning to deprecate `Extra` in favour of `Contexts` and given the fact that both deal with `objects` instead of just string key-value pairs, I'd keep that out of this PR.

So let's just focus on Tags here. 

Makes sense what you said, as we discussed. Just lift the field to SentryOptions and the code that applies it from AspNetCore or MEL integrations straight to the MainEventProcessor.

I suggest opening a draft PR first so we can discuss the general approach, before you invest in tests or xml docs etc. It's fine that the PR won't pass CI.

I can send you an invite to our contributors Sentry org. Or you can use your own DSN for testing that's also OK. If you'd like the invite, ping me on our discord server #dotnet https://discord.gg/sentry

**Comment by PureKrome** [comment]
Cheers @bruno-garcia - that's ok, i'll just make up my own DSN.

I'll go ahead and work on a draft pr (after hours) and just do `Tags`. Kewl!
