### ISSUE TITLE
Rename CacheFlushTimeout to something more descriptive

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#638]
https://github.com/getsentry/sentry-dotnet/blob/429c58bbaa2aae2ad02c772d6f04c19e3039481a/src/Sentry/SentryOptions.cs#L384

Ideally it should clarify that it: Blocks initializing the SDK if offline caching is enabled and events are on disk to be sent. Something like `BlockInitForCacheFlushTimeout` but ideally less horrible.

Which makes me realize, before using the field, make sure the CacheDir isn't null.

**Comment by lucas-zimerman** [comment]
CacheFlushTimeout  -> InitializeCacheTimeout ?

**Comment by bruno-garcia** [comment]
Maybe Just InitCacheFlushTimeout

**Comment by lucas-zimerman** [comment]
mmm sounds good,
