### ISSUE TITLE
Send full method signatures to Sentry instead of just the method name

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#647]
For integration with https://github.com/getsentry/sentry-visualstudio (and as a good practice in general when dealing with method overloads) it would be the best if Sentry sent the full method signatures where available in the stacktrace.

The parameter list is available on the `MethodInfo` from the StackTrace Frame:
```cs
var stacktrace = new StackTrace(e);
foreach (var frame in stacktrace.GetFrames())
{
    var method = frame.GetMethod();
    var methodParams = method.GetParameters(); // These are our parameters
    foreach(var parameter in methodParams){
        var paramName = parameter.ParameterType.Name; // The name of the parameter type
        var fullName = parameter.ParameterType.FullName; // Full name including namespace
    }
}
```

**Comment by bruno-garcia** [comment]
This will change grouping so better be part of a major change. 3.0.0 is a good candidate
