### ISSUE TITLE
Add: helper for formatting HttpRequest Exceptions.

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#650]
Since the SDK isn't integrated with the app HttpClient, it would be nice to have a simple function where a SentryEvent is going to be created and Http fields are going to be populated.

**Comment by bruno-garcia** [comment]
@Tyrrrz prob goes with that HttpMessageHandler discussion we had

**Comment by Tyrrrz** [comment]
https://github.com/getsentry/sentry-dotnet/blob/bcc12cb38d6891b31e0e21e20574dbb4f13834b2/src/Sentry/SentryHttpMessageHandler.cs#L9-L71

**Comment by mattjohnsonpint** [comment]
Closing this for now.  Feel free to leave more details if we should re-examine.  Thanks.

**Comment by lucas-zimerman** [comment]
Looks good with the implementation of SentryHttpMessageHandler.cs.

Maybe for MAUI, check if it's possible to use the SentryHttpMessageHandler on HttpClients from users without requiring them to manually attach the SentryHttpMessageHandler to each HttpClient they use on their code. Otherwise, it would be nice if the docs mention how to use the SentryHttpMessageHandler on MAUI
