### ISSUE TITLE
Issues with UserFeedback

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#651]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [x] Xamarin
- [x] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [x] Mono
- [x] .NET Core

* Version:

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:

1. When trying to register an user feedback with cache enabled, Sentry reports a serialization error and drops the envelope.
2. When sending the user feedback without cache, Sentry server seems to be dropping feedbacks that doesn't contain the username field.

EDIT: Validated with the Sentry.Samples.Console.Basic by setting the user as null on line 155.  (The output request is correct so I guess the issue is on Sentry backend?)

EDIT2: the cache issue can also be validated on the same project by setting the o.CacheDirectoryPath = "./Sentry";
the error might be related to             var name = json.GetProperty("name").GetStringOrThrow(); since the name could be null

**Comment by lucas-zimerman** [comment]
https://github.com/getsentry/sentry-dotnet/blob/54e1853dd26c526613706aeb54da5b9f4b221229/src/Sentry/Protocol/UserFeedback.cs#L78

**Comment by Tyrrrz** [comment]
Are all fields on user feedback optional now? @lucas-zimerman @bruno-garcia 

![image](https://user-images.githubusercontent.com/1935960/102515122-04848d80-4096-11eb-8ab2-c3cf28c32616.png)

**Comment by lucas-zimerman** [comment]
I don't see a use case for a UserFeedback without all fields being null, in this case, I think it's safe to just ignore the userfeedback.

**Comment by bruno-garcia** [comment]
I really dislike making everything optional. What's the point of an empty feedback?
At least comments should be requried IMHO
