### ISSUE TITLE
UseSerilog + gRPC

### ISSUE THREAD

**Issue by zs-dima** [getsentry/sentry-dotnet#652]
Could I kindly ask you if it is possible to log to Sentry using gRPC and use Serilog at the same time?

Could be nice to configure logging using `appsettings.logs.json` as well

Thanks in advance

**Comment by bruno-garcia** [comment]
It's possible already with `Sentry.AspNetCore.Grpc` and `Sentry.Serilog`.

You can configure things with ASP.NET Core using json:
https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/#configure

**Comment by zs-dima** [comment]
It doesn't works.
Could I kindly ask you to provide working example for gRPC?

**Comment by zs-dima** [comment]
Link you provided about Sentry without Serilog only! You could see official Sentry Serilog example to see how it works!

**Comment by bruno-garcia** [comment]
The link is of the docs about configuring with appsettings.json

Samples with ASP.NET Core and Serilog are here: https://github.com/getsentry/sentry-dotnet/tree/main/samples/Sentry.Samples.AspNetCore.Serilog

Just use the Grpc package instead of Sentry.AspNetCore

**Comment by zs-dima** [comment]
@bruno-garcia 
I know how to configure appsettings.json
But Sentry does not have setting to enable gRPC with Serilog same as plain Serilog settings
Even without appsettings.json.

**Comment by zs-dima** [comment]
This options are missing:
.UseSentry(builder =>
                {
                    builder.AddGrpc();

**Comment by zs-dima** [comment]
https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.AspNetCore.Grpc/Program.cs

**Comment by zs-dima** [comment]
https://github.com/getsentry/sentry-dotnet/tree/main/samples/Sentry.Samples.AspNetCore.Serilog
