### ISSUE TITLE
Document: Misleading XML comment for DisableAppDomainProcessExitFlush

### ISSUE THREAD

**Issue by Genteure** [getsentry/sentry-dotnet#654]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [x] Other: Not applicable

Please mark the type of the runtime used:

- [x] .NET Framework
- [x] Mono
- [x] .NET Core

* Version: N/A

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.8

https://github.com/getsentry/sentry-dotnet/blob/1271d52b28805ad39f12f4388424a4a4bdb6a9f2/src/Sentry/SentryOptionsExtensions.cs#L52-L57

The description for `DisableAppDomainProcessExitFlush` is misleading because it does not "capture errors through AppDomain.ProcessExit".

https://github.com/getsentry/sentry-dotnet/blob/1271d52b28805ad39f12f4388424a4a4bdb6a9f2/src/Sentry/Integrations/AppDomainProcessExitIntegration.cs#L30-L33

**Comment by bruno-garcia** [comment]
It flushes any queued events (i.e: captures errors) on ProcessExit.

It arguably doing what it says but I agree it could better explain.

Would you be willing to submit a PR to help out with this?
You can do that through GitHub:
![image](https://user-images.githubusercontent.com/1633368/102370154-c2baf080-3f8a-11eb-95b3-8d7d4ca629ec.png)

![image](https://user-images.githubusercontent.com/1633368/102370237-d8301a80-3f8a-11eb-8437-1da2b3178d7a.png)

**Comment by Genteure** [comment]
> It arguably doing what it says...

I agree. I was trying to handle those events manually so I can set the event level to fatal, and was so confused when I saw the type of `AppDomain.ProcessExit` is `System.EventHandler` and there's no `Exception` property.

> Would you be willing to submit a PR to help out with this?

I would love to, but I think you should change it since I can't think of a better description, and I'm unsure about my English grammar.
