### ISSUE TITLE
UWP: App with cached events/envelopes freezes the app on startup.

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#664]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [x] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core
- [x] .NET Native

* Version:

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:

The app freezes when initializing Sentry on the UWP project when there are cached envelopes.

To show the issue, I made the below sample app attached to the SDK to make things easier for testing, simply press the button for capturing messages (without internet) and restart the app.

You can reproduce the issue in Debug and Release mode.

Sample branch: https://github.com/getsentry/sentry-dotnet/tree/sample/cache-freeze-uwp
Project: Sentry.Sample.App

**Comment by Tyrrrz** [comment]
Does it freeze if you set `SentryOptions.InitCacheFlushTimeout = TimeSpan.Zero`?

**Comment by lucas-zimerman** [comment]
@Tyrrrz  with TimeSpan.Zero the app doesn't freeze, all events seem to be erased but the first.

Before restarting the app without connection.
![image](https://user-images.githubusercontent.com/8229322/103105205-0ce74600-460b-11eb-8e10-b661ea49d461.png)

After the app got restarted (without connection)
![image](https://user-images.githubusercontent.com/8229322/103105214-1a9ccb80-460b-11eb-9441-443a9c9ccad6.png)

[1608840496_aba60a2c8e91459385556077c5984f57_56140151.zip](https://github.com/getsentry/sentry-dotnet/files/5740448/1608840496_aba60a2c8e91459385556077c5984f57_56140151.zip)

For some reason, it only left one file

**Comment by bruno-garcia** [comment]
@lucas-zimerman it tries to send stuff up to 1 second. Then it gives up.

**Comment by lucas-zimerman** [comment]
It shouldn't delete the envelopes if you have no connection right?

**Comment by bruno-garcia** [comment]
@lucas-zimerman By default it'll block `Init` up to 1 second to send cached events to cover the case where the app crashes right after starting.

After 1 second, it'll continue to load normally.

@Tyrrrz we really need to document this btw. Maybe a PR stating that's only on 3.0.0 (preview)?
So it's ready for GA?

**Comment by lucas-zimerman** [comment]
@bruno-garcia  update:
it doesn't delete the envelopes, it only moves the envelopes from __processing to the previous folder.
[70A818B33F1E50BB3AE349F80F1ADAF8C6218DE0.zip](https://github.com/getsentry/sentry-dotnet/files/5740524/70A818B33F1E50BB3AE349F80F1ADAF8C6218DE0.zip)

On the attached file, the UWP app moved 10 files out of __processing, leaving two files and then the app froze. (there was no connection during the execution).

**Comment by lucas-zimerman** [comment]
The issue was related to a deadlock fixed on https://github.com/getsentry/sentry-dotnet/pull/694

**Comment by Tyrrrz** [comment]
@lucas-zimerman sure.
