### ISSUE TITLE
Sample for UseSerilog + gRPC

### ISSUE THREAD

**Issue by zs-dima** [getsentry/sentry-dotnet#677]
Could I kindly ask you if it is possible to log to Sentry using gRPC and use Serilog at the same time?

Sentry does not have setting to enable gRPC with Serilog same as plain Serilog settings:
This options are missing with Serilog setup and exists only for plain Sentry gRPC:

```C#
.UseSentry(builder => { builder.AddGrpc();
```

https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.AspNetCore.Grpc/Program.cs
https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.AspNetCore.Serilog/Program.cs

Could be nice to configure logging using appsettings.logs.json as well

related issue: https://github.com/getsentry/sentry-dotnet/issues/652
Thanks in advance

**Comment by SimonCropp** [comment]
IMO this is should not be done. it shi approach is accepted, the resulting vectors of similar combined extensions would result in too much effort to maintain.
