### ISSUE TITLE
Add hook to notify the app restarted after a crash

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#701]
The UserFeedback spec for SDKs include a hook called `onCrashedLastRun`.
This is useful for Desktop, mobile apps that completely crash when an unhandled exception is captured.

Often in this case the user feedback dialog is presented to the user when the app restarts. In many SDKs that's the case because in native all you can do is create a dump and crash. ~In .NET you could technically open a dialog on the crash handler and exit only after capturing the feedback.~ (Not advised anyway, [see](https://github.com/getsentry/sentry-dotnet/issues/701#issuecomment-764201318)) 

The spec defines the hook fires only on startup though, so to align with the other SDKs, that'd be the way to go for .NET too.

https://develop.sentry.dev/sdk/features/#user-facing-platforms

**Comment by CADbloke** [comment]
Be careful stopping a .NET application crash, the OS may just force the app out of existence anyway. See https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?redirectedfrom=MSDN&view=net-5.0

> In .NET Framework, the total execution time of all ProcessExit event handlers is limited, just as the total execution time of all finalizers is limited at process shutdown. The default is two seconds.

My global crash handler saves app settings and flushes the logging cache before it does anything else. 

Obviously this doesn't apply after the app restarts

**Comment by bruno-garcia** [comment]
Thanks, update the description accordingly.
Also, removed `up-for-grabs` until we finish some discussions about where this callback should live.
@philipphofmann once we agree if there'll be an API the user will call into when they are ready to display a UI, or not, we can update this issue.
