### ISSUE TITLE
Disallow sending attachments over 20MiB in size

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#704]
Core culprit of #688

And deal with error such as file not found, permission to read etc by catching and logging.

Simply ignore the envelope item. If no items in the envelope, don't send it at all (ideally) but it's OK to send an empty envelope worst case, as Sentry supports that.

**Comment by bruno-garcia** [comment]
Related: https://github.com/getsentry/sentry-cocoa/pull/891
https://github.com/getsentry/sentry-java/pull/1134
https://github.com/getsentry/sentry-cocoa/pull/887
https://github.com/getsentry/sentry-java/pull/1141

**Comment by Tyrrrz** [comment]
Why is it in options? Isn't it enforced by relay?

**Comment by philipphofmann** [comment]
Yes, it is enforced by Relay anyway, but we also want to give the users the possibility to drop big attachments locally before sending them to relay. This is especially useful for mobile where you might not want to send big attachments, because they could eat up the users data volume.

**Comment by bruno-garcia** [comment]
Docs: https://github.com/getsentry/sentry-docs/pull/2813/files
Basically C# and F# snippets and adding `dotnet` to the list of platforms.

**Comment by Tyrrrz** [comment]
Docs missing, but tracked in #723 so this issue can remain closed.
