### ISSUE TITLE
Add generic type to method signature

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#706]
We recently added parameters to method signatures: #662 
We're missing though Generic arguments.

Ideally we'd take Ben's tests: https://github.com/benaadams/Ben.Demystifier
Capture an exception with frames having all those use cases and find out anything else we're missing.

Since 3.0.0 is a breaking change and will effect grouping, this isn't something we can do it again.

**Comment by SimonCropp** [comment]
@bruno-garcia i dont understand how "Add generic type to method signature" relates to https://github.com/getsentry/sentry-dotnet/pull/662

can u add some more indo?

**Comment by mattjohnsonpint** [comment]
This seems pretty important to fix!

**Comment by mattjohnsonpint** [comment]
Actually, nevermind my last comment.  After discussion with @bruno-garcia - this would affect grouping, and since we now have enhanced mode with Ben.Demystifier, we don't want to do this.  Even the change made with #662 mentioned above has since been removed.
