### ISSUE TITLE
Performance doesn't merge MVC requests based on routes

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#708]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [X] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [X] .NET Core

* Version: 5.0

Please mark the NuGet packages used:

- [ ] Sentry
- [X] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [X] Sentry.Extensions.Logging
- [X] Sentry.AspNetCore

* Version: 3.0.0-alpha9

Sentry doesn't seem to merge routes when used with ASP.NET MVC and configured inside Program.cs:

Configuration code:

```cs
        public static IHostBuilder CreateWebHostBuilder(string[] args)
        {
        Host.CreateDefaultBuilder(args)
              .ConfigureWebHostDefaults(webBuilder =>
              {
                  webBuilder.ConfigureKestrel(options => { options.AllowSynchronousIO = true; })
                      .UseSentry(ConfigureSentry)
                      .UseStartup<Startup>();
              });
        }

        private static void ConfigureSentry(SentryAspNetCoreOptions x)
        {
            x.SendDefaultPii = true;
            x.MaxRequestBodySize = RequestSize.Always;
            var assembly = Assembly.GetAssembly(typeof(Program));
            x.Release = assembly.GetVersion();
            x.AddEventProcessor(new OperationCanceledSentryFilter());
            x.AddEventProcessor(new FixHeaderDelimiterSentryEventProcessor());
            
            x.AddInAppExclude("MySql.Data.");
            x.AddInAppExclude("MySqlConnector.");
            x.AddInAppExclude("Pomelo.");
            x.AddInAppExclude("ElasticApm.");
            x.AddInAppExclude("Hangfire");
            x.AddInAppExclude("Serilog");
            x.AddInAppExclude("App.Metrics.");

            x.TraceSampleRate = 0.1;

            #if DEBUG
            x.TraceSampleRate = 1;
            #endif
            
            x.AddLogEntryFilter((category, level, eventId, exception) => eventId.ToString() == "Microsoft.EntityFrameworkCore.Infrastructure.SensitiveDataLoggingEnabledWarning" && string.Equals(category, "Microsoft.EntityFrameworkCore.Model.Validation", StringComparison.Ordinal));

            x.AddLogEntryFilter((category, level, eventId, exception) => eventId.Id == 10000 && string.Equals(eventId.Name, "Microsoft.EntityFrameworkCore.Update.SaveChangesFailed", StringComparison.Ordinal) && string.Equals(category, "Microsoft.EntityFrameworkCore.Database.Command", StringComparison.Ordinal));
        }
```

Tested with both legacy and endpoint routing; the route in particular is set up with attributes:
```cs
        [Route("Fiction/{id:int}/{slug}", Order = 0)]
        [Route("Fiction/{id:int}", Order = 1)]
```

Additionally, static files are also getting traced, which isn't ideal.

**Comment by bruno-garcia** [comment]
@kanadaj a bug **and** a feature, all at once

**Comment by kanadaj** [comment]
Just to document this one, this seems to be an issue with the order of the middlewares - since the Sentry middleware is added before any other middlewares, routes aren't available yet since they are parsed in the Routing middleware.

**Comment by Tyrrrz** [comment]
> Additionally, static files are also getting traced, which isn't ideal.

This is probably because the transaction name defaults to request path now. It will probably be solved by putting `.UseSentryTracing()` after `.UseStaticFiles()`.
