### ISSUE TITLE
Release Health for Client Applications

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#713]
Add support for Release Health, by [tracking healthy and unhealthy sessions](https://develop.sentry.dev/sdk/sessions/).

The use case here are apps such as: WPF, Console, WinForms, Xamarin, UWP, Blazor.

Important to note that this mode optimizes to send the session update as soon as it changes. That means `StartSession` will send an update to Sentry. And `EndSession` also sends an update.

This is different than a server mode where multiple sessions are aggregated and sent to Sentry periodically (not 2 sessions updates per session, like on client mode). There are [more about this topic on the server-mode docs.](https://develop.sentry.dev/sdk/sessions/#server-model).

**Comment by Tyrrrz** [comment]
Anything outstanding on this? Docs maybe?

**Comment by lucas-zimerman** [comment]
Sample apps would be nice

**Comment by bruno-garcia** [comment]
Also list the feature to the features list like other SDKs do:

Like: _Release Health tracks crash free users and sessions_ from [here](https://docs.sentry.io/platforms/android/) in [here](https://docs.sentry.io/platforms/dotnet/)

**Comment by Tyrrrz** [comment]
Updated the docs, let's close this issue and create separate issues for each platform (WPF, WinForms, Blazor, etc)

**Comment by bruno-garcia** [comment]
> Updated the docs, let's close this issue and create separate issues for each platform (WPF, WinForms, Blazor, etc)

Sounds good. Feel free to create any follow up issue needed
