### ISSUE TITLE
Release Health for Server Applications

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#714]
Similar to #713 but [for server-model](https://develop.sentry.dev/sdk/sessions/#server-model).

This will be used by `Sentry.AspNetCore` and `Sentry.AspNet`. It can be used by any other server integration if this server-mode is enabled.

**Comment by bruno-garcia** [comment]
Some considerations on this: https://github.com/getsentry/develop/pull/323

**Comment by mattjohnsonpint** [comment]
Also #1162 ?

**Comment by mattjohnsonpint** [comment]
Per discussion with @bruno-garcia  and @SimonCropp , we aren't going to pursue release health for server applications.  The feature will continue to work correctly for client applications, when opted in with `AutoSessionTracking` per https://docs.sentry.io/platforms/dotnet/configuration/releases/#sessions
