### ISSUE TITLE
Add support for SSL transport options

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#72]
I haven't yet run into any issues with my on-premise install, but it still might be good to add support for SSL validation overrides/disabling.  For example the Python client supports `verify_ssl` and `ca_certs` options: https://docs.sentry.io/clients/python/transports/.

**Comment by bruno-garcia** [comment]
I'm not sure I understand the request.
If you mean to validate the certificate of the server, .NET does that by default and a self signed cert, for example, will invalidate the request. Like other .NET apps, to use a self signed app you would need to add the CA to the certificate store of the computer.

**Comment by lunim** [comment]
@bruno-garcia Thanks for the feedback.  Yes, I was looking for the capability to disable ssl-validation for testing/etc.  Most out-of-band examples I've found are not available for .Net core/standard 2.x (example: ServicePointManager.ServerCertificateValidationCallback) and now require a callback in the HTTPClient handler.

**Comment by bruno-garcia** [comment]
That's a fair request and the hooks to do it are all in place already.

`DefaultSentryHttpClientFactory` is internal but has two actions in the constructor exactly for this purpose.
`HttpOptions` class has a public `SentryHttpClientFactory` which should actually be made `internal` and instead expose those same to actions. At the `SdkComposer` they'll pass from the `HttpOptions` to the `DefaultSentryHttpClientFactory`.

I'll try to get to it soon but if you want to submit a PR, we'll be happy to merge :)

**Comment by bruno-garcia** [comment]
Done here: 

https://github.com/getsentry/sentry-dotnet/commit/f198dd4201a0098d93e8016dafc22414b5002db7

Will come out on the next release in the next few days.
