### ISSUE TITLE
Improved stacktraces (based on Ben.Demystifier)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#722]
We recently added parameters to stack traces: #662 
Since this is going to affect grouping, we could reconsider this approach altogether.

The ideal world is to use `Ben.Demystifier`. But I'm wary of bringing in a dependency since this new format should be configurable. And also we need to carefully update the dependency since this can break grouping. I've [toyed with this over the holidays](https://github.com/bruno-garcia/simbolo/tree/main/Simbolo/StackFrameData/Ben) and it's just a handful of files to bring it. Interestingly enough [after my experiment a lot of improvements were added to Ben.Demystifier](https://github.com/benaadams/Ben.Demystifier/graphs/contributors?from=2020-11-26&to=2021-01-05&type=c). Even though the lib had only a few commits in 2 years, we'd want to keep up with the changes (perhaps on each major bump we do if that will affect grouping).

I'd like to propose adding `Ben.Demystifier` as a gitsubmodule and use msbuild `Include` properties to add the files we need directly to `Sentry`. If this is approach works we can bypass taking the NuGet dependency which simplifies the integration with Unity and other use cases.

**Comment by Tyrrrz** [comment]
I think adding Ben.Demystifier would be very valuable. In fact, I would suggest only to keep two options, the "classic" mode and the "extended" mode. No need for the in-between option for the current behavior we have on alpha.

**Comment by bruno-garcia** [comment]
@Tyrrrz that makes sense, I was on the fence about the the second mode so I'll just drop it.

**Comment by bruno-garcia** [comment]
#732
