### ISSUE TITLE
3.0.0 Release Tasks

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#723]
- [x] **Clearly state the breaking of grouping due to stacktrace changes** (might able to work around this in Sentry)
- [x] Document Performance API. [Draft PR](https://github.com/getsentry/sentry-docs/pull/2790)
- [x] Document the Attachment API. [Example iOS/Android PR](https://github.com/getsentry/sentry-docs/pull/2826/files).
- [x] Docs breaking changes: https://github.com/getsentry/sentry-docs/pull/2755
- [x] Documentation for ASP.NET ([PR ready here](https://github.com/getsentry/sentry-docs/pull/2669))
- [x] Wizard for ASP.NET [PR ready](https://github.com/getsentry/sentry-docs/pull/2804)
- [ ] Documentation and wizard for gRPC integration
- [x] Finalize and document, with opt-out, the new stack traces strategy (https://github.com/getsentry/sentry-dotnet/issues/722)
- [ ] Flatten [exceptions from AggregateException](https://github.com/getsentry/sentry-dotnet/issues/270) 
- [x] Fix: #708

**Comment by Tyrrrz** [comment]
Looks like this is also outstanding: https://github.com/getsentry/sentry-dotnet/issues/270#issuecomment-753349350

@bruno-garcia can you please go through the issues on Projects and add/remove them based on whether they need to make it into 3.0 release or not?

**Comment by bruno-garcia** [comment]
@Tyrrrz I've unmarked some items that don't need to make into 3.0, and also assigned those issues in the milestone to a project to see them in the lanes.

**Comment by Tyrrrz** [comment]
Closing as 3.0 has been released.

gRPC documentation is tracked in #676
