### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-dotnet#724]
Travis sprung some surprise billing changes on us, so we are now prioritizing removing usage of TravisCI completely. This issue will be used by us to track overall progress, but please let us know if there's anything we should be aware of.

**Comment by bruno-garcia** [comment]
We're ready to kill it. we didn't so far because sometimes codecov reports were not reported from GH actions but doesn't matter. Will kill it today.

**Comment by armenzg** [comment]
Is there some prior work?

**Comment by bruno-garcia** [comment]
we've moved to GH a while ago, just got lazy to drop travis

**Comment by bruno-garcia** [comment]
Sorry, no, no travis here.
