### ISSUE TITLE
Add back Code Coverage with Coverlet and Codecov 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#726]
We removed codecov report from GH actions because it was flaky to generate reports
Once there's a non-flaky alternative to getting coverage reports in CI, please address this.

Also revert:

* https://github.com/getsentry/sentry-dotnet/pull/1584
* https://github.com/getsentry/sentry-dotnet/pull/1558
* https://github.com/getsentry/sentry-dotnet/pull/1588

**Update:** We should be dogfooding with Codecov. See https://github.com/getsentry/sentry-dotnet/issues/726#issuecomment-1433463801

**Comment by bruno-garcia** [comment]
Coverage removed here: https://github.com/getsentry/sentry-dotnet/pull/1541
Removed badge: https://github.com/getsentry/sentry-dotnet/pull/1558

**Comment by bruno-garcia** [comment]
Removed restore depth (https://github.com/getsentry/sentry-dotnet/pull/1624):
```
            fetch-depth: 2 # default is 1 and codecov needs > 1
```

**Comment by mattjohnsonpint** [comment]
We should be using Codecov, now that it's part of Sentry.

Also, `Covecov` appears to be showing C# integration via OpenCover or SharpCover.  (See https://about.codecov.io/language/c-sharp/ and linked GitHub samples).  Either might _work_, but note that `dotnet new xunit` pulls in [`coverlet.collector`](https://www.nuget.org/packages/coverlet.collector).  We should explore which approach is best, and update the Codecove docs and samples also.

Codecov has a Coverlet page (https://about.codecov.io/tool/coverlet/) but it's lacking any details.

**Comment by bruno-garcia** [comment]
Btw Jared Parsons recently went through this, maybe we can learn from his experience: https://twitter.com/jaredpar/status/1729558507035185384

https://github.com/jaredpar/complog/pull/79

**Comment by jamescrosswell** [comment]
This doesn't look right for a start:
![image](https://github.com/getsentry/sentry-dotnet/assets/728212/db67c301-f40c-449e-822a-e88dc6287369)

**Comment by bruno-garcia** [comment]
> This doesn't look right for a start: 

Why? Isnt' it saying that it can't give coverage diff for the PR against `main` because it hasn't run on `main` yet. No?

**Comment by jamescrosswell** [comment]
> Why? Isnt' it saying that it can't give coverage diff for the PR against `main` because it hasn't run on `main` yet. No?

I read it as saying it would show code coverage results *in this comment* once the changes were merged into the default branch.

directly below that you can see Jared has already merged into the default branch (but codecov still doesn't show in that comment). 

So it doesn't look like it's working. Maybe it's just poorly explained though 🤷🏻‍♂️

**Comment by jamescrosswell** [comment]
In terms of the earlier problems we were having, were these related to Coverlet (and so should we be considering something like AltCover) or was it about uploading the reports? I can look at adding Coverlet back again, but only if that makes sense.

**Comment by bruno-garcia** [comment]
> In terms of the earlier problems we were having, were these related to Coverlet (and so should we be considering something like AltCover) or was it about uploading the reports? I can look at adding Coverlet back again, but only if that makes sense.

Iirc it was when generating the coverage file, it was some I/O or Stream exception

This:
* https://github.com/coverlet-coverage/coverlet/issues/1436

**Comment by bruno-garcia** [comment]
Worst case we could just avoid breaking the CI run (` || true` or something if that's possible, better than no coverage. But hard to believe this is still an issue for so many years

**Comment by jamescrosswell** [comment]
It looks like [Microsoft has a CodeCoverage library](https://github.com/microsoft/codecoverage) as well. It does have the disadvantage (vs Coverlet) of being closed source.

**Comment by bruno-garcia** [comment]
> It looks like [Microsoft has a CodeCoverage library](https://github.com/microsoft/codecoverage) as well. It does have the disadvantage (vs Coverlet) of being closed source.

Interesting. Any advantages? If so, we could get it working first back with coverlet, see how that works for a bit. Then change to this one and compare the results (in codecov)

**Comment by bruno-garcia** [comment]
> > It looks like [Microsoft has a CodeCoverage library](https://github.com/microsoft/codecoverage) as well. It does have the disadvantage (vs Coverlet) of being closed source.
> 
> Interesting. Any advantages? If so, we could get it working first back with coverlet, see how that works for a bit. Then change to this one and compare the results (in codecov)

If this works, it's enough reason to change. Just hit the same issue that made us remove it:
* https://github.com/coverlet-coverage/coverlet/issues/1436#issuecomment-1879191857
