### ISSUE TITLE
Change SetFingerprint to take `params string[]`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#728]
https://github.com/getsentry/sentry-dotnet/blob/8d581b798745ac1f96af8d4f2ed2bb18dee5f67a/src/Sentry/ScopeExtensions.cs#L152

Examples need to be updated: https://docs.sentry.io/platforms/dotnet/data-management/event-grouping/sdk-fingerprinting/#basic-example

Breaking change should be clearly stated on the release notes.

**Comment by Tyrrrz** [comment]
The docs are still up to date
