### ISSUE TITLE
Connect errors to the transaction (and span if possible) they happened in

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#738]
Discussed in: https://github.com/getsentry/sentry-java/pull/1156

If an exception bubbles out of the transaction middleware, the error in Sentry should get connected to the transaction.

It was done in Java recently: https://github.com/getsentry/sentry-java/pull/1156

**Comment by Tyrrrz** [comment]
Linking to https://github.com/getsentry/sentry-dotnet/issues/663#issuecomment-760227782
