### ISSUE TITLE
'op' and 'description' are optional and nullable

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dotnet#739]
See https://github.com/getsentry/sentry-java/issues/1170

**Comment by bruno-garcia** [comment]
Same as: https://github.com/getsentry/sentry-java/issues/1170#issuecomment-761268711

Trying to validate reasoning since I wasn't part of the meeting I might just be missing context before we make stuff nullable.

**Comment by marandaneto** [comment]
answered on the linked thread.

**Comment by Tyrrrz** [comment]
A story in two acts :D

https://media.discordapp.net/attachments/751489752905154691/800818593369161748/unknown.png

https://media.discordapp.net/attachments/751489752905154691/800818614789472286/unknown.png?width=960&height=141

This should be correct now.
