### ISSUE TITLE
Fix Scope.transaction behaviour

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dotnet#746]
Context: https://github.com/getsentry/develop/issues/246

**Comment by Tyrrrz** [comment]
Should be fixed by https://github.com/getsentry/sentry-dotnet/pull/740 unless I missed something.

**Comment by marandaneto** [comment]
> Should be fixed by #740 unless I missed something.

you're just faster fixing than me creating the issue :) thanks!
