### ISSUE TITLE
DisabledTransaction & DisabledSpan

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#747]
According to an internal agreement with @bruno-garcia , we chose not to add `DisabledTransaction` and `DisabledSpan`, in contrast to other SDKs (like the Sentry's Java SDK). Having `ITransaction` and `ISpan` allows us to do that in the future though without breaking changes.

This issue is here as a note for the future.

**Comment by bruno-garcia** [comment]
We'll currently just create a new transaction, `sampled=false` and move on for now. We can add those types on the next release

**Comment by marandaneto** [comment]
@Tyrrrz what do you mean by `Disabled`? is the equivalent of `NoOp` on Java?

**Comment by Tyrrrz** [comment]
> @Tyrrrz what do you mean by `Disabled`? is the equivalent of `NoOp` on Java?

Yes.

**Comment by SimonCropp** [comment]
closing this for now. if we have an allocation problem in the future, we can measure and address at that time
