### ISSUE TITLE
Exposing Contexts.Trace is dangerous

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#752]
As discussed with @bruno-garcia, as well as @marandaneto and @maciejwalkowiak, the current design for transaction that involves using `contexts.trace` as a holder for important fields is dangerous.

![image](https://user-images.githubusercontent.com/1935960/105080917-2c528100-5a9a-11eb-9e3a-0011b6685f7e.png)

This is not a mere hypothetical issue, but this kind of errors already happened to me while writing tests. I had to be extremely careful not to overwrite the contexts object by accident.

**Comment by Tyrrrz** [comment]
I want to close this issue because it's not really actionable. It'd be better if we had an issue with an actual solution. Collecting design problems is useful, but probably not the best in the form of issues.

**Comment by bruno-garcia** [comment]
Users can't new up transactions so it's a no-issue now
