### ISSUE TITLE
ASP.NET Core performance integration should bind Transaction automatically to scope

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#760]
Currently, there is no way to access the transaction that was created by the middleware.

cc @kanadaj

**Comment by kanadaj** [comment]
Things needed:
* Bind the transaction in the middleware on creation
* A `GetCurrentTransaction()` on `IHub` or `ISentryClient`
* Possibly a `StartSpan()` helper method to avoid fiddling with the transaction
* Either make `CaptureTransaction()` internal, or change the parameter type to `ITransaction` for consistency with public APIs.
