### ISSUE TITLE
ASP.NET Core performance middleware doesn't handle Attribute routing

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#761]
With the current middleware implementation, attribute routing (eg `[Route("/route/{param}")]` ) is still handled as paths. There are 2 possible ways to work around this:

1. On platforms where available, use `httpContext.GetRouteData()` (probably .NET Core 3 and newer), which extracts `httpContext.Request.RouteValues` if it's available.
2. If the above is insufficient, move transaction name retrieval to _after_ the middleware pipeline:
```cs
var transaction = hub.CreateTransaction(
    context.Request.Path, // Placeholder
    "http.server"
);

try
{
    await _next(context).ConfigureAwait(false);
}
finally
{
    transaction.Name = context.GetTransactionName();
    transaction.Finish(
        GetSpanStatusFromCode(context.Response.StatusCode)
    );
}
```

which will allow any logic that modifies routing to be applied before the transaction is sent.

**Comment by kanadaj** [comment]
cc @Tyrrrz

**Comment by Tyrrrz** [comment]
Afaik `httpContext.GetRouteData()` uses `httpContext.Features.Get<IRoutingFeature?>()?.RouteData` under the hood.

https://github.com/getsentry/sentry-dotnet/blob/72c6aa6d4b9b254e93020c808a9ec8e2f25f847b/src/Sentry.AspNetCore/Extensions/HttpContextExtensions.cs#L12-L51

I'm guessing the logic short-circuits when it finds the route name on the endpoint feature and doesn't get to the routing feature. I wonder if switching them around would fix the issue.

**Comment by kanadaj** [comment]
Update on this one, this seems to only happen when a route 404s.

Also, GetRouteData() actually does more:

```cs
        public static RouteData GetRouteData(this HttpContext httpContext)
        {
            if (httpContext == null)
            {
                throw new ArgumentNullException(nameof(httpContext));
            }

            var routingFeature = httpContext.Features.Get<IRoutingFeature>();
            return routingFeature?.RouteData ?? new RouteData(httpContext.Request.RouteValues);
        }
```
