### ISSUE TITLE
Transactions should include all tags from the Scope

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#762]
When a transaction is captured, it should include all tags from the scope.

More importantly, the SDK isn't adding `environment` and `release` to the transaction.

**Comment by Tyrrrz** [comment]
Are those added by event processors normally?

**Comment by bruno-garcia** [comment]
All event processing is done today on MainEventProcessor. So we'll need to refactor this to have part of it run on both transactions and errors and others stay on errors only.

**Comment by Tyrrrz** [comment]
Can we decide what that part is? We discussed this at some point before, but it wasn't clear what data we needed so we didn't do anything about it.

**Comment by bruno-garcia** [comment]
@Tyrrrz transaction without environment and release are not very useful if you see the product. Tags are also a must because it's what we use to index stuff. The other context data could probably be OK on all client-side transactions but I'm afraid of the overhead on a server node if it's just too much stuff.

Other SDKs are just adding everything you'd add to an error into a transaction, the goal was to opt-in as we see things make sense since adding is easier than removing.
