### ISSUE TITLE
ASPNETCORE Serilog : Failed invoking event handler: System.ObjectDisposedException: IFeatureCollection has been disposed.

### ISSUE THREAD

**Issue by madzaf** [getsentry/sentry-dotnet#764]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [x] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [x] .NET Core

* Version: netcoreapp3.1

Please mark the NuGet packages used:

- [ ] Sentry
- [x] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [x] Sentry.AspNetCore

* Version: 2.1.8

I'm running a small process with Sentry / Serilog and it seems to work fine other that the fact that I get this error in my message breadcrumbs:

```
Failed invoking event handler: System.ObjectDisposedException: IFeatureCollection has been disposed. 
Object name: 'Collection'.
    at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
    at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed()
    at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
    at Microsoft.AspNetCore.Http.DefaultHttpContext.get_TraceIdentifier()
    at Sentry.AspNetCore.ScopeExtensions.Populate(Scope scope, HttpContext context, SentryAspNetCoreOptions options)
    at Sentry.AspNetCore.SentryMiddleware.PopulateScope(HttpContext context, Scope scope)
    at Sentry.AspNetCore.SentryMiddleware.<>c__DisplayClass8_1.<InvokeAsync>b__3(Object _, EventArgs __)
    at Sentry.Scope.Evaluate()

```

Below is the code I use to build the WebHost:
```csharp            
return WebHost.CreateDefaultBuilder()
                .UseShutdownTimeout(TimeSpan.FromSeconds(SHUTDOWN_TIMEOUT_IN_SECONDS))
                .UseConfiguration(configuration)
                .UseUrls($"http://*:{parameters.PrivatePort}")
                .PreferHostingUrls(true) // Make sure the WebHostBuilder uses the URLs set in UseUrls() instead of the Kestrel ones
                .ConfigureServices((hostBuilder, services) =>
                {
                    services.Configure<HostOptions>(o => o.ShutdownTimeout = TimeSpan.FromSeconds(SHUTDOWN_TIMEOUT_IN_SECONDS));
                    services.AddSingleton(childProcess);
                    services.AddSingleton(metricsHandler);
                })
                .UseStartup<ChildStartup>()
                .UseSerilog()
                .UseSentry(o =>
                {
                    o.Environment = parameters.Environment;
                })
```
And the relevant configuration is here:

```json
  "Sentry": {
    "Dsn": "MYDSN",
    "AttachStackTrace": true
  },
  "Serilog": {
    "Properties": {
      "source_agent": "SomonGameChild"
    },
    "WriteTo": [
      {
        "Name": "Sentry",
        "Args": {
          "MinimumBreadcrumbLevel": "Debug",
          "MinimumEventLevel": "Warning"
        }
      }
    ]
  }
```
Any help is appreciated. Let me know if you need more information.

**Comment by bruno-garcia** [comment]
@madzaf Just to clarify: Other than logging this error, it has no negative side effect to your app.

This is likely due to work being schedule to a background thread from serving a request.

Are you doing something like `Task.Run(..)` on a Controller Action?

If an error happened in that `Task.Run`, Sentry's SDK will try to load all available context, including data from the HTTP request (which was captured with a closure). But since the request was already finished (it's running on a background thread outside of the request), it throws as it was disposed.

The solution for this might simply be to remove this breadcrumb I believe. We could try to detect if the request was disposed before trying to read data from it, likely a better work around.

**Comment by madzaf** [comment]
Hi @bruno-garcia, thanks for answering.

As far as I can tell there is no negative effect on the app but it does pollute the breadcrumbs somewhat and I can already hear all the devs asking me why there's an error there :) .

I do have a BackgroundService running with 

```csharp 
services.AddHostedServices<MyBackgroundService>();
```
And that BackgroundService has an ExecuteAsync Method with a Task.Delay instruction in it but It shouldn't cause any issues that I can see.

What's weirder is that this doesn't seem to be related to an incoming http request. So there wouldn't be a request to read or dispose of. Could that be the issue here ? Is the sink always assuming there is an http request to be captured ?

How would I go about removing that particular breadcrumb ? I'm using the Serilog Sink so all the breadcrumbs are added automatically.
If you can add a check on your end to prevent this that would be great too.

**Comment by bruno-garcia** [comment]
> Hi @bruno-garcia, thanks for answering.
> 
> As far as I can tell there is no negative effect on the app but it does pollute the breadcrumbs somewhat and I can already hear all the devs asking me why there's an error there :) .
> 

Agreed. Far from ideal and needs addressing.

> I do have a BackgroundService running with
> 
> ```cs
> services.AddHostedServices<MyBackgroundService>();
> ```
> 
> And that BackgroundService has an ExecuteAsync Method with a Task.Delay instruction in it but It shouldn't cause any issues that I can see.
>

But that's not executed from an HTTP request. So that's not the culprit.
 
> What's weirder is that this doesn't seem to be related to an incoming http request. So there wouldn't be a request to read or dispose of. Could that be the issue here ? Is the sink always assuming there is an http request to be captured ?
> 
> How would I go about removing that particular breadcrumb ? I'm using the Serilog Sink so all the breadcrumbs are added automatically.
> If you can add a check on your end to prevent this that would be great too.

You can use `UseSentry(o => p.BeforeBreadcrumb = crumb => crumb.Message.StartsWith("Failed invoking event handler: System.ObjectDisposedException: IFeatureCollection has been disposed. 
") ? null : crumb);` to drop the crumb.

The sdk uses sourcelink so you could also set a breakpoint on this like (when it does match the right breadcrumb) and take a look at the stack trace. It should be outside of the request pipeline, and help you find out why this is happening.

**Comment by madzaf** [comment]
Ah I didn't know about sourcelink ! I'll look into it and try to see exactly when this happens. 
Thank you for the breadcrumb removal tip, it should be a good workaround in the mean time.
I'll post more here if I get more information by debbugging

**Comment by madzaf** [comment]
So couldn't get sourcelink to work on my project. I followed this doc https://aaronstannard.com/visual-studio-sourcelink-setup/ but nothing happend. 
Might be due to my work proxy or network.
I added the breadcrumb removal so there's that. Kind of wish I knew why we have this error though.

**Comment by bruno-garcia** [comment]
@madzaf even without sourcelink, if you put a breakpoint on the BeforeBreadcrumb callback, when it stops there, maybe looking at the stacktrace is enough for you to figure out what's wrong

**Comment by madzaf** [comment]
Just as a final comment I got sourcelink to work and I think what happens is what I kind of suspected, my background service logs a warning, and the sdk tries to recover a spent http request when that warning occurs but the request is already over. I've added the breadcrumb removal and it works perfectly.
Thanks for all the help.
