### ISSUE TITLE
Description is nullable but ctor param is not

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dotnet#773]
as we agreed, Description is nullable, but ctor requires a non nullable value

https://github.com/getsentry/sentry-dotnet/blob/8bc640f1c5873d9acc10d8a1b05c4ee58e2d4fc2/src/Sentry/Protocol/SpanContext.cs#L21
https://github.com/getsentry/sentry-dotnet/blob/8bc640f1c5873d9acc10d8a1b05c4ee58e2d4fc2/src/Sentry/Protocol/SpanContext.cs#L37

I believe we should match them, or was it intended?

**Comment by Tyrrrz** [comment]
Ah, on the call I thought we were talking about `TraceContext` (I keep confusing all of these things).
This actually looks like an oversight, it should be nullable on the constructor.
