### ISSUE TITLE
Add a method to get the current span without the scope/make GetCurrentScope public

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#775]
Currently, the only way to access the scope is by using `ConfigureScope()` which is a closure. This is inconvenient in scenarios where Spans are started in a method and ended in a callback - we either need a way to access the Scope outside a closure, or - if the closure is needed for thread safety - a way to directly access the current Span or start a new Span via IHub.

**Comment by kanadaj** [comment]
cc @Tyrrrz @bruno-garcia

**Comment by bruno-garcia** [comment]
@rhcarvalho @marandaneto I'm surprised to find out that `startSpan` isn't documented on https://develop.sentry.dev/

Python has the startSpan on the Hub I believe, JS on the `Sentry` class? Maybe not. This is the kind of API we should be aligning.

**Comment by marandaneto** [comment]
it's called `startChild` and not `startSpan`, which could be done either via Sentry static class, transaction, or span object (Java).
Java also has a `Sentry.getSpan()` which reads the latest active span from the current Scope.

.NET does have the `getSpan()` in the Scope, but it's not exposed in the Hub and Sentry static class
@Tyrrrz we'd need to align here

a use case would be if you want to pass the span along to a callback, but requires a `configureScope` which is a Clojure.

**Comment by rhcarvalho** [comment]
> I'm surprised to find out that `startSpan` isn't documented on https://develop.sentry.dev/

It was intentionally removed in favor of `Transaction.startChild` and `Span.startChild` such that parent-child relationship is clear and that there is "only one obvious way" to do a certain thing.

In JS/Python/etc the Scope is publicly accessible.
