### ISSUE TITLE
Add full URL and possibly the individual query parameters for transactions

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#776]
Currently, transactions only have the route saved to Sentry, but this loses the data for the individual variables so correlation becomes hard between an individual set of parameters and bad performance.

Maybe also consider using query parameters as tags? Not sure about the performance implications for this.

Edit: Data about logged in users are needed as well to make full use of the Releases page.

**Comment by Tyrrrz** [comment]
This should now be in as part of #763 #762
