### ISSUE TITLE
Enable dependency validation on tests

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#793]
In the [existing test](https://github.com/getsentry/sentry-dotnet/blob/2827a1bfd74c1c7619aacf13d5893644346f0636/test/Sentry.AspNetCore.Tests/SentryHttpMessageHandlerBuilderFilterTests.cs#L38-L90), if you modify it to enable dependency validation, it does trigger the error that I receive.

```diff
var server = new TestServer(new WebHostBuilder()
    .UseSentry()
+    .UseDefaultServiceProvider(opts =>
+    {
+        opts.ValidateOnBuild = true;
+        opts.ValidateScopes = true;
+    })
    .ConfigureServices(services =>
    {
```

Now even with this in mind, I'm not entirely sure who to "blame" here - is this Sentry using it right but bad docs from MS about `AddHttpClient` etc? Is this a bug in `Microsoft.DependencyInjection`? I don't know...

_Originally posted by @Turnerj in https://github.com/getsentry/sentry-dotnet/issues/785#issuecomment-772449387_

**Comment by bruno-garcia** [comment]
Oh, is this done: https://github.com/getsentry/sentry-dotnet/pull/789/files#diff-f3c06b0b1c398285264d3a3a10eddd257c54f323a6737827ab9ed057f5821db4R51

@Tyrrrz ? Resolved already?

**Comment by Tyrrrz** [comment]
@bruno-garcia yes i added it as part of the fix.
might still want to add it to other tests that use testserver.
