### ISSUE TITLE
TracesSampler does not contain a path/name

### ISSUE THREAD

**Issue by tengl** [getsentry/sentry-dotnet#799]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry 3.0.3, .Net 3.1

### Steps to Reproduce

I just upgraded to 3.0.3 and was going to use the performance monitor feature. It worked great, but unfortunately not the `TracesSampler` that I wanted to use to filter out calls to `/healthcheck`. The documentation is not correct because the `CustomSamplingContext` is not a string as in the example here: https://docs.sentry.io/platforms/dotnet/performance/sampling/.

I used the following code in `Program.cs`. The transaction name seems to be prefixed with `GET` and I couldn't find a property with just the path. 

```csharp
options.TracesSampler = context =>
{
    var ctx = context.TransactionContext;
    return ctx.Name switch
    {
        // The health check endpoint is just noise - drop all transactions
        "GET /healthcheck" => 0.0,

        // Default sample rate
        _ => null
    };
};
```

That would still have been fine, but in my case the name was `Unknown Route`. It seems the transaction name is set after the `TracesSampler` is called. The code in `Startup.cs` file looks something like below. 

```csharp
app.UseRouting();
app.UseSentryTracing();
app.UseCors();

app.UseEndpoints(endpoints =>
{
    endpoints.Map("/healthcheck", _ => Task.CompletedTask);
    endpoints.MapControllers();
});
```

If I move `UseSentryTracing` to below `UseEndpoints` it doesn't call `TracesSampler` at all. 

Am I missing something or is it a bug? 

### Expected Result

I expected `TracesSampler` to be called with a context that contains the path of the call in order to avoid sending transactions that is not relevant.

### Actual Result

`TracesSampler` was called with a context where the transaction name was `Unknown route`.

**Comment by bruno-garcia** [comment]
Until we sort this out, a work around was mentioned [on Discord](https://discord.com/invite/PXa5Apfe7K):

app.UseWhen(x => !x.Request.Path.StartsWith("/healtcheck"), x => x.UseSentryTracing())

**Comment by tengl** [comment]
Great, thanks. Will try it out.

**Comment by tengl** [comment]
We actually ended up using the work around as a permanent solution since it is is more descriptive and less code. 

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseWhen(IsNotHealthcheck, app => app.UseSentryTracing());
}

private static bool IsNotHealthcheck(HttpContext x)
{
    return x.Request.Path.Value?.StartsWith("/healthcheck") == false;
}
```

**Comment by bruno-garcia** [comment]
Sounds like we should add this to the docs @Tyrrrz

**Comment by tengl** [comment]
Maybe add another extension?

```csharp
public static IApplicationBuilder UseSentryTracingWhen(this IApplicationBuilder app, Func<HttpContext, bool> predicate)
{
    app.UseWhen(predicate, app => app.UseSentryTracing());
}
```

**Comment by Tyrrrz** [comment]
The only issue with `UseWhen(...)` is that it's limited to two states: on or off. Traces sampler, on the other hand, is supposed to give more flexibility in the way of providing dynamic sample rate.

I think we need to expose `context.Request.Path` in some form in the `TransactionContext`.

**Comment by tengl** [comment]
I just realized that it will be difficult for us to know how many requests we will get. In order to limit the number of requests we would have to monitor the transactions every day and change the ratio all the time. 

A setting that would allow us to limit the number of transactions per minute (TPM) would be far more predictable and useful. Just record the first x transactions each minute.

**Comment by Tyrrrz** [comment]
That should be possible to do with dynamic sampling already, I think.
You can implement it in such way that it counts how many times it was called in the past minute and either returns 1.0 (sample in) or 0.0 (sample out). Something like this:

```
UseSentry(options =>
{
     var lastTransanctionTimestamp = DateTimeOffset.MinValue;
     var transactionCount = 0;

     options.TracesSampler = ctx =>
     {
          var now = DateTimeOffset.Now;
          if (now.Minute != lastTransanctionTimestamp.Minute || now - lastTransanctionTimestamp > TimeSpan.FromMinutes(1))
          {
                transactionCount = 0;
          }

          var sampleRate = transactionCount < 50 ? 1.0 : 0.0;
          
          lastTransanctionTimestamp = now;
          transactionCount++;

          return sampleRate;
     }
})
```

**Comment by Tyrrrz** [comment]
Regarding original issue, the transaction name passed to sampler should now match the route name with a few caveats:

- It may not be the final transaction name and may change by the time the transaction is finished
- Transaction name follows the format of `GET /route/{param}`, i.e. it includes the HTTP verb
- In some cases, for example when using legacy MVC or if `UseSentryTracing` is placed before `UseRouting`, the transaction name will be resolved as `Unknown route` at the start (and thus also during sampling), but will be changed into a more specific name by the time it's finished

We're also looking into automatically adding some helpful information into `CustomSampligContext`, potentially the entire `HttpRequest` object, so that you can filter on other details as well. This is tracked in #814.

Can this issue be closed?

**Comment by tengl** [comment]
Yes, the work around fixed our problem nicely, but this fix will probably be enough for those wanting to control the rate per path.
