### ISSUE TITLE
Make ISpan implement IDisposable

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#801]
Example use case:

```csharp
var span = _hub.GetSpan()?.StartChild(
    "http",
    $"{request.Method.Method.ToUpperInvariant()} {request.RequestUri}"
);

var response = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);

span?.Finish(SpanStatusConverter.FromHttpStatusCode(response.StatusCode));
```

Here, if `base.SendAsync(...)` throws, the span will never be finished. Making the `ISpan` implement `IDisposable` (and finish the span when dispose is called) seems like an idiomatic approach to solving this problem.

@bruno-garcia thoughts?

**Comment by bruno-garcia** [comment]
Makes sense. We'd need to use a NoOp singleton then to avoid dealing with nulls when tracing is turned off.

**Comment by Tyrrrz** [comment]
> Makes sense. We'd need to use a NoOp singleton then to avoid dealing with nulls when tracing is turned off.

`using (null)` doesn't throw actually.

**Comment by Tyrrrz** [comment]
After careful consideration, I decided that this is a bad idea.
When handling a potential exception, you will most likely want to set the exception and status code on the span, which `Dispose(...)` won't be able to do. This will promote suboptimal usage of the API.
Additionally, in many cases the span may be exposed from external sources (e.g. `Scope.GetSpan()` which returns a span set by an integration), finishing which may be a bad idea. Making the span disposable might incorrectly guide the user into thinking that they need to always dispose it.

**Comment by bruno-garcia** [comment]
Agree. Worth including @untitaker and @marandaneto since we discussed this about Python and Java/Android
