### ISSUE TITLE
Transaction envelope files look broken

### ISSUE THREAD

**Issue by ZakMcGrabben** [getsentry/sentry-dotnet#812]
### Environment

How do you use Sentry?
Sentry on-premise (21.1.0.dev0)

Which SDK and version?
.NET 3.0.5
Xamarin.Forms 1.0.1
Sentry.Protocol v2.2.0-alpha

### Steps to Reproduce

```
ITransaction transaction = SentrySdk.StartTransaction("name", "operation");
transaction.Finish();
```

### Expected Result

Transaction should have been sent to the Sentry Web.

### Actual Result

Transaction gets rejected.
envelope file looks invalid.

The envelop file only contains the eventId.

Log:

Envelope queued up.
New scope pushed.
Disposing scope.
Storing file C:\Users\XXX\AppData\Local\Packages\YYYY\LocalState\Sentry\F5FD1C2C5D957F03AABA443AB31F4354A68702BB\1612907709_cdfc881f6cfa435f9b98be450fd6fd53_51814648.envelope.
Envelope cdfc881f6cfa435f9b98be450fd6fd53 handed off to transport. #1 in queue.
Flushing cached envelopes.
Reading cached envelope: C:\Users\XXX\AppData\Local\Packages\YYYY\LocalState\Sentry\F5FD1C2C5D957F03AABA443AB31F4354A68702BB\__processing\1612907709_cdfc881f6cfa435f9b98be450fd6fd53_51814648.envelope
Configuring the scope.
Sending cached envelope: cdfc881f6cfa435f9b98be450fd6fd53
**Sentry rejected the envelope cdfc881f6cfa435f9b98be450fd6fd53. Status code: BadRequest. Error detail: invalid event envelope. Error causes: unexpected end of file.**
Successfully sent cached envelope: cdfc881f6cfa435f9b98be450fd6fd53

**Comment by bruno-garcia** [comment]
> Sentry.Protocol v2.2.0-alpha

There's no need to use `Sentry.Protocol` from v3 of `Sentry` since it's bundled all in one package.

@ZakMcGrabben could you please intercept the envelope sent and attach the raw event here? With a tool like `ngrok` for example?

**Comment by ZakMcGrabben** [comment]
I removed Sentry.Protocol and tried again.

The error stays the same, but the envelop file is more complete (or I intercepted it too early before)


Here is the http request (gunzipped) and response:


POST https://xxx/api/2/envelope/ HTTP/1.1
Accept-Encoding: gzip, deflate
X-Sentry-Auth: Sentry sentry_version=7,sentry_client=sentry.dotnet,sentry_key=xxx,sentry_timestamp=1612947872
Accept: application/json
Content-Length: 590
Host: xxx
Connection: Keep-Alive
Cache-Control: no-cache

{"event_id":"0ff8eda88ffe4339b1a45a4e05aef8da"}
{"type":"transaction","length":1113}
{"type":"transaction","event_id":"0ff8eda88ffe4339b1a45a4e05aef8da","release":"4.3","transaction":"name","start_timestamp":"2021-02-10T09:01:30.376017+00:00","timestamp":"2021-02-10T09:01:33.454155+00:00","request":{},"contexts":{"trace":{"type":"trace","span_id":"c7ded698a5c4407e","trace_id":"6edf830f78cb459bb0d594be4e02b15d","op":"operation","sampled":true}},"user":{},"environment":"production","sdk":{"packages":[{"name":"nuget:Sentry","version":"3.0.5"}],"name":"sentry.dotnet","version":"3.0.5"}}




HTTP/1.1 400 Bad Request
Server: nginx/1.2.1
Date: Wed, 10 Feb 2021 09:04:33 GMT
Content-Type: application/json
Content-Length: 71
Connection: keep-alive
Access-Control-Expose-Headers: x-sentry-error, retry-after, x-sentry-rate-limits
Vary: Origin

{"detail":"invalid event envelope","causes":["unexpected end of file"]}

**Comment by ZakMcGrabben** [comment]
And i attached an envenlope file that i copied while debugging stepwise.

It contains more data than being sent, e.g. [breadcrumbs.]
[1612947700_0ff8eda88ffe4339b1a45a4e05aef8da_43257534.zip](https://github.com/getsentry/sentry-dotnet/files/5957206/1612947700_0ff8eda88ffe4339b1a45a4e05aef8da_43257534.zip)

**Comment by bruno-garcia** [comment]
@ZakMcGrabben thank you so much for the detailed report. We can spot exactly the missing bits and we'll review what's wrong with the serialization.

I'm just trying tracing with [Xamarin on SymbolCollector so this will affect me there too.](https://github.com/getsentry/symbol-collector)

**Comment by Tyrrrz** [comment]
@ZakMcGrabben just to clarify, does this happen consistently or on specific transactions? Does it happen during normal runtime or when the application starts? Does it also happen with events, i.e. are breadcrumbs missing from events too?

**Comment by ZakMcGrabben** [comment]
I just started using sentry after the first beta for xamarin.forms was released :-)

So this was just a test to find out how transactions worked.
My first test (with an earlier version) worked, but the children did not show up in the sentry web.

```
			ITransaction transaction = SentrySdk.StartTransaction("name", "operation");
			//transaction.AddBreadcrumb("Add Breadcrumb");
			//transaction.SetExtra("Transaction Extra", "right?");

			/*

			ISpan span = transaction.StartChild("ChildOperation1");
			System.Threading.Thread.Sleep(500);
			span.Finish();

			ISpan span2 = transaction.StartChild("ChildOperation2");
			System.Threading.Thread.Sleep(500);
			span2.Finish();

			ISpan span21 = span2.StartChild("ChildOperation21");
			System.Threading.Thread.Sleep(500);
			span21.Finish();
			*/

			//System.Threading.Thread.Sleep(500);
			transaction.Finish();
```


After an update exceptions breadcrumbs did not worked anymore and later than the whole transcations.

I decided to just wait for the non-preview version.

Then I got the breadcurmbs back with adding XamarinFormsIntegration() and reviewed the sentry code in github to finde out I could add the TraceSampleRate.


This is my init:

```
			SentryXamarin.Init(options =>
			{
				options.DiagnosticLogger = new SentryLogger();
				options.Dsn = SENTRY_DSN;
				options.Release = Version.Major + "." + Version.Minor;
				options.SendDefaultPii = true;
				options.AddXamarinFormsIntegration();

				options.SampleRate = 1;
				options.TracesSampleRate = 1.0;
				options.MaxQueueItems = 10000;

#if DEBUG
				options.Debug = true;
#endif

				/*
				options.BeforeBreadcrumb = (breadcrumb) =>
				{
					return breadcrumb;
				};
					*/

				// Offline Cache aktivieren
				options.CacheDirectoryPath = sentryCachePath;
			});
```


UWP Target Version and Min version is: 1903 (10.0; Build 18362).

Tested the current behaviour with debugger attached and without.



I'm gonna trying to find out in which version the transactions (without childrens) did still work and will report back then.

**Comment by ZakMcGrabben** [comment]
So.. I debugged further...
I hope this will help you to nail it down :-)

```
			SentrySdk.ConfigureScope(scope =>
			{
				scope.SetExtra("Git Branch", Version.GitBranch);
				scope.SetExtra("Git Commit", Version.Revision);
				scope.SetExtra("Build Date", Version.BuildDate);
				scope.SetExtra("Build", Version.Build);

				scope.SetTag("dedesales.flavour", "Vanilla");
			});

			ITransaction transaction = SentrySdk.StartTransaction("name", "operation");
			transaction.Finish();
```
=> 
Sentry rejected the envelope d516d8bfe38c4a74900da62bd52e5e57. Status code: BadRequest. Error detail: invalid event envelope. Error causes: unexpected end of file.
Successfully sent cached envelope: d516d8bfe38c4a74900da62bd52e5e57




```
			ITransaction transaction = SentrySdk.StartTransaction("name", "operation");
			transaction.Finish();

			SentrySdk.ConfigureScope(scope =>
			{
				scope.SetExtra("Git Branch", Version.GitBranch);
				scope.SetExtra("Git Commit", Version.Revision);
				scope.SetExtra("Build Date", Version.BuildDate);
				scope.SetExtra("Build", Version.Build);

				scope.SetTag("dedesales.flavour", "Vanilla");
			});
```
=> 
Envelope b0f006a96e6843e995b5cb28db0e7d12 successfully received by Sentry.
Successfully sent cached envelope: b0f006a96e6843e995b5cb28db0e7d12

**Comment by lucas-zimerman** [comment]
I'm attaching a sample app here that is able to replicate the issue, it only break if the cache is enabled.
```csharp
static class Program
{
    static void Main()
    {
        SentrySdk.Init(o =>
        {
            o.Dsn = "https://80aed643f81249d4bed3e30687b310ab@o447951.ingest.sentry.io/5428537";
            o.CacheDirectoryPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            o.InitCacheFlushTimeout = TimeSpan.FromSeconds(10);
            o.Debug = true;
            o.TracesSampleRate = 1.0;
        });
        Console.WriteLine("Press key to capture transaction");
        Console.ReadKey();
        var transaction = SentrySdk.StartTransaction("name", "operation");
        transaction.AddBreadcrumb("á わたちわLUCASで☺;");
        transaction.Finish();
        Console.ReadKey();
    }
}
```

for now, you could disable the cache if it's not needed while the issue isn't fixed. 
```csharp
...
options.DisableXamarinFormsCache();
options.CacheDirectoryPath = null;
...
```
