### ISSUE TITLE
Sentry.NLog not logging to Sentry

### ISSUE THREAD

**Issue by RPM1984** [getsentry/sentry-dotnet#817]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [X] Other: .NET 4.6.2 console app

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.6.2

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [x] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 3.0.5

Hi there! 👋 

Trying to get Sentry wired up via NLog, and not having much luck.

NLog.config:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwExceptions="true"
      internalLogLevel="Debug"
      internalLogFile="c:\temp\nlog-internal.txt"
      internalLogToConsole="true"
      throwConfigExceptions="true">

  <extensions>
    <add assembly="Sentry.NLog" />
  </extensions>

  <targets>
    <target xsi:type="Sentry"
            name="sentry"
            dsn="https://secret"
            environment="test"
            includeEventProperties="True"
            layout="${message}"
            breadcrumbLayout="${message}"
            minimumBreadcrumbLevel="Debug"
            ignoreEventsWithNoException="False"
            includeEventDataOnBreadcrumbs="False"
            includeEventPropertiesAsTags="True"
            minimumEventLevel="Error" />    
  </targets>

  <rules>
    <logger name="*" minlevel="Error" writeTo="sentry" />
  </rules>

</nlog>
```

Things I've checked:

- DSN. Copied and pasted from the Sentry portal, so i know it's correct
- No filters on 'environments' in Sentry.
- Nlog log file shows no errors. In fact in shows Sentry being wired up.
- Added other targets to NLog (e.g console, file, etc), they work fine.

Any ideas?

Thanks

**Comment by bruno-garcia** [comment]
You need to opt-in to get the NLog integration to init Sentry with `InitializeSdk`:

https://github.com/getsentry/sentry-dotnet/blob/6ce7f933f64bd517677b5e837d6c7e8cc37b4217/src/Sentry.NLog/SentryTarget.cs#L148-L155

Could that be the issue?

Unless you're using another integration which already initialized Sentry, of if you call `SentrySdk.Init` yourself though.

**Comment by RPM1984** [comment]
@bruno-garcia thanks for jumping in! 😃 

reading the [docs](https://docs.sentry.io/platforms/dotnet/guides/nlog/#configuration), i thought `InitialiseSdk` / `SentrySdk.Init` only applies when you're using code?

i also followed the sample [here](https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.NLog/Program.cs#L87) which doesn't use any of the above approaches

**Comment by bruno-garcia** [comment]
Oh, I got my answer inverted here. [I copied it over to StackOverflow and fixed it there](https://stackoverflow.com/questions/66148473/sentry-nlog-not-logging-to-sentry/66165259#66165259):

```
Did you opt out of InitializeSdk?

https://github.com/getsentry/sentry-dotnet/blob/6ce7f933f64bd517677b5e837d6c7e8cc37b4217/src/Sentry.NLog/SentryTarget.cs#L148-L155

Could that be the issue?

Unless you're using another integration which already initialized Sentry, of if you call SentrySdk.Init yourself though.

But by default the DSN alone should be enough to init the SDK. You can set the SDK to debug mode to see what's happening.

There's a sample project in the repo: https://github.com/getsentry/sentry-dotnet/tree/main/samples/Sentry.Samples.NLog
```

Did you try the sample from the repo? Just add your own DSN to it and `dotnet run`, you should see some events. Then try to copy that approach over to narrow down where your setting is wrong. I can't spot anything by looking at your config.

Or could you share a repro?

**Comment by RPM1984** [comment]
@bruno-garcia my bad. I think the problem was i wasn't waiting long enough for it to 'flush'. I was logging, then killing my app.

I let it run for a while, and it eventually came through. I guess i expected all NLog events to 'flush' at the same time. In this case, it was flushing to output 1 immediately, but Sentinel a few seconds later.

All good, will close issue. Sorry and thanks 😊

**Comment by bruno-garcia** [comment]
You can call SentrySdk.Close() at the end of the app execution to flush things out.
