### ISSUE TITLE
Set tags from exception?

### ISSUE THREAD

**Issue by Lobosque** [getsentry/sentry-dotnet#818]
We enrich exceptions adding context to the `Data` [dictionary](https://docs.microsoft.com/en-us/dotnet/api/system.exception.data?view=net-5.0)

Sentry does handle these and send them over, in the UI they appear as "Additional Data".

However, it is not possible to search errors in the UI using Additional data Key or Value, only "tags".

I wonder if it makes sense to somehow set tags using the Data dictionary? (maybe under a "tags" key).

Since our modules are not aware of Sentry (they get a Serilog logger instance only), I cannot see another way of settings specific tags on error handling time, but am welcome to suggestions.

**Comment by bruno-garcia** [comment]
What if we special cased the key? As in `ex.Data["Sentry:Tag:Value"] = "tag value"`?
And when processing the exception data we could `StartsWith(Sentry:`, etc..

Either that or some mapping that can be provided via `init` but convention on key name sounds simpler.

**Comment by lucas-zimerman** [comment]
I like the "Sentry:Tag:Value" idea, which would save me a lot of time on my app since I have to create an extra step before capturing the exception so that I extract the tags inside of the Exception Data.

**Comment by bruno-garcia** [comment]
That could work to.

What about?

`Exception.Data["Sentry:Tag:123"] = "321"` results in 
`SentrySdk.SetTag("123", "321")`

And:
`Exception.Data["Sentry:Contexts:123"] = new { Obj = "312" }` results in
`SentrySdk.Contexts["123"] = new { Obj = "312" }`

@Tyrrrz thoughts?

**Comment by bruno-garcia** [comment]
Another use case I came across:

Attaching a file by path, such as:

![image](https://user-images.githubusercontent.com/1633368/107900298-9da51880-6f0e-11eb-9a8d-7a396fe6f4ae.png)

Defining `path` explicitly to make room for attaching the actual payload or other forms in the future.

Makes sense?

**Comment by Lobosque** [comment]
You guys implemented it before I could check the issue back again.

Awesome!

**Comment by bruno-garcia** [comment]
This wasn't shipped yet though, it'll be on whatever comes after version 3.0.7 (probably 3.0.8)
