### ISSUE TITLE
Custom Context object serialized as string

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#822]
Adding an object to be serialized like:

```csharp
if (uname is { })
{
    s.Contexts["uname"] = new
    {
        uname.Machine,
        uname.Nodename,
        uname.Release,
        uname.Sysname,
        uname.Version
    };
}
```

Results in a broken contexts:

![image](https://user-images.githubusercontent.com/1633368/107865698-5d269b80-6e37-11eb-86f8-6e5be32f8be5.png)

**Comment by Tyrrrz** [comment]
Specifically with anonymous objects?

**Comment by bruno-garcia** [comment]
@Tyrrrz It can be an actual class defined by the user. We don't have a strategy of serializing objects via reflection, right?

**Comment by Tyrrrz** [comment]
Nope. But more importantly, during deserialization that object will be resolved as a dictionary since there is no way to identify its type.
