### ISSUE TITLE
Move `SentryHttpMessageHandlerBuilderFilter` to `Sentry.E.L`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#824]
`Microsoft.Extensions.Http.HttpClientFactory` can be used outside ASP.NET Core.

Move the types related to it to `Sentry.Extensions.Logging` so it can be used by console apps and even mobile apps that rely on the `Microsoft.Extensions` bits.

The registration can move from:

https://github.com/getsentry/sentry-dotnet/blob/b744e676de78c6b4e4533d614c30444f38e3745f/src/Sentry.AspNetCore/Extensions/DependencyInjection/ServiceCollectionExtensions.cs#L40

To: 

https://github.com/getsentry/sentry-dotnet/blob/895533bff43118dd45f82d0a08ff085ac871b870/src/Sentry.Extensions.Logging/Extensions/DependencyInjection/ServiceCollectionExtensions.cs

Since `Sentry.Extensions.Logging` is a dependency of `Sentry.AspNetCore` we can define all these generic framework dependencies that are useful outside of ASP.NET Core in there instead.

**Comment by Tyrrrz** [comment]
This is possible, but we need to take dependency on [`Microsoft.Extensions.Http`](https://www.nuget.org/packages/Microsoft.Extensions.Http/) in that case.
But in my opinion, this functionality doesn't belong in Sentry.Extensions.Logging as it's not related to logging. Maybe it could be abstracted away into a separate package without inherent dependency on ASP.NET Core, but putting it into Sentry.Extensions.Logging seems wrong.

In what contexts do people use Microsoft DI with HTTP client factory outside of ASP.NET Core?

**Comment by bruno-garcia** [comment]
> This is possible, but we need to take dependency on [`Microsoft.Extensions.Http`](https://www.nuget.org/packages/Microsoft.Extensions.Http/) in that case.
> But in my opinion, this functionality doesn't belong in Sentry.Extensions.Logging as it's not related to logging. Maybe it could be abstracted away into a separate package without inherent dependency on ASP.NET Core, but putting it into Sentry.Extensions.Logging seems wrong.
> 
> In what contexts do people use Microsoft DI with HTTP client factory outside of ASP.NET Core?

I agree. But in practice people use M.E.L on everything, outside ASP.NET Core. I already need this on Xamarin and couldn't use it.

I'm not keen in splitting out dependencies to map `Microsoft.Extensions.*`. We're providing value from M.E.L level (any .NET app) and ASP.NET Core level.

**Comment by Tyrrrz** [comment]
So are you okay with taking on an extra dependency in that case?

**Comment by bruno-garcia** [comment]
> So are you okay with taking on an extra dependency in that case?

Only on ns2.x it would be a dependency right? Netcore3.1 and net5 won't change. 
Also this isn't a surprising dependency for anyone using M.E.L, Adding another M.E.x.

Wouldn't add it to Sentry package though for example

**Comment by Tyrrrz** [comment]
No, it's a dependency on all frameworks. `Microsoft.Extensions.Logging` does not normally depend on `Microsoft.Extensions.Http`.

**Comment by bruno-garcia** [comment]
Can't we use framework dependency?

**Comment by Tyrrrz** [comment]
Hm, which framework dependency? ASP.NET Core? Wouldn't that invalidate the effort then?
`IHttpClientFactory` and others are defined in `Microsoft.Extensions.Http`, not in `Microsoft.Extensions.Logging`.

**Comment by bruno-garcia** [comment]
I wouldn't use FrameworkReference for ASP.NET Core, I was under the impression there was one for the .NET Core runtime cache, if there's none then we could add the dependency to `Microsoft.Extensions.Http`. Definitely better then introducing a package just allow someone to use logging without a dependency to Microsoft.Extensions.Http.
