### ISSUE TITLE
How to configure performance monitoring?

### ISSUE THREAD

**Issue by aleksihakli** [getsentry/sentry-dotnet#830]
Hi!

I am setting up performance tracing for our .NET projects and have configured SDK settings and am getting error tracebacks, but no performance monitoring data for transactions. We are running .NET Core 3.1 web application with REST API controllers. The SDK docs talk about `TracesSampleRate` but setting it does not seem to affect the setup for SDK version `3.0.6`. On version `3.0.0-alpha.10` everything works as expected but that version seemed to collect everything by default if I recall correctly.

These are the documents I have been referencing:

- https://docs.sentry.io/platforms/dotnet/performance/
- https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/performance/

This is configuration I am using for testing in `Program.cs`:

```csharp
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Example
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddEnvironmentVariables();
                })
                .ConfigureLogging((c, l) =>
                {
                    l.AddConfiguration(c.Configuration);

                    // Adding Sentry integration to Microsoft.Extensions.Logging
                    // https://docs.sentry.io/platforms/dotnet/microsoft-extensions-logging/
                    l.AddSentry();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseSentry();
                });
    }
}
```

And `appsettings.json`:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "Sentry": {
    "Dsn": "https://abc@o123.ingest.sentry.io/456",
    "TracesSampleRate": 1.0,
    "SampleRate": 1.0,
    "Debug": true,
    "Environment": "local"
  },
  "AllowedHosts": "*"
}
```

**Comment by aleksihakli** [comment]
By using the custom instrumentation code I can get the performance metrics sent to the Sentry system, but it doesn't gather anything from ASP.NET Core 3.x API controller requests - should that be done automatically?

https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/performance/custom-instrumentation/

**Comment by aleksihakli** [comment]
OK, I just downgraded `Sentry.AspNetCore` to version `3.0.0-alpha.10` and immediately started getting traces for controller invocations on the Sentry side.

**Comment by bruno-garcia** [comment]
@aleksihakli sorry this isn't documented yet.

You need to add `UseSentryTracing()` after `UseRouting`, like such:

https://github.com/getsentry/symbol-collector/blob/388544347c8362ac9e5c3d3c4fd7450c3b8f5a14/src/SymbolCollector.Server/Startup.cs#L157-L158

Docs to document the ASP.NET Core integration is tracked here: https://github.com/getsentry/sentry-docs/issues/3090

**Comment by aleksihakli** [comment]
Makes sense, thanks @bruno-garcia!

**Comment by bruno-garcia** [comment]
Some docs landed for ASP.NET Core:
https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/performance/included-instrumentation/

Thanks again for raising and keep the feedback coming 🙏
