### ISSUE TITLE
Performance monitoring in  ASP.NET (.net 4.7.2)

### ISSUE THREAD

**Issue by insanity13** [getsentry/sentry-dotnet#831]
### Environment

I am setting up performance tracing for our ASP.NET project (.net 4.7.2).
Exceptions work well, but Performance has no data.

Sentry: 3.0.6
Sentry.EntityFramework: 3.0.3
Sentry.NLog: 3.0.6
Sentry.PlatformAbstractions: 1.1.1
Sentry.Protocol: 2.1.8

### Steps to Reproduce
In Global.asax Application_Start
`
            SentryDatabaseLogging.UseBreadcrumbs();

            // Set up the sentry SDK
            _sentry = SentrySdk.Init(o =>
            {
                o.Dsn = ConfigurationManager.AppSettings["SentryDsn"];
                o.Environment = "Production";
                o.Release = Common.Utils.SallsaUtils.GetBuildVersion();
                o.AttachStacktrace = true;
                o.ReportAssemblies = false;
                o.TracesSampleRate = 1.0;

                // Get Entity Framework integration
                o.AddEntityFramework();
            });  `

### Expected Result

Data in the Performance section.

### Actual Result

![image](https://user-images.githubusercontent.com/1174911/108167181-baa83a00-710e-11eb-9226-dd9888d5cbb1.png)

**Comment by aleksihakli** [comment]
Hey @insanity13! I was just configuring performance tracing for .NET Core and managed to get it working after using the correct middleware in #830. .NET Core is of course different from .NET Framework but I'd assume .NET Framework also requires some sort of middleware to be instrumented?

**Comment by bruno-garcia** [comment]
We don't have some auto instrumentation for it yet, nor documentation but you can achieve this by creating a transaction on:

`Application_BeginRequest`

And finish it on:

`Application_EndRequest`

How to start and end a transaction you can [see on the docs](https://docs.sentry.io/platforms/dotnet/performance/custom-instrumentation/).

We eventually want to get some samples at least out there on the docs.

**Comment by insanity13** [comment]
@bruno-garcia thanks for the reply!

**>but you can achieve this by creating a transaction on Global.asax.cs**
Yeah, I've got it but thought you have some instrumentation for it.

**Comment by bruno-garcia** [comment]
We'll get some auto instrumentation for it eventually. If you'd like to help with a PR on the `Sentry.AspNet` package, we'd be happy to discuss on a draft PR and see this through.
