### ISSUE TITLE
Transactions don't have any device information and other useful data

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#844]
![image](https://user-images.githubusercontent.com/1633368/108615231-e6a61280-73cf-11eb-9c7a-e01302e934a3.png)

Transactions at this point don't have any extra information since it's all getting attached via event processors which don't run on transactions.

**Comment by Tyrrrz** [comment]
This is likely outdated now @bruno-garcia, but transactions still don't have device information.
Here's an example of what they have: https://sentry.io/organizations/sentry-sdks/performance/sentry-dotnet:9f6351f3785d4983be24e31d7ef19d24/?project=5428537&query=transaction.duration%3A%3C15m+event.type%3Atransaction&statsPeriod=90d&transaction=GET+%7Bcontroller%3DHome%7D%2F%7Baction%3DIndex%7D%2F%7Bid%3F%7D&unselectedSeries=p100%28%29
