### ISSUE TITLE
Making sentry subscribing to "exception" events optional

### ISSUE THREAD

**Issue by FilipNemec** [getsentry/sentry-dotnet#849]
I would like if sentry didn't subscribe to AppDomain.UnhandledException and TaskScheduler.UnobservedTaskException. It would be great if there were a flag in SentryOptions to enable and disable this or if user could set property value of "Integrations " in SentryOptions. It would also be acceptable if  AppDomainUnhandledExceptionIntegration the "Handle" method would check if the exception is handled and ignore it if it is.

**Comment by bruno-garcia** [comment]
You can disable `UnhandledException` with:

https://github.com/getsentry/sentry-dotnet/blob/72c6aa6d4b9b254e93020c808a9ec8e2f25f847b/src/Sentry/SentryOptionsExtensions.cs#L38

In other words: `Sentry.Init(o => o.DisableAppDomainUnhandledExceptionCapture());`

`UnobservedTaskException` was added in #481 and didn't add this disable extension method.
So we'll need to add this, would you be willing to open a PR? It's literally the same code I linked above for `DisableAppDomainUnhandledExceptionCapture` and but for the other integration. And whatever tests it has.

**Comment by bruno-garcia** [comment]
@FilipNemec also: I'm curious what is your use case to turn those off?

**Comment by FilipNemec** [comment]
@bruno-garcia thx, I wasn't aware of this extension method. I will make a PR. 
The reason why I want to turn them off is because the production code is obfuscated so the stack trace can not be read. I subscribe to those events within my application and send deobfuscated stack trace on sentry.io, then I exit the application. So some times when the application doesn't exit fast enough I will receive  two events (from my app and sentry's SDK) one that I can actually read and one that is useless. As a result the event count goes up and the statistics get messed up.
Example: "#=zDX10$N1JmfkyGFfzJpPGBb7yCYFh2od3IzW$eHeeboAIfvJTxQ==+#=zTNevi_Y= in #=z3fGb9W4uReeaq4hmmqp1QYQ="

**Comment by FilipNemec** [comment]
@bruno-garcia I'm trying to make a PR, but I keep getting 403. Tried with ssh but still nothing. Do I need a permission?

**Comment by bruno-garcia** [comment]
@FilipNemec oh, can you also fork this: https://github.com/getsentry/Ben.Demystifier please?

I'll change this so it uses `http` instead of relative path

**Comment by FilipNemec** [comment]
@bruno-garcia I keep still getting 403. 
You want me to fork https://github.com/getsentry/Ben.Demystifier to my account?

**Comment by bruno-garcia** [comment]
> @bruno-garcia I keep still getting 403. 
> 
> You want me to fork https://github.com/getsentry/Ben.Demystifier to my account?

Yes because we're using a relative path for the submodule to avoid using either http or ssh. But I'll settle to http so it works more universally. Until then if you don't mind forking that too.

**Comment by FilipNemec** [comment]
#870

**Comment by bruno-garcia** [comment]
Resolved through @870
