### ISSUE TITLE
TaskUnobservedTaskExceptionIntegration is not used

### ISSUE THREAD

**Issue by bddckr** [getsentry/sentry-dotnet#853]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
.NET 3.0.7

### Steps to Reproduce

Have a look through this repo and check out where `TaskUnobservedTaskExceptionIntegration` is actually used.

### Expected Result

Besides the tests this integration either needs to be publicly accessible for consumers of the package, or it should be enabled by default.

### Actual Result

The integration doesn't seem to be enabled by default.

**Comment by bruno-garcia** [comment]
Thanks for raising @bddckr ! 
Seems like a gap. Wouldn't call it a bug but I must admit I expected this was enabled by default and there were integration tests for it though the `Hub` at least.

**Comment by bruno-garcia** [comment]
Relates to #849

**Comment by bddckr** [comment]
I'll close this as it seems to be resolved by #870 now! Thanks for handling this @FilipNemec!
