### ISSUE TITLE
Add `App.StartupTime` and `Device.BootTime`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#866]
iOS and Android send this data and we're [planning to extend it to show duration from it to event](https://github.com/getsentry/sentry/issues/24209).

Device.BootTime was done on SharpRaven actually, somehow never got added to `Sentry`. What I did there was:

```csharp
new DateTimeOffset(DateTime.UtcNow - TimeSpan.FromTicks(Stopwatch.GetTimestamp()),
                    TimeSpan.Zero);
```

Not sure if it's always accurate though, there might be a better approach.

AppStartup we could track the time from when `Init` was called and assume it's the start of the app, if there's no better way.
On RavenSharp I did:

```csharp
using (var proc = Process.GetCurrentProcess())
{
    app.StartTime = proc.StartTime.ToUniversalTime();
}
```

But again, is there a cost on `Process.GetCurrentProcess`? Is there a better way?

If it makes sense we could also add AppName (if not defined by the user in the scope/event) as done before too:

https://github.com/getsentry/raven-csharp/blob/678d83f8784f107bcb4acf6439aaee50fe4f8f5e/src/app/SharpRaven/Data/Context/App.cs#L125-L130

https://github.com/getsentry/raven-csharp/blob/678d83f8784f107bcb4acf6439aaee50fe4f8f5e/src/app/SharpRaven/Utilities/EntryAssemblyNameLocator.cs#L26-L29

Other Device info we got on SharpRaven but not here we can consider adding: https://github.com/getsentry/raven-csharp/blob/678d83f8784f107bcb4acf6439aaee50fe4f8f5e/src/app/SharpRaven/Data/Context/Device.cs#L191-L193

**Comment by lucas-zimerman** [comment]
a static DateTime.Now could do the trick :D

**Comment by bruno-garcia** [comment]
> a static DateTime.Now could do the trick :D
> EDIT: despite proc.StartTime.ToUniversalTime() being more taxing with performance (~35ms) I think it's a better approach than Datetime.Now by being more precise and also it seems to be more reliable on Servers.

I think `DateTimeOffset.UtcNow` is a better approach not only because it's a much more lightweight API but it's also a more portable approach. This will work on Xbox, Android, Unity or whatever. We don't need very high precision here, it's fine to be a few milliseconds off.

**Comment by lucas-zimerman** [comment]
not milliseconds but seconds :D 
![image](https://user-images.githubusercontent.com/8229322/111820640-81571b80-88c0-11eb-8e69-4b9e0c757079.png)
Got 10 seconds difference on UWP (haven't measured the others).
App center seems to be using the Process.GetCurrentProcess approach.

About using a Task, I believe it's not required since the cost of creating a Task is ~41ms vs ~64ms  using the GetCurrentProcess using block.

**Comment by bruno-garcia** [comment]
> not milliseconds but seconds :D
> ![image](https://user-images.githubusercontent.com/8229322/111820640-81571b80-88c0-11eb-8e69-4b9e0c757079.png)
> Got 10 seconds difference on UWP (haven't measured the others).
> App center seems to be using the Process.GetCurrentProcess approach.
> 
> About using a Task, I believe it's not required since the cost of creating a Task is ~41ms vs ~64ms using the GetCurrentProcess using block.

> cost of creating a Task is ~41ms vs ~64ms 

These numbers will vary a lot depending on many different factors.

The goal of the Task is to avoid running the expensive `Process` call on the calling thread (often the UI thread or anyhow slowing down the startup of an app).

So we can start during Sentry.Init: `Somewhere.StartupTime = DateTimeOffset.UtcNow` 
and run `Task.Run(() => Somewhere.StartupTime = Process.GetCurrentProcess().StartTime()` to override it later with a better value.
We can also suppress any errors happening with the `Process.X` API since we'll have some value already set.
In the event that an error gets captured faster than `Task.Run` finishes, we'd be using the `StartUp` value a few seconds off, which is totally acceptable given the trade off of actually slowing the whole app startup down to get a more precise number.

**Comment by lucas-zimerman** [comment]
TimeSpan.FromTicks(Stopwatch.GetTimestamp() return 9 days on Console Basic sample, I don't think it's the correct value.

**Comment by bruno-garcia** [comment]
The two snippets we've discussed are:

> So we can start during Sentry.Init: Somewhere.StartupTime = DateTimeOffset.UtcNow
and run Task.Run(() => Somewhere.StartupTime = Process.GetCurrentProcess().StartTime() to override it later with a better value.

**Comment by lucas-zimerman** [comment]
My bad, for some reason, my laptop is ON for 9 days (should be 22 hours right now but I guess I don't understand what a turn-off button does anymore...)
