### ISSUE TITLE
Where is `Unknown Route` coming from?

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#867]
![image](https://user-images.githubusercontent.com/1633368/109856176-31712700-7c27-11eb-8ac1-50da4c7de429.png)

Would be nice to know where this transaction comes from. Where it's created. Perhaps a context info with the full URL? Or the middleware or method that created it.

**Comment by bruno-garcia** [comment]
We need to special case 404.

Maybe group all `404` in transaction called: `URL not found`.

**Comment by Tyrrrz** [comment]
@bruno-garcia do we really want a special case for 404?
In normal circumstances `Unknown route` should only really show up for 404. 
Also now that transaction includes request data, it should probably be easier to identify where it comes from.

**Comment by bruno-garcia** [comment]
Fair enough
