### ISSUE TITLE
Introduce `SentryTracer`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#868]
Today we return a `SentryTransaction` from `StartTransaction` which can get bound to the scope.
We're changing this in other SDKs like [sentry-cocoa](https://github.com/getsentry/sentry-cocoa/pull/950) and [Java/Android.](https://github.com/getsentry/sentry-java/pull/1304)

We can make this a non-breaking change.

**Comment by Tyrrrz** [comment]
Closed via #880
