### ISSUE TITLE
Only include release prefix if it doesn't already exist

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#873]
This change https://github.com/getsentry/sentry-dotnet/pull/682/files introduced a regression for customers that already appended their own prefix: `app@`.

Before adding a prefix we should make sure one isn't there yet.

**Comment by Tyrrrz** [comment]
I don't understand this: where is the prefix already appended?
That method is called only if release is not set, neither on the scope, nor in the options. So if the user has the release set, it should not be called at all.

**Comment by bruno-garcia** [comment]
@Tyrrrz he set the release on the InformatinalVersion attribute. So it'll come from the Locator
