### ISSUE TITLE
CI fails for no obvious reason

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#878]
I might be missing an obvious reason but I only see:

> Error: Process completed with exit code 1.

Example: https://github.com/getsentry/sentry-dotnet/pull/877/checks?check_run_id=2046994870
Happened to another PR but I reran the build to try getting it merged

**Comment by Tyrrrz** [comment]
![image](https://user-images.githubusercontent.com/1935960/110825494-c5cd3080-829c-11eb-8e30-93752fe67f0f.png)

It's a test that became flaky all of a sudden. Runs fine locally.

**Comment by bruno-garcia** [comment]
Here's an example: https://github.com/getsentry/sentry-dotnet/pull/932/checks?check_run_id=2344303887

Am I missing something? I can't spot what went wrong

**Comment by Tyrrrz** [comment]
Relevant info:

https://twitter.com/danielmarbach/status/1382694722922291201?s=20

![image](https://user-images.githubusercontent.com/1935960/114900669-c6696180-9e1c-11eb-85df-ee56e4f82dea.png)

https://github.com/xunit/xunit/issues/864

Will try disabling parallelization to see if this is the culprit.

**Comment by bruno-garcia** [comment]
Lets see how CI behaves now given #942 and reconsider our approach

**Comment by Tyrrrz** [comment]
@bruno-garcia did it help?

**Comment by bruno-garcia** [comment]
Reopening this coverlet never gave up on failing us.

We could use an alternative, e.g: https://github.com/SteveGilham/altcover

**Comment by mattjohnsonpint** [comment]
Seems to be old, already fixed.
