### ISSUE TITLE
Make sure all logs in the request are added to the transaction breadcrumb list

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#881]
When using `UseSentryTracing` not all request breadcrumbs are getting added to the transaction.
We need to make sure the complete breadcrumb list is added to all outgoing transactions

**Comment by Tyrrrz** [comment]
The scope is applied in `Hub` here:

https://github.com/getsentry/sentry-dotnet/blob/2337261333d5743996d6d96ca3aa289d34a9d3ec/src/Sentry/Internal/Hub.cs#L208-L214

https://github.com/getsentry/sentry-dotnet/blob/2337261333d5743996d6d96ca3aa289d34a9d3ec/src/Sentry/Scope.cs#L248-L305

It's actually the same method that's used for the event, so it should work the same.

Make sure they are using a version of Sentry after #875 was added (ie 3.0.8 or higher).

**Comment by bruno-garcia** [comment]
Thanks for clarifying.
