### ISSUE TITLE
Align transaction sampling with spec

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#882]
[The spec](https://develop.sentry.dev/sdk/performance/#sampling) defines that if a callback is defined it should be called even if a header exists with sampled=true. The sampling decision should be in sampling context.

We need to update samples so this is clear.

https://github.com/getsentry/sentry-dotnet/blob/2337261333d5743996d6d96ca3aa289d34a9d3ec/src/Sentry/Internal/Hub.cs#L114-L139

More context: https://github.com/getsentry/sentry-java/issues/1315#issuecomment-797071507

**Comment by marandaneto** [comment]
@bruno-garcia I believe the changes on the proposed PR do a bit more than the spec, I mean, it adresses a few flaws, should we copy this over the Java SDK?
