### ISSUE TITLE
Add "sampling rate" docs for ASP.NET Core

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#905]
Add "sampling rate" example for ASP.NET Core

Currently shows `SentrySdk.Init` which is confusing:

![image](https://user-images.githubusercontent.com/1633368/112765385-f7533500-8fda-11eb-929b-7e67a953e472.png)

**Comment by Tyrrrz** [comment]
https://github.com/getsentry/sentry-docs/pull/3346
