### ISSUE TITLE
Fix references to removed code from configuration

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#906]
[In this change obsolete options were removed](https://github.com/getsentry/sentry-dotnet/pull/533/files#diff-1d159d4d1b3ae2019aa2be1fdf0bb15efbe863987cf00934b13c51436b1c1904L20).
The usage of the option [wasn't removed from samples.](https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.AspNetCore5.Mvc/appsettings.json#L11)

Sample needs to be updates to the alternative API such as `MaxRequestBodySize.Medium`

**Comment by lucas-zimerman** [comment]
Weird, IncludeRequestPayload should be replaced by "MaxRequestBodySize": "Always" ?

It turned out someone (me) replaced IncludeActivityData by MaxRequestBodySize while on other samples IncludeRequestPayload was replaced by MaxRequestBodySize...

I Gotta fix my mistake.

**Comment by bruno-garcia** [comment]
Thanks @lucas-zimerman
