### ISSUE TITLE
Settings aren't being picked up from appsettings.json when calling loggerFactory.AddSentry()

### ISSUE THREAD

**Issue by xt0rted** [getsentry/sentry-dotnet#91]
I'm using Sentry in a .net core console app without the generic host. [This is my basic setup](https://gist.github.com/xt0rted/d15bc65617120e00e3e87c8388c8f3a2#file-program-cs) though I have refactored it a bit as you'll see below.

When I add Sentry to the `LoggerFactory` it's not picking up the settings from my `appsettings.json` as expected. The following code is what's currently working for me:

**Program.cs**
```c#
public static void Main(string[] args)
{
    SetupConfiguration(args);
    SetupServices();

    using (Services)
    using (var loggerFactory = Services.GetService<ILoggerFactory>())
    {
        // ...
    }
}

private static void SetupServices()
{
    var instrumentationKey = Configuration.GetValue<string>("APPINSIGHTS_INSTRUMENTATIONKEY");

    var loggerFactory = new LoggerFactory()
                        .AddConsole()
                        .AddSentry(options => Configuration.Bind("Sentry", options)); // This ensures the settings are loaded

    if (!string.IsNullOrEmpty(instrumentationKey))
    {
        loggerFactory.AddApplicationInsights(instrumentationKey, null);
    }

    var services = new ServiceCollection()
                   .AddSingleton(Configuration)
                   .AddSingleton(loggerFactory)
                   .AddLogging(config =>
                   {
                       //config.AddSentry();
                   });

    ConfigureServices(services);

    Services = services.BuildServiceProvider();
}

private static void SetupConfiguration(string[] args)
{
    var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

    var builder = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
        .AddJsonFile($"appsettings.{environment}.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables();

    if (string.Equals(environment, "Development", StringComparison.OrdinalIgnoreCase))
    {
        builder.AddUserSecrets<Functions>();
    }

    if (args != null)
    {
        builder.AddCommandLine(args);
    }

    Configuration = builder.Build();
}
```

**appsettings.json**
```json
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  },

  "Sentry": {
    "Dsn": "https://xxxx@sentry.io/xxxx"
  }
}

```

I've tried moving the `.AddSentry()` call to inside `.AddLogging()` but I'm not able to get all of the loggers to resolve with a mixed configuration, so I need to stick to one method of setup for now. I did try loading just the console & sentry loggers inside `.AddLogging()` and the settings weren't being picked up in there either.

The latest WebJobs SDK beta uses [`HostBuilder`](https://github.com/aspnet/Hosting/blob/c9a4ee8b719ffb01eb44705d68efd158eb80c221/src/Microsoft.Extensions.Hosting/HostBuilder.cs) which is what asp.net core is built on and .net core console apps are meant to use. This will allow for a similar configuration setup to asp.net core. These builds haven't been published to MyGet or NuGet so I haven't tried them out yet.

**Comment by xt0rted** [comment]
I was just testing this out on the asp.net core site that's part of this same project and that's picking up the settings in my `appsettings.json` ok. It seems to be when you add sentry to the `ILoggerFactory` or `ILoggingBuilder` where they aren't automatically picked up.

**Comment by pengweiqhca** [comment]
new LoggerFactory(builder => builder.AddConfiguration(Configuration.GetSection("Logging"))

**Comment by bruno-garcia** [comment]
@xt0rted 
Just ran your sample with the new version:
![image](https://user-images.githubusercontent.com/1633368/45205587-e3138500-b282-11e8-90b4-910b1410d89c.png).

I'll be publishing it today.

**Comment by bruno-garcia** [comment]
Resolves on rc2. Please reopen if you found any issues
