### ISSUE TITLE
Help debugging SentryClient disposing/disppearing in ASP.NET MVC

### ISSUE THREAD

**Issue by nicholashead** [getsentry/sentry-dotnet#912]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
.NET Framework 4.7.2 - Sentry package 3.2.0 - Sentry.AspNet package 3.2.0

### Steps to Reproduce

Run the site using the global.asax/Application_Start pattern - store _sentry as a private IDisposable, initialize inside Application_Start. Logging works fine but then randomly(?) will start throwing these errors (to the DiagnosticLogger) after some time/successful errors logged:

`Cannot access a disposed object. Object name: 'SentryClient'. at Sentry.SentryClient.CaptureEvent(SentryEvent event, Scope scope) in /_/src/Sentry/SentryClient.cs:line 67 at Sentry.Internal.Hub.CaptureEvent(SentryEvent evt, Scope scope) in /_/src/Sentry/Internal/Hub.cs:line 167`

### Expected Result

The SentryClient to not go away/be disposed.

### Actual Result

The SentryClient seems to somehow be getting disposed. The problem seems to be happening more often in 3.2.0 - I believe 3.0.8 wasn't doing this?

----

**Comment by bruno-garcia** [comment]
This means the `IDisposable` returned by `SentrySdk.Init` was invoked. Either that or `SentrySdk.Close()` was called (it'll dispose the last instance returned by `Init`.

With the steps you described I'm not able to reproduce. When are you calling `_sentry.?.Dispose()`?

**Comment by nicholashead** [comment]
@bruno-garcia thanks for the reply. I'm not specifically disposing the SentryClient or anything. It seems to randomly start happening. I saw what I believe was an increase to it happening after upgrading to 3.2.0 - so I downgraded to 3.0.8 and I haven't seen it happen recently.

My theory is that during a deploy - something is not fully wiring up Sentry, or it's breaking somehow (flood of queued errors?) - I suppose I could add logic to check immediately after SentrySdk.Init is called if _sentry is null maybe?

To be clear, the only reason I know about this error is because I wired up my own DiagnosticLogger to sentry.

**Comment by bruno-garcia** [comment]
That you for the tips. Between these versions we've added the `UnobservedTaskException` hook and it seems it copied th approach from the UnhandledException hook, which is there since the app will crash:

https://github.com/getsentry/sentry-dotnet/blob/37d12db67ae67e5cfe598b06ced312b43b755a62/src/Sentry/Integrations/TaskUnobservedTaskExceptionIntegration.cs#L38

We'll revert this and release a path.

**Comment by bruno-garcia** [comment]
Coming up today on a patch release
