### ISSUE TITLE
System.Text.Json.JsonException when adding complex objects to scope extras

### ISSUE THREAD

**Issue by FrankGagnon** [getsentry/sentry-dotnet#950]
Please mark the type framework used:

Console Application

Please mark the type of the runtime used:

.Net Core 3.1

Please mark the NuGet packages used:

Sentry 3.0.7

When adding a complex object like a TimeZone to a scope extras, the log fails to to be sent to Sentry with the following exception : 
System.Text.Json.JsonException
  HResult=0x80131500
  Message=A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonException_SerializerCycleDetected(Int32 maxDepth)

The exception was caught when debbuging 
at Sentry.JsonSerializableExtensions.WriteDynamicValue
at Sentry.SentryEvent.WiteTo

How should we address this issue? Could unserializable properties be ignored?

Thanks

**Comment by bruno-garcia** [comment]
With Json.NET this was taken care of with `PreserveReferencesHandling` but seems like we're missing this with S.T.J

The error message suggests [ReferenceHandler](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.referencehandler.preserve?view=net-5.0) but I'm not sure that's the way to go. If it stores metadata about the type to initialize these can expose some security concerns. Ideally we'd serialize to a type and from that point on treat it as a `Dictionary<string, object>` though I'm not sure that's simple.

`ReferenceHandler.Preserve` might be the way to go, just need to dig a bit. PR welcome to address this too

**Comment by bruno-garcia** [comment]
I took a quick look at it and at first it doesn't seem too straight forward. With Json.NET we had some internals static JsonSerializer class where we could easily control the options passed, but now we're initializing `Utf8JsonWriter` at different locations and that isn't what takes this options. It would require using `JsonSerializer` instead taking the writer and some further refactoring.

As a work around I suggest simply setting values that don't have cyclic references. I.e:

```
SentrySdk.SetExtra("key", new {
  Bla = objectWithCycles.Bla
});
```

If the value is getting set on the event through an integration, you can modify it through `BeforeSend` or an `EventProcessor`.

We'll take a look at a general refactor to fit changing these options down the road.

**Comment by Tyrrrz** [comment]
> With Json.NET this was taken care of with `PreserveReferencesHandling` but seems like we're missing this with S.T.J
> 
> The error message suggests [ReferenceHandler](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.referencehandler.preserve?view=net-5.0) but I'm not sure that's the way to go. If it stores metadata about the type to initialize these can expose some security concerns.

This is effectively what Json.NET was doing, I think.

> I took a quick look at it and at first it doesn't seem too straight forward. With Json.NET we had some internals static JsonSerializer class where we could easily control the options passed, but now we're initializing `Utf8JsonWriter` at different locations and that isn't what takes this options. It would require using `JsonSerializer` instead taking the writer and some further refactoring.

In case with complex objects like `TimeZoneInfo`, it's probably serialized through this clause:

https://github.com/getsentry/sentry-dotnet/blob/49575e98544ec835fd6af1a70c97d14876461690/src/Sentry/IJsonSerializable.cs#L94-L97

Which is where you can specify options.

(I realize this is all very ugly, it would probably have been easier to just go with `JsonSerializer` from the very beginning and use custom converters, but I was concerned about AOT and reflection)
