### ISSUE TITLE
Add readme to nuget package

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#956]
Something like:

```
  <ItemGroup>
      <None Include="..\README.md">
          <Pack>True</Pack>
          <PackagePath>.\README.md</PackagePath>
      </None>
  </ItemGroup>
```

from `src/Directory.Build.props` so that all nuget packages take the root one.

Optionally we can have a README per package but that just sounds like too much work to maintain

**Comment by Tyrrrz** [comment]
Do we need to do anything else to have it show up on nuget.org? For example, icon also requires specifying the name of the file via `<PackageIcon>`.

From my initial investigations, it seems that readme is only available if you upload the package through the web interface. There doesn't seem to be any info about nuspec/csproj requirements in this post:

https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org

Also worth noting that external images will only show up if they are on the list of trusted domains (see the aforementioned post). Looking at our readme, there are a few outliers:

- tokei.rs (line count badge)
- sentry-brand.storage.googleapis.com (Sentry logo)

They might not render on NuGet.org, if I understood everything correctly.

**Comment by bruno-garcia** [comment]
> To preview your readme file before it's live on NuGet.org, upload your package using the Upload Package web portal on NuGet.org and scroll down to the "Readme File" section of the metadata preview. It should look something like this:

Sounds like it's relevant only "to preview your README before it's live".

Pushing the NuGet package hopefully just works ™️ 

The blocked domains could be an issue. We could upload that image to the repo and use `raw.githubusercontent.com`

**Comment by bruno-garcia** [comment]
> Let's upload the logo to repo and maybe remove the line count badge (not sure if it's valuable tbh)

We'll eventually throw some badge there in the future and have issues anyway. Isnt' the side effect only that it won't render?
I rather we don't bother we badges for as long as the readme render nicely.
