### ISSUE TITLE
Transaction should be enriched from the client

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#972]
A SentryClient can be used stand-alone. All event data is applied through the client.

This rule is broken for transactions:

https://github.com/getsentry/sentry-dotnet/blob/d25c97f0e5c77b520e30877444e93a9147afb9cd/src/Sentry/Internal/Hub.cs#L223

**Comment by Tyrrrz** [comment]
To fix this, we need to expose `Scope` as a parameter to `CaptureTransaction(...)`, similarly to how it's done with `CaptureEvent(...)`:

https://github.com/getsentry/sentry-dotnet/blob/d25c97f0e5c77b520e30877444e93a9147afb9cd/src/Sentry/SentryClient.cs#L105

https://github.com/getsentry/sentry-dotnet/blob/d25c97f0e5c77b520e30877444e93a9147afb9cd/src/Sentry/SentryClient.cs#L63

**Comment by bruno-garcia** [comment]
Yeah the client should be getting a scope in order to merge it too, like it does for CaptureEvent already.
Sadly it's a breaking change. This will affect only customers using the client directly and since they can't create transactions on it (only through SentrySdk.StartTransaction) this is low priority indeed.

**Comment by bruno-garcia** [comment]
Lets add it to the next major yeah

**Comment by mattjohnsonpint** [comment]
Before waiting for 4.0.0, we should also validate whether scoped data (ex: tags) makes its way through to transactions at all.  If not, that's a p1 bug to solve now.
