### ISSUE TITLE
`AsyncEnumerable` exceptions don't trace back to caller

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#973]
An event coming from an `AsyncEnumerable` doesn't trace back to the code that triggered it:

![image](https://user-images.githubusercontent.com/1633368/117545402-9f551880-aff3-11eb-9c12-ecd5b8fbf1cc.png)

If there's no way in the framework to get this, it might be worth raising an issue on dotnet/runtime

**Comment by Tyrrrz** [comment]
Is it any different from `IEnumerable`? Wouldn't that also show up as `MoveNext()`?

**Comment by bruno-garcia** [comment]
This could be a EF Core thing then. Not sure

**Comment by mattjohnsonpint** [comment]
Since we can't repro this, it might not be our bug.  Will re-open this if it comes up again.
