### ISSUE TITLE
Performance and tracing for ASP.NET 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#981]
We already have an example hooking into Global.asax.cs:

https://github.com/getsentry/examples/blob/master/dotnet/AspNetMvc5Ef6/Global.asax.cs#L53-L97

That's missing the inheritance of the trace-id and sampling decision. 

We also need to add that to the docs:

https://docs.sentry.io/platforms/dotnet/guides/aspnet/performance/included-instrumentation/

**Comment by Tyrrrz** [comment]
Hijacking this issue to add what we discussed:

Add extension method for `HttpContext.StartSentryTransaction()` in `Sentry.AspNet` that extracts headers, starts the transactions, and binds the transactions to the scope automatically.

**Comment by bruno-garcia** [comment]
Please also add to the docs and wizard.
