### ISSUE TITLE
Documentation issue - advise that assembly names that start with "Sentry" won't have their logger entries logged

### ISSUE THREAD

**Issue by cpwood** [getsentry/sentry-dotnet#99]
For the Extenions.Logging implementation, it looks as though any assembly whose name starts with the word "Sentry" won't have their logged messages sent to sentry.io .

This cost me a few hours of frustration because I started a new project called "SentryLoggingTest" which logged _nothing_ to sentry.io ! Took a lot of reading of source code to find out why!

I suggest the README.md file is updated to reflect this.

**Comment by bruno-garcia** [comment]
I'm sorry that wasted your time. 
I hope it's clear why we filter out Sentry namespace though since this avoids an internal error in the SDK getting into an infinite loop.

Besides documenting this behavior, I'd also suggest we log a debug message.
This way, for those who didn't spot the note in the docs, by enabling Debug mode it will be clear what's going on.

Thanks for raising this.

**Comment by cpwood** [comment]
Just wondering whether there's potentially another way forward.. Thinking out loud here.

Is it true to say that any Sentry namespaces that could cause infinite loops are either within the Extensions.Logging project itself or a referenced assembly? If so, I'm just wondering whether you could say "it begins with Sentry _and_ it's in this assembly or one of this assembly's references".

**Comment by bruno-garcia** [comment]
An error could come from `Sentry` package and end up in a global handler defined by the application which calls `LogError`. Or from a package that wraps MEL like `Sentry.AspNetCore`.

We could have this filter prefix configurable, with Sentry there by default.

At least this is only an issue when creating _test_ apps named 'SentryTest' or something.
Perhaps imply changing to:

```csharp
namespace.StartsWith("Sentry.") || namespace == "Sentry"
```

This could be a simpler change.

**Comment by bruno-garcia** [comment]
@cpwood I was explicit about this behaviour in the docs now:

https://docs.sentry.io/platforms/dotnet/microsoft-extensions-logging/?platform=aspnetcore#installation
