### ISSUE TITLE
Make `UseSentry` available to `IApplicationBuilder`?

### ISSUE THREAD

**Issue by absolutejam** [getsentry/sentry-dotnet#995]
Howdy!

I'm leveraging the [GCP Functions Framework for .NET](https://github.com/GoogleCloudPlatform/functions-framework-dotnet) and it uses a custom host, so the setup methods use `IApplicationBuilder` instead of `IWebHostBuilder`.

I tried to replicate the `UseSentry` method but it uses some internal classes. Would it be possible to make this compatible with `IApplicationBuilder` at all? I believe it should be almost a copy-paste job, but just targeting `IApplicationBuilder`.

**Comment by bruno-garcia** [comment]
Yes it's something that definitely would improve things.
The original code was built at around the .NET 2.x times and there was not IHostBuilder yet. Since then we just never got around to do it but PRs would be welcomed.

**Comment by josh-degraw** [comment]
Is this handled by [this code](https://github.com/getsentry/sentry-dotnet/blob/54aaf7ac788849f16779820ac8848afb55b549e0/src/Sentry.AspNetCore/ApplicationBuilderExtensions.cs#L32) or are further changes still needed for this to work?

**Comment by bruno-garcia** [comment]
Oh, actually we have a new integration with GCP Functions. 
Docs: https://docs.sentry.io/platforms/dotnet/guides/google-cloud-functions/

There's a 'new project wizard' in Sentry. You can select Serverless and GCP .NET in there.

We dogfood it on our Sentry Defenses game: https://github.com/getsentry/sentry-defenses/tree/main/server

**Comment by jbaumbach** [comment]
> Is this handled by [this code](https://github.com/getsentry/sentry-dotnet/blob/54aaf7ac788849f16779820ac8848afb55b549e0/src/Sentry.AspNetCore/ApplicationBuilderExtensions.cs#L32) or are further changes still needed for this to work?

@josh-degraw That code looks like exactly what I need, but... is it not in the latest nuget package that was built over a year after your comment? `3.17.1` published May 7 2022.

It doesn't seem to be there, or at least I don't know how to reference it.
